aws:
    name: ENC[AES256_GCM,data:WSx7LdJ3twEgyoDsumU+QSY=,iv:kUQVfoiabbGtVIpVXLwYfxlqa1aJuK5OjahK2cL1RiU=,tag:f1TqU4UqP3V1U7X+rxDRdA==,type:str]
    region: ENC[AES256_GCM,data:UhkiQL5iJncH,iv:RZ/C5X8pjSbOX63MJX6cUStiA0rPHfuDIAAmTU7zOSU=,tag:HfQltjiMUkMBoUEcnN14AA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:OTy7HJIV8OucBS4IFDjuyOw=,iv:SD/WCOqv/xpSwZoFAThiaXUTT/uxi60te0sIz8rnBA8=,tag:STvj71Gjf1Gzqkz/jjsrDA==,type:str]
    sso:
        alias_to_id_map:
            certificates: ENC[AES256_GCM,data:/yu9rTBDe5NEv118,iv:uKHy8ik2eKAJCPV0W1JO2lvqWYp5cJnmbPeJ1cbBG88=,tag:1jWxNmFLErSKuz25bL82+Q==,type:str]
        managed_policies_map:
            Administrator:
                - ENC[AES256_GCM,data:AMb5D2GvLx913SUBQVSvEp8u3w==,iv:utNBHxvvDSSqNqIxXlL8ihvV3wzmBV+rJ5UUvHZggjA=,tag:gehOPyy1dlGV18tmorPxew==,type:str]
        custom_policies_map: {}
        boundary_policies_map: {}
        administrators_group: ENC[AES256_GCM,data:Rfr7MjeC/OY6Yn7Ze0c=,iv:pXLiMk9REKWvhU9ObTI4bGLztOIqqXOVS72sk7xNHOQ=,tag:2Qk1Ic1RJiBBU1gkE7oGag==,type:str]
        cli_roles_map:
            Administrator: []
        users:
            gerard:
                name:
                    first: ENC[AES256_GCM,data:ngqyjpMv,iv:mdrjoe+KollA2uBNdgHuzS71Cpsl0TU/hJFAfC/NWNs=,tag:QHMo4UP14PQICReUXJxUYQ==,type:str]
                    last: ENC[AES256_GCM,data:nz1KsEo71Y8=,iv:p+dOF/XEfBcVzhuouD7cQG99rHeRQOI2sypSI+cQR5g=,tag:RFd4oqiVNdP7VjCO+zpfaw==,type:str]
                email: ENC[AES256_GCM,data:KJMEC6R0tVcy4pB11iS6/3rbbIfToJA3,iv:QPVXYuUGLLDfMLaHvuhRgyHdw0jR1+dtO/eRcPRiD9Y=,tag:HIamXF6y95LokITYJZmFPA==,type:str]
                cli-config: ENC[AES256_GCM,data:3Dgg2jg=,iv:osDxy/NLIYBlOp3Ix0QXZLZ5/09N784uI6vsFh07K3U=,tag:P4a4AzvOA4E/WdYfIQncQw==,type:bool]
                groups:
                    - ENC[AES256_GCM,data:/atSWBEZ/vo=,iv:rMwCftHBywV+vwsQdvoO9b4+UGK4jcgQx+x6pSGoQDE=,tag:x272gk94rbVj7gsr5nuDEA==,type:str]
        groups:
            Founders:
                Administrator:
                    accounts:
                        - ENC[AES256_GCM,data:mIfS5zoz1OnSY6tc,iv:M/qgdOUaygOQfHj2itR+3HlIboV4J44rVQcFyIBWmAI=,tag:6arFyQX1YzA3ECdOYUEUdw==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:90O4fMwG37ywyAdqhe8PVKW/iUHcKa1N5l5pdG4lh1caCkTw9qnWmqn4gg==,iv:fN9h8YWfNvdT6qakdanyrVXM9uGLm2VMWKM+P1Efb70=,tag:pnJJdQgQlp4gHFH8QItiEA==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:OWeBnn8tyccZY6N//g5k2oA=,iv:V9KN89gpaDN0m61FfbZYcmJ/bDudo/HbxfQOmKzohYY=,tag:s44V46zavUipaiSQOaOZmw==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:l6nYvLCo8XRAvT0WSQSrndzCbiaXvnKXL6AKrd6LRwxwO7Kf8t4wCQ==,iv:+A7G1q4PtVdIOgbzL2FwGrVpufg4wyb1yzqYqrflNg0=,tag:KHlHDeuLH4R//iQpgVkl0Q==,type:str]
            - ENC[AES256_GCM,data:yH2lvq2O05aXHj2qMYdeL6fENCfAxCxS4d8zHryxkiTbYp9h9xZZ2w==,iv:Hl4uRiqCfZEEMaJe8007zq8BBkMpZamW2fy4sdmWP0I=,tag:kVq7NpVy2N+q7uSKeuMbCg==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:IZxv3uDgAsETpaSzhhWkG3AQwiM+,iv:VolX7IBg+LN2/mSEb4PhQDPnXXeRlfdGXoNIjSqEJR8=,tag:vK1VU3PGfH/TU1loIDAIag==,type:str]
                    - ENC[AES256_GCM,data:ySrwnKOKB1Kn3aU8jX2vF1WX,iv:0hXs2VTGyrKUd1AD/qZBTqYJN70bZAz171oug0RM9G8=,tag:G5xZFjBc/qNZ9FQ6fmuX5Q==,type:str]
                policies:
                    - ENC[AES256_GCM,data:aRzwWmkppGUcco+2zsctAMvHLoqqqnZVrGXqUdjl,iv:6eZ2hEcy4qkjKrzrIczfVLHioW3UHOGZTvWuX9StPQY=,tag:RixzPWbqFrUdJZaGQl2GjA==,type:str]
                    - ENC[AES256_GCM,data:F6oQCe87T3kudEYBu7Kn,iv:/ULydcC9v8Md/02U64AQIn4YX63EeJnqi8nyLgtchCI=,tag:r2yFL8mBCVDD+mty0/dyMw==,type:str]
                    - ENC[AES256_GCM,data:w4orkpVpUIpT9zI9xQ==,iv:8lFXQlHQvCLBU3H5H5qLCfobPIRxKx5C6xbfJ4PrSb0=,tag:s7uTqlGyZBijVcDmRJNcMA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:2lbZivYDlepKuUG2M2E7J2Q=,iv:sw749gkYQ1hn5+rTSTg3pda32K91r4N8OV1KUDzZvPk=,tag:gfT4rjsqsxVTAcyWDmz+HA==,type:str]
        - ENC[AES256_GCM,data:IFxOdYvaepPr2lUoYHj20R5dSYY=,iv:03ZNuekRZAmjpNHmw6SjSqa8Z3Mvoti+v2XQ190RTnQ=,tag:+M6JnbPOHylyApoT26dWmw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:som4oO8UHgKSOdZNZg==,iv:uIQ2u1U5I7nzGXJT88nMYvSFySNf6R7Nir0yDZPokb8=,tag:t4AvoMmb4S+wUSAYxY8BBw==,type:str]
          description: ENC[AES256_GCM,data:N/UN5tMm6VVGm1oPsw==,iv:HkcIaxVOgSvcj2WCjN7clYTLiJ1Jpa5pgNsf2b+Kh3Q=,tag:+yz1aKGGdcUmIL2pJ1Rclw==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:I/D0XBLX9ZUr0HG5jA6C,iv:3mKIQcQZBBKcPX2jIM0RBcS9HDago5phJtVKIqtD1bc=,tag:blFRSVletxTEhTRICdSlJg==,type:str]
        - name: ENC[AES256_GCM,data:JwEuA5BM4MsIbz3/,iv:Vl4KPRwZt7d130QEid/7UQMdFUWIny9yHyJ+wFwChWQ=,tag:xGnnxkRtMeyhQHtoP0Ok/g==,type:str]
          description: ENC[AES256_GCM,data:DcMhX+YA62xa6LHgxkDg9E83VtAskck3,iv:Vykjd/GBRIKX4FsEzO+tXrXQqK7Z9QOLEPa4OTP3OLM=,tag:0HTTkMiDpVmTSNb/XGyYAg==,type:str]
          deletion_window: ENC[AES256_GCM,data:TA==,iv:vkWf3aaf9aSz/rCWDOTM1viJR2iQVxPPAOc+Y6vs/H8=,tag:Y3TOKLJ4Bmy61hM0aSMZSg==,type:int]
          key_usage: ENC[AES256_GCM,data:XBBdyIrAR1I//1tXLRr8,iv:v+/niXeo3lkEIkxtgulC/MJk5j6eZE9cABbX1jUo9As=,tag:/r04VwDEYV1TXMozFlvDsg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:n5P4UmZVnxKnZIw=,iv:7L7RO5LOcHdCyfC9LlnxWVeW16cdgQM0HgpzPrdivos=,tag:TgH3Ed18qWlO3rd/sRgrCQ==,type:str]
          limit: ENC[AES256_GCM,data:Vdbu301RSKI=,iv:ae9+VkBI4Q3pCFMX9il6HwpDeGhHJtQKknE3oZzJwX8=,tag:mf9PAbDl3ViwbvdbX+PRKQ==,type:str]
          notify: ENC[AES256_GCM,data:Xjavqx/cC2ULf7YMQETapjYnkCwvqwF9,iv:Eq8ywkvPMm2NKTmChLU03vasc5yMLzTLLyDsCJq1io0=,tag:nMI6NKbHSxThVuZBMbPafw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-01-13T17:10:41Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFUA6Tvje04azy6bnHUk2f4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMMKoZbBavcix392yAgEQgDuSgnxSIM+IdPr8OVVUi6DtwBtDLny/AptB9nKI8UHpazT4Qhz7K8bc5kExJIQ9FnAuK/Db8SPV8dL+gw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-13T17:10:41Z"
    mac: ENC[AES256_GCM,data:VuWqSpbK4kJsI3pJOW4MZ/WMrYBy4AGPtDebY/8t+6u39F2zXL3ocYyb/EnjRqr2+2DRMWfOXP1Y/wLZddgEZ9EDYa+eSSVd3So86QCJG1qlqPWYI9LmEM3ayIT1XIG+JjfcTBYnvpb145WwBlBYgoHEjx4OXeMoFV5z00+MSVM=,iv:DAuTdco8k+YKJI1n1Yug8dQIg8Jvg0d4v72h5985hgo=,tag:OWqQYiNVSIjyVp12wScPeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
