aws:
    name: ENC[AES256_GCM,data:IEr/2Bt+xu5U6oV21d1VQrw=,iv:7rAjGcFmWjYmH1Y5n64taSwIPNLY5vUsyw3KSed5+1c=,tag:BRSfxk30HGp2me8M3kWFgQ==,type:str]
    region: ENC[AES256_GCM,data:O5PTqARQVFIU,iv:Yy8Ud0hQzHPdzbNt6Js8TuDcyW8yxdOGwhkiWRZGO8Q=,tag:HAEPirV+L9oPDzMa8dbJag==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:YiKFTfCLUEzvycKFPfiNoL4=,iv:ySOBdIvzisboi63qfVLBaiR3W1zdtmY+thlVlCqpdJ4=,tag:LfFqlGE0xwP3KOfnx4Ee+w==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:96zftzrjsB7JZnmDabOZ72EVjoCTACPL4k9Eso1Z,iv:7YIxSDXlwVrkZ0T/sgRMvjiuoweu3+MULUdJhZ1g2Ks=,tag:N1lAL9lYANXpc2qxjIerFA==,type:str]
                    - ENC[AES256_GCM,data:MfqHHAfnRoJfJyxapzPU,iv:g3YidXA9tc11MKdHr6MkhebkV3Vr9oQlPJlYkZMe+gs=,tag:zEVm5WDNLJbL5fEiO0amyg==,type:str]
                    - ENC[AES256_GCM,data:nRlbb/gfMqzwQCLvQQ==,iv:a3eHPwIozKR1IqwYYIWe5KlamlWmzSl3+QT/J+7/rs8=,tag:/+FbrhPL1vrQzQViRb7kJw==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:CbgX+/zL0umTvG6xiw==,iv:X/Ce8XKAnUidNTtaT/WJfIKSNszDopEkpgP6F8aztu4=,tag:jnkoEdHSqAgdKefpn9T3kA==,type:str]
                    - ENC[AES256_GCM,data:h8Fg7eXhDA4gB/5Vnuk=,iv:AEnbZo5vZbXf383dqbFnf0l65iKUWduXI2rPb+yycv4=,tag:pRJ8v7mMHadHfNDCARTL3Q==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:fgiLRFd97E65jT8WwAOZlT9rliPC48MqU5gcf9HiB9eE9A==,iv:PKPdwWNUzw+CICFrl6vikuZjxHTtaz5UPpKi/yXIm9Y=,tag:mBuCuF2iFcbpt7PLh5tjaw==,type:str]
                sso_role_name: ENC[AES256_GCM,data:HUxI0fzHYI10UB4rCuyHJSAqSLGgXg==,iv:MvDDBpNayno7c6rwBp+E9eArsmVaZ75YWnmKdX9GJZk=,tag:JZEQX8jj5g2RxyIkGDb0/w==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:PqwPv0g6mzMwT+hS,iv:+pUK0+pb7WZ9Pr/ewE8M8xcy+kIiBTFV/4GOD7MjXrI=,tag:4rKPNQ3irUsHYNOlxXjoPQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:5B2DSpo5v3ufwVySOFhay7F1Ew==,iv:w51s+Qp6yC6axBLd9kkZyEGat4mliysn/kDpSzK9zDE=,tag:EBSWkqEcnmeFdA481X1zSw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:F0i2jZ4b,iv:X9JfOdZ93WtCVvomm973v3HHixtMUQI9atHrDWx8wwk=,tag:Gx9dTTkTP3VYDTf0dvB49Q==,type:str]
                        last: ENC[AES256_GCM,data:ecNL8vUNhOE=,iv:s9tjKObmxUXk+VoFSsIGM5/EvjKfJTF3FhTmP0tAtJg=,tag:P+XT6x3qA7vYBZLWKf9yhA==,type:str]
                    email: ENC[AES256_GCM,data:dbuDjmrS0dVh65wqd/a3mVsU+Xpqys6H,iv:fFNuAHkVzcXreiD1NAGnzMu7yJx2hjjlqTqoMILlMng=,tag:h85RSNRYoUGezcjuzJwH5w==,type:str]
                    cli-config: ENC[AES256_GCM,data:sgKXhYI=,iv:+w0JcnXBFDIRljkoLI4QR9sI/e1yWPgtRQIe3Gm26Ak=,tag:et/0tfb2wdC5UTHUJC6kHw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:JSaN/KJQACg=,iv:7+msFS6jvjyZ+kI3na7o3FNnF7uU4tBya2uJD+LfjKA=,tag:kb5NpPXQJeMqiGsyoY/bKg==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:Xw7MZn4EwzFeuoGh,iv:kIy1uDSmQHQtD4cV7rkfVDwRvVeLtAfWe7xP59f0p7Q=,tag:DvaqBy3yIGdzAdvHooP3mQ==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:0P4Zkwc7SExf78HeKnl84gWuWir8ydRW5zucajHo7Dtw0esgw5C0V5wB7w==,iv:muCOe9LnIU40suiGBySXJ+CMCzYUc7a69g//xj/djKQ=,tag:79nqZzinVlATo1J08PXf5Q==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:RsF6jGCnawvqNgIXfqsgTJA=,iv:8BFmqhoT94kFiBv5uEQxAJTytE6IB/YtZTnimHWApok=,tag:BSQ3BSZYhJOOP0MkTHTmJA==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:JhIbm8ogpnTFc8esxyDEv0xbfl7pmS9QCStfaAyGSA/YnitZP5F7VQ==,iv:YdWB+ZrZ44n3gDISMsv/NjpGtknEUlqg759Yd3hkNXU=,tag:rq57BaOX0Q8216eUpl0WrQ==,type:str]
                - ENC[AES256_GCM,data:jm4jB0+bA1QpKWQ90iMLhA58plS9OiyvlR/o3cbyJch726E8kKAjbQ==,iv:r+hL9NoDI+z1Mn5ohlGa9VNR9JQedw1KfDFzT8xzu3k=,tag:2dMUdO4VHOKR668qn7e2lw==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:+nOdKNec+fbxo5tZKOwffV74,iv:GcUsiRpkfOXJDGWmjNtywhjQ0z90KHCURnZKKDI+kJQ=,tag:hnsz9u9pDoT+rOebmpjvcQ==,type:str]
                        - ENC[AES256_GCM,data:dvrgJKRKTTa/6G5onP0WlX5ehg==,iv:y2jye3sbuMZkgA/iiEimApNMJHGMoIvdFY9Q9/+1axU=,tag:+l+50AOmnmGJCsEj1CJ4yw==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:iFua30NXFpXSVglSsaOYIiCvlhDJ,iv:YbGWdotQj6Wp6p8tsUYISW44VP0RHJ7YuSMuts1+on8=,tag:fF9/6lWEXGPUeF5VztyvEA==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:IDxiFz59HLuDC2S7JFpet4KCwKsF5BHdSz105WGq,iv:TwqMjH0j2W8pgTnL5/xoPmR38sKV5OtQYLF5TyN18/s=,tag:dWFYnSVgQyQ9XK8xNudEbg==,type:str]
                        - ENC[AES256_GCM,data:j8qUCmICXaHwSHX8E5DZ,iv:/Tf/bGIqLbFqD3x92fV7DaiYCOWor+VNj7DtewCGEUM=,tag:TAVsPhAhUQ1ytiKiBFn1ww==,type:str]
                        - ENC[AES256_GCM,data:spaxDQ3SRcfcdSioew==,iv:yDAi2phz3sGNN2ofYUPnv+GE2OBpnLWKLTyoKkWcrwg=,tag:FBOgnN+xK+Fv96oA7FzOIQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:HMgfrTeadK6BVT0LR5XySKA=,iv:g34QSbGC+QS5TSMp2jMP/JYJIXZxADpbjf1/oUD284M=,tag:a3auSUF+CwLOVOxVZzjrGw==,type:str]
        - ENC[AES256_GCM,data:k6w+5KVKCuAR/JJSGa9IWx04SmQ=,iv:e93mlzi5BW1r/MGzhG6ZaGo7cUOcaS6fNMI+Sztz0Yg=,tag:0L/nHCd6ygRjtvk3qtsPpA==,type:str]
        - ENC[AES256_GCM,data:rhBYGpCSZkclGscgrTWxmwck,iv:KZJlgPM3hnNnmW6yJPBFMKjgAYMdW4ro3lL2i699VGY=,tag:3PG0mcUgQ8GEbBhOKr18ow==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:fqr/lJJi+g9csT8/sA==,iv:R6dGctZON3Sb8qUfNgLjqwCXyVT37Ujm4l0T6u4qpJ8=,tag:CYEENO05ZFT+zzE1P+69tQ==,type:str]
          description: ENC[AES256_GCM,data:Ys58zDKBjZbxNUl5Dg==,iv:TnIp7Xm0c4rPHEUyCiLgMd0Srrjtorv1yQXno4zpegM=,tag:tJz2pM14gAfe97306CiMbg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:GEmzHgPX0x+rUn503e1j,iv:L/AM4PcyAksiNBe6uZ7mMiqg9ywDeA2EN/q27oVvOmA=,tag:g0RtXxAlZyIBeGTl7d+tQw==,type:str]
        #ENC[AES256_GCM,data:QmFoGAURYE+4cJJVf/BeEhLdiqVHdcP1QHvcTL0=,iv:YwC554ordAlavxPihuG6FCuqqv6+a76augqNmuSbW7A=,tag:ahT7hMNLVatQG2HaMhu5FA==,type:comment]
        - name: ENC[AES256_GCM,data:hD117inUcGNydMJ9,iv:tsK6tGXaKebH9Aoz94D8EOO+xOpXU57IWmpfVPYf5pI=,tag:kTdLtowJ4aw0+nGuToT5Eg==,type:str]
          description: ENC[AES256_GCM,data:dZ5QiPmX3Z9P5rbz9qkf5gmKGvrQGlWn,iv:sb8fSxb7JiuyztONGdMEhrGOI3VEO4Q1qWNJqIXRzhw=,tag:f/Tmz5eMEr485pVTNWXDWQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:RA==,iv:d17T4r2j6X3ftU+izUooypE54v1RjS6IY431jhwY2u8=,tag:BQVhw/5CB8noWm5HmRHuxw==,type:int]
          key_usage: ENC[AES256_GCM,data:TnIs0wfcv7w7F/n12gw8,iv:obU3BO6n9NNs0ucvRn0ypkROgIxBi1snR01nVNEHl+w=,tag:inVyh9DWjEBKqDEaZbYJjA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:URBVLyMSpHtjAmc=,iv:oRVIWJ+3qmR8teF2znID/saO4v2i+VrzpRHklHYg+dA=,tag:nE0Mn795WzepoesNQsYGFQ==,type:str]
          limit: ENC[AES256_GCM,data:+kpESu2v4G0=,iv:oZj+0cLgKy75e8nADvKJMKqMSwIYqOzcZSb68WIQ24U=,tag:/tMludXGZboPqnAByhQHmg==,type:str]
          notify: ENC[AES256_GCM,data:37+EyFEOjPBXYQsdEs4jkxDScHY6M2CX,iv:4zcJdiNFTb2aafuZtdlxeQNu+dt3ozRiqQOaNHRcMqs=,tag:Rwm8S3xHpedT1HbGC0e2kQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-03-11T14:40:57Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEAYybAN6zS8t1hAXdwHG75AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM523OVy2X59dCtsBmAgEQgDuaE3Nrn6LMXH8mSuy4IrE2BmL6ol/EQJuy9BlDcA6/qhD25OQKdsl23dVgOROKxXfElogl7YLqJqUqzg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-11T14:41:54Z"
    mac: ENC[AES256_GCM,data:zwtrRivKZO8rjXdC1H3BeJNeICI9NWVj9gFBSPM0W8IkS6xVcX6m67H77RO3kCvwpLKCPxBo59BkhftqE9tKSwGIMN2+OqqUchK/slyCCXVVGjwnWENLtChcBNEMxjIRUiw9HuLFwBVwXL9QWmGATaCBZm9o9Up6vsbf/JWi7zQ=,iv:gJs4kjA+IUDPx0mrdAYC632YqQ9cg5uQUyRJlN+Bm9g=,tag:HJ8O6cAo6Z9UQNfhfQ8UmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
