aws:
    name: ENC[AES256_GCM,data:/dtvlgk0IhaGk+Kf8olJke0=,iv:1NjlromzGsG5Vby5+qRyzT0e+18Vu3gdeC0exeFaYBc=,tag:sqqKpTYrnKFtdAegmY/OOA==,type:str]
    region: ENC[AES256_GCM,data:R368q4MteRY4,iv:nuTx46Xtn/JThpEYtgWysXgkHyoR172w3reVXSeQnDo=,tag:b2FNlOCJI7jsKvBiw/n+Ww==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:aE7e07mUQZSuMRemuOU9PrKIRHPB6cdJ3EWNBcmRbzpAgw2W8l0mKJ7EoA==,iv:qynj6hYgX9JA9nPOrjWGfrBvq+BJoH8t2HiWlfZ3tzY=,tag:VWtlQ0WAxdBw02Q+MogJjw==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:YU9HQch8WfgotsKkYPwlGRk=,iv:3uDzNYf1atmrvn0nuZJzqZWLTQ8whqAvz+RtgZusSoU=,tag:12mLYvYVTC8PVqzw2+oi7w==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:wl5KMiUwnew99dWCsObcHtizwmJRlMihEoMI0GCJNB7oQWZNRlwBfg==,iv:/hDmAGMIb5NSZc1Gu5ega0GwdHwWOZwC/pbPAcYSWCs=,tag:xo3T0T/gxxhS4CPJzJXz3Q==,type:str]
    buckets:
        - ENC[AES256_GCM,data:XcBImF4a0jwwxlubiw/JBiw=,iv:bMwhoMOfDIDoTr8X2ICAlv0xtoE3La0EyVZLnFsKuz4=,tag:qB/fINK3mE/PL595c4MbPg==,type:str]
        - ENC[AES256_GCM,data:UQ6v8U6lR7SlkrnfVyDHaidBvg==,iv:hjXKLJCne9R4BuLSLKvlOoLzVBP4u0+cSJTgUciv1ak=,tag:KORh2PipOYpAkOo4XwRLRg==,type:str]
        - ENC[AES256_GCM,data:NW2T/DV569+MfqUDSsTwttB+3QY=,iv:uwakCqMG8RoFZ5bTF7rEpaemZDfspQ4q62h3vaLb6WM=,tag:Dg5rliRqlrSoi799n6rTPA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:tFFwl5M+/VpBGJo9IQ==,iv:0ysYZzhKzUvClpZqBy6M7C1E+pTiqr0vbXQB9wTBqjU=,tag:MNA8it8FCWJKgvUx5G1Pig==,type:str]
          description: ENC[AES256_GCM,data:eItE5A9i3PpC2tZiFA==,iv:tt/c8KwaG3/i+xaECjoBn1HzF5MG+d8I8PwhemQSx6M=,tag:J5W1v1mCBCqLxLo+vmBl8Q==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:hW7LPa4O49i6kyGbsfjw,iv:YqVFlhytN+S2PIFAA6TRmg19LKoDSkS34QkYYBiMh1g=,tag:67CANVxZdTv4X225fSRb1w==,type:str]
        - name: ENC[AES256_GCM,data:BBvuyRLB+7Tg9hBK,iv:F9T5+LVboua0QsS3peQsmFSe+DXyjbHs5Q6YyXxIDHE=,tag:1REox3ipu6zjfrjwYK9/sg==,type:str]
          description: ENC[AES256_GCM,data:q41FFYY0o27KAN9cgtQcCxJfsGLSVymM,iv:XvTHB3bBsBBhjtPqvjketjIViZe+KfoQKGK/w9jfGKE=,tag:eYNPdy1vJ2JY/Ulxy7eonw==,type:str]
          deletion_window: ENC[AES256_GCM,data:Vg==,iv:0qkdS1uSTJkBWzK1Wu9WBywwk6SVtmf2rgGzyhrQQkQ=,tag:ahmVnjupsuZ1SG2vZX3Nyg==,type:int]
          key_usage: ENC[AES256_GCM,data:8k3tns6PHvgtXbXe7Q9d,iv:dGy4R8jeTXSr/iptwRmsv4vzbCtxeysLmDCwUqP5Ar4=,tag:7UYvv8wm0GEBHEMKu9rZcw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:j/gtVxunS0bkbDs=,iv:L23OHxspvVDkpapv8qc7eglT9awSZSSPvub/9mH+xf4=,tag:Kva0ITgROScPdx63WRgtIA==,type:str]
          limit: ENC[AES256_GCM,data:UBHLlkvAkw8=,iv:oxxJdBGX0d4QSLGT9Zm/G/ZrbjGG5zhROWjRJdRZPvo=,tag:C650yKW/EQCR1u2lFg+pFw==,type:str]
          notify: ENC[AES256_GCM,data:K+pduggUKZYlLs0FrURCsOFOfPCjsuh5,iv:FdcyT5BIZD/4NZCwJ3aMiukyxol//zhB7EWxUB8okWI=,tag:C3mYB/Poyq6zboFzrVCYdg==,type:str]
    ses:
        - ENC[AES256_GCM,data:TCcvmAT6+Ek0bzRdxXs4fPfld+h5XWTp6ZEf1st3wA==,iv:zc90rpmA+0v8oTcoFbiSDiadKeEMckQDn/tOnIra05o=,tag:gHA+dwzcBjn3Z1gMdRw8aA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-06-03T22:35:29Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGFFLNiRAKgs9Q0vX9ys/LnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIjpRruELuW1DJZNQAgEQgDtvqPKrKlKiTfjtwrNMIwkY9ujYMd8HA6aJOKn6KcjnEXWhv1OcUiVFC9ZmWcp8LAg73zA0+i1pCx4Rlw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-03T22:35:29Z"
    mac: ENC[AES256_GCM,data:Pd4UGLFd537ycp/Ni52BmK8hN7/2Q6Y3YUQJubYxvNuZuzgAjhMj/MFsApCMrimLUJ3tjz28aT94UnybRgZIb/NnWXRy+VoJbh24HhYBoKLWRIQ68usLXalu2E9Gvvil27WwkmLffOURPRpz9GfuJAKJNyyEuXabPZFPv2a40zA=,iv:rtbJJWLC5mLl0y7Ua9l4djT1moYIiIsdPWQLJRRRryo=,tag:qTxg/74rbXA2kG6FT6CmBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
