aws:
    name: ENC[AES256_GCM,data:HlunjgTkVzplCZKSh4+9oiM=,iv:1Axe8R42K5lOdsSNO89dTPPBmuhhDe6SB05nQMFZ0Fk=,tag:2AwDKp4qpPoAgBQzsU1kDQ==,type:str]
    region: ENC[AES256_GCM,data:MNa8CszeVDji,iv:1FCzWtTofuP4h/ofmX3F/OA34MnR2J1wDGx/hgwLLfM=,tag:tASyGNckVzTC4UHBwpp7Eg==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:U0bviu9SzupTd0gdIHu9LKs=,iv:dU5spIXo73RLAOuhRXaHqDhiCKw2yXUaoPKVVy0UVD8=,tag:cQAkcn2F5OxFarPGrw5MVw==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:fMOsaNOonkLHfcnjPIDWIXcEzn2fW0CmxOKv+GOx,iv:QdpQDu4ZPXRLTPw7eyMe0U5ee4W3bValYEj2cBj9Iy4=,tag:rAa6vrcHHlad63IVvvlzTg==,type:str]
                    - ENC[AES256_GCM,data:0Hg1ocOnFIJtXE60r2mz,iv:PrGzig5yTU9ZLmDp/S7Tr8+kEhAJsOcpbVZ7Tm24H/U=,tag:n6lSrn5liIrRzItDamKhyg==,type:str]
                    - ENC[AES256_GCM,data:X0eLdJSoUOcYpkAkkg==,iv:mRKFJDM/pXkGP+0NXDEacqFp0fe9CFkp025eWP8VLs4=,tag:axxiev3n4trYruyihP6W3w==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:hAa3sJGOFiL255P2Og==,iv:ls/NT6pcWHpjjZFmUHxZqjFSycNUYo9ggy3DDm8Jsd4=,tag:b2AaoIIbN0bs2hqP0kEScA==,type:str]
                    - ENC[AES256_GCM,data:Axmm+yYIJdj+8Vs3s7s=,iv:UWNKmpOzfMyoGt/YNCseAUfwfPo6YWlaXzbEWcSMowY=,tag:PGCmRXb475g3wQr/javAnA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:Cq5beRCZ2/k/9xJL2o70/EeE4sfl/4yu4TgetFcAKt5Whg==,iv:LyWtIsdkNKzZxSOif7HTycaz+d7ffje9bCsbXKnhXKQ=,tag:zwn7JC32IKorCePAPyvL/A==,type:str]
                sso_role_name: ENC[AES256_GCM,data:hhjbp2E5GRiC6Ru0FB+yklhYZvyr/A==,iv:Xo2it3A3y3eKoOLmy+WGB3vcjTRq3JxbBZu8oNGGjHw=,tag:tRC3zXA0TBUUG6R/AtzGUA==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:kcZ4MDWi0HnSPsbG,iv:+cLRVR4LuRMtNBn0fiRjTe2FMItyWDmtr39sn9YDeVg=,tag:O0QEN8flXXrBuFnnpUQalQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:SrqsxpdJAW6qvY+O6yzMH9G20g==,iv:idh21QyrZcpGOANxGhnVOTdtqySXGKHKE/nUKw19VJk=,tag:Yl2ab+DF2P8k1vszxKZlRw==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:qnnBrWoenrL0yk4dAi0L,iv:MrX31mK7i9E1U9MDOdP03YD8HPOBEpg9BtdY8crQLvw=,tag:lY0zFF/pcidoY1inI6nfCw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:W1PKJGI/,iv:8uudk+OCibnbKn+kQRmL5A58/AtRfmQamaR48DTtr08=,tag:ur1UTjKC7gO8G1nCyqjq6g==,type:str]
                        last: ENC[AES256_GCM,data:Ow7snJAujdQ=,iv:ENOP9/5ZTX6XHArwb90I/bSS1VoBKYOjIDgfk4BqDi0=,tag:JS1erd+bRp0TP1JfNmA5DA==,type:str]
                    email: ENC[AES256_GCM,data:Vh1chLEBK1r5sZrEIJAWqChWmvBcgRup,iv:5O76k2MJEt+v8thFqShFkBj6cQznd1ZwhDM7RaLBOvE=,tag:/sMO2x1n7XJ45T+KEwcBaQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:jvEJ5Bs=,iv:zBpvi00We28qrl/uQnln1dg667k1vbFmIY/OQz0GkxE=,tag:C+vX4aPxiIEkaNPo2Uolsg==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:gQjoXMuhsEo=,iv:uWvd7XHUzAac64IcObO8Fv9IbiU5Pqu0SzHlepUZ8dw=,tag:FehEbqyVjq0SuxFB54Ykrw==,type:str]
                pezocoin:
                    name:
                        first: ENC[AES256_GCM,data:wT0JPQnDaRI=,iv:aKYYrnlrivcmX3tUmQ3j3mvXXjxbMgpkiD2a5qNf2dk=,tag:SRELSwnC2Kq628Zvv+ez1w==,type:str]
                        last: ENC[AES256_GCM,data:F5boiALNNzw=,iv:f88CcBiXsLFinIIiOU4KFl35O48kdXrCWoI1gq0Vxws=,tag:wgSEmr/QnjpfLJyvNgWvOw==,type:str]
                    email: ENC[AES256_GCM,data:Lle8Zcz7PX/J6IEX68q5lAIet8cqzsQ=,iv:FT12mAT12lJF29mbuSOkNFsTgDHljT33BpSjYLFWTrM=,tag:jvkEKRFpSSlXZ5W6HIfehQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:EnE1TXM=,iv:c8UKhi4yvyMtYr0ZcFVUVXBzh3kzAae4bxUJD0Dr6Ac=,tag:qqeZYIeq2rDR9l9HwCLaDg==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:Ux+ckZ8h9gETUP49,iv:wrUabNPx8Zp6Hh0kRHXPHoXW2LLdDBCTgkoyW7lTu48=,tag:ZOs2dhzvdO9dA9yRs5ekGQ==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:kN6xSSuIrIi8jbN1,iv:Ax274ascKMspd42ArOJe3FnhoYzRrAYPXI3U+cjyAZw=,tag:9xUoacfgx4XXJzRuJKmKVA==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:H/HQh8JfNji9dl0GLfvfhqotX+YbFQak956EPJ+2Kr3mfNrqEYy2o8DYGQ==,iv:ZmYdr/jOe6ETDmyWVw9utSyNohmOSDybzb20uRg0vrI=,tag:jmcW2qhHdP3pyMEodQZNhg==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:0nCVQKKD6ztXBEfU71nIrVY=,iv:lUCf8GKsXIV4GJBNXHoHX0v2tdPe1/v/0qoCAQPvARk=,tag:fbILMEAZQUUfnutTR672ZA==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:P0ImlJCXd2cqwX04IBWC9PoR675ynC1p5NooDqKoCJvpzbTmeiPpaA==,iv:WS4rmkDV2xDtUsZqpUfE+5glHvsQLWWvtpGUcYRQbHM=,tag:51egohpw5StYmd/AXqJs1w==,type:str]
                - ENC[AES256_GCM,data:UL4vhuRY0a89OhBAtHuhLUnCDBM3x4/MRnzFBnfwpwxHglvbD9+PGg==,iv:dszrKvbniULqt3uM/zjrArF6ouZYUs61NaWtSUYyXCY=,tag:9MygFGAgm0xul8KQ42feIw==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:ImFAUopFXDsF48a1a/bL/1Gc,iv:kgvqrDl40IvXq33cNA4QcjB2RqcnF6xszE1QbntYHXg=,tag:7QvLmBRYDRRQN89rM+W5BA==,type:str]
                        - ENC[AES256_GCM,data:P36Ye6AV3DqNDQjzYWwycArz2Q==,iv:PFbO1aNAcn0q6xE7LdKmlIQhlbsSRKF1ernTsb4XYwY=,tag:bpCVBRKQRQHz6VlFXCVnqg==,type:str]
                        - ENC[AES256_GCM,data:rHnE5Lbb8OEgnRe0wjtVryYt,iv:GwaKDmVg/sVoNB4Kt7sBDB3hznWVAim4dp/h+SWEeW8=,tag:Dgh6cj+/ZBJMLTxR3MAEFw==,type:str]
                        - ENC[AES256_GCM,data:pi7rWmabemXfDx94KVEUXW2T9+ncKA==,iv:1HT9sZ4uahXyqYPk/4e+Pc1c2kUEe6IAvlrxaa4hpWI=,tag:tE1JgvZMaNLTgXUp8DAp2A==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:2XYCGI8QiYARxx+N3vdGNNvePF6k,iv:3YPpR5BuKL48IsFxIXjnXoFpS0t4th8KzrpbAvT9hpo=,tag:DP0yDjioHzOrtZFW+sZKiw==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:mTFuBQbd1KAc6a/ZOyVyE1GgH36rjKjSLhfaZscA,iv:9EZTsTRI9/eieQrGXc/OAWXTR/yVyjpOVwfMSnei9IU=,tag:pbm1ntb/CUgKlcyCVaLQjg==,type:str]
                        - ENC[AES256_GCM,data:1djJzgZ/Fn+ZMfAlzkXi,iv:mFnjZtjRyWoLE6kxNXMxN7Cc9Te8jobkSGkRWi2hSho=,tag:EeHVjIg41tKSqgpEW8Zwwg==,type:str]
                        - ENC[AES256_GCM,data:ICoEXnldtzV2agxaUA==,iv:eDIZCXyFLMScqEB+2msruX5gzHGnBTyV/M+7xRREaXI=,tag:yHT2rUPy0wL/ztOpiUy+2A==,type:str]
    buckets:
        - ENC[AES256_GCM,data:WBL9usX7XM9VH8UptPPr8+Y=,iv:lVFfIBz5LrKmZy+0ImFfhpEz+R1icojb9g1Y+Vafu7Q=,tag:Moul56vBYgLPKbkqXE26Xw==,type:str]
        - ENC[AES256_GCM,data:olgGOXUIIZqIeAI7nShHsyDE/VM=,iv:JzohrS9vlAMzHzj2HYrrpu5AwoOg3OtbBfVIb3Dta4o=,tag:R2ybP1VWogfl0BiTrvL0JA==,type:str]
        - ENC[AES256_GCM,data:Ho3Uk308PKsi/CNeC29XDVUz,iv:XrpROLN0HAPZ156waESqXxRzZJn1QnJ+ikLyxZcvmY4=,tag:gN1B8JerpE0DlaSVquy3UA==,type:str]
        - ENC[AES256_GCM,data:z73loT4IAWj7+TkWV4LRtxk=,iv:pCICHjwJ7dB7cHw7NXODLPoiViXRhaTL4VOiPRz0kl8=,tag:yMDAoEoxmoy/hEPD+qIaLA==,type:str]
        - ENC[AES256_GCM,data:iQo9FWF933s2j7mVP/mgQlk8HG8p,iv:mmHVeAKjwlNS4FMWK8yCFFhwtg9zTKUfIeeJgF9zHIs=,tag:SIVUyvD7fOrPXGI7o5HdeA==,type:str]
        - ENC[AES256_GCM,data:dL/2sPnuiuLa1bmkGBeptQ==,iv:FDsO7DdyrJ1rhOHncPiBHAcesTCukTWJZ/op2hxHhqU=,tag:p8WtCCHRBwhVnULDRQ5k8w==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:iogUgvBTgTK4o3awfA==,iv:hba0wMl5lqZvaZ2gxoxFL2NYzB2Z08BRE0FGSsPBoHQ=,tag:7qejhMUhpV7awS7enqESew==,type:str]
          description: ENC[AES256_GCM,data:lYSRPz1uGa4D9G6yJw==,iv:iysBJH2QVK6B9iJLve0TBXSgsNaTh84JB5YSObKQB/U=,tag:g1cMp5Db7TudVSIswa2DqQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:V/UdOHB8nwL31yH52TRW,iv:DwhvSZbkOZV/zEYtvFzgnlxcXAz62VD0mW1/JIoBMoM=,tag:88wYwCgLqO6VZvTzb6mWgA==,type:str]
        - ENC[AES256_GCM,data:TUuZqHebeWK51QhSz+CCjvKrMBRHNl8rWuEcPlU=,iv:ysem54qDvhVdrYmRf19ti2SGoWnnP+yb1gZaqbGoiBU=,tag:00brdW/hxoz1ubvozERzfQ==,type:comment]
        - name: ENC[AES256_GCM,data:lWTyy4cow2twQTv0,iv:lYT92KCGb4Z0pWiVaX30GW+8IOMBwIimYuNuqOKRNDM=,tag:4+SbyjTO26AA56adONOMWg==,type:str]
          description: ENC[AES256_GCM,data:AtlI2J60Bhe8457S0Nk/RStNuLIEuHN5,iv:3zqZeS7biamATVkn4hYYPMtgu9zBijqG8M/Mi8iC6hI=,tag:JcMvqQ5W9T1Wbm001zCW1A==,type:str]
          deletion_window: ENC[AES256_GCM,data:lw==,iv:3o93wi36D05HAsxY+nCbgkPN6CrUxOjl6mXxecCG3Cw=,tag:u1U4gQsKXThqCgNbc1kPQA==,type:int]
          key_usage: ENC[AES256_GCM,data:cwE39jBhz4itrpFJAnak,iv:2TfGfwnzrNLhYMqn7cRfIoPiH+Q/aXJNGcqd4aAIbCE=,tag:yd9wRv0S2FndAOrtUHdfCA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:6REVllOKwgpeEU8=,iv:qnED/2J3ID3PVpH73c4h8koTAEyP+sKy2njzFrER/UA=,tag:YQivKtg5krL7hBzPcxZ+Mg==,type:str]
          limit: ENC[AES256_GCM,data:bElXLOFjxcc=,iv:UqsEkPo6q31PZBAgKNO7e9zkAhLE1kml15gXiBDDFEY=,tag:mDaS5/MuFpUW+ILJH9v1Og==,type:str]
          notify: ENC[AES256_GCM,data:JwsNVun83R6Mxj5R1t42agAhtOmKbosl,iv:tf34i7byt0+A0cBd/x2GkWHoVgt8qMa9fpnq49JceS8=,tag:7G07ogNT4npHNlTZsfBfwg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-11-30T09:58:18Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHyYkzMO6Z9L8GtciHs5U4HAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMWwR85BjnqsFDPIAIAgEQgDsoQ0MPI+2/ssyn0E3b667NZmtbNZt/Hwpi55955vOAgVPkYz3gXulZgzB5uwR/OEE39Zu2ftpjmDJhQQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-30T09:58:24Z"
    mac: ENC[AES256_GCM,data:3BWhFqZ+youPnXZMBSS8u/l4DFIgTPWOhePaFBZX/E05vAHp6QW29EZ2lMTtx7MgsYa7nhmH+KY51ZPJEEp4ljgs/dUFM7/ghuX6hbQw/1suopwVomh1m3ch2HOe+3c9upPSHa3smlwhVSTfeovM5x5VytSyteZA2lhPMzfqIe4=,iv:hYRfQkbOfjZV30SCE5+ixdycTmCdW+GXnZpR6P+5Dnc=,tag:RQQGMf0BQavJe7Em0BY1RA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
