aws:
    name: ENC[AES256_GCM,data:307edAVro9iC53Yh4+BEaSA=,iv:AXt9shnQ3posAI4pvsIkZSwiZyIJD8hxCCxJBA71SF8=,tag:FkUZN4EdDOJNsPRyZWZQXg==,type:str]
    region: ENC[AES256_GCM,data:9gUlyGgtpgNx,iv:2Ac0YV07+hPNv0RV3XpAZ6aZPUnX4Xa2j0Tg62cI/Sk=,tag:5nqQ7hjpZ+T8swF5Do1bOA==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:7U9ftYPBpNYlrVGyRqpbc5IU9BcjGHUopgU2dANci40zqvZD79JkFTEgTQ==,iv:ovUsTNtH2m+ASwbjLHh/IjV4desiplLjiXxeYhQTv3U=,tag:KPDvI+Zu9yfh4LatHzOUcA==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:OB3IgHu44LrjY2sqwLOUAU4=,iv:a3wQSqYpqeZAaaU24HPOJkBes5DOCRh9dAaOxRGgJTE=,tag:ad/lfRXEJ2XNVJhm2Ewr7w==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:iLr7NVsgyFYN8/58P1NBcHuK7bPZgiT0vmJ7S2qWsNn0ZHtUxdK1tQ==,iv:a/dRL2GzVPn7PBGzRiYxBFsnLpeogb9kLP1JrAsOtLg=,tag:UZVmr83ayrODeGZ2YDVBMA==,type:str]
            - ENC[AES256_GCM,data:zmck1cEyMY0LgxqrLTlrklGmcLuVFd6lZZLJl7O/6TLeO7wRqjVHJA==,iv:ef4S0hCugdSirha7icfcRUY0uFCGpEbmB0Gg9M6+8yI=,tag:XyPtLNrXea54EVBJFJ2yCw==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:lOdqP6loXvevlS9gak0ZbRTBW95d,iv:ZqILHUoZ2NXlCJZK6PyRvCW/s7qr/Y7kCWdNIZQmzGs=,tag:j9Aby96Cr1isADJa/pbgYw==,type:str]
                    - ENC[AES256_GCM,data:itWbddI3TQb+jQpCZ/4A6zyg,iv:V5Lt+x+ZAuWrLmWHyCVjE0dD7NaxAHG3Y4vgIVs3978=,tag:T+gnsVLyOGv7oqIAUi+CsQ==,type:str]
                policies:
                    - ENC[AES256_GCM,data:VuvC2E2R9pHJFGJ+dJssKW6cSw==,iv:yAWo0LdW9XIGumTw4oG8MYHBz0yk4PN+LoYDp2mKgNk=,tag:3gmaekCXdvlaAPLLwr564Q==,type:str]
                    - ENC[AES256_GCM,data:Rn3acp3kvXj5eCbVNMuoSKlH,iv:4r1t9CYW1otq6TNf3zk9k47PcIhjUH5y/fuES4L2N38=,tag:oV9XgwLLsC509Fu2viUcYg==,type:str]
                    - ENC[AES256_GCM,data:dVgtJfF6kwcH8g2tRcqQ5sjbWA==,iv:nMw8zNyO9yeQLVaPd+6B2dQu4Cy2efaZ/UTOSNnzHBs=,tag:t8BTPJ2v7synVF3HME5gGg==,type:str]
                    - ENC[AES256_GCM,data:ENLjiAwuwZBxfO64cnVp437r86I=,iv:ERGCVzUczfsIn1W3JQy7SYyVJqXIlUy9B7Qr93rXbb4=,tag:O1XJGQHorQwQPIlVTCJd3Q==,type:str]
                    - ENC[AES256_GCM,data:y3Cj+YbekQkwUBxgww==,iv:0zjI5DUaL7fyRv5QlF/FUvCDHuQRPJ5KgV7Rfa+KBGw=,tag:qwRkvOOlTDFLitqN5YrbtA==,type:str]
                    - ENC[AES256_GCM,data:sOZDXqRMaBw/1VvmHaqdnrSDV5uwOE+e4S87ovFVo4J+rO6kRJ8ffVi4ZN4C,iv:Th/9/7OgMlJW11WRzGhOT+MpgWHfRKigBgkqU1gnq5I=,tag:RRVezuPziR+HhJaE/a07/A==,type:str]
                    - ENC[AES256_GCM,data:popq30zv4UJCmhxwINZikU6DoESaGFExbfImpa0=,iv:s6u3Z20qs2wmm2+Y1ImZWHwxeLXXAAS/+ObQWA9a4Wo=,tag:guJiU7icKGVjOVodsamweA==,type:str]
                    - ENC[AES256_GCM,data:1nS8uL69uBJJssiv3a/6yer6+Uk=,iv:t4gGvEWDYz0++Y9im7PRq+PI8f9AIut9dBhCoMB52Og=,tag:y3pF2HWQ92DPgDmw0cuIZA==,type:str]
                    - ENC[AES256_GCM,data:E1cZk0RCF6i5hw45dMupzKCmAgqhZWU=,iv:6R8hnxIAPPe8E+eF6Vn7D59bhSEtH1UB4OLB9nvxoJo=,tag:P1TQ3KzUDSBxAuzwG4ECsQ==,type:str]
                    - ENC[AES256_GCM,data:3TakON6up1sFHrVEpTyHSaNDrMotgRsuM+pGPgaGAA==,iv:U113ootsF/zPWxigLNTgw2OTq99m5DRxUfI7OchajvU=,tag:JLsCfm2souRTxbTlheNcXw==,type:str]
            github_actions_continuation:
                repositories:
                    - ENC[AES256_GCM,data:aUO7yCmBhq/vCF8gc9HIBOfGxPT1,iv:od52avQ9NWrHQ2jACaKvaY83iR4djFiGSvWIBKbSGMU=,tag:OKoPlUBxGcqHlcKnfxSN7w==,type:str]
                    - ENC[AES256_GCM,data:WCq1OmpUljpMMTiSixW5KFRy,iv:V9Jn3JrCjJQqKl1xgpeRgqc5ThEu+Wf5ffGRw4LIU9U=,tag:jn6eL81LSxYf7ORDbgtWWg==,type:str]
                policies:
                    - ENC[AES256_GCM,data:ITzy6uQ3iWzLyNtgeP0jQPmkBw==,iv:Uzdd7Tm7j0jyfV4ZbBkSD7wye0hBkJWDgYmMBiMgw+k=,tag:onUn0xOvz5psStM9y0yqLw==,type:str]
                    - ENC[AES256_GCM,data:vflgScreZ8gaHi2GZx5Ug5JA2zZz+JtjZqFt,iv:2f+Mi54EMMm1fnd02ToY0kpGnfHPvhVI9PRzE2WOz/U=,tag:2namgQ4NPwenzBlQtyikcg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:cGo/qtzPe5V79M8TduCmMUQ=,iv:iMMgCFaS/bwR5TxeUxOVAvQgE81xmy1eqTYo0+schYs=,tag:WU5znqgdc9bXeyuQJuSP+w==,type:str]
        - ENC[AES256_GCM,data:OIBNeN2Dp527qIiVtgpbMrOEh1M=,iv:aOP/y24mx+imvWxRZHKXq2sFCXw0QAFT+1lo1wMsMEQ=,tag:7LnwS8WDcYuZ9c0IJUMSyw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:FBnZFzjV94vDhJVALw==,iv:+g0bRyIrzfxP16Y2R2W0OFzC0XbmTr9rxKcrV245lgI=,tag:G+gf2QocAp6zxwquCSe/lQ==,type:str]
          description: ENC[AES256_GCM,data:urh9QpF256MfwTOXjg==,iv:Fyx0isgfEbTLrtm2w3+Xl7nl3S2qsPpu+Rg+moGwuCI=,tag:LA8zPmcUv5VkVa5hencFsg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:qPj3DFOnDC3SYHtnv4Ih,iv:mx6Wlu4BkcDuLgMNq3FDH0OhaRP/DQNNI5Dd+Bu+yRU=,tag:LKM5Zz2Xauw2oilwNAERLQ==,type:str]
        - name: ENC[AES256_GCM,data:p50Wz2XapWxUBcFv,iv:seJwgq18B0dWrYNRztKeusksSBEAnrVka7NcbKyoa7I=,tag:HzSBOkQE7cjuhciyV8nS0w==,type:str]
          description: ENC[AES256_GCM,data:vEegqhXwyzuAksC14Ttp2/EcNii+3G59,iv:Cd/dJxxOtz1XjZfOCuWPl4gmxtoepKA/veCUg2C68E8=,tag:p5crNw/oVnGkX6cin7hKBg==,type:str]
          deletion_window: ENC[AES256_GCM,data:AA==,iv:LyGRVhfQIpWZODR3QITrpkUUba5iMGUal8VLri1Fyxw=,tag:ykQU7GJLzcbIAvG7jUohpw==,type:int]
          key_usage: ENC[AES256_GCM,data:QZhVemXh3GS5NHbahVtx,iv:WwNE2gMXk7tGpCa1QrxJulnWT7TdrKhWLyc0Ci7t1Wo=,tag:KKGZvgiGj/lEt1FlIHVCJg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:m/rsO9PI7iwmFlQ=,iv:spF0Ji/+SuLmO/myypMnrflRq6EeEmxOFYi3u/uD3XY=,tag:vxLup2wEK0XOSunwGnHVRQ==,type:str]
          limit: ENC[AES256_GCM,data:g5fIl0WHn0k=,iv:jmMZdkY4FA1ZAmVYg88t+vUSuybj4GpOyBbPEZz9vfc=,tag:8oEGdOdl9KGXuiBFoRuO4A==,type:str]
          notify: ENC[AES256_GCM,data:AzQdxemHyEJGMvdrlFlP6MbhtYMOaDNR,iv:9Fpa++KlHM6yFRiIISp6QW6LcRiFk5rgxpObTNWIcGE=,tag:vylQQFNiRpjCMC+fA/VQYA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-13T19:48:45Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGPcLiaGnPLKvB45NwcWB0JAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVq/EtF8H2lww4oASAgEQgDuxMndwUDQI/Ipu37IkB7FHFsxL3mN/Qj4u1zJlxJlDnsyaYO7T3hJpfn+0NjcI8reV2W6vi32MjPooSg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-13T19:48:45Z"
    mac: ENC[AES256_GCM,data:xO3iVuAUEHleZFrlzub4ImWf2AnbWssyZRZRH7oTjXy0+4/0DmlyOHFKcd44NSwcpWknYRkZFCMmWB4ly1qYMyxjHAsF0/zpkjoTaoNgsnMAv+aOmK669RoOZzs3o9RK3IBmjGshPmS2X9zu1riaKa4wrBFx/rkKv0jC/n2lGyw=,iv:DZatI3MEDOaDMpG1TK6IKkkZ2mkqFW/NlRUzGaf4OhE=,tag:1jLOzaFrxwbKLOJrAFHd2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
