aws:
  region: "us-east-1"                           # Choose an AWS region
  aws_service_access_principals:
    - sso.amazonaws.com
  iam:
    roles:                                      # Role configuration
      role1:
        policies:
            - policy_name_1
            - policy_name_2
        allowed:
            - allowed_role_name_1
            - allowed_sso_role_name_1
    sso:                                        # SSO configuration
        config:
            sso_start_url: https://company.awsapps.com/start
            sso_role_name: SSORole1
        alias_to_id_map:
            main_account: "1234567890"
        managed_policies_map:
            Administrator:
                - AdministratorAccess
        users:
            gerard:
                name:
                    first: MyFirstName
                    last: MyLastName
                email: example@example.com
                cli-config: false
                groups:
                    - Founders
        groups:
            Founders:
                Administrator:
                    accounts:
                        - main_account
    oidc:                                       # OIDC configuration 
        url: https://oidc-url.com
        client_id_list:
            - 1234567890
        thumbprint_list:
            - 1234567890
        roles:
            role1:
                policies:
                    - AmazonEC2FullAccess
                    - AmazonS3FullAccess
                repositories:
                    - octo-org/octo-repo
  buckets:
    - "bucket1"                                 # Bucket for terraform state
    - "bucket2"                                 # Bucket for terraform state
  kms-keys:
    - name: "key1"                              # Name for the KMS key
      description: "Description1"               # Description for the KMS key
      deletion_window: null                     # Deletion window in days (Having this makes it free)
      key_usage: "ENCRYPT_DECRYPT"              # Key usage
    - name: "key2"                              # Name for the KMS key
      description: "Description2"               # Description for the KMS key
      deletion_window: 7                        # Deletion window in days (Having this makes it free)
      key_usage: "ENCRYPT_DECRYPT"              # Key usage
  budgets:
    - name: "Budget1"                           # Name for the budget
      limit: "1000.0 USD"                       # Budget limit
      notify: "example@example.com"             # Email to notify
