aws:
    name: ENC[AES256_GCM,data:7T+1vDQgbvMBnTVuiaX49CM=,iv:gmSHIz9TLwRmI3PTk/DKKJqZqMjohJrZqd7lDIi2A+Q=,tag:9UVxBbKiREbKQsWylxYvXg==,type:str]
    region: ENC[AES256_GCM,data:dKQ2GdtZXTv5,iv:EB2g3KbJdM8o36Twaqml7BwMnFtMKpD0SyRb1dQta0s=,tag:yTpm0F+BsiDKvCyT0mEWcg==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:fZDgQWt0ZxTNnB1r/jN0pMLLiLj/tysaOcCrsBHQdL77zgxEAF1mOZ3jgg==,iv:Zu1bgheuRH77d2hhBAFX07L95bZXqCYMzVNbU2WEpoU=,tag:L3RXnk2Rb3x2EtWSgG0FwA==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:7+3RVt/Tu8pwIYz25n2BdCc=,iv:yR0S/sl/99Ju1RSqyVkNrMV43rRKtjGO6MmgnK21+4A=,tag:Be7AO+7VMz8guH0Ax0ScIw==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:a2X1tY0LG6g7KzCazDFbPlezsKyP5wpv0eXKrDTtKoIPDJQjMcRGZw==,iv:c72VGG3raz46/nk4luGagTldxgDOY1E/fm+vTz3rg8I=,tag:8c7M9Ed6WWwjleWstp9mUg==,type:str]
            - ENC[AES256_GCM,data:zFsxq0mxBeqDg0ofKwgjfawXaIz11HBTDG5ro5Vujm8X0qFV4ESugw==,iv:Lp0Wsmobca/u3TZG9nHiblIp4vLxzLxQqskr3Wl3OtM=,tag:GqVbVS6F+TQkeICvpxuELw==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:NyoTJXpVnRUDnTcf43F1nMltow==,iv:SAySzmgV5ddTVfwWUuit/Gs4zGrPqpnRw5y2bF9hOxk=,tag:cOucAbckaFoefb2R2uxgCQ==,type:str]
                    - ENC[AES256_GCM,data:vV/YJyGkFYNePSIfboIX79aT,iv:kJ/vvi/tQwOZmKMRaOHYzM7Yvr3CCfFvOFnEV4Mipqs=,tag:HRuDaaVv5fw0RsdRhO63eQ==,type:str]
                    - ENC[AES256_GCM,data:eqCPRfmKWHFNzvrb7ZQOIwR7HQ==,iv:DgVbmwLiID5eQuuVGXVMpQaI6sPuSJtdxuLUbVGs/f4=,tag:IvooIZsIvJ3TMMHfoHay9w==,type:str]
                    - ENC[AES256_GCM,data:Zkr0CHEf4iZK5H8rAVdszprovJs=,iv:xNzKUlKWYEYV0wzNmxS/KVs5hjBMPmBv+UVlbZxTlps=,tag:7nWiCMJhSQPgfeeUAeb/xA==,type:str]
                    - ENC[AES256_GCM,data:o+v5KAdPzQDkf9ndGA==,iv:KR79MM8NBESXVINlewjGZfXEhnnD/AI4lDOoqn3DZhw=,tag:/L0/V2yrNu6UTnPz5oIU8g==,type:str]
                    - ENC[AES256_GCM,data:STIRJcC7UIaLNK5pFHCoQ78UVZoBeMzl3ABFnolAa5a2uoCvfPerGgOyRmrt,iv:EBD+lJtggpaUKpX2lBgUSSMLRaEpBMr/0wptwbvltpY=,tag:9qC0vk4eihM9AmZtFvreyA==,type:str]
                    - ENC[AES256_GCM,data:Vlzdcbd2KAuAtfbCKKDwi9a5TJbLiNub8mY1ShU=,iv:xrxhLTsGQywy7ZWMLbWkpG26dgk3sCN/W1DRRlatoDQ=,tag:OGKt98vpFdqAAsMGjjWAZw==,type:str]
                    - ENC[AES256_GCM,data:idTmgJfdxXDyDw1ADK5VFPNjgck=,iv:t8LyCbOS9avGX2nWbX8Pj2Ux3kIXwsfRr6zb1hVcjlk=,tag:m+daSwm+jzawAY8UmdzBfg==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:hn6fogCbZuuUqLsKnr+m47upTAkh,iv:IQuyBxjHpydbeTs38qQreZEetEU+lvVBLWVe1Iw3N5c=,tag:KJxmuAivHLVt1RToxrAHzw==,type:str]
                    - ENC[AES256_GCM,data:RAtk4oz3GqxVMNbZChk3lSEP,iv:E9wJZ+T+QjYInpBe78rSCj524w3xmnWBtBW5RXvnUOs=,tag:0ogcb9ein0WIEgcsnT5ulA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:B/XEh+pBYmQZZdw6H3zQQmg=,iv:hOuT0f7aStYF1qnvDJyEJyA0yF4IcwEbkOp500PoNeo=,tag:m8ymN1XAVyoDpHF6j4+dNA==,type:str]
        - ENC[AES256_GCM,data:XIfDKHVkFi4ntuKoxWSj9EDhM/8=,iv:GHkg5in+vXy78rnrwVXi42U3RMah3kWfTi3rOwolTjE=,tag:t+v2f7q9dhK/3OftX2DElg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:QhnEvnzUKHLyTfzLOw==,iv:oBes/0TtuexKp1DW9eSJKcNZq5c8S391P7IhKs5K7oI=,tag:vD7spV4TV3iNmbOnSRIQdA==,type:str]
          description: ENC[AES256_GCM,data:ozILwRILclBjIyv9Xw==,iv:qT6qnPqtYzdwrTpH1dNduWFTwvh5rvAqxUji06FjuGQ=,tag:03UGQZfnODJOI3wmwoPgbA==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:R7ChEOXzwlxKr1lxZTol,iv:Zn9rErD2xLHcSG60MXH+KpBZ5dSa6YuLLHt5mB2E/LQ=,tag:IfFa+GzhBZy4HJgFeYL9ig==,type:str]
        - name: ENC[AES256_GCM,data:WM4BH05lUkQYj085,iv:k4eAfTnEbjtyXGMgxKIIpfHuZjDKy9yFV9Ie+3HuL2c=,tag:LRnPfrR+gQNTYn1Ba13qjw==,type:str]
          description: ENC[AES256_GCM,data:udd1TJpI6OTf9r90Oq7MUeLh6DESPBH8,iv:SU6AXM/cEeQlipL3l7WlArJsgnVBV672STvqN7ZL36Y=,tag:zGPIT9o9z3mipZ0ZzuU9Yg==,type:str]
          deletion_window: ENC[AES256_GCM,data:Gw==,iv:LwxpmVumrdZ9bY0qmC70mK2TTDrgAoLgwixQvS2EtFA=,tag:+z5taeCH3kLkeZFP0CaWqg==,type:int]
          key_usage: ENC[AES256_GCM,data:HUWZDES8WtSKbLXja3ci,iv:L/tzSlZXMVSHK38vjyZEpQP8aqEPkl/yBJcZzYFhDoQ=,tag:fDYxdUSMRTC3naO+IDKq6g==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:1ROYSsxYZ1pIWWM=,iv:PFyGgpTfiWi1cU13Bvv5rbvq5rGlgccl1b7KmYWSS24=,tag:w+shrX+zln4GMKEXT0iHHQ==,type:str]
          limit: ENC[AES256_GCM,data:VSuaRTvdicI=,iv:Dvng24+lERwCHWCEe6uELz6yIj6+tz32+0p8ISwwyuA=,tag:cpQFx8FkGsFD79H58raYXQ==,type:str]
          notify: ENC[AES256_GCM,data:xSJ0Q0dzvsLzu0/YCKLwvXJ8kWzkvISX,iv:D98KfOgs4fuZdETEUvb9fXe+KLEAti99eAwr+DtM2x4=,tag:xDMYn3DFxvEvj284m5qGCw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-01T18:14:12Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgF8XEyMkAjEahu4dvBKc17qAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqMHylzOVLtgFrYYqAgEQgDu3oPzGHVQPfaW7eqCKvT3N37uL3iwJheTPUbzb6DQ/i4bL9E/4ZFRTU7odvfq77XyHxV6ZpcqZP1uMEQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-01T18:14:13Z"
    mac: ENC[AES256_GCM,data:0bUSbLb9WMxxzYMi2AkVGoV1RjKGFfzN1ID/Motcum+eHkLS1/nmzSbkHlS5Jy/a/n1Paw1OH0z7fv8BDogvSiDKqB11SoTCMVsefCQxPG92vFyGT6jIS6WqsZr/ret/wg3XUzuUqRO4KNvm77akXdHXfTJQiffNLIgbV0+Zy8Y=,iv:J27whiJFKwTW8Eg/fd9SGWsCGouJW0RwPDVawpVdZ6U=,tag:aeOqF27uJCDdoUGHGgEY4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
