aws:
    name: ENC[AES256_GCM,data:3tJySUfGPUJT+5RKnLIYkok=,iv:6iHjnRKLLkNxk3i/b74lEBvqtGXV4DgSULR1sGtkfFI=,tag:vx6Fdoh0We6aO4M5UgW9fQ==,type:str]
    region: ENC[AES256_GCM,data:uHicVqFfUnk+,iv:jNRAGkwykEKbhqeyZswmImT3hd2Y2mLwXeZWTpkkU+s=,tag:ERQrML4Fd+j/ciyAgaHTPQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:yA3DmJJrJBslGrsZneCDZlk=,iv:F0PJC6HHdyAcVZk7tSsRtvAaU/e24CodBG6EweFutoM=,tag:NKBQAZSK4T/lHIIonyBuEg==,type:str]
        - ENC[AES256_GCM,data:21YucABW/WZj5Z0CHk64p+kC5g==,iv:TegE8QfFxW8ByFoksioFbqSpsEHI9JjHimH4BoaBGuw=,tag:4D8iDbVRWePRl8U6pnRxbg==,type:str]
        - ENC[AES256_GCM,data:Uj7tYp5k1J28xR3SHthfPcJNDK0=,iv:7FWIhYE8mFDVa6Y+NsfS0DPnE/kGigN3O5/7jprY+OM=,tag:9YBmbmh+RcL0WeFOVO8X+A==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:VEqdQRpRzsuhJXu5fg==,iv:tLOghpEWo69H97wl6r/hTyJ1CAQ5Z/J4sW/y9siVU+I=,tag:p8zR6jcii+DZO5kdgpaCvw==,type:str]
          description: ENC[AES256_GCM,data:/7Csb3IUS7cj8CwE3w==,iv:MTVAj3MMBc04at6FGf1EI43Sq2T+m9oXUofbJ8fm6Z0=,tag:VNS++po389EFtH8SWoUq9g==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:ba7AR1OL+bJVwlKRkjV7,iv:59FBsBEi/8qrES9tTTVuOcT/Jnl18V5U9VMyabCmEy8=,tag:iZxmjkk+RxLBfKGswaH57w==,type:str]
        - name: ENC[AES256_GCM,data:B1nLrf6Aym4w+6Kc,iv:bvO5ncczXq4lo7nFmHI4dKimTAVqRxvj1bkIeTOGQA4=,tag:88iB+n/bMpTEOpR0QTWolQ==,type:str]
          description: ENC[AES256_GCM,data:AlLlTSkFFKWBXSrkHTti6blGUpwvL6YQ,iv:lBeD5dB2HBGTFZwUF7VoW1HY0wzPwCkhmljdgsiB7Pw=,tag:26niTZCRrhhFQZdKHNPSWA==,type:str]
          deletion_window: ENC[AES256_GCM,data:mg==,iv:WCcqnhrpT3MJULUJs8kWgsFmhnKMbeSKSA0y+fxvwME=,tag:dsPel/y8vm8NQ/e1vbkTrw==,type:int]
          key_usage: ENC[AES256_GCM,data:z9Ze9Lzsw0Y3+B1tp1yh,iv:5vpvzOm72GIZVtXOCZmtqRr3b/Fq7RIKq9W79/eRtTM=,tag:oO1BthRZV0VFSW+qC6yQWg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:+JmpK/nLeV6cyvI=,iv:52WH56ciLjrhJDuCa3ATBuOVu6/TRh838rYz89AGmaA=,tag:AOmOVU0vHFtMx4PwOAM3OA==,type:str]
          limit: ENC[AES256_GCM,data:m4535uNaEXI=,iv:AM8AjgSdKC8hO+t4B8SFJwlcLNLEYTuNbWf3qz7y5gY=,tag:om2G+Ax/m7bLoai3GJu23w==,type:str]
          notify: ENC[AES256_GCM,data:USM3FT9QKcZTUY+6lnrIZ9OAKXooYD5x,iv:3KWPqV938cg7jRnO4AdbE8idWzHLqmTgsbZ/uQzx278=,tag:6tbspzvRJiC0C9ezX/dbcQ==,type:str]
    ses:
        - ENC[AES256_GCM,data:fIYNe5Z5uIvrYOdtTRWfpW6jQYZMPBjI,iv:9FDxuqrSn9qnoDlokpDsOpd2bM5AHbkTod15AqKEw0s=,tag:B9XdXcnmZMtLKLnmTyUHMQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-05-28T12:20:09Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGLSP2ju20rGWB3FP/HdtlwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMm1c/e4jZuc7SChVbAgEQgDsVXxnpwthmvIkpAgShDJ0pKtjw1PoACYCJJ4QpfW/Ew0L3FwFjduJumQM2oBz9cL3fiH9oFYm/VTEPLA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-28T12:20:09Z"
    mac: ENC[AES256_GCM,data:BrAIrdyr5pLiZr74LWIwnjwAaQ4oFA9BZBX5NIgGYJjpuzt0MD88UXFpwdLdvu8FLX2n08Ry6SRwVPsf78dyMNPvHSPO/PFfcP710n0IJwrd07nBHFtHJgNV25F0VyQ1HLxyZ4M/qVhQRHdgPImDtqWEo1rghHy3tqP0YrQvZs4=,iv:0lFCNTVRtRSTdvmzq5m08PUkvMdpHH1+Yey1kP/U2ug=,tag:/0qWBb/UukO3zDB9vUaCKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
