aws:
    name: ENC[AES256_GCM,data:DAhHVdvRQbyi8P1vZNL230U=,iv:KkVEfCNUqFijaysoO6tpeUCNOkqMzynGcHLJ1uWmMkk=,tag:OqqfDy3OCrjn6zdZbbsUMA==,type:str]
    region: ENC[AES256_GCM,data:OwryYalbs3sH,iv:tziYKv1KEGedIqQoGJzltvv+fFwJZwga+grTtAny+jM=,tag:GZWc950aRePoPgZrMahBkA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:ubSA5+czIg8Y1ZrzYiVFz6I=,iv:Y6LStLnxN9EhvTQp9doXdEwaNp+S3647kINi+gMjzW8=,tag:sNBPCrYncRjesoxjdf4PxA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:wELypxhJGzL7hiveQg+wcerq7zEu2fpQaGquxbgS,iv:HfUgb0Zxf/1ubTx8qQu2t3gz4rycDZPz7lmWXeos/6g=,tag:XazgwLo0IqSeKKdVBlVM/Q==,type:str]
                    - ENC[AES256_GCM,data:B3v6wF4vNv3sPy8/WM0k,iv:R9vBp0wczqRz39HAdtMPyeTsmnQKCDleASrZ1jOcI1A=,tag:775p1QuGMHWBCMTNwllnBw==,type:str]
                    - ENC[AES256_GCM,data:ELZn8bcahYP2v6iq1A==,iv:adN6tIuRxJW0jOrsMENeKzp5hlivCyuaeNLDdnrTmMo=,tag:ay+1axh93I6wwcaWfRLI6w==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:vGuGBMFjG3VZkmnOCg==,iv:u5KlNFZ5L9ZBo4ciSngZGt0cjJnGk5G74BqDEMClTFk=,tag:xwEV0RzAmQtBNc9xv+mdOQ==,type:str]
                    - ENC[AES256_GCM,data:MDFR1kmCOf0au+2CSAE=,iv:lPM6rT9NWOzC7iO+zLpr0rr3/Yw1x8Y7lq1jBAsDqFA=,tag:rEXjhU/CBDv9ozAULtHsCA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:A3DzwkMYPTr4VBnGYVRWQCLFiQcTt1ZvfO7EPkkKo9NSAA==,iv:7nTwpkk8rdqoMUhYhKir7w8tUPXFabQJR/hLLHj2+uI=,tag:FYbaxKibvSBpGLIT8wWQJA==,type:str]
                sso_role_name: ENC[AES256_GCM,data:7rK68/kXPgS4XOdEEp/HPQ5e0Fso8g==,iv:H11vWLxPQrKo9wLSeCYdt+K9kDALB/dz+I104vD8Yyw=,tag:lYQT6TkNtd5EiTF1Wust+w==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:mi04JOqAeIHiKc5e,iv:g6rwKSqoDFkehpRZ8o6qo8kz87XriPOfgy0KQaI32rE=,tag:u1dgEqtV1RVHb5uRoPlW0g==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:pCsKfgNcNS0U8xJ7IPHpjSpdHg==,iv:eisU/8OZopesUHgJnUS3Xr26tSvpzmq3tnPxBEcuJaQ=,tag:BD3CxwFK1tvDPopbH7nDeA==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:HYUq/NfM,iv:xyvMI91a9zs7m0Y5TphgjJbakLqxg72212Ta6iqRF3k=,tag:Bm24YHRBhmJJdPMw49xaxw==,type:str]
                        last: ENC[AES256_GCM,data:EALVYvfUxO0=,iv:Rx+gIvUMAiFg03FNNIVy1WwpmJX5fK1uDJ3qhGssJmU=,tag:e9vhUl3mqxMRhwdT6qgAOw==,type:str]
                    email: ENC[AES256_GCM,data:d5DQ6jFP3SwfyRsC37N0RzjJHYt9KLUe,iv:cezKA+S+qZj04iJlOFfcsGRK4GU7rxkBSfT+kCbhJwY=,tag:ErZ1LvKlYP+Iwx3hrboliA==,type:str]
                    cli-config: ENC[AES256_GCM,data:Ll/ec8I=,iv:vBnipfeuK0tdWAdK+Zjn0e7tq7Ve8Ir6cJLdRsKrtH8=,tag:fcwIfm+yPvwmrhE/IRhFBA==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:zXkI5BkPQHg=,iv:eTtdp1QevVQdIuZw6/k5oL22PxTA39r6CmeWN/1f3dM=,tag:p4/50D+vmiqiZYAoolUKqw==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:L1ENLjF/qo6KUCfg,iv:o0mASld5HU//RidaWdt+ss4TyMhIYy5YIjXcQDGpJXM=,tag:0itq/+LUr11lJ/rMD5APZg==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:IeUsotNp+O4j/6zsl7pG7WU+tN9+Xntny/CtDhWXY6VSpld5FInPQ152CQ==,iv:lwR0gWraE7PLiJcPpS69bt/KgWwTJOtSrPEJKUCmtgM=,tag:yNna5Oi1JqI6evFt3Ym/VA==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:UXn0XtHH9n7BeXd5ubD14hk=,iv:iEWk+QomGlsStAi3au+EcpHbbCT10xUFPCBFH/GKEqM=,tag:53s6v5RgRou0uFDIKONO8g==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:3M9e/LHjwFlrvplaA0lhP8tzjFWg6XwaA5GM/0msZJ+8x6bTfwcZkg==,iv:Y4iqGneJjeHUQ8TnArycJ4AqrhKcOPeEY63m/Rjyumw=,tag:1y1KDpkzMnXOT+MrsiJEIg==,type:str]
                - ENC[AES256_GCM,data:cmvzPk0Dt5su+FxOwDh5QubRne9xV5F0wh6W7C09ViqwnXkQX5S1jA==,iv:fHGcX6/+h6UCVcuyynocRtpLiOfnr91SMMz3kexOAvc=,tag:QFfMBlhBaBJtd9NypDNpsQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:G4lUcPxWANE+okcq1LQJieQI,iv:2cPWDfhIIbDeRWMFi3aC2pMiK83OaRJalDEsh0tUjQg=,tag:bHBcIUKNnTWYbK84AoqLAA==,type:str]
                        - ENC[AES256_GCM,data:5vdogqwuLoWAVGyV3iOwwvAd2A==,iv:kapH4GiUkRNjAVJOFNgEMEFBvS1AypVz1nl2Ar4HRRU=,tag:f5V32x6qgL609aoUq3CF2Q==,type:str]
                        - ENC[AES256_GCM,data:2lHzgeENleor6Kl3vw17VWvf,iv:ySfBpzRMGFJ3FgK3fRTB5wVM2liFwkEMzvS9IaPFT/o=,tag:ZSRk0Ibu7ZpaEcA9IoGViw==,type:str]
                        - ENC[AES256_GCM,data:YXLkp6cAHyIX9SoD+EeM/70ZXk2c1g==,iv:SP9tH+P/FFU1U58b/MDtYYczB80dYnhFhNGhGyfIFlo=,tag:8EtwnRcYOCsjqG5swCeTLg==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:3aaGW/w1Xg5wP+QDBw2z0w3ZMsAc,iv:ExaUHwhmXrOFgWK0Z2aPp+NxLL6bLir4IxITpc/rJhI=,tag:ircxyqkq1GUbQjAR755E5g==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:j5xgJlrM5ZHEtcSzHHWz9kTgkWMC6QPRxs1RTKI6,iv:EYNDsO87FCYJZ1nSCCSKadIRuqt0pmOjXfIycDU608k=,tag:0dx9+HYZ0t5f37+Y8DWQ5g==,type:str]
                        - ENC[AES256_GCM,data:PlVkoWwVlnXECLWrMPRq,iv:dpAqt/8u9U6/JNQpcB3z5UdUg6opVHO+uWs3ctNbtZM=,tag:jqtCxVLY6VCV9yK0WkAAxA==,type:str]
                        - ENC[AES256_GCM,data:p9If2LD/JfsL9OThNA==,iv:dJiRgIbq+OIuQuEHMZvhf2vszOhJQaYb6vIB3dT6aLA=,tag:BLOJBXgIddP1RwDg/a7HKg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:9q4BVpi2dKMivWijHMI/fhs=,iv:y770Pqwb1xp7DJSBeVoE8JpK3vNLM0vFcEJjEYZyd8M=,tag:Hly608kT6vp7ySEzI0Voiw==,type:str]
        - ENC[AES256_GCM,data:APRRDAMYxm71OsDhVdeXJIfmkGA=,iv:GxrVPr1vLlfl36JAvwOqySYFKhZL5PGRdtKpaWDzNw8=,tag:ZXq1Age+TVz//8dZn2kFXQ==,type:str]
        - ENC[AES256_GCM,data:/t1luBalHHs2w0l+FwpOgKiM,iv:EsY5wh9qUsNMfw8OVSRzToQhSLm/ct+EnWseZTNnHnc=,tag:j2jnXvFV6NtMJQ6iA8ZEJQ==,type:str]
        - ENC[AES256_GCM,data:b3U7r1/ZVQYW0+qV27oMkP4=,iv:6eG5ooI9A3kAOEImOv0pcR7lCwH+8nGJkQIDWxCjid4=,tag:DQkreWgPv7RlLqfS0v685A==,type:str]
        - ENC[AES256_GCM,data:VtJbIbMb91zR+pEM27Gts3N0gGxT,iv:ZrrUx/kLCaKF8xT2y1CJ8gyUUvtaAhGRwpyP4mvWGpA=,tag:rP3QD9+0SctMC+e21ffFeA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:m62Wj7mZmd0UzsWgeg==,iv:ohFa+5rN3gY2a/QmDow1Jkho8AjEQdo6tdgyGvL0VPo=,tag:cNvijPK0Cq3C0dYRzBGBHg==,type:str]
          description: ENC[AES256_GCM,data:H58YV0OELOpkG+L7Nw==,iv:N1HseRJfjXHQ5F7VTaQqmkfemdQZMb7kwfj4Jpi++lg=,tag:BOYM3pkfpGaPrfoV0NiUdQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:qSEGGXG9k54wA74hsNcG,iv:AQ1SDVjUlIpCLri4Ib1FHJ0IAiIgWWsShioDI+L8ZjU=,tag:tmE6II/MER8aRl5/liWwRg==,type:str]
        - name: ENC[AES256_GCM,data:/l06qcnLvCJg4d8oSg==,iv:/n040NUBe0B9AvH4syW4llE0rhCCAuAfkcAGiQk40e0=,tag:5DVYTspq5N/rv/lDEElfuw==,type:str]
          description: ENC[AES256_GCM,data:7MQLC/AmZqxO5e/o8/jD0K3YJFSo+X7uQWnwPTej+90T,iv:aXAoiGxfcSv9myNTyJ28wm2bhAqob6hi98WguoSPvW4=,tag:bBEJbT5qlgEIOKHLmBh7Rg==,type:str]
          deletion_window: ENC[AES256_GCM,data:2A==,iv:pmngBN10zxvlQYCwCg3kDmzzpoyx1uG3Jb4Jtyhnyu0=,tag:FEW5ENzrxp/ZR3FyxtVYZQ==,type:int]
          key_usage: ENC[AES256_GCM,data:jim1NsNc30x/Klm96MkJ,iv:NepGCTihoO+4XFhy0gN5Iz1H3VT5sPURg2OtT9i6su0=,tag:BhKVZuDLcaYPK4wK60z6MA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:kma7nCLORvqN8Ic=,iv:epqxDjqsG7zGdg/Lm+oNNBk4zEWKLjnOVjZW7z8dnQ0=,tag:VCZeIYSFYGXhy8oj3Zj2Kg==,type:str]
          limit: ENC[AES256_GCM,data:WuPRxU1mIQ0=,iv:RP7Mx0mq1aHZf0iiLicTqabhY20zkIl/UWmQsUhRLFQ=,tag:DNhTmYFpSiYvm4C+cbpDow==,type:str]
          notify: ENC[AES256_GCM,data:iZCnejW8qfWAcU80SvxmGY0BHq423ep1,iv:fcRM4X2wEQruyGIlm/fWoUgbnOsqO3pFrCkOQn7m7J8=,tag:mUtRtP3yNee4ciAmkCXaJQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-07-06T21:01:56Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEBaGbBPc/uNT30IaFUwqpwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQckj5JQSKV8IpqIuAgEQgDtL5PLTtTOzGwnHpnrS1sx9kcesCWUW7i6UiC8frt/msToxW862z8f3rf+0lZCR0VVF9t0P8If9ZkJsjA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-06T21:02:08Z"
    mac: ENC[AES256_GCM,data:vBO8AVXSd9y4YOefKMvigRRMNltZ6U7bXUv6b79M4Ol7aSiXHpz+y4eE7J1Wx1qoB8GKkSG2G7PXgdR41jQzuH/Md9C53HD2M/wnLy8cpdLJUexZ48E5TW5YPoFaSmKi1GYrJgecAkPDSTPuvyML4xfwfHmO3wDJzujOT2FW3N8=,iv:+7nltMGFysuGPOTrQwQkTuM3wAsA1bCj23r9TrhmXXs=,tag:tkro6oklFp/z3kEakyJi8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
