aws:
    name: ENC[AES256_GCM,data:stqMM/yNyCIijgM/QwQi/LI=,iv:vgNrBqaoFmsf24sKBa13m2Uwd3yhrgeMHuhMhYITAwI=,tag:3Ewe6WUvCjVrjsjez19GJg==,type:str]
    region: ENC[AES256_GCM,data:tMY3fTzh4PKO,iv:CKxmhW6+1eEZU+jPStqvxdzR9lwuFk1j/RGp77o14sM=,tag:oSz31T9jML32KMKdJGkZuQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:Ehs1z55aAcDkwcVa2g/BlaE=,iv:pSh4QG1ywAH4MDwsWJcoot8dV6aqgRRZdwLoYPjDG9s=,tag:sU79yTgCSby9wPjym45HLQ==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:ZmRkn8ca187O3iGEqECEuyFTiPJW66opFAcGxhf4,iv:pH7UanYWSZkf6QweQQnauI3waxlPMDIMZJV/1YmaaRM=,tag:c4dEA2pNi+Pn1qFZv3dFOw==,type:str]
                    - ENC[AES256_GCM,data:j8N9ME7DRMWetmmAN+T2,iv:T5HLK65UEbwgoB6W9HLMeFuc1YL5wkmvyeOgEz3Had0=,tag:Ke6myZYghtqBtJ6uXlO7mQ==,type:str]
                    - ENC[AES256_GCM,data:8KeeF4tqe1SsQbTOEw==,iv:ZIw8WB0Mi6w7eGzBrm+KBUGSBl9DmGRQsfZOkaZoG3g=,tag:TCqYrQrvBgqsqAKCB+mzQA==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:zWikQzMtoWBAKQdTBw==,iv:X5gLvPWs3cGbKLGYtbs00uVB0A3cyAMLqWMq5VNR0Us=,tag:iztRqCFEZUmOBkXiJQti7g==,type:str]
                    - ENC[AES256_GCM,data:GB1A5UqDJvASwpyKQWw=,iv:UQCi58OEneFXR8wC3Ke99mtDJpzMVvLsYC+6iIpxtc0=,tag:5HMDJp+jz8bjyfTsq/zSSA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:WH3CoUmFbTxxwzPTXXlKNYGt7i3/QKnNTw14gG5Dw4gcLw==,iv:TEqtnEdE1DShvBVMnpZYW/37ZYmRbWNHd0el9clUOBc=,tag:QUO99alDHZZ8JTvYadxc4w==,type:str]
                sso_role_name: ENC[AES256_GCM,data:tdnyxGqGg3wZIZTlNCwMKyGG0ayCpQ==,iv:mQ9SvhML96bpjs7Q/4EDAWB7HOtjqHUuEaXKbfFS1CM=,tag:6uaiPAu3uedZcUSbSUCpvg==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:JMtW5VPfthkYlOmR,iv:9vodwSPjWdxc/GNMF/T2C/YIvXpn1yUm0MN0gMR1KE8=,tag:vPFnd2/E3D/DlxytqR4fRA==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:vRWfZ6K5/dEHw/pMqoffBx43+g==,iv:aurNrkaV/h6E0Wi6qavWRX4JikJeb3xWMAKD85cl6l4=,tag:sZf6UoHEIvrutlp9pNUd1Q==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:PkMc6DE9kW/bZqqAv9tF,iv:nIiOj0/4Fwj5OsONx7gm0d7xM2pPAx16KUzxytawoQA=,tag:9Mihg2X8KShucQSkLd0Cgw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:YcoRIhwP,iv:+WTBhM6j/JIV+aT8qvI6HSla8bBfp6Rrv2icBXzAreg=,tag:m/5P95KBxGlvr31latziYQ==,type:str]
                        last: ENC[AES256_GCM,data:E+LPwV9DvKE=,iv:CywPinBn1/gLfG1uQFMNHoubxstEFQRIHMWhMj9ikmA=,tag:DkJLATdMkFhaFEnMMNu+gA==,type:str]
                    email: ENC[AES256_GCM,data:OC6ri6uUmuAcISNlQoDWdCMj5ESmG0ZC,iv:NrITfkcASe++43RRRDnIgoToq/hVJ1PfmMo7kEmpKBw=,tag:aO3+gX1x1WFooiJDwY7Liw==,type:str]
                    cli-config: ENC[AES256_GCM,data:44KpA70=,iv:v59wJ7OOxSjP2J35lmJ3sEJcozw/0O/B5Qdui9aYUuI=,tag:HUyHyiG/W9vHxHQR3sBkDA==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:+/Bu1WEzJys=,iv:c6vNNDwfWXpnOCdMpUFoWTJue3Cf4ijTciks99XIwY0=,tag:PzrzxQL/wgaSKe7hqHGYtg==,type:str]
                pezocion:
                    name:
                        first: ENC[AES256_GCM,data:BrzZfFFNS1w=,iv:/FVtBRKqplQ+kZyd69822gbmlx5nYGdYsUV0FWRurFg=,tag:sF16z8pMXs6j25YUY6zAig==,type:str]
                        last: ENC[AES256_GCM,data:DRID7OtVD3I=,iv:cfcIV63wlpMQtIqb6cw/Ou9pcQNmWtqEZpr3MT4gwiM=,tag:O9NmIXcOpa5PGOSLsmuePA==,type:str]
                    email: ENC[AES256_GCM,data:eMJICi1mIl0fC+T6LkuSDy5xyIfxjJI=,iv:TpQkbuQvVbKy85c1lLeHQ7SCnCenXGoyRD28fG5u+J8=,tag:KyGm5bEDx1QPdtMC92lkyQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:X/c2WRY=,iv:PQ+LHEK75nvzD39/1mPQjD0ZAqmraNsZSBExCKykS2I=,tag:9iDWwGzRJ1NnObwsZ3yLfQ==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:JDtlQ39dXzvv/uk4,iv:Ri4J3BcHQ+4SnSlhwumD91GLQbUfMJzkwGq4MCt/7go=,tag:NHXyfdeQAemgpaZqcA7+KQ==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:QAewD/C3h/kVwKBm,iv:64r67nI6Vq7ErkV0Zn0MA7NvM4K/Vh3v9OEtb+npHGw=,tag:+fYfT7jfLdHof4LToigG5g==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:ORjO0SSVuAIpuGO/uoYoZFhTKkKQi0xJ0oJX1tXhVVAPEWCKatPwFaK2Kw==,iv:mbRwfggr+yS8g8Ei6SXE2WS+R7RyGydPRm2RaB6GVIk=,tag:xGXXmiFHkCeSBk3tezAz6g==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:tQGfwQFWEImEEAw2G6KT8n4=,iv:XVUsaNqKTyz2BQZRG9kI9tXU9lhe17g9WoYI/xjg8es=,tag:HiZvcnhFae1JJftt0bH2lw==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:Ned67FF3s7unjaEDQvRh6N9yP8hsyLjIJpBxE62+Kq8sCIaRCrg2Fw==,iv:0EkjC0QMVaTofPWmxDGHvhf1VmUXl9JBVvcPQ7LhGgA=,tag:l3caDBD7TUbc85kFzLQI5Q==,type:str]
                - ENC[AES256_GCM,data:8KUINZxx0eeKkCFJ0clCjCPKSeD2Pi77QwD2lucZouJkDO06kurF6g==,iv:Fio/xs0mH3mvMUUM5HJpD3nIs6p3blCdetIG7X88eYo=,tag:x6xW6MjZq+ywQ9zLUqW/gQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:tvCSX3sYlIbvMa5GT12N+HvE,iv:UAfBLWz08piK1IOA5wEmsLtp4OttNkK7PnLh3pOMHmY=,tag:WbEIapA1urJDqxXrNZufXQ==,type:str]
                        - ENC[AES256_GCM,data:PIJ6wD7O2ttQiboRnFdt8rnidw==,iv:/kh98kFBYhJckgZSqxxjI8Mo781Cq+RKwAckq3S+fH0=,tag:+Qy9GLYMgMZJzYcVjmkwUg==,type:str]
                        - ENC[AES256_GCM,data:nfWo2qxG46xklueLag0Q7FLv,iv:BVxdOOnzW6/H3CVgUDN8mEFEcA7AkqDW+bzZTF7dHYE=,tag:7lGWizLavfNCIu9rDFyIdQ==,type:str]
                        - ENC[AES256_GCM,data:vrJTb8exvx05HxpMDXdhJuyOkJHWzQ==,iv:rw3LWjfIEWGVuwOgg4obWvAAsg71BbTL0olpMFnucA0=,tag:iN5tsBuDBScB4Z/aRyKd7g==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:F2AV0Bi3hqpJB5j1j57cxIRoQdHs,iv:lVQ9Cb7AswH9cOp9h5cmnOKpqJl1WeTbY3sDhtIyDq8=,tag:6VvjLh5Qj3KpJrLiGF4JhA==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:D8twwnAeTk/gNi1rpRAmif8zR4umMXUVIV1RrTJ+,iv:BILr0xSfFRAOOX5U23z/BGZC3sFbg3sL0hDIdlyO5T4=,tag:Bs/8VEnLx56OTrMp7R3FXA==,type:str]
                        - ENC[AES256_GCM,data:a7D5Jz0ovMjtCVOZLLwy,iv:5b6NuiAlpykcSWwSb8eZAbrC9LqRGgUrk/LlB4NPz/I=,tag:GL2VN4IUpS6zk+zhSbKChA==,type:str]
                        - ENC[AES256_GCM,data:4AoIZc5Su3F16MxJMA==,iv:/dIAG+jimRyxITpZmu0yZKjGLLltSqEU7nSy+4FwWr8=,tag:UE/zwC2KiDNjGfWdfWEnow==,type:str]
    buckets:
        - ENC[AES256_GCM,data:RyZhLixaRtZuJfXLKgkP98Y=,iv:GAVhXnKkTdxjEiPxYD7UEZIYkzHHp79lAwWzzhCzxuE=,tag:1N8vIoJJ5mPLnho5A6uHQA==,type:str]
        - ENC[AES256_GCM,data:XoHaZWa9Tngi+pgehFXLTRbtpoE=,iv:n8PYCmICsFXcRhFa2RtySHXENxG33g9QG/Lm/FN/J+U=,tag:/OFSu3C484/jqg8AHlWlmg==,type:str]
        - ENC[AES256_GCM,data:3xm2HalqOBTVkO42Za/bCl5G,iv:Mrfev/qJVR3lvnNnud0d7kN6Dsh95UfTlmize3YNz1M=,tag:JBkV7zgeREdCgEyUE1atYw==,type:str]
        - ENC[AES256_GCM,data:57U4U7rkuhcaQ1sBhSE8TPw=,iv:BIWOkgks3zBirlbUvXIiIz8prBLTbFNzJc8pv7S9cnM=,tag:BRZpEcygAF35PEQXYxnCJA==,type:str]
        - ENC[AES256_GCM,data:Da3n/qdjBUfLVenh/4ohMsIfBgY0,iv:2nno79H9M5yEstHMkBxFfUhrIHfojLUm+KxTO9+8oME=,tag:J4mf1cGJu/o96ez61ptxBg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:+V7tJLRtDzKjessqlg==,iv:9MtjWJOK6KpRESQ028B2oxmpbuyzzT7Io/o87C4TnFA=,tag:GuE5FO2ZAT3R/ro7/UodQw==,type:str]
          description: ENC[AES256_GCM,data:7DHuuag6R/bzhmEc0Q==,iv:djI/Wm+i+9X+3YNUcjDfF3gKJSZpzMLMr90+U0Y0wZs=,tag:NinXH5wmQTtDXwqBh8X5Hw==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:uSbN4HzuwgV2HTGUwPyy,iv:NvhsaIG9PkvjE8kyhBIOISFJdNTuATMRIJItp7c+zNI=,tag:B76UVqQRIN4EBIWBWRyrpw==,type:str]
        - ENC[AES256_GCM,data:ZUhpXq/e4a/fCgzeROcyHI587m4A01s5M/bcWBs=,iv:8e6rYAZhRoz/t2nxvAICZmfdbELOxz0SDJBQHfoY6GM=,tag:CrdtQ1x1HDoYUBCa9ljtLw==,type:comment]
        - name: ENC[AES256_GCM,data:fYokLNkc9CINYufu,iv:ZyDgsYLSBjm0QD/c3VXcxkvAQsTeoPO7Ta9yRyjviZg=,tag:rCoctuRDkUlM1KiJ+CWGJQ==,type:str]
          description: ENC[AES256_GCM,data:KupTn31vwNLApiDeB2Bw0GkV0BFRbM5n,iv:03ysGlBaTh1eavgMD1aRoQp6zFjRmBqvPfcS4Z133Lg=,tag:A/xSlvqnbcR3wIO/1aJJuA==,type:str]
          deletion_window: ENC[AES256_GCM,data:VQ==,iv:OOTHEMdz/naghUYzJyQnxFM9ZYCyQu14QhPAa1Kt/1A=,tag:kTUMem6HIwQNGIPXiHsaMA==,type:int]
          key_usage: ENC[AES256_GCM,data:6WrumyhfoqzBb4DUwPpF,iv:MvFCB8o7iK1a/7MSyhOAuvtlaqgVKAO+oIVSDQRnvjE=,tag:0tzWQtUMriv5fqwJx73r+w==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:HYlEum1XXSVzdA8=,iv:5/WdaP8NnUhpoNqAbuCGqMnX4uZptivoMkqCAzixrLU=,tag:sF1qnENQXE5SbSnm939SYw==,type:str]
          limit: ENC[AES256_GCM,data:ecl26fVouE0=,iv:rGixejDzYWu2X+Qc6SeXjMpkPUKdCJ16VHybKuCHpxM=,tag:4DVIk/8Ld5cnPkmkAJgjLw==,type:str]
          notify: ENC[AES256_GCM,data:v53Y0FjouX+iSRfTn7/32xsn0B6LLP+p,iv:Asv/L3RycUsUpnmJKWBfHucdG991G7XNkeNZMIwVA50=,tag:tjNBZ12cSUOlAZLchGjkAQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-09-21T09:38:01Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHYI3pQVYMrUoK77naKtPMwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+pV8xxX2wvL4CqZ3AgEQgDtMGIbRrAmkLJtNeFQWUfuP9a8fiJnm1seQa4FaHuev5uNj6GlUo9z2FxoZy2ct3X2GUbMT0/6WW8OcyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-21T09:38:02Z"
    mac: ENC[AES256_GCM,data:1RW+KPrL5TZoTPkgqpi3SyzGh/+2dhiBZlwv21+1bZUcIu1AFxgLRYNYgriVlvrTKZNv+8pXRiEigYTVm4mOgdujt2gTVN7+VmcEP8vrtYpEi1T21tp0d65Y5vVAdPuPSuUYNwP5bcCU6LQex29/D+LgQKEIixM6F87E7rZ1eUM=,iv:3pQ4PCEl3K8uNpDIRy3pJbUYgcVc+8i2Lo5lpsshp30=,tag:zHgpPP67ZMFFu2VsNkoXSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
