aws:
    name: ENC[AES256_GCM,data:/nhAhzGI4p2jeLsYzFoATmY=,iv:AfygNC/xyvn5R0ltltwcLKqK5O9GvoSLZZFkzGGnF/Q=,tag:cFOq2z5I3Vc7zRq7HNQu8A==,type:str]
    region: ENC[AES256_GCM,data:cn2MWwyMj85C,iv:3MjPFYxLsEInaHzjrAmJCn29LrIaxLKqyikc5zEdTQ4=,tag:6mZwVUDC6a0/q1Lvvwh5EA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:XV4c2Rn6+tFJR8+tgXAMNfU=,iv:rV9zFfzwGGqUSefDUSloLfkhhvcVX5M6WVX2wQoFH3I=,tag:wC4QegWhPjbHkVPYqBhjZA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:QKX8OGRdAZmlvauBqfaDWfjWyrptNZ9YxyPyTLBz,iv:Qisrodlai8R9jnR634HOVZm53drm5H0s3KGzWYeAYIQ=,tag:f712hT5Oyvc/38cQAEbMRw==,type:str]
                    - ENC[AES256_GCM,data:mBv+QCfCck4k9R6xQfrt,iv:neSaRywuBvl5/wt/BQl3Ui/Uqi9hruVKeeDjoOQPhJE=,tag:Ik4vWg0oE1EPDu6p8ho0XQ==,type:str]
                    - ENC[AES256_GCM,data:alo4hrg3BtSINgtbOQ==,iv:+mM5+Yj7TUWZ+6Y4SIars2vaftI3JmP0U0pNkiT45ns=,tag:UB1Eqa1MrrxB4PiiLA88KA==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:GILKEVICEH7iAA5bbQ==,iv:/wcbuY21DKE9Sqc+WN1YIzHHT74AkuO0LnrIZtuG1m8=,tag:5WGtEOMQVTfMwlkiYw2fNw==,type:str]
                    - ENC[AES256_GCM,data:VAQShkGf0jkIS8dt254=,iv:qBgtPs8dBqbKbg5+MJEPKj1Tgok8TAjXhIs/Bf5SeIU=,tag:DVZvw9dO/v4CRmAHIKYWKQ==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:S0Wk6mB4Oxwlfbzs62JxoC22DhotjM9HkGn2jtcpfLMiHg==,iv:viNTbUji/pVKZwRLxcDg+VkteVxZJuehHB4BNyBiIPs=,tag:Q9teklH8CtskbOZ+4bAZcA==,type:str]
                sso_role_name: ENC[AES256_GCM,data:P5gQOGANsK48/bANcB/qhDP5XqYJdg==,iv:VOmX4Te4FFlXpoTovr48jmX2qVLE9rY90AjgUnixrV4=,tag:Lyz7H2yycnXCHaAHvSyOBQ==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:2K1sJ7pQx1NlLUWE,iv:g8+tpKr9CZ3DxYNiCF6TJO2kxiIWawNxIlSLT8XXcY8=,tag:1tnRGHwhCsB8cK2w+MrRVw==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:1+p5csY8dAyF0hqRz4ojqrBmpg==,iv:XbqGX1TXfCn/W/R2fYbsIvcbXQNvgutjdewnT4zOFH8=,tag:4P7kvro8aOqBQS2BkWvZ5w==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:CILAKHDziSRacR3iC7Qg,iv:BaoYExsPV2Ec55CjCKHZl0hWBmQKd3/3Xubr7apgIhM=,tag:t7rTBDheg295J7rvkppaTw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:MiI+mBYD,iv:VxkdFzDXsHNVrFzzC+R2YuJP8lLMKf/Q1Lfmt2o/exo=,tag:Pal5D8a9CCh7g3Grkqx7+w==,type:str]
                        last: ENC[AES256_GCM,data:NkBfxadKEps=,iv:1elyNDz0OkWvD5JWusEgXm0EMHiWgHL0SnnMJXmrHRQ=,tag:3S2nQph6spkTk+SHEcjpGg==,type:str]
                    email: ENC[AES256_GCM,data:9D2TACc1oAu25Pwfx/Ggqiiiv3ZTlwhp,iv:XKZg5d9D7TCs7Tk1dYVAZHVkfAyTrqQsvhBkj627TOA=,tag:2hu8KE/HxT8cPj5RArWJ/A==,type:str]
                    cli-config: ENC[AES256_GCM,data:cRQlltU=,iv:eAK1D+P0eyZfBjqam2vnmxNmmADbJGCzEsWzSudVbhs=,tag:R4kKsjMbFvjgTqgkqJCsrw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:5qFhhcuWEB4=,iv:lEivGW1o/0au+0/uHgIkM91FHLIDibfHTDYM8pV2DVA=,tag:XP6IJcA9tZArxfVH5EOlng==,type:str]
                pezocoin:
                    name:
                        first: ENC[AES256_GCM,data:a0tU88Sk4fI=,iv:Aoo41C0bauXJbD4Z6y0t563MLgLymt+19Vrb8dqqqu4=,tag:7O743gC9kMph4uxk3GIZ7A==,type:str]
                        last: ENC[AES256_GCM,data:ySipHAhgR9c=,iv:x+iixPiV7ympJ8+IJueDQmy5IVqHDuQRNVIh11ZvZ6w=,tag:2nr69piYFbRJ0CrOsVVx8w==,type:str]
                    email: ENC[AES256_GCM,data:4iHWQ9Nbzh7DXY1MS9QFom5J6GySJ+g=,iv:tIISWAKTyvpcfpHeIT8bY7qiObL9fspIValax368YvA=,tag:4zH7fPTLC4UnbruA/PfADQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:mfqzeqI=,iv:EjZLMuEJbTp4c36/hozG5D1ORzMQt3wVv/EFhIjDQ9Q=,tag:A6y1m/pS3G/sOWsAVQffpA==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:2lBMoQrZiUBIpT5q,iv:U8OLBHrRheLwrKBhWgpocZWOyrEdKfAoWUwX7qTPWmw=,tag:v4n4TMnhQf/DvLmbqmr+8w==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:3J2hSriaMdcpkiQ3,iv:uYZLuSc2MJ/7Xv+8eUo6y91+yQMZzAirEtZ5rs5aMYY=,tag:iDC+VBpjZhl6AqfoJkb0QQ==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:ru32eM2zL0rfmPVJyoZPZra478GNGQwZBYHFtMC3gPGqqsEXCKsePBaS5A==,iv:E0IJ2Y4tQoWyJLCFvd6KRbgzoPCTWOozMaq5LGzqZ8o=,tag:fcOMKKURLzC5XtmvHK/xnQ==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:yZLAcmrrQy4G2Q4y/RPs97E=,iv:dmjZ799rI0pKlu7UeIWyhbSrmGyxSRnNNk5I04JzyHA=,tag:fgLTNY4i81MgnDzaGdYWYw==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:w8qYNhM7LS+OgRNQGmlFbK0gTmhlddzg9nXihbkB+V0KzKW1NDcQ7w==,iv:mqXpztOLxTWOrRfDFK/puOdvbRWJPS2XId9yKcLDQrs=,tag:KdTQwgraA3srLokHJ5wnCQ==,type:str]
                - ENC[AES256_GCM,data:IoSz3w4jquvaGSuQ6ViVFlm2P7T208VOt0D7PQoRgasmflcxWcgDkQ==,iv:tV7+jODWGtC1W2tQ8g3iVlUiCqZo5EG+ht/4Jdp2RUQ=,tag:bK221HmwRUYLnCVL7ggUkQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:m8Wa+Or0FR7kXL+ARY1RgN5C,iv:5xajb/eCZsY88+cMv3xWMghGMQNJ5wQYUgb4pqYvfmA=,tag:rYS2wLo8McjLJRCfXkuE4g==,type:str]
                        - ENC[AES256_GCM,data:cQURFgMpti73wUQj8tDwVS72Wg==,iv:xd4dXnHPoWQQnFsDKbEtNcs1p0tH6X+bXqcyOsgepqA=,tag:Y/LbdfDat+5TYtnKhqUqBA==,type:str]
                        - ENC[AES256_GCM,data:Wj+skXxkSL+MIQ5RWWo16pGw,iv:sPQNt+qiRGq2rkvVyeEr10+dOf7x6hXvylIIhfJVhCI=,tag:ZpSdMHKRtllmykELfiLPMg==,type:str]
                        - ENC[AES256_GCM,data:nSvbn4BiAKE9+cQdnCdKqeDrXcwdSQ==,iv:IWpNUtfmgHS9MhAb0XvfspXFTi/nICw1T4ScpqRHP0I=,tag:UhWJQ1qN8TKawHKs2CbPnQ==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:l8KgOV43b9SiJ/mxf3E3STcVXPbt,iv:JDF4vAdDGkiWe0ebCK6DE7D5JC/n5nupPM99keH/XjY=,tag:+VCWYTTkKuI3d1bbNlpf/Q==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:p2/fr9DXbtE8X19ClbWMPqDE2o6Wh/0YOqPNJQR0,iv:hK0zH0EjZoA2BqUw3CQM1PsXR4m+T1i1kpUzvnAqq84=,tag:dxJF7/QWNV4rMyFgZup4qg==,type:str]
                        - ENC[AES256_GCM,data:cpkyLMmNXPyW+sXzcVFu,iv:oPiWXcJKi5LdE8MIuCcssZfWIGtv140+/4I+JgYqpj8=,tag:WxgABBGi6Wz/7qmeVMm0xw==,type:str]
                        - ENC[AES256_GCM,data:yjUZy9N7NIHfgCCllg==,iv:W1hQ2h+U5vx9rDXQIPuvSD7yvaf3D8TaxK7Od4pw12M=,tag:dU/rUgGhl+GQNPGdHDKOeA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:BtlRj0KMqcBoqkim62BtVuE=,iv:kkXQQf7QQAVC1bl99ZkT+tCi9kPUlwcPBPWjV8wf82s=,tag:tUO/+mbrJZ9Fh/nr9GoHNw==,type:str]
        - ENC[AES256_GCM,data:NYOd607pGZSZHN8yGLCRsqXOYb0=,iv:r4p84JWsZ4hbpUJrNlpDhQ3X8MfTJWILzQ0VIAyY8ao=,tag:srStOyov7Xzoh7KVPEgJMA==,type:str]
        - ENC[AES256_GCM,data:CvA+u/ZTqJbxZ9a9ZoahyoJb,iv:mNlBG7gj47ztYodGMFOHEUHIcPx1xvs9+87EwX90JOA=,tag:hO8PIe98O1sPxhc1wDcGAw==,type:str]
        - ENC[AES256_GCM,data:N3JgLAYhFpoPYG0sh7mMBD4=,iv:XOyRZwuB6uRscpmLy0ZpTUElE0LBMv8xkggVhLCPCSo=,tag:9qE0IcGlQHuazIS82gIhhg==,type:str]
        - ENC[AES256_GCM,data:8o5wsv2P1nAAlskB0ZOrok8qUP8E,iv:CLs3/9ZtbibObGLdp0TX0x2KGUyznv5m1vbkSc1c1rw=,tag:rc6kfD/hjO4eLX9nKhTZZA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:KghQvX73X1JDHmX80A==,iv:JYgUTZmZRl3UD0KLdWJGePyCjq/KNuNHoTKR9JW4Ul8=,tag:CvPFVMV4xdR+JArQD3vV/Q==,type:str]
          description: ENC[AES256_GCM,data:W5tkU8GLCjk4T7Zx6w==,iv:3A4Nr9MgPwcvV+gp5Fd9+Dy0p9iHaX8BdWJBJj9hpdk=,tag:Q9Mdr5Lwi8IWpVmVlfFxng==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:7EoBFEZ6By8toNqEjjyz,iv:ftjSe0rbZBbZy4IpPkQsismAkiEPbqXVzI3Wr+lJCn0=,tag:cNnSB/khJrmabphZG3mk/w==,type:str]
        - ENC[AES256_GCM,data:ZODNx9nXRUdlg0ykNCVAhdgzDKuUlgCd4Iro9Is=,iv:KhpOXBlZXWgyA2ZrQ8PSjWpY4OgQ0hgtVy0/dsrsK10=,tag:hYTK4YBVFtHeVcwpDp4H+Q==,type:comment]
        - name: ENC[AES256_GCM,data:GO+hsmD9eV5HibPO,iv:xFpYoD0fmyKYG/HqIMzl8m1bqu1eCMLV1MbLMztB+Uk=,tag:EPPcXyU6s9/U/qx26iYMGQ==,type:str]
          description: ENC[AES256_GCM,data:8OhbmZ94YOQduXHLobf1LIZ3RuwZiwf1,iv:lKcIDRo9d32YcwvURtbVPVaMLiViWkARbdnIIeB6xL4=,tag:uFSg/sHwuoWsiEUGdST5mw==,type:str]
          deletion_window: ENC[AES256_GCM,data:/w==,iv:JyReMr++69Rb/qDkPvVOxKwA4XASAfPwBh0tDDd6RKw=,tag:KaUKtcSVx1NKUnbvYRxrTA==,type:int]
          key_usage: ENC[AES256_GCM,data:pDQo3OtMHCcAVWepZ+eD,iv:ng8vcaUxLdrNIPri2x63gp/DvKZhXayaYN13+rOJP4M=,tag:R1GPRHrIvw6yACi+jyRBXw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:8fvvwSrJyRIzSjU=,iv:5yfHwf3drDDG+YZ3JR4AWtuztgO46ognkCnBEbimyr4=,tag:80uGnOvkXaTsrPK52BsbqA==,type:str]
          limit: ENC[AES256_GCM,data:aDeDp7P6Wfw=,iv:X66m+mfSqs1TM6/07JDQ3pLOucypCpuwoDvjFOVhGbQ=,tag:OOe08PzNoU/YOSeUzNOReQ==,type:str]
          notify: ENC[AES256_GCM,data:CEaOm/bGpF7kunb7GQYzMaw0VD1RKyk8,iv:Pjz6FHS9n+15E6z+9fuvwl9NbK3HtKmSANfPvYgaBys=,tag:38hazEwuvQpUWYIM5J2NVQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-09-21T18:53:52Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEQVOElgStVVaANTCMt+QVJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMh/OqrVGFazWmVQ09AgEQgDuGjoC2gOY9X8TIDQROwHoSVORC0TMkElr7MGobkC8G19NlwqBmYAgbr/85knisIn1r/FNQLEIwo4BYDw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-21T18:53:53Z"
    mac: ENC[AES256_GCM,data:Vy2cPZydcH6ZN7JeEwWf+9t+Lorxz48nt1eaflMNY8nZS9mKaILh1Q1AAExhV/gWf+ZyrfPMGjw/gaxR1us+jiGug2AZVu4R+r8H5nEc4SwRJN88vppBKuMmG0I2kSozy0JyRxVZETLNzpQ8PLwHDML8amXPgTpJWgCF8N7eVeI=,iv:WKUsSLfYraGy5f1muo/SLa4Agh4DPk/+SNkbvPt+5XI=,tag:rL7xxANLRJ9fgKGFXHarPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
