aws:
    name: ENC[AES256_GCM,data:8rQsLXNRxzkLu1k+FSIobi8=,iv:T6Zr1OsudN6LaXmzumRlMXfvCmA/u/zgCOAbPaPG4cE=,tag:tbLn9/I15TAWaRxYdyAXcg==,type:str]
    region: ENC[AES256_GCM,data:U0UmEsitWGQ9,iv:CdHPbRsAiB40HSfieLQlGlrUHY+q7p2TTWrqFKlMIJQ=,tag:qs5N09KVlc3TTgODavX1Ww==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:SDQ8uz/VjMJMajyc/YDFTJ0=,iv:cDwDSsgegt8t7T+fPS80HDsm/haZQMsR9beAkiMlAoc=,tag:gj21QfLMMYVAviWGgMw6Vw==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:HlFjt0+V6VVs9oocM+Qmte0mwgxvOtJtzOKWXcug,iv:90LfmckEY36ARupJSQmavojpOGga0a3v3altQLBCCrU=,tag:qjg4SqGrrtrQDW5h0xdVSA==,type:str]
                    - ENC[AES256_GCM,data:96siway7wvW+VXa6tbg9,iv:2TwKr4HFRJrsq3TYrfC8k6AAlLIWuVZhUKFpn2TkXiY=,tag:EMd+M1ftC3870BCljAjZsQ==,type:str]
                    - ENC[AES256_GCM,data:kinUTj/jn4fPaRZXBw==,iv:2mqoGhali8MvCU1sjDibF1Lyc9EV53+ff1B8uwN33UA=,tag:nA3x+HVGrkRWEwasGI8mBg==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:9B6BN7IsoD9gvRyJcw==,iv:Eq99se+qaZJCZLrJMzlWXJbcfPROGLSa4CLBDI8CRs0=,tag:XXDHc1U28R9mUL+QXUBa/g==,type:str]
                    - ENC[AES256_GCM,data:FrTJPtJHU9P3OvqbNM8=,iv:OJbJWzpjTk4ejsebV2xJpwnBJdJVkyGx+fzC90qYHOo=,tag:26dUgpV1uwD8dXLbja5i7g==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:dJeZs1xpiQWWilgB67jJ8HtEJsVdr2eN0OKga0pK61WNtg==,iv:wWs3Vr92vSQFgKwhK8PFlAyBh00fNZCgIng5H1fH54g=,tag:pWmD1lgIEXYBO/01x1KBgQ==,type:str]
                sso_role_name: ENC[AES256_GCM,data:i+ywo59+3011L+sRYL8b3eZJjj+sjA==,iv:95s5hzvNboteMvozFqoBdrsWnMtS6dOa79gikW6e18c=,tag:1Rd5AByXKsx7C/W9e/vouA==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:3+kPMEx1PUYNKFG4,iv:abMXIL5sxIikD19HIYTxaJuv1N74xc7qBQndeu5uHKs=,tag:rWRkD8Xz0vsS57R1WnBKoQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:fbxRDdXxlejH4w6dwwSdkId1ug==,iv:mcUPRX6G8hnc9jSz7MD9WJxWiD0ZCjuK+FBx2Yvg41Q=,tag:F0ZIEIW/KFm9xx6vEL9CHw==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:/WR+ASvKcmUzPskjddIl,iv:DkGEzW++xo6cupberghjAzavwEeH+ky6GcXt3PLBcIM=,tag:TErF0CHuNL8nWkrm5YJlHg==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:mflpHkLH,iv:f9CIwNcyX5YV5zbwGDo9YddD5PmHyiXhWxYc94LtNY4=,tag:ozyEuPF5G5WWnfOW+8YJrQ==,type:str]
                        last: ENC[AES256_GCM,data:W6FL2ZYjcIo=,iv:CvQ4OEuDDDtKxxw/g8x/wu/6en5+p5U/ujYUx4JoUtM=,tag:g1QmJj7yUc3WwhfLzCqi2A==,type:str]
                    email: ENC[AES256_GCM,data:+a7arx8cP9Gv8SS+gYm2D4I1WZmz9BLW,iv:4INjE3AhMvI9GZ3BmywsiwjV77maql2rlHSluweEKyk=,tag:I/TanYljyWRPHis0uhY8OA==,type:str]
                    cli-config: ENC[AES256_GCM,data:AArPNOQ=,iv:LS0xsYXOrarz9Uo3m8tpStw2OxtdtNZw96pm/TCkfIs=,tag:i9jzCjwqtZVgMxwQFmAT3g==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:LJJdHKa/qh0=,iv:4G8otDAQ/X96Lk+NxZdGXC6PKryG+z29iMIDHksQUis=,tag:3rxIQfmhqlu6o+aJ3f0wfg==,type:str]
                pezocoin:
                    name:
                        first: ENC[AES256_GCM,data:gOkJShV/1tE=,iv:7HeODJl/e5xBBUuBYenDgAZy6k/4Bm1N2V3BV/jdKBc=,tag:yyRAeWpyMzhnMr8S/ktD5A==,type:str]
                        last: ENC[AES256_GCM,data:FRGtK8oXiic=,iv:RuUTQXdV+LoWR7LKCeNOqIZFBg7B24GL27fCz4wPjiw=,tag:Mey4SXAc9NyUxKER9YcAJw==,type:str]
                    email: ENC[AES256_GCM,data:DDV5/8u+WuYWOghOggO9nSg/XIGBpdA=,iv:RzvQE03z+UX8OUgDb7xP1XGjvKW/FZi4jbFejrsOvYw=,tag:iaLHG+ualeJycmjFF7XpFw==,type:str]
                    cli-config: ENC[AES256_GCM,data:t5SaqN4=,iv:93BWBN/wdsJlzC3RfakjynodGK9O+DNa9bXBtufLtYI=,tag:HNOA4oq6++pOa0ykXOS2RQ==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:zsSTeQckj9YEcnZB,iv:91ph7Yx6f7vD6aq58iWVeP+PLjTjbWS5CWlUo4LfnyU=,tag:6RVLPo3gsc5bvRBrY3WrqA==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:wbHEpmC5wb/x1KkF,iv:xfsAyts5RzB8tH4itSjW3URERbeW6CM4fyEzBdWcl5A=,tag:NHEO3wpWyYa075f/0bKCJw==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:EBYr0svrT7vqB389Nr/GT5Eif41bXLbQujE8KBIFur2YZz89Xl5M1XzAHA==,iv:O8s4TZTQdc4QoEnDC0B7gZ5T+AqlB0YnWq6BR7+Ra9k=,tag:65dcf8T0xAgGf7phaoN7Lw==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:Rlbdn25a6LIWEKbjKWffbtg=,iv:fvcxzq2pChSW37p11SkFLPF1JGUM+e2oARK+LzpKY0s=,tag:BfEnY7LRMrnAToRZetzVfA==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:edP4QAB+VD6oSOG8uvb8nOilIGKst2E0MedInYnoPh13YLHg6R1Ylw==,iv:8b+0cqopp98WEHs1qwj7lzI/RIvhe0ozkKwIi8iJLGI=,tag:04OZ57+oMZW/vwiyqKR8KA==,type:str]
                - ENC[AES256_GCM,data:GKYigI/SoI8ulXoQD7BdPGQo+Kf3n6q9shByeV/eeU5edHk8Zd5ugg==,iv:zsz2pOtETDiqPbb9KKMemOYQT69nz2o5vNj/K7/jwOw=,tag:09QpPgMRS7h6X9RWUtk8EQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:U/4NV/NzRX2oDK08uiYqCbpo,iv:8iqez1lsWjSXHc+Fk7d4YbaQhGK9X+iwTKWDMojgxXs=,tag:hws4WwYQvA9RVhaSU+6MhA==,type:str]
                        - ENC[AES256_GCM,data:MkTfrXWZueeKtSfS/z3AXRB65A==,iv:+x9If1nbfjI/tleU0ynv4MsYudZQZWtOeplVXwvdCkk=,tag:yHZgozDnjw5Ika0oGOmhgg==,type:str]
                        - ENC[AES256_GCM,data:8S+xOI1vyc8HFB2frQItoeM5K6Lm4g==,iv:6I+gl9/BgEmc1jhW2/VaA3WfbhMQoEpk0N2w+5GVvhY=,tag:ISjeMWJECbYElm8jmRjEHA==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:5RNplVinELdlmVOqk6TqvwgGfZhQ,iv:wmlXskWGi1InPqUkxAHdu9dJkmjtKEe9L0S3fhYPtlg=,tag:D25MjqmSFbVU9qGofEkAYA==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:UMpl6SVmWG6cR2w7U6TlqcIMBQ5DsXMbiC5maJkP,iv:HohvplD5yFJnPq9WEATA2C4rqEVm0yEC1GYHx/02SRU=,tag:clanjIQSzQ5K1Xpw1XbOJA==,type:str]
                        - ENC[AES256_GCM,data:Z7rV9BoRCY5+9Irn+Emr,iv:I/EOX3+SVm7TDYK/YNNRXVztNHBOGE1ps21B7jYYP54=,tag:S0AgXLsGXLFzzYBo/+Z+3A==,type:str]
                        - ENC[AES256_GCM,data:fcLlqpyw02jvMkpisA==,iv:pt5n3upJ1pfJIsWl+vl3t5EdvV0kJPKCxN3DdM9NCfI=,tag:eskUzsqQbVgwnP/m2s74wA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:1PGawHvWuTJD0XQpYHxLAhE=,iv:jDrLXxePeNWzU3OzYU0W1nDr2OblD+8RpsgiGKbZglk=,tag:JCWraxU2z9q0I+ck6zLjng==,type:str]
        - ENC[AES256_GCM,data:9iQC3uD1/qLUgQi+y0419GiLK1U=,iv:CCjwOkZqt5FjY/92YMGlqtK1zHny99tGFgpImEa37pE=,tag:chTVqhfHftzGvHiYv4CCVg==,type:str]
        - ENC[AES256_GCM,data:dqf/1qHSAmp9GpwUIKPZfBtY,iv:GAB25mLdV0PqlAgmzVvUQbe1Mh/gyAvEMpAhFr81nuc=,tag:0QPyogjMJcA9FTHI1Azqmg==,type:str]
        - ENC[AES256_GCM,data:dFv0tVSa41ByMnQzdN+JYvM=,iv:j6N5CU2UeF5Qw0grw/cG9mUY36eLR1zcoafZG0lsuFg=,tag:tYrIGCFG4MN4mehviFFhOA==,type:str]
        - ENC[AES256_GCM,data:idRyrbazixCFBIKjxkY9OQZoYl2T,iv:HuURlezU7k53mzGft19aeEg+igo72ZGZdqziX3r8tH0=,tag:WS+kyHJd5pu4fcJPxnrfjg==,type:str]
        - ENC[AES256_GCM,data:OaZf9t+Kw6CjLDYhsF6y9BUdbGyJeyC8YA==,iv:rIrvJkWmY1idqUtkUJ4uA2R4l+h3CzXerk2ibT7eXF8=,tag:DvkQSw3GEW7Wbifkc2NUVw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:MINUr/4CCjCr4ZadgA==,iv:Q90dPP8iw3IlReRmLmm4SLdQScOmNYFb5/4ZiG3psXY=,tag:yWL38p873JF6VBFLZsAV1A==,type:str]
          description: ENC[AES256_GCM,data:Rp8QDbBANNFDpseLfg==,iv:T+TBOlCX1ZkidQbqkDx3QGsUFbtD+fJqBbh9tqOf5cc=,tag:sk2f1HqVF1K+PLKyPZAB3A==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:ZnmfiDpn7x+FsNsiVZzr,iv:zsrJtTACLOf2M3cQ8gOvWPaqqPuXP+K5uErjTM9UlxQ=,tag:Fe8VUX7QYiz+J7l8keA3Xg==,type:str]
        - ENC[AES256_GCM,data:zaPXKwLshpaoMv3m99hVh039HrrjJxp1ZRjS7mM=,iv:gbMv+L1+wJwFqVGqIYOZ8PiFD05f37UirpMxZYqn9tI=,tag:N9Jg6OBtxysqNql6mKPvBw==,type:comment]
        - name: ENC[AES256_GCM,data:wHwPXO/gzaP5MtMi,iv:CFNGguxqILb+o5Lor+LmSPWU8k3hdk7GIDRBI+Jw/k4=,tag:517TZtIvKG1lDuodou7byQ==,type:str]
          description: ENC[AES256_GCM,data:1JslYwv/wXYrHOlVvZa/cijC5j8GsArs,iv:Wy0ymO4JlcZYiaSuWlp7O7Ky8FT7/7GhT+7gU9+rWt0=,tag:f8tv7QD9ZS4Xjh4w47zE+Q==,type:str]
          deletion_window: ENC[AES256_GCM,data:5g==,iv:fbpC2pnHUi2FHsUc39VhWwxs2D7KoB5Y9uAoOzb9qz4=,tag:xo5SOND7XxxlP4aHHNP83A==,type:int]
          key_usage: ENC[AES256_GCM,data:MZpV88ilwLISwOuRF98I,iv:a5OsyWsS5hZJeeoOu5eTOSMigrPjLlLldI/ZhRnyjy8=,tag:Ew2FFXMk0jX9EpfioiPvWg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:ypJKykaRv6Me3HI=,iv:6PUAPkVWKa1w5Y99FxHGMm6+5HmKBaxZowiH5xugMJw=,tag:6twAIhzAFmGudnfEXR1IWg==,type:str]
          limit: ENC[AES256_GCM,data:oCLqy9oFEAo=,iv:GMi2M2yXd+HsyXsHrNHIJIxVu4LoPmvKWMbqxU4K/NY=,tag:LKPsWcI+uiYDHOwrszNPQA==,type:str]
          notify: ENC[AES256_GCM,data:PdV7sqkAA4+CWu/v1t9vIR8bXCJtDoNS,iv:SyzypSoKsFxqSMNdLUBmkHw70KxxH4oIKY8iT4vFW5c=,tag:6Q5TzPCqr/RKo8k0o8YyGw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-11-30T19:39:44Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgF69WSYOLH0hwWqmVBRZA+gAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGxM5ok8my70UUf+nAgEQgDukrYxxU9YRTr8ncNxoWEC4M5BBLLYc9/4e5S/ngmNq2tYzpfJbnRzOpAHPYxaxE2+b5iWrQ+/fxN8pow==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-30T19:39:45Z"
    mac: ENC[AES256_GCM,data:zEs/ssuidMS1cTslcAhtRXVytLHoe968aJPJsLd14L3tWtHWVVWthZbMArn8ECqDTyULHWmx+c9Xn0/MYrJznSQTdzdfCWHHnSOts4BMwgCqAuI15Y+Y4A4aAYvG2kzDQg87hBaWaNS5IjP5/7zw0z6N1qusN4WSzExCSrApR98=,iv:6inO0ux3CPRIh/8rsXuKGgPZYepVwr8EKy9YP9I5WNg=,tag:emLyL66XAxSAeVQr5jqqnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
