aws:
    name: ENC[AES256_GCM,data:COl/VZ4+EfgJHYfvG1DDiy0=,iv:obDrXXq88klRolS6Hu/c8dN+zq6k/N/R185If2z+3cQ=,tag:rLDPgqMHXdmeKN9v2YZRog==,type:str]
    region: ENC[AES256_GCM,data:96WbF09jZMMc,iv:I5dX+Oebz+mxmvNfPGXrUlyVQtrvmonrcHNFlf3tYkw=,tag:lGASr4kZ3eC1tbSh22IXGg==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:1CcOJBQQzK9sNCBVtG9b/LM=,iv:DMdd0zs/WP0Ek7tX15ykUpLkNzdv+jPDcVZqJJ7sQ6Y=,tag:bHPdFsx0kaEqTYlPScrS7g==,type:str]
    sso:
        alias_to_id_map:
            certificates: ENC[AES256_GCM,data:250dySPhmxAnuV9P,iv:x9V9eGF3ko0awFXEvw1o28TDU3N5lQWR6tjphP/3pak=,tag:oGLMbFQFEzr9VF/sFc/C7A==,type:str]
        managed_policies_map:
            Administrator:
                - ENC[AES256_GCM,data:NG7kCS+Q0eIDdvZeOB07g+pWXw==,iv:s9va/x+Uq5hOOSXaq5ApRd1fRSAvo99wNZd4IJU12u4=,tag:SkhIypPdJmgd4l3+qGc7HQ==,type:str]
        custom_policies_map: {}
        boundary_policies_map: {}
        administrators_group: ENC[AES256_GCM,data:2ef4Az1Tx/XiYnS+hoM=,iv:1bzmmUZp0lU/RC5sVRoVK1gvLU38Eq7NWi9/P8MxbAU=,tag:Nl6jr67FTjRpiO4O/koQ5g==,type:str]
        cli_roles_map:
            Administrator: []
        users:
            gerard:
                name:
                    first: ENC[AES256_GCM,data:X0idJGBx,iv:UwbR5/1v6kEGI/IK8tkujouR24N+lHF7feLth8PFGk8=,tag:jJo2yaligpnwaFnkGvtIyQ==,type:str]
                    last: ENC[AES256_GCM,data:LLNyKu85Uu8=,iv:ovvGBkjUjcT9v2Oi88RqPtph9Qk6NL0fy7bha5rwf6Q=,tag:jM7APhfqsrf1UfNHZYHOug==,type:str]
                email: ENC[AES256_GCM,data:WDV/0JczznTuYBJNjLUQN4B9WoH2fzLz,iv:Z+1moRF6qPFa1OzLd34ZnlROgtD4Z0Jba2KE7w81DNU=,tag:1Cg4QZjytDGpS6+ULE39vQ==,type:str]
                groups:
                    - ENC[AES256_GCM,data:e+SOIHf5XTI=,iv:v8r9OhHK0PDp792r/QyloFQ//p705eNZB2nw8SYV2Z4=,tag:okXJ8ZsnQOk+SiCESlIUNA==,type:str]
        groups:
            Founders:
                Administrator:
                    accounts:
                        - ENC[AES256_GCM,data:xrJ38P/U1AG/ZM1M,iv:OO8OTm/jsCE0qREcyFtmJyqhzAkMK4arIPhhcGVbRaU=,tag:gjw/TIisWQQwJkBm/SdIBg==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:vMYR8B2qtPjbOGZOl4sjomEEJTjCZr8+4wyCsYE9+0uoiQ5uRfr8QmJ2CA==,iv:t+iFy3VPM7SZwV7qzZpxgUnRWsloLQ/tyZl2GZ+Adq8=,tag:A3+UMpdKUyMbYa6MzcWCJw==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:Huq636/bjx2QSzpKHRjv8FA=,iv:w5ycNpuQRUetBb9NiCgl/VZ/gGaZ+kcoHnNvK+kgJzM=,tag:lsa4zkEB3TaOtxWL988quw==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:Ti/lIl8QrzpD6BV8qMaYSyuR6+cBvi/e2+fvv5FVzgKoru539QLKGw==,iv:Nd0+T+otbYiiI6xTxzRoJIFiCdOKwnNDS98oiMzkUho=,tag:hUm3FQsO9KqQLLVrArtL8g==,type:str]
            - ENC[AES256_GCM,data:dY1zGcBrmFBSluTC6KR/gEli7nGGtkMHhj5lzoXTRoqSX6eMzjoi8A==,iv:HD+bkIA9+23wpp4O7hadDeCl25vYHZACQ+4kMgwuUCE=,tag:BHMl+18gwtLG9QdsE8Mvyw==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:vqgegJbFM/y4tf2kea6jY4O43tHb,iv:a8NrRwV+GPgZYPvKOlbrNGSBpZoUgc6p4cujD1sXpVI=,tag:fOSVIGXYetF8YH3X7YFztg==,type:str]
                    - ENC[AES256_GCM,data:cECdx/ca9hFRgciOMtAGy0EW,iv:4aKxoWv54QqPHYEY9gzPIYzT3FgcRarYS0Gwz+HRnKw=,tag:umuLnt7II/AOtms6+dVR2Q==,type:str]
                policies:
                    - ENC[AES256_GCM,data:1EZOQh27C2rlMZqeoh15weVepJ2xco6SyPuN1P88,iv:azOqXtTi2l5X3Wj3MxLW84pFd57Qw1jDr8qmPAV8U0I=,tag:TCuKyZC5MpVVJgieFhXi5Q==,type:str]
                    - ENC[AES256_GCM,data:Ptlv8nAQruIKMoziFga1,iv:+q1n44x7VWrWA1IrXj6BJjOfXapRdLfRNIm/IJdbMvU=,tag:lgEECHx+Ka+wjFIM91G+tA==,type:str]
                    - ENC[AES256_GCM,data:LCSjF47JiT3lD5g5Cw==,iv:j8TCznWJ6LN6Wv7lmP+SRKIqvQYxLvg05pYVpBsY4iE=,tag:VnvUk7F7p2vmCYD45XV5bg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:0m2MJO3giVDSte2u4eqIAMg=,iv:QhZN1sF0O4wIaC0jJ9HC1Iur/UXNLYMsZ41b7cPFNwo=,tag:sB0fauqYKh4tZ4way/m1ig==,type:str]
        - ENC[AES256_GCM,data:ZtMhmQ2eqzv0hQkbEMB1d8XgFg8=,iv:KaJb+hWA0twUP9zQobGMxNVIZiLBesN92jsgLLhEDjY=,tag:a1+iWoct2Q9QK8ZGSBYfZA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:edZIqGbPNfd4J3JD9g==,iv:lIvD/SeOrHcIaI+jBJ/0XqRnhA1LsaSmRRoZM6BmqT8=,tag:m8wwkbKfPY3m8puz+8232Q==,type:str]
          description: ENC[AES256_GCM,data:rLbj1y4VycTEo1rDwA==,iv:3/Znzv9oS8tMIbwjzqUmxDKsBs9fYe1gjZt91+vZimc=,tag:42MfXbE+5FTng7FLSat77w==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:GIUdjlTKgEqNpL1XrYSv,iv:fnyMLNIC7p0I7duQQm+uI+J23MOuIN7zuZugMMtz9Cc=,tag:l5wL6ItxI6AoBv+HDc6X8Q==,type:str]
        - name: ENC[AES256_GCM,data:oeSRhIwU/wOgglYK,iv:WGwtENfxpxeX9suUdnRDkXOWH+LvEYDfqxLUfGuK+9U=,tag:EQaaq+fVxHbwpkME/Hd17g==,type:str]
          description: ENC[AES256_GCM,data:MI6AbPH5sZlaKiG0+BdK1NNWtW7wLDt+,iv:/+IfAfi+g1G4YOkYLhy42wtsrekiCK2wj5niZHPAx0Q=,tag:gGLIOVoutI0hKMw96NqW2w==,type:str]
          deletion_window: ENC[AES256_GCM,data:DQ==,iv:pswWinH26o9DABF3MbTB3NRze1J4hVr4oLiFQsvSz/4=,tag:P/RkB7zjPNwdR3MtZ7KiAA==,type:int]
          key_usage: ENC[AES256_GCM,data:wZCfpxCh+YRNNzuC/rrQ,iv:f0ODoNLl+x5CifNe46Qm2CnMjynd4cVV23zaP4xwbII=,tag:qw4eUYqtT6FERWkrVcSqhg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:4GY7cdZixB4X0QU=,iv:3gZOR8RaHSj8kHguK4TcKHos8Ue1vPQQRrWYBKLxjUk=,tag:JBIuHEsEMkVDHb22EoMZTw==,type:str]
          limit: ENC[AES256_GCM,data:Qmfs9ZBlVmg=,iv:gmp+hVysIxdn+T/qQt8nhhnylT6NaAnYTEZ+R1cdbls=,tag:bNZ75N71rqdqcRdUpaRoKA==,type:str]
          notify: ENC[AES256_GCM,data:jib9sLQvrqOFQYuv7fKmtNTfkDx8DdGJ,iv:hI4XmcntjwOfoDJi6zaZuYCmo6tm/K0RG3P72RmMrzw=,tag:pEJkCR07FeyULsX5z28/1g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-01-13T16:23:45Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGC+W9Z9tv0uiRMLxQX4i9oAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMk7qgye3i2BzhDo/HAgEQgDtWJw1HwtdA4af4b+ah3uzYLT8QAbRg5aOkxJavKu6tmeblXHBRwVCfsnfDIXnZvEnKHuOKdkOdcybBHg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-13T16:23:45Z"
    mac: ENC[AES256_GCM,data:BSFg+ChECG1tWmnwL0MZi2MGqDEabRoPnSo/QzDAepWG7kMbKO6iTsR3WS0vLatA7SUgLSoscdUqYqPG1MPCf2fa5PXHXyNh5Map3fhCRCGJKtEWOcPzcjyVbAHjWwEI+jCgUz6NCc5JeQ6uQFny9wYaVdQtonKY4eW+boJPSy0=,iv:Mu/hnxBM2jN/BhBEMtZ1RKOV5tFsk51UPetAh+b5w4Y=,tag:xGcYV5Ag4T/VXoJbEtnR+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
