aws:
    name: ENC[AES256_GCM,data:lP10Ja+V8T3akYmmR8hTMkg=,iv:tjQmQxdp847kCzizRjsLggkO0IA9yRL109sKevvf920=,tag:I3UmJfYZq1zwQJlj0J73Yw==,type:str]
    region: ENC[AES256_GCM,data:WL3R4O/kzOdQ,iv:JKdV8UZruOgJC+um2oR5eAFC8lpUTcHrsLyTl4zr2r4=,tag:Z7wnFf/9JxjcQRwKEY66lQ==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:ghzgo6xtcoUovpmHzvdegFF84VL1bAj5FVr4CkPmMycEAV9EG73WuZmMvw==,iv:r/l7EFeCsnlRjOdlwNRVp8VALFnQ8kz15bBy0/Iv5uU=,tag:nkik8Aj4e6ksqL7H8nq4xw==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:De5BDPulcj9NOo6lGDcgeKM=,iv:Z2jRiyNWp2qr1Wpxh4RAXLThDh21IqXmsUZP+RfrkVw=,tag:vT+2fP0tUJ/hFA/PBE91mQ==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:q7JIE+No6FrBnW5eZXEZ11PIdy9dPk5K89YHeOn5sVhFw9NtH+vetA==,iv:Q276s+LtZmCeh5n9z5sM7hXHgxUk8FfHBXaPc8Ueov8=,tag:jdVkwC5y6RjO4ZHudSdAiA==,type:str]
            - ENC[AES256_GCM,data:+IlbY2M5fYI9i/rYIY7aGeME50Zji0HJFy+5b+GdSH/+hPxLKQnHew==,iv:YCY+gRs58K8M5gv5UeVB+dH8sc9OV/RLO1nCOSSVRH0=,tag:OIbmCYSRTU8O6Am+UpslmQ==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:9Hhwn7KDFySYRJBWAEcori7wxA==,iv:cAqeOBc3k9jEUae2/ezLnKOokrJJKIRLunqfcyqvcrw=,tag:jsPXcQFvDhc6H/6sOwqwvA==,type:str]
                    - ENC[AES256_GCM,data:Z4rjKr6Y4okCMMoGY9LXWS6F,iv:WJKWakbxFEugoJOemWPq/NTtWkxRFFyEMRN+j1Jk+vw=,tag:N/ULLvj1sV6ap0nR3AQhJA==,type:str]
                    - ENC[AES256_GCM,data:eL7/fgaTShBKX2vlGmEIRd9I3g==,iv:1knQo/2yg/suCmiH17kVmWOayPB6+3qk6u+T7fqFaH0=,tag:T4J2VTg3vzwz2HlG5mcFPg==,type:str]
                    - ENC[AES256_GCM,data:7nGE0KmwRKN5XWQ2jy1114+z7IQ=,iv:mXTMrjClMfSn7pDLhduFzeOJ8xav40nh1Bnxpn94gBg=,tag:Hp1zFKSCx+rjcOLThl23OA==,type:str]
                    - ENC[AES256_GCM,data:4Juer7GOLvKoMK3aHg==,iv:FQIQlbGWmAfmGJN1Vdqto8L0y13HneGGOcJ800iie+4=,tag:AGG0p5qbVXxbLeKG7DHhsw==,type:str]
                    - ENC[AES256_GCM,data:rEHzOV9YiyJc53UsC+2ePcXZohF6XW+3efK/WRHw5p+1JHHg+tnr00MnoHq+,iv:TGkWphY9MTAViCuEoG8rpMC9J3sxHkJ/VcoqS38IQLc=,tag:cSmu6n2kojDcR0rP4di81Q==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:grE/mR6Jud9TGH4Eq1RohCccZ0VA,iv:6izzatQRwxezWnp0b7xxLJg5zP6C6Vh4huOfg3b5TOs=,tag:15yDk4NBBrkKH9RkYkFTjA==,type:str]
                    - ENC[AES256_GCM,data:+m10gL7O2kfhA0QbXqFpgDOQnc9ac/o=,iv:cmTlCvL/jWyRUZ8tZ/bNikQfbQOS4uqKaw2ZdaZG42Q=,tag:nP8T81DK/cW5WEjicI7ytg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:4c+12eSLhnJiJuUrGJUe1W4=,iv:+a13YcleqNMzqWul7M/Xylh2yo7hOTj3D3GBQ2RxbPY=,tag:sa/PnkvDt7NNtzPw8cOxnA==,type:str]
        - ENC[AES256_GCM,data:tGVUQb+7ybEDQmo7elsOzRqa+A==,iv:YK9tDu0MxufGf9OKie3hillcpFfMiZsYY/hwI4RKf70=,tag:IAbDlvVWe29LX9Jiu21ETQ==,type:str]
        - ENC[AES256_GCM,data:50FriLUIigMyXvnyTK1c3iCj3cI=,iv:GM6EDdWaJskGQxovkILMtxO6es9ZMyOfI5rit6u0YDo=,tag:+VZCIQX+G92f3kZGWgnWLQ==,type:str]
        - ENC[AES256_GCM,data:8EMy2BdJKFl4/h0r5jEAUQ==,iv:NRqtTGbC8BalNjwyzbhkSmFrqBpH9e2n4WB8AfiWIcU=,tag:kjVvZ3CDgqYYWjNsVJ5PuQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:HPHHJp94XP5trLSkhA==,iv:trjYgEtpqJFTMjshE7ShKxri7S4ytQWURAL1+OwENjY=,tag:gAIrGINtCRdFtFvf7oFh7A==,type:str]
          description: ENC[AES256_GCM,data:nSBdK/GnFFxFD5W6fQ==,iv:1wxPWB6qo/PycyVO4S9MT6oh1xUAWO7G4A6iIBucd6Y=,tag:b7kn+Lh5k363kK0mFKCHGg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:oE9yQkHl46ZpZeuW01AT,iv:GDru4VtcIh8IliBJ/MsSV4kmYqex0xv3SzKAsOg6jw8=,tag:LDsYfhKBFa599x6FolYNvg==,type:str]
        - name: ENC[AES256_GCM,data:MysaXhBSNKAJ7XbR,iv:snkyFjIm8/QlaK21A920UG9Ngz+5GoWt8W3SS8biuX0=,tag:L2t3klo0A5/awDh5xYDZQQ==,type:str]
          description: ENC[AES256_GCM,data:hQ4iGTevqIEyNl+ZyMnHaa9rnsIKe9mk,iv:F6q3HPTd8ctJZkIpNzX8lEvsW6dyI8Gg5gV2WQaAHns=,tag:Aj77xG8HtX3C5xb3NJBXlw==,type:str]
          deletion_window: ENC[AES256_GCM,data:5w==,iv:5fXJYkfocWy78jihGRDsUWA1kscenfvMr+Ar+Q+YpYM=,tag:aTEFWHh8L+UTdRbapRhcqw==,type:int]
          key_usage: ENC[AES256_GCM,data:UJBBSuUuSNqN2gPtU8Uf,iv:szoVjuwwpMbEX4ucycLHnQsWSTt+EYamtZCFqFIEiD8=,tag:KP68zKLO5Z7t+9DHUA+YLQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:zeFq+mNrMoEUAJo=,iv:YL9eCIf/lJ+0mkxpYCeqWzf0dpkVOxNIj+GBCaOuR0w=,tag:aDDdmSFqW5K9u07p79s2vQ==,type:str]
          limit: ENC[AES256_GCM,data:zRkQD0HxvM0=,iv:j3miiSZwYyY8NEPbL1JyBEUaerPwnj4NuBu+nDZVimc=,tag:34ukjVhim+qzSOEcvKbkiA==,type:str]
          notify: ENC[AES256_GCM,data:cddgcZx1qv05MufkUvGKpCaS1F5flp99,iv:CvY4ve7N7VYBnha6MNlwXUc4bmmX4GrI0qnGgp32KFY=,tag:kN351Z3TdkOqqBFIB5q7bw==,type:str]
    ses:
        - ENC[AES256_GCM,data:a/IzFgqpxt9LNCovtZGtH6pYNwNYYrDPXMr/fhevZg==,iv:mPqtChH1lA52t4hHbLYx6fdqP9e7ZLdV7tWA5mIsIi8=,tag:qw8s71pYjZEpi7g5to+mNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-07-01T15:15:38Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFHuOmJgVNJyn+Q5EVoIXiMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrGK63qtPixZrcOPMAgEQgDuoNuJQrExCh1CCHnVYDH75ar+neRdkwIc+lLB87yBgO0LDoecC+03PwDrzE7zZPT7p3Og1XYMKvsMxsQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-01T15:15:38Z"
    mac: ENC[AES256_GCM,data:qXWyqnz5ya0OlOOfVLg2fhyELMssYwpXSdnBo5tKuKLIpeEGxh2W1iPQMyWt9wic4gzldnGYEG33bIhJUDK8NAJTyVVQ4eAzbzx2wqLIp5XvfstsyIiVSCCYu1gbVxus2w/kqvdiGJpYUBxPBgrciA8E1LJFunzKN3yUDap59J4=,iv:LYXk7HkfD5zeog3H53bbyrfegXKQu4ZM/O0alSa92+c=,tag:zNrphdNU+1ZWoQqEtgGR7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
