aws:
    name: ENC[AES256_GCM,data:9FSdg6NapsCPUiYM5ojSeQQ=,iv:p9FsVTp5Czx0kUMZSzVzqnOc/x8bz2QbcVMafHEaKJs=,tag:oO6vsU1D5gxMImjGJSkXOg==,type:str]
    region: ENC[AES256_GCM,data:UvPfRR5DCRTR,iv:69RipNy6au5u7WQr/3t6cminMW2KhEgxA1cebguJvsI=,tag:Xnezy2eCL6x+jbjhyzijLQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:j3ZEiJ6NOtIQHiiX7FGI/PQ=,iv:JRDHdX1nTM8DMP8WIjt+dafQ6zS2Ktq5yPFfBSXDWDg=,tag:m3MSyZTChLs5f4FpM4rX6A==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:DwGwxJBfdomH+vHo7JH5RhPbZbespiokzLBN/x3I,iv:0zZyZ+7+TBLc3ptrWkAhQJy/4wN4o9aq+o8SEjA0IAE=,tag:47Bi5tZp7gjzyg0umQQK1w==,type:str]
                    - ENC[AES256_GCM,data:iPbpH11JXwbjr+L+0pG8,iv:SaKgQCnb8QrFc1f62ClGgCORlVhDbdytOZ8TKIlaI7k=,tag:AxxfUkLOD1Ca15RJHYq7IA==,type:str]
                    - ENC[AES256_GCM,data:b5h4N0K/bMzn5qCyQA==,iv:E7K96H2VUqbsOzFtbklCP24gGYbWtnfuKNsRdEUSrug=,tag:pOHGzv9MkeMaNXaax+PJ4A==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:KmFrkoEWVHgCb60C3g==,iv:vCyiuvVIdlIjRRweh5Gfd1X40IdwWQcs4RwkK4dIAu8=,tag:ankC6979SnCjUH0LJmrpfw==,type:str]
                    - ENC[AES256_GCM,data:Xoc4JZNGES/eDtvHqIw=,iv:h4laiYAjhwM8HmMTOtDNO653l0oXXbm2TZLGjpVAxEQ=,tag:oi76ImquRiwh3+xZxBV75g==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:Y4UY7ojp4a7qY6iM/UXfOPzgbhu+aq86QPDuPPUOcFe4Rw==,iv:EKoY3YnfMTmYXzFihSUlqtC9tXhn8tVKMQXcFqgSKi4=,tag:mdZGNVi6EurAK720XFZYBw==,type:str]
                sso_role_name: ENC[AES256_GCM,data:62aAvHhiXnJhqh5oQTVx2XsjLZ0PnA==,iv:MJxRO9UForfzBObh04Hx8+YcGWl6OXcnVFplcbEhrQY=,tag:efAXMXewEmGWy1t3SqsP/Q==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:8EO/fG2Y+fyWlD1j,iv:NMNwEKx5VDGoq/HXlFivFEATHCJ3vdlwvX7r+Qe0ppg=,tag:/rZzXTXOJ2Qc2WTr8PXHzA==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:oQnxJx0XwvG1WExiGBmA+5gM5g==,iv:KK7Zv/5MPXhmnS0Ez6jHEdyGj9SqOKUJzprTZpTNSxU=,tag:xHSSG2CpQ+CjCrKj1jbdcg==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:V8hi0UlJ,iv:YCc/zfDXQCZCypccvG5hqxNnSB+CC7jvcLWe31qRdow=,tag:eqFIU7fOCBGWdBLZ3VFTiA==,type:str]
                        last: ENC[AES256_GCM,data:acOYXLIy/w0=,iv:n8FBd2q45XVGpUxyDEnuWN5/g00WjeGCy/IXL4IqXY8=,tag:wun0EE8BoxkjS3bpc4f5bg==,type:str]
                    email: ENC[AES256_GCM,data:zZyAyvLnSjV2a6KPxMSMXIrVQYaNNExF,iv:y/3DrkumOIft8fn3kI8pMQOldC5XzBBKdzoIZRD7BQ0=,tag:/k/a0wS1ptoPt3azH0dtWg==,type:str]
                    cli-config: ENC[AES256_GCM,data:I+43pSE=,iv:ng4Ov+NjRCadILZDfHqqwsT7ugIvGapu9Az1vEr7lkk=,tag:eeonYAhP6lh2Cn8m+EQ+SA==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:Yc1Nfl3ew00=,iv:wGnlLV5glOBxMcSIeayJiiuAClZGIBvHp3ksDHnUkkA=,tag:bNWnv4o/WFW95reqWo1N4Q==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:sJciyPGqd7s67zn3,iv:qbcMdlZl+CT1udUziIgYMTcshrluzRO1YJYHGweOxZ8=,tag:OqBSpnnHfYaJkasaff6lfw==,type:str]
                Test1:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:qg6bUsJd7hRlW6NJ,iv:LKAx6/drVRJ1R/ItcsVFPyO47bS6PdyqfmjC/ewP0UI=,tag:KpSXsB5SZM7FBkChu2k2Qg==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:iV4LF0sO/m5fyIajOZksqk2GLMPadbUaz2R3RkDmhfeN6uyos0VSBKsjLQ==,iv:VlPip8ka1PIfq+0JH1tWRs8QY7h9wAITlxslP62sLUA=,tag:lelRV9BPqACF4vpKKIYYbQ==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:2bVs43Hk/BU+zjiGeYOqCqA=,iv:N0t8cBFdURMDbkOMNXxkkijNUc6btXznrpfbl9WS1hw=,tag:SZnGiZBFTnVsPLPodWIy5g==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:wD7+VbzOaifl3A+Zhib0DiZ+2TZyWi3tBy57h9WOj2UZKtEGItY5qA==,iv:Kk0AbcGn/YqWab4iC9VD7JV6fvRNoQx4Ko5aAyjGBdg=,tag:tlwTbirMqRrwK3cUiHWweA==,type:str]
                - ENC[AES256_GCM,data:ttjq2zzyCJskaCKiR/fKDr6R97BkFQVBzMXNpPjpM7HHrdpBhIg4Xw==,iv:a/0imDgZ/cLHq89zN9HJLppr+gtyNaWAIUqv1RVIyBI=,tag:jFofzOjCPDQqVk/mUOn06A==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:WnWLm6Bmwgl9AFtLiFO0Fv22,iv:RDONeBOqg9dA2kzwMWFbPeu/x07vHkynIkmWImDWOSE=,tag:qFQcMWv1AtY9jhmpLBGVMg==,type:str]
                        - ENC[AES256_GCM,data:6PgZrn9QGN13GaSrjtvkmTELbg==,iv:gtIL6hnsag5NjYJ5lprdPb6f/qEK1k+vxB4fACt6lVA=,tag:p092R+rcNcWzlAOdH3ZEDg==,type:str]
                        - ENC[AES256_GCM,data:+YzN73c9DMV6qcxqXgIFw+WD,iv:s31TSSgluGh5V2TCrUGCUQYb27wqYAumr5U4ZR/3+2A=,tag:VEhc+6bnLF9F+KGvGAgUsQ==,type:str]
                        - ENC[AES256_GCM,data:LbL6GzspmiRUQ4RFLw2z/BscFob7uA==,iv:gSq7KcjoLIFqVxEWSSlUSOAKpprHJ4P6zuji5TcAB2M=,tag:MDKndila6LKPVdxYSAE1mw==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:eWk5GAKeWXphV+D3mmXWT/6+NiD/,iv:tPobEkBJS42K2XmW7+CTd9pFa3nYNurlhVNYh+hkoXs=,tag:VyqdaHs0M+Ki9OsCx25awQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:yjAsdCOW81Y5Mr1Q/g5ytwxHb1ZXeeHdpXwJRM6v,iv:oZ3NDCj18/HwuhnNnBbCeHnT34rNIPt4jsfbOBb9AhI=,tag:bIyT7NE196S9335Se2pbhw==,type:str]
                        - ENC[AES256_GCM,data:wnDzBLTra148GcSJY9lh,iv:11rx4L4PX0UrCd4WgqK4441q/+LbuNFaeR4zOe11lRU=,tag:PL5MykwWVGlDsI+0VgZ2Hg==,type:str]
                        - ENC[AES256_GCM,data:4kKeXb+4MRSkhaGVvA==,iv:7NMMPwGnPNaUFOnAK1Z4wG+5zj/CIHY9dkZhFH43l38=,tag:KVAS5TpscWQMxmJ+pKzbpg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:yT4DdXHeuNmPVIYbilkJzws=,iv:LUOTfW9+7A0aGQBBMtHss31HQLXUJwuRqAXUk83A/+E=,tag:M23jueJN/KvvXk9pEGHGpw==,type:str]
        - ENC[AES256_GCM,data:KyPyl0xc1Ug6sqa+l5Un3yR+USI=,iv:lDVJRIA7OyNOFEO+f6N8bViQnoj7ctKAOC1WkXkIs0M=,tag:UEP5JYiwXMVL2HC9ZC1+RQ==,type:str]
        - ENC[AES256_GCM,data:9Lq0t60hpqSjeq7x9o6V94L7,iv:miV/RJVN5X5MmujepY1anT5Uy5LLt7vZvveTD8b919U=,tag:iISnhYJZKDh5YMsvVMIlxQ==,type:str]
        - ENC[AES256_GCM,data:DJ0htU2HS1NO0MMXDD15jBQ=,iv:EwBvnOTlWkgldlQcFwc8rpT6YC4Pq7KvIPdGXNTPxj0=,tag:T84XhWCKtV1LOPs6iKQfaA==,type:str]
        - ENC[AES256_GCM,data:bGBirpviqSPYl248J1e6OM5bDoMJ,iv:z3VraMDqMAW5q9pun0kg8f1XAqGaA3XgFOXeUjAevJg=,tag:68Nz67bB6McfWbgsaLpWTQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:xp2F0kGCQEXWEMtMzg==,iv:GGx7/yGOREKF58yP783mdo9+EVG92mGwWKTNtbd2YiQ=,tag:HfoMpAVtWzCUGeRtN9wsnQ==,type:str]
          description: ENC[AES256_GCM,data:fd/JIA6//frRmTmM7Q==,iv:1mgd4miDbKp9Bi8COZmO0nG9/u6QWwu5Wj3JWpZVrSI=,tag:NWIXqxArtSeedB5ltSvsNA==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:EdUTDktZUtpViKCTErYQ,iv:yPEO4ZNjMCbhux7/Om37lX3Ppoxu5wRFc8xYN5tvS2U=,tag:sZrbXOZuWlMIhrgtTyKATQ==,type:str]
        - ENC[AES256_GCM,data:iKumjGwfyv1jGX1KSq//8BoD9Y4RMYoI55ZpIOw=,iv:/MbI2MgJ0GWGZA/4p8KEuh3tbc/faYxCHSp/iPnkW+8=,tag:zc1xOtJwlHoVc8sCI7UuHQ==,type:comment]
        - name: ENC[AES256_GCM,data:SJ7iO1ZLN3uvQY7c,iv:r17LCSh/a9wQKvzH0SYO/GTDJbgr8/3r3+6DocpuAjY=,tag:f6Yl6THRIah8F10dWFbIgg==,type:str]
          description: ENC[AES256_GCM,data:ETm8OsaL0W6sgP8DE+SNN005OCg1oye4,iv:IQ8HwssDLrQH96/utw54G3C0IgJQjbyM+/Nkmx+arSQ=,tag:pTmqVNmhNWfjMgrPudIHBg==,type:str]
          deletion_window: ENC[AES256_GCM,data:eQ==,iv:xJGGBegzWxJn07ZjDHL3I3VCKT1drk7uHpzynIRes5c=,tag:QFSJFGiMxS1B2phInOOPvQ==,type:int]
          key_usage: ENC[AES256_GCM,data:q/22GTAAjuJy/HiIvwOk,iv:VD10914IMl5Zc9d/ns4tBakZvj1GQ59iw5fSyv99nhc=,tag:yjesb/GDtuLc9jjSUGLA9A==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:EwynoxSiqGqkw6c=,iv:+d3OS4cJxGPtiI6i269Izrt0cJ4oaqVJ4RZ/ynfrAT0=,tag:h1KZNWcpp7pdFrZ2lq8mrg==,type:str]
          limit: ENC[AES256_GCM,data:WhPj3lNEuKc=,iv:uGs0d64azbATQwTh6ROyW1PhzyeqUyZTVxwtX1d/RDE=,tag:uvijBUrbSHqfQdhlyZ0uhQ==,type:str]
          notify: ENC[AES256_GCM,data:yXk9xLvBuPQsakmHr0Wyu1QYyOI+rn3M,iv:o+Q0Hf/C2HEW3lnmwbGoW3NY1AU9ykiXTZnHtURdee0=,tag:KCxglKjLvBxAhaWPrJJ2HQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-05-18T07:19:42Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHraM6vbtOhbD3UvC7ThPCZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM10qVHiyWjXmw0jitAgEQgDtDYKyf42xtdaCbpgTXfwuJ4+RaEeOGG/WScFTc1QyfLjYWSBj6ErG7hyKzbe74NYORw5ZBa7SwDNXJvg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-18T07:20:16Z"
    mac: ENC[AES256_GCM,data:1N9JKKHJ7F6xJl3NAdrMyxPafDq4mfk/k+AWbLtYIMY36NDRU/Catd8LzABaCbZaqmIam+s82hQZ6AHFwlVwMQVq47+HwcV1/vWs6X4Qt6uMjcxvywaX0qjNIbf+nMV3E4uWiadJB2ADKDOLuCn/J2VYBNjM2sxEQ62ilPyp25g=,iv:zVCLhnkVLNVhUiqCIgLcTxd4pizUHqtYirC+0Z01DjM=,tag:el2LYSiiCR5+T0IePK8AuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
