aws:
    name: ENC[AES256_GCM,data:BrOrEjyWZGk+A+Er7jLIfSo=,iv:A4+r6+prWkByhz5SCuPgaiwPVNCpnJmzc0PI/EBe7tM=,tag:mkrL52ycAveqtvKXW5ScQw==,type:str]
    region: ENC[AES256_GCM,data:kh+r0Q+52TMk,iv:Pvh8pBEtpsVgf+XwhvGdwXoXzhjrbmu/bLrk7z7+y90=,tag:x4Yycz7KvfWexj3d8rC7gw==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:hj70ig2cfSFkYqQSnLL9dg/QpCqtMO9/c86w0J2G7sy2sxSwjpU9ljfmFA==,iv:8fkZh0BV//40xPLe2LvXx4q6tCXNELelfyOmvYDgxbg=,tag:jzqmhGLUmgmTFUuUcnDaxQ==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:k97huIEGaxk8I643zEgXlp4=,iv:LKrKng44+tdgfLxmR8E+is8L/O+d2thpzdcDilbftE4=,tag:9GM2VAMJ0ruWhh8iKlzKGA==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:mwNtwFwmH8kHeGrIpJ1ei6xVsNyqFcMIHyTZ1lc7yOzQm93AeG8vTQ==,iv:Lik+kt2OH1oVrc9YTvp2dZD00sxIH8id7WsMh3siYfI=,tag:xI92OxVFE159rEuvw2cn5g==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:o1Q1AQYJYwU0Mk0xCGNrcfo6/w==,iv:FqdddTxS9PMCvjtXapAdIN5b3GiYkipEFQbIpfIymYI=,tag:67YplsFneEiFKJ+oC9I3MA==,type:str]
                    - ENC[AES256_GCM,data:ngHYAQnm0BY0VlKY1GAXpBI6,iv:MhC+7tH7E1Q0aUtcdnJ/8F6/GtybEr9iPnADHm02Zl8=,tag:WXlQtdpn/b83E02oZp4OXQ==,type:str]
                    - ENC[AES256_GCM,data:c11nrHFI+3RDTt2+MQPQ6AHjgA==,iv:dML8wJej1GzaPV8Llp41ghg6sDW7LYKl/8SBXKGsEXQ=,tag:/noueDijnrIimwSvtxZTrA==,type:str]
                    - ENC[AES256_GCM,data:ZgiDOlzZtSzX+cCtxhQxj1BXP/Y=,iv:YjHSAV/BPlOsxlSmUnDCrrCunz+OdPWxoyjir8Dyy2E=,tag:p3f8iZdv6hmE+qgHZos8zA==,type:str]
                    - ENC[AES256_GCM,data:xX3WRU9KJAYz5V1Wkg==,iv:C3+sOo2+FwJEiuMYH5VrtKU51E5hlKqNi/EvYNrplvE=,tag:xliKwHuetwhJL6oJ64Cpug==,type:str]
                    - ENC[AES256_GCM,data:4wTF9sfC0IJwBneq8q9ZQ2QHFy5cTPx4tLghTfyPt3WsMeDNUWiP5bhd1UiF,iv:o6GqAFVJQANl2WMIvOzG77qiJYvAcAnHek0lXLlCzGo=,tag:lMNNZgMqrfNjyS4JllqzLQ==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:mdygye7T7pXCUNb0OM1BvTj2H7w/,iv:Qjgzd7cBF6ypPkRRXHLWPz0ePurtfkH3qJPD4n+Xd3k=,tag:aN5cj7Yi5fnc62wJ8RVdMQ==,type:str]
                    - ENC[AES256_GCM,data:Dej9DDWJkxu1torqmgWvA8sMUGgBjm4=,iv:iYbNe1lJR7AgRPfashLrqz7Z7+Bse01+6sMhcCvIgGw=,tag:OTMa28Mh8O9wQGAE/zfKPg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:+oX6k1j73RYepU6zBouM1+Y=,iv:DvQqbxbkRhwt+rX7xjGiWLBmlVuEtexRUBvp9vetfBQ=,tag:ItekRSdkZiZQPAuucfUXWA==,type:str]
        - ENC[AES256_GCM,data:wkGfobZWCu48FLEbpYfLhL5+Mg==,iv:70VysWlByKXap7jOwB4bGqRWwpymW0v9WIrNFhQL06A=,tag:ZePcEgKZMYwbUVgAemCTcw==,type:str]
        - ENC[AES256_GCM,data:3Z9M/3On9Xp1UP4YRSSEmWN0pAY=,iv:gblEmfcC0KSP843Ycb7ybyDtAnNI/mLAlVgk3/Oap9E=,tag:964w1laiZhK5KtD9ifC5WA==,type:str]
        - ENC[AES256_GCM,data:XXg+q7zy9n6MbHeWfWqcvg==,iv:kYUZMzwz428Q27Z+G2rr7FgZq5/efWBcw88kBKJAKHw=,tag:Qp/YGtoS2e19ToLI7GJuJw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:phB9Y7AkBEqdXzw1sg==,iv:J8vIMWipVAsgx1/uVu6W7dDo/Jb6TTJfYzI2aYzaxrw=,tag:PmzKtJIhBvK1SDYocQPE3A==,type:str]
          description: ENC[AES256_GCM,data:LsdhNkLlX0rb1b8kMw==,iv:jfT6v606Rpkc2v56XQe7WjXGn7xk+fmVlWLkro1Hglg=,tag:oZGFWQStfnOJb7+7cGm9VA==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:C0xgK55AgiNmfd7OQXaj,iv:/Ws/2mcR7Dp/7mM3avxAiY29/N9w22UnfREJp4Ghb6g=,tag:qSSciFzAZ+5bUanstor9mw==,type:str]
        - name: ENC[AES256_GCM,data:1/x1tzoBXawF8FQ7,iv:WwIUCMnyrXApER7C29WLTDMMEFP5aizSKTb5D+hDUuY=,tag:SD4TWLM67gtCJrnrlq7jMg==,type:str]
          description: ENC[AES256_GCM,data:PU9TJVIjWNoW1EK3vbYdN781Od6fv8YA,iv:j24TYoa2NJLR1u7e8IKfksp6trk4kaatq2W6CECEZ/I=,tag:vfNlczXFxNPUI+Yyj3qheQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:9g==,iv:iN8Z0rC+Gm9jcrL1zMRQCaGte3+LxH+V7lHmPyTYN/M=,tag:BWIPfJEdwKPRhcwbWxtIAw==,type:int]
          key_usage: ENC[AES256_GCM,data:xISX0D0pzpKYm4d3PsdT,iv:nCtQEiE4k9rE1z4HBpPbb1gV3+QRnsyTXyWXsWlwj2Q=,tag:Iqb+8AokrP/ZgD+PO3STZw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:wozRB9ssbVZyI60=,iv:FFMfnv7ibb2fd5bSHe8FNVkLIO1bfAQvMKoB2Lflj4U=,tag:4pI7+cjyO5I7crho1TTTKg==,type:str]
          limit: ENC[AES256_GCM,data:hee23AfKSFo=,iv:+3mV/n1kC2uucTF8sgNe01HS/NbVquTFuawsR3rRJW0=,tag:SXHtDJYy27NC1hNlwzWx6Q==,type:str]
          notify: ENC[AES256_GCM,data:yCGHe3OkJ6P6BKvUbZYb1nI/ZRYVNG8r,iv:Q7H3igIxq4sa2H3G2WsNB94jtexzN7f7s9Tr3VHPlo0=,tag:PpstF1lk5FFKhrm0KJfOVg==,type:str]
    ses:
        - ENC[AES256_GCM,data:x9TRF+rNJp/zyhCnr+2OuNaJ1Uvo+ZExBOFD33VSTQ==,iv:8JLr8GVCZh2CDrbvRIvL+UFJKuOakIW3SKu9/h+yhzU=,tag:dMtQ9QNCykFdfLuo7W/7Pg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-07-01T14:57:20Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEiR2/hry9OCQgDoMssgZBhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsMUUUg4PoXZbDJOrAgEQgDumnFjjPuKuHW1g+RZrxCV17YYlyM7AdsWVb4pL6pHtRg6weDshLDNRlxrZg0qVYCWwkbp+M2Mxtmx6tQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-01T14:57:20Z"
    mac: ENC[AES256_GCM,data:jZoYggP5oGHHhKg01PKjZf/E2tcQpG11eYVVXOZvOYhxex1HL+K7H2bXdV+rIdctApjIKTOljQBZyyjAZiB37/sdaWgFO6r4NwT35cugxD+I4Z+3R1vYBIZx/9lDSxKwOp+0jr52AHxDicKyCRNPYzbovkA2eqg0EsAtsoBxeMY=,iv:zZPz3NkJ1xHuZBNIVmOGrBfx0D2jGFOAAGrm9K7NXtk=,tag:VpYfnrAIzj+5hNqV7fTWbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
