aws:
    name: ENC[AES256_GCM,data:8EM3HIBtiDn7nRhCq9HMDaU=,iv:+H9AmuK1C7MN6p72S8OLG2IM0thB8GEtmFrtCg9LFcE=,tag:jCMudKI0JDqcwhGpbKjukw==,type:str]
    region: ENC[AES256_GCM,data:k+w2W+ZDQoFg,iv:DW19zy085x+ww3sXYt/hrX9sxZO7JWW6oBn+eDFao1s=,tag:7V1h8w5y1EkjOn2okSg0fQ==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:wzYYGY8orFZghstMCezcUTUD0Ci25+W9uZpdMfIVxxc4nhoB75pMJVCfAA==,iv:iflpZmSV8BTiS0n0zyqqDkxPn0npu3NuhBdJdoyAbWo=,tag:j94DJAmqCBL6TjuUrDBDLQ==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:2tIRNCfhMZ0EuzO8M3xWTmo=,iv:ltPQPwNPWWYpPumY7VDWXHEeN1bHMrTA3AfTkaTROAY=,tag:IX+KmwrBXNe0DV9aknSanA==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:reCFQUQH0pP1mJrw/okOCKrjzkfnBa7i5/UvRBWGHVFImt1jBp0VZw==,iv:N546fY1gSVkoT22DyIsHk1RP097DNjOnA18K38boUxc=,tag:ctPZEb/RhRZzcNW/broDGg==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:yjigQl/2ryhTIwCgnikYvBUxMw==,iv:y7P08Z1MG2bXpxGdObK1rcSMJHJQ7jFHZTZHG0AOaDQ=,tag:Y5keTKHwieTrYVxt4XVgqQ==,type:str]
                    - ENC[AES256_GCM,data:1tqNcHWkTcGSTcpikuL+FPcF,iv:QWLUuVN6568TqlO2FN2wsQGXUoLVR+4CeXuGrvlVdM0=,tag:72p/YIov58wPBXSMITnq8g==,type:str]
                    - ENC[AES256_GCM,data:Im2Se8fFjov0P/JEZKQ8CnFeSA==,iv:A2r03fAjyvob+hICrShcy82k3U9Ocbg5dnFte00hRX0=,tag:IHqETw+4T4SkHTOoWCmwTg==,type:str]
                    - ENC[AES256_GCM,data:GDPZEICM18vd1zrOspfzEPGkoQE=,iv:Ly16RU5jZnAeSNVZUNDPKfEPK3YIbFWpfaEkIXTMa/M=,tag:pPZPF8i0yairMstgwC8QnQ==,type:str]
                    - ENC[AES256_GCM,data:sO4iYaMFqGbSB0vlVg==,iv:CAFhOXH1BToKd0vRUroY3wsvu4EVIRrzGIL215bYWng=,tag:7sZBTZ9HOaa9becXnB0pVA==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:KdXA8sIa9e3auWrTpUQvz/RhWE2f,iv:Y/Vh6wND38s9Yf4/kqJw5+VjVxWhHsAawTPsPN8iXrQ=,tag:oQDcH7IPMBS8KP4FWoznzA==,type:str]
                    - ENC[AES256_GCM,data:ChFl0A6T7Gn98q0sUvAQVi14HEeq9pY=,iv:8NuFIt6jlr9ZmydbjSwnfk1SF3/O0hH+kVAtuEqstaQ=,tag:sw/VP8iohVW1qVuXVBaUcQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:gZhiBSit6eToGxhUla6pZqA=,iv:Wf1FXANEyFD6rL5uGqQ0AP5HfZWx0qeBWwJ5Cn/o7tM=,tag:FM2v/uVdarIB6+DWSVubyQ==,type:str]
        - ENC[AES256_GCM,data:OifXvbqWlwn4CUloSSjv8TngWw==,iv:GAVpha8Ms7NksqaCBy/hOgp7t1wwSB3tyR9b8NcF9tU=,tag:Rw5XqFPgbt05CAZKAMcJrw==,type:str]
        - ENC[AES256_GCM,data:DHclGed3DEzpEaH9xTusycEPe0s=,iv:2aJmfDtNka8kNruC1AaezEmBu46hyzngGkQXJkjHxqw=,tag:zlfnBGStklneylf8J+aPMA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:hr8s4vUSjH4Px7Dq1g==,iv:xYXj/gIfZxhdPnu1lpYs7k9XqRgbLVN5IRDtZYA0fOc=,tag:gQdkN7q32/n4SEHo7vCymA==,type:str]
          description: ENC[AES256_GCM,data:vOKwiytx2Wv8ZjT+VA==,iv:773ijQf/BmATYJ1z45/q6/An9wW0iRGUW1F5cuf51eI=,tag:pSpWdyzI85zkYhD9bshF0A==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:ogIWelzxEfu3WRP/rIXP,iv:5ymTgl5lDm+xQAGSZxj3eCBSo1Qod9KQNzCH0bKpTyY=,tag:xmDnbxvDpbM9fxdFTgyvCw==,type:str]
        - name: ENC[AES256_GCM,data:pWMoYXbriRE2smad,iv:a/QdeWQnpuATu8pcoxjdqHKwS1HemtsPkoniigvo7gs=,tag:KvB6+ttJ6sxdxoiB+nR5tA==,type:str]
          description: ENC[AES256_GCM,data:x0g4EJtaFlCsg8qiqhZ+FUxBFxUNl4nx,iv:eg2euzEVLBxKy7g0oatOED9ZEBZidCOqzmdyb+60RQ0=,tag:AVNKNRFCvl3uncPfv7kNkg==,type:str]
          deletion_window: ENC[AES256_GCM,data:AQ==,iv:dyjSyBLmVFiP8XUDRa1Zqet5NK1fxW86wEHwxk8xfFc=,tag:iSTjxHROHz874f4rQnnQzw==,type:int]
          key_usage: ENC[AES256_GCM,data:4/xT6IH2piRTreZRPbhP,iv:aeBBQl9yAfsX0aYkTQWq827wnpvXVPaI2QlxzPw9wBE=,tag:u7cqRnvW1TmPgczDSvWfyQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:EM4yJYPMpq+iG4A=,iv:uUTbARqrjP/ttkVlKCCXjxXjL8hukvE1O/tPPfiOgjU=,tag:28t2T/XCkfnQtLC/aQZOlg==,type:str]
          limit: ENC[AES256_GCM,data:19TNY4gnuQs=,iv:76/BC+Zvgp6i4ruVyJemHe4V8lw86VfZ2RZi81/34JI=,tag:0RwkfVRT99ENPp8IJZDWew==,type:str]
          notify: ENC[AES256_GCM,data:/1b+S++OU6sDW9B8I5jcEgBHN77Jou03,iv:de9QRe/jHZ7qvowV8NzTeY2znIG0BDeF/dKHWa7LKM8=,tag:kqWPOvVd7j3Wpaen1lTt3g==,type:str]
    ses:
        - ENC[AES256_GCM,data:G47wdHS8/yfnH90tDXqUj4wDCFoUw67kQ5/daU4qaw==,iv:wsDeL3BuyrWRD+H6likD/25eIv46CPpdHxrDlvBjr+k=,tag:d/2gJUT0b7jKmOH+ga7iGQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-06-03T23:13:05Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEJRh8XnaCf7df6BeSyrMMeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW2uGamuVS4R9+6HXAgEQgDt7bX6oqHOoSEe4CM9YGnhJ0Wo1y/9IiZ1tHpNo2aBzmTcoh//5wetf4mZeXxY6mw9iN0ZaxNUAsqc+sA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-03T23:13:05Z"
    mac: ENC[AES256_GCM,data:qTw82TGaU3fZGL0YOCj0lH6UvYTv/Cuk12TtbetCDgoxo+FU41/Ap2AbgJ75a/mr7pHi/kuRR0RifmFy9IE7MQwfrgE7o967DnfBre08oVQR9dlE6D/iMMcG+gK1CYC95YxyXW0btcGAorUrBEPX62FjEbjMh/XnaldKUKoHwDM=,iv:7KXNUNALWrVJi3UkaNrxod+Dyhvg/xGe2RhrtMPZZ5s=,tag:N2FdcsBJ4S+Ut3aQ4iVDPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
