aws:
    name: ENC[AES256_GCM,data:bh9uqhiKQzkSg0j3m9Ex5dA=,iv:ZrilmEdEn9xMJXldFPvNSTHaaCfT2B7WVHHYxnOHw/0=,tag:N6N4D2jbFKGMKf1HCL53EA==,type:str]
    region: ENC[AES256_GCM,data:DaF5GiSuSpuh,iv:9s6RAL/I+0Sd8lZ5UPxrdz69cauEHjSiytgVHm+JG6w=,tag:NXr/K+QSvT9cVzMv12x5iw==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:Imyqk9hJyH0jVmGB3DZlms3aZHHTZbJdKCgIBbLS2rTDjMotaI1n1TueVA==,iv:2HTJpwcnvjfcy01Hyz7L7n4Nkc2FC/mht5YIEIzLDC4=,tag:AUMV8qACNwhGvxdmqY4+Aw==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:p2t4GeDVYuUmoGRO7izbbWA=,iv:2frOlzZRs9DlRj+XfeZfyypXViMSSWrXTfiYZjVxwsE=,tag:ZasuasebOZYb3U6An0IYLA==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:yJYVmzTOG7Qs8p2Zq8xBevJQ5C+9cse/7vi8j5nm5DPAG8RYWDZidA==,iv:P7Yi8Ef74Fg99MlRZRtW+cLXks7oErkaVjv1Tkmyggc=,tag:tW3aMu6alIP616SEzAEGXA==,type:str]
            - ENC[AES256_GCM,data:s4vZ0sIMUy+55XHYrokNmSHBaf531kxqKf3FPSHrG9nlTsXPIFeDsw==,iv:4Nk2RlUKpBF+4Cajq7Nee4XDq2oqXc81JSahXp24EuY=,tag:GiXYc6pcr6CFpNfNJqwpUw==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:dHuj4lDPRmjMMq90cAMj/lURDw==,iv:0v4AoMrhBtiipOLZmzpqWo2KlLdIMz6jsQXz1YiSqT0=,tag:6NVTLDFp9aCFvvmJGucFzA==,type:str]
                    - ENC[AES256_GCM,data:4rL+YihbeS/DevJ7dY1RZvLw,iv:X/8UNKPSnZXFmcwz8JF7zjbB7pZsk/HlgHgMYShUPUI=,tag:sOdeqWrLO7HKMsc2yIxelg==,type:str]
                    - ENC[AES256_GCM,data:hjLJrrklt1YC9k7Fs3W4L/MlGw==,iv:OeVGcvg86541FmGZPqc4jpQEmJ/PWE1y+uMnLfSgIi4=,tag:mbZxMtjB6M03VOlZsn3YjQ==,type:str]
                    - ENC[AES256_GCM,data:KyKQpybAOOgEJWzGym6X1XsA5tU=,iv:6xO8wNPIDYYateuAZ+DsosMxP/cfpOSIxRaZyxdt8j8=,tag:WM86AUBV10lVYg3i7UIY+g==,type:str]
                    - ENC[AES256_GCM,data:f1ufZffHL7XlGFNzNA==,iv:1D8ijSrWNljVLl8stW2bpMw1T8vcwpzkc0Sdado8IoA=,tag:Z5k1/SiRe3zokaj9fyhclA==,type:str]
                    - ENC[AES256_GCM,data:Du/+D3A2j/x5ZTAU1iS3eXI0P+RgmAOGS1FwbsLQnMLFAGn1Be5MfodcZV4v,iv:CePH3RuTZiwG1z0yF4JVBujYyzHR9sfJNgL7T4jQzPk=,tag:O6D0nAZdPY3RWMgqq/KxAA==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:CzIPUWX8hHrSZ+3Gc8KWYnEYg2Zc,iv:HEdKAq9tqsSWq+KQQOQ5Gr9p4tTNh4ZI+Jqoe26Grdk=,tag:e7uGXOWwSbw2/oc3YVUvGA==,type:str]
                    - ENC[AES256_GCM,data:z/gihK9uOHt6ODuSZmhhxq3e6AlfjYc=,iv:hl1fBtwixSZn6UzhZVamdYW98o1dnCiLdXDIKW2QQDA=,tag:giollip7o+jTdWu31zcVQA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:BHzm+wBSArEyXwW8pLV5axY=,iv:erPWZmUTFoDkYq0XAf/1BdQdJfYuJVz2XyYx1b02jhI=,tag:nstMHaa5WFkmPMUVMf+mSQ==,type:str]
        - ENC[AES256_GCM,data:AU2AVeIOxzAWFRC7kXv4FK/brg==,iv:EyqlRNAUoCW0X4+D6hdZzuddQK2tVWeSileVEjssbag=,tag:A6hHc79Asaeso37tg+HZUQ==,type:str]
        - ENC[AES256_GCM,data:HzB2QVxhcvMrkuDT0+kAQyHfUao=,iv:+PCIcqbIx4b7LI3TRmRHLb2POUn7aZmo8K43tGX6EHM=,tag:oBPlwN/XkQa0z9ee3lK3QA==,type:str]
        - ENC[AES256_GCM,data:37a8Jcra5LTYX6bffbO+vg==,iv:qoY1haMKl8yNfIXOkf7xZ7JAmqOIPTp/yhckstRZWuw=,tag:6jZycnX2GTGaQgRllVK3tg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:SnX3MzokI6u6axfA8w==,iv:KEkyFIHWsNbrGcBe/uYj2a56Enj4SJxyoEKIqNCfSUo=,tag:9vTh7oXe4La97PIwmggnTg==,type:str]
          description: ENC[AES256_GCM,data:wu+fQnUiYSeBus4gww==,iv:0ljPldM/STL3VTI07oLMbWf0TUilA7HPuuLQgD9ahOQ=,tag:bPTebPQ6KGJnYu5eM+xnKw==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:AXAviAs+21igKiZ3lTBH,iv:zkW7Qzj0k01zBhHnGZkJiDFQITxHNSF9H9rGJSLhVSg=,tag:0z2NSLKgVCqRK6KI7Nvjmg==,type:str]
        - name: ENC[AES256_GCM,data:OFQxrQih7uqVH19E,iv:o6qmkITMIyftwgrBeZJhaJWb37RVejpeiFEbqg6XPUk=,tag:mrBRwOyalJxBZNLTyctMxA==,type:str]
          description: ENC[AES256_GCM,data:bBQDkDoa6AK5ft+BMo1Nx2G3UViDCJ7Y,iv:s2+x+/X3UJR0HYpGbrOsluuBfKjQjkBeItzQ8lnk97o=,tag:Ex0Ivw89L03NpghztAi3qQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:Fw==,iv:tis6Ambt/8Vtu2zC4aShzFYlWcWLWGNz4iWqwKgZPIE=,tag:jCn+QSOiQNL7beRbv5Zliw==,type:int]
          key_usage: ENC[AES256_GCM,data:OfGXjLZ/WGwczAPWyim1,iv:sFdH8JjO6UnlZGJ9NWHt0WZf5ruzgS4XwVlFFS8TGDE=,tag:R8Mtn8+e7Lh6a9ICuwELHg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:iXa75Dzjpmk6k+0=,iv:uX1iZoYIyjKdLKFCv9a7XKv813FWN8XKh3wyo4EuSEc=,tag:LxD1fGekfjT8QgF0CSIChA==,type:str]
          limit: ENC[AES256_GCM,data:CpnYIgmH9UM=,iv:mBS+phZa+VSa3685EbHfuVHLG2N5c1laUV0QKmPfWQM=,tag:HxFwMfgFHnGGaFGZMAp4YQ==,type:str]
          notify: ENC[AES256_GCM,data:46/QlJtOdnI5ueAZfRXHFSzVT3UnMnxK,iv:8PUjkaVH0TKrSdANRJ2X7f1+0LmBFeF0nTjBhPMidyA=,tag:V4GBbtjLh/YwuEAziIphHQ==,type:str]
    ses:
        - ENC[AES256_GCM,data:TSpc70OgIj4SD52f/gOxlaJBODw3GP2ycSolPH3CJw==,iv:L/7v/d6QYQob/TxQz0XdKHY3LdaJQn1qThd5Ka1V48c=,tag:S+ArgrfRe6fB2S4w3LQEXA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-07-01T15:07:51Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgE2gnjcFnlcIYkj1bC8Ex4qAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyTHqfGS4RJWo5Z2lAgEQgDulygKWM9MXWUgzY/Q01uNPJ50fhhuBnlUMs1nhcdSWNfpDl0/gq2ALONRhbcrPRtNWPc3z2nvycItUNA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-01T15:07:51Z"
    mac: ENC[AES256_GCM,data:ZuuM1kVo73ZjYODfzWgPjpI6OInDUlLAJafkoBSr5cWmQ+eNtOyCSFPpEsC0TtX/mhyA9oa5x5EuqXrHCNmYKTVsUCkibrglmmqz7sTaitOH+ajWfdPI5pPvZGJ5mnlsySSS1zN2+P8D7tvwNbptT3JmhMXzPk4wycffpCD5VkM=,iv:T4X7+Zo1piOqtYPe4147oYrmwSBhVdA6jL6JC8Gw0B4=,tag:7yyzxT+wKma8ez+WPA3fBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
