aws:
    name: ENC[AES256_GCM,data:Ur3CBUoApKSubhxEP7Rv8Hs=,iv:iCWyUswWP7ga1C7T6tafi4NPAUMNtWrMyNt8rbtm/WA=,tag:GsgBKXRo3myDogSE4IBbNQ==,type:str]
    region: ENC[AES256_GCM,data:3oHEXc5po+bX,iv:VuU0i7rIgP79wzsQt9CGPOanJYxnfV3QDL7CsK8JJI0=,tag:drIGgQHv/QqeY3drtkZO5w==,type:str]
    buckets:
        - ENC[AES256_GCM,data:QQhLxV3onAqaQ4XPlbwWKKU=,iv:EO+ZtxtEXNcD8dadURyaLbpikbXCUNeBbSUwtvC2ikc=,tag:vdSO9bl5qIjUUFzkrzDHUw==,type:str]
        - ENC[AES256_GCM,data:CE+i5B33jJnuq5HEjNJq2BpZ6A==,iv:vs2po6V6G5LmzGaeueibqkotgNjMTUYO03WzZaWVEYM=,tag:a5iYZgwINoGmXHpfyQIuHg==,type:str]
        - ENC[AES256_GCM,data:J1RLAO6qGPNqrjXy1/mxIvHxKMs=,iv:HSVhzohOy9nLW3gJjHWAEVzHysnSBGoR0bK9KCQYxwo=,tag:NAIXKXEwihjV39OPoCDiPA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:XW1fPLMRt5PfUeEoQQ==,iv:JS1rPpPPgeZ/1pWCvSg3irMqT+FXa+2+Oiaw1zmRyNs=,tag:g61H5lpwuQS8NgQo2rJRQw==,type:str]
          description: ENC[AES256_GCM,data:NldmiCHaC4ElfKfAhA==,iv:DwISK93NKALMkuytMRC24bU/n9GpZY3uD9TBUtDRGnQ=,tag:SrrpbU+pMPBkC5DdTS0uOQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:aCLFYuSQdw1KSx9txexK,iv:5xK+lhIrxFQdYZ4FFzX7U6Kg3We5T2RrZt6rnxIr09w=,tag:HLGWKRwu/rKzf9+M/M+0Sg==,type:str]
        - name: ENC[AES256_GCM,data:ZErnWKEmND0Pgd3K,iv:L1Qr1ATCFG+/obT9cA0VQwhgz16PvMYLw+3LthCRHik=,tag:ohb5ySIzhPrhL70aooiQBg==,type:str]
          description: ENC[AES256_GCM,data:2OFIqTT5Q/syzQqtQh96svT1QF+0D4NG,iv:1crToXi8Us2xhpyzIM7qlAVBX+1gcMLVyFfbtXG2jlw=,tag:NDLRh4DI1Qm167mLz6ASKw==,type:str]
          deletion_window: ENC[AES256_GCM,data:Iw==,iv:fymEJUCO9+zCV7uFJFAV+FqFzte3SjTJ6PJ7uyRsKfs=,tag:s01vxEElVJzq8ZqRstBZvQ==,type:int]
          key_usage: ENC[AES256_GCM,data:hoBLPty2Cjd0QCagxmmw,iv:cQnJyZa/qy3UTSN+XAzHKS9fV06p+Tde+95tSwY8X2I=,tag:AyXgmOEBEcTu6f7B+NlRmA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:Yh9sP8gFNQ/D7HE=,iv:IZVj5Aum5QLntTXRbyAVMXXGzwOqvjDREyPrihuH8e0=,tag:fdcqJJ/GV5lMoE/utkRemw==,type:str]
          limit: ENC[AES256_GCM,data:jNlGNBHFJPU=,iv:BXlqMHArP0HgcQq4J13gm/jiDvPmTOLivOn28nmQzMM=,tag:2zH1QuKQVm5Ifq8PHLJb+g==,type:str]
          notify: ENC[AES256_GCM,data:LqbidPj6TSjugXnm0ASO9NbLhL1Q25DP,iv:hUbKggaklecc5++XLf3zAWTtqXEIjl7PpEeLCdGoXik=,tag:AOi9BqBMY7IFyDvV4e9A8A==,type:str]
    ses:
        - ENC[AES256_GCM,data:Vwj5j4HLrg3xPqdmuiSnzuyt8tFVpeAG3rNzwrW5Uw==,iv:Uk2mdKdQP8OCt/5JmPmLkL7zPR1evUPK2iuwKwQg1hI=,tag:oNpvbaFdxi4Mhb2Bmw7N5g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-06-01T20:03:32Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgE/VeDtYCM1CTjJq5vsh162AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMASSulniziNcUBob2AgEQgDuwNCXXFgZibzAbcM1vuJU/afVdiBphFJ1P0D1+JZjs/W7GhPO3eeANJTABQ8PWRSxmywde/CAT2HiyBQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-01T20:03:32Z"
    mac: ENC[AES256_GCM,data:Gn6Tqf0JBNoKiaJvwI1bZqfN3cvvSIvavQpkPw6TRcsXKgyAQpr+bZH0g/XwMtGWU3PHXiuUhTzaTxrwKto4ohI0dTNtIzUq1l6mbEGQlsSeENrfZI9DugRViOm2cQlcNwOp1UgzIW2Roq6ovJ2W2SY/uIQT6YyiraZ8NFYjIM8=,iv:/tA1TyyUWfFDc8U7Rd/8LdM0/+stlgH/79QI2DCD+fY=,tag:NfQgaDgvBSJY0XFY7QwuQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
