aws:
    name: ENC[AES256_GCM,data:x/BZRZq+abSu5NfcVkcSZzA=,iv:eq1/JRfworslOHdIQShxFP3a/pg78mb4UtwHnWXVGtU=,tag:FEeUu9g4v/mIGWreJPGcMQ==,type:str]
    region: ENC[AES256_GCM,data:Ybtehhir/N+R,iv:fPUpBF6jV4Jg1KgyKNB67yLJG6rlauIKBpAxzhZjIQU=,tag:fVgCAmyQZUCkNpk7SGG17Q==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:HS60x/b/Bf6CudV35bFzrMvDmc0ZhgiwabTETBxtqZ5GPW5EGwSrkVFaZw==,iv:olxeGPlExDLPYjaowZR10eK3EXBMekBpJurQSrDO2Yk=,tag:wwmIvIgl3qAM2zwjjTHrBg==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:qVmv8Hbha1tDPCwrJaC/rhE=,iv:uz8WjhcGAnfXA8+S3QnJuOcCjVTNpCah12NSJYk/V18=,tag:OkVzyH9s8SOB0qMLw90NsQ==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:gvOLrGrEDuIOMaS71GPHykfWbxdO4dtEK/ciTLSs/0PdVzHt9LvsZA==,iv:MNPSuq6tG3nlj6tSd9xDPkXq/pPjZW2Yt1zPuQ74tK8=,tag:BL92neyPOxrHitHDNe0ltg==,type:str]
            - ENC[AES256_GCM,data:K5DQbuhJn4kLAsBeJZkROsJfwop6FeVE6Sh4hwz2tio4GmrgNFGyPw==,iv:Yrl1dFy9OGXCbR6VT8/mS+5M/gRDNCN3+pOaESTOd4w=,tag:zfxRSKdShi8oq/rkShR6gg==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:7tX18H691VWQFTLQn7x9rkECYA==,iv:ujn5tz3i6zYm6kPvQB5uP/MiTqfAzv8hDPyR0x99wN8=,tag:0kVZuMvchdlOhBtEPUxnQQ==,type:str]
                    - ENC[AES256_GCM,data:u5uCOxNuyllfU7GaNh/DCWSR,iv:J8RoLgkLMuzzjePN/mt02iARPPYBGZh11aNQC2NLUfg=,tag:s2VMtym0U3dRAAMx9fNUgQ==,type:str]
                    - ENC[AES256_GCM,data:FsUBwFtcuU+ZTclph1uylPiFjg==,iv:lLDgs5WjUQc6e4VnVFITJufrKbh6fXtsJQ+o0OMU6A0=,tag:orz2giOp8Ody0iY4Xxk5hA==,type:str]
                    - ENC[AES256_GCM,data:LLlsMvidEwPy8cu2Qtpl/D5Aq90=,iv:87RrPRMAEtGfc3o878VDzUqUXLXXE2DUDtRGYYoffMU=,tag:VLzp1ZAzFy4B93SopW07vA==,type:str]
                    - ENC[AES256_GCM,data:gk/ZbpimdUTPPxpbmg==,iv:+dmOfrO3eAA8ad3nYjG00XRpvotujv1JWqhrqUgl6No=,tag:E7gmycIGRoPp7/DFlnRJYA==,type:str]
                    - ENC[AES256_GCM,data:OAgC7At9YQYsKwVjDvMuULVC6ZhRba8bH6/ZldkFriS/hje60XR/FXuawQot,iv:DIU00+U1vQA+eKNvYv0e2nAnaHuVh2ci/HeiK0IZ174=,tag:7EWcd25q/dNAJsplI2G1yA==,type:str]
                    - ENC[AES256_GCM,data:nvztatXRNUtqRoxvDFZUYkJqrNZW+1wdcJeiWZY=,iv:mBQyr3x2FDX9ahbWLTijXFjT7T4cRUU+T+jVVMzQji0=,tag:L+ZYvA/Z0UWCUjetSBiASw==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:gFDO22/L5KhSeqhaHU9YfUbApJtS,iv:TkXWfGz7fylmyZ0Lz0HgeaQsElpTZyFYrVGGLeBw854=,tag:E1RKHvhIELjnBIFKIvgUtg==,type:str]
                    - ENC[AES256_GCM,data:G5Bl5bBAMj19BY5TXNoGthqp,iv:rw7IEXD+Znh5bKkvP4XSh1vwu9wtG25yvky2FeVqNeg=,tag:k7dbR0qNwk1JMoENcruVGA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:Z+Ko7IakpVRxkWdzSR5mI8U=,iv:UYu8ANR3+RxMreVZr7kjosqiWRNZYBeJ5ytYgl3599E=,tag:7Hb6MF4hFZ2s4RpctBf9Rw==,type:str]
        - ENC[AES256_GCM,data:zLGOgu9Aa78BKshHD8n834Xl0Ck=,iv:U3ISPdIpj38sRQskoMVYiX/W24I7LdS2jTyzbEDCP8k=,tag:Q+CEirn9JxO8FTg9YIxQMg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:0nzFZQFYq/N30/T1lQ==,iv:FTi+VoFU2LZtYMgsYjEpAckR4kyfzO5ePsCkaCAjZ10=,tag:kVdt3dnvVUYFIDG9ti+RgA==,type:str]
          description: ENC[AES256_GCM,data:PJqq27Aa+XqJHxs3gQ==,iv:7GnhBI2DiqC97MxRwqUvwa38EKRe4oa9GmvKeBykrOI=,tag:1zXkwDGYINgLLpTkXxNHFg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:m5j29Ypy91UzkfiUw+p0,iv:bzCLE57w/k7VzGv0WjjLJb1TQ/1GWm+veiSaixk+Yu0=,tag:l4Z/lVKauJ2/hEij7ykqKg==,type:str]
        - name: ENC[AES256_GCM,data:NaP7eDAvO020scNW,iv:MK9A1xsjXGY9RNweSYazqG1uoJcf4mqKAYy1chete98=,tag:JInEQGDLmp0DkU1B/LPBcQ==,type:str]
          description: ENC[AES256_GCM,data:rAquleRYpImvqxNqpSaN0GNZ317c537w,iv:A19iBhxLhORrdc9o4FQ3BiiBCwftwUB/nMAWmBj1q4g=,tag:bTkX63Q2scnAr4oJKzQ74g==,type:str]
          deletion_window: ENC[AES256_GCM,data:/Q==,iv:MILIZ+qAwruXw6ETKoirbN0QAKfqN42uJ5X684qCJEE=,tag:B5rQZcszPaI0TaC9u7lAow==,type:int]
          key_usage: ENC[AES256_GCM,data:DC80LZF7Qooly2avOX7D,iv:UlBeuqWjmqxCnv9ADOg18jjMY04De1GywF4/PdaCCI4=,tag:Mjp4FkXe9SWv8UjeDD1g+w==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:6X0KdYtmHtLrrMM=,iv:V3D2xljG/I6a0rlxA42kbQoDgsjbJRSWeOjvajAmIq8=,tag:aifyBeEkhV9sUR3sFHGoYw==,type:str]
          limit: ENC[AES256_GCM,data:x+SOKXyGku0=,iv:vFx7AQWn/qqyFW33a7OfarOd7GYzUCBWHxaVIGm4I1I=,tag:aGABR4KuSpJl1CElWnPKBA==,type:str]
          notify: ENC[AES256_GCM,data:/BY59N1SCq7JCvfqRd56DZMkonOnv0nn,iv:TrUnWeTfTtIIZLSwqbZiZASEJmM4vgZ6Z7OISapKbMw=,tag:9j59GGr0CAAzN2IPA4XnHA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-09-24T20:53:54Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgG+6/WWXz0jUO+VfudfT9FNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtIDC4qI6rOtkakyjAgEQgDsHKriBs9a73Fq2mq71PBz+YnQHqMNoVTk+2Z4MC94moveKhvOB3H/Wc1c1TcK7kcRWRODd3eWZeQgrrw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-24T20:53:54Z"
    mac: ENC[AES256_GCM,data:TnznTYNCSrn/Lquql1GAVYxb5pkjtlzHFHlCNcmcyjKZ8mTtR5oU5VGzJBsXfMag3Gj94xgZgvOPaeTwKR62lMgmnJVUDrijLySJIWLnrl2fBPzLoFcEdai1xuLGmiQkiEjSuHX/gT0JoNf+yDKKu/kGQOYSJ5vkXV7noAVWpW8=,iv:h5t1XP3qyyaLHNnzQJ2pYTtEZgKNKEl18TpFNYuc+Jk=,tag:RDiWUFWdieOc74aelcTFug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
