aws:
    name: ENC[AES256_GCM,data:qlQ1miRKNhDaMhsUxZGEqlE=,iv:xxPfQfwiS8UVLYlG/0GLYNOyPrdXKB7gu/Jny+ndL9c=,tag:StS9dtI+URWy64jtecFk1A==,type:str]
    region: ENC[AES256_GCM,data:Tdzt6SDjvIBm,iv:yczQ9Dk492sgJGMFsXHqbBHJrCSWqgF5k1iS3T9BQMQ=,tag:BpEO4ng6PZEUP62YxDcbRA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:KrHdplDZ1I7B/U/x3qQrD/0=,iv:0FyZTkdSgGN+IRYrjQ5OzF3RGQzur4pyTEQ7+lcySaE=,tag:SBOjZJDamR/Srzl8O16HLg==,type:str]
    sso:
        config:
            sso_start_url: ENC[AES256_GCM,data:ljgLo75hvdz8F/XQyalTaSYKirA+mgpomwlaxxjBaZAYWg==,iv:UrNfTGct8Y9qEQH4soN3OnPuBRBaRD6HFWgDz59eF2U=,tag:6zonvpB7wZVuPLU7hwXi1A==,type:str]
            sso_role_name: ENC[AES256_GCM,data:WOELqQ4vK9WJPUHfeafM4W4NRfWwWQ==,iv:UcvOYySYKoUOPl4vlyV9gQL0ds5dE0BPGzi4R4ikfv8=,tag:/W7EZR2FXYMKcOTmQM0ipA==,type:str]
        alias_to_id_map:
            certificates: ENC[AES256_GCM,data:vE1oacwNrRX0E8BP,iv:FYe+A8Gj7lwaErbsnM8ntYRftUkb8mrNOse/ODVPUxw=,tag:jQXOqiUpnN3GylXZBGLofg==,type:str]
        managed_policies_map:
            Administrator:
                - ENC[AES256_GCM,data:dZNal7JuknanbDJhsutYmq+EdA==,iv:6E6g+wz3A6qwLmKBnROdSyqIODPGOrhGi5MskkXQm9g=,tag:02da/mlc1AdAjKfKWpyeSQ==,type:str]
        custom_policies_map: {}
        boundary_policies_map: {}
        administrators_group: ENC[AES256_GCM,data:fHm2hPdNrkEg3fpDv4Y=,iv:/zvbS+LXKRcHgbif171JoOjDJtbIXcV5yBl8sCzzrWY=,tag:z7iatpS0rI4O07qYQoKKkw==,type:str]
        cli_roles_map:
            Administrator: []
        users:
            gerard:
                name:
                    first: ENC[AES256_GCM,data:USC8hjrA,iv:EI+P+NzyvWH4jqEmJ2qMJ8RjhRmHFokHYD9WulaLDzA=,tag:ntnh2WjrEbKauqFJf4dfIA==,type:str]
                    last: ENC[AES256_GCM,data:5WKG+kyVyDw=,iv:TEqTvdzHBCynFz425aqRKlkU1xN9iyLMzUilcd+pbFQ=,tag:kIj/KPGzgHBpgagNBm9EDw==,type:str]
                email: ENC[AES256_GCM,data:xs41f5wGVo9QfnJJnQC7s664vCYW10w2,iv:ZEHyvoV3LQKxG0tasdjBV50ucU35DdYYIkseZ5av76o=,tag:OJ5XbuVVLsAaJxLHOOc/hg==,type:str]
                cli-config: ENC[AES256_GCM,data:syylP7U=,iv:bjy27NApBS9noDsBAd8eJR8+KtZHqxMG7GaYT5Bhgn0=,tag:DJg99dm+eewpNR+k6fF5Hg==,type:bool]
                groups:
                    - ENC[AES256_GCM,data:OV9HeKtkrrk=,iv:PAC2wsZjB3WYPY4N396FwRfiRnT31PjpMkR0K+lI/ro=,tag:yKjMQlc3Bk7RCmLHB8U9Ww==,type:str]
        groups:
            Founders:
                Administrator:
                    accounts:
                        - ENC[AES256_GCM,data:WucWTvG0pM1nO++C,iv:LsfT4IEMXVIg98Z0l0NtHfJKFJOsy7gUdkpWXgggNR0=,tag:0lqJ9mO65mvo0GVxm5s6kQ==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:WzBiYmXWtHqUvs9xDnkDAp5PAhm4E9jvb94pG6BITfKmONFvhoq3Fk2LIg==,iv:8pl36SpDD3iA759hZ5s+tu4IcwevrZkbmecgwAj39rM=,tag:ae4G+s5K2MNOwx09JMQ78A==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:pXoE/6tO14wGirzxmNGBe1o=,iv:D8Py1lOkCoDXFY76e3Oldk+BF/BNC4WKd8OAdP/XPp8=,tag:+ZtYP9QJRp/q5VShdeq3kA==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:4o+hnS3j61B4nLZWBj5x2PpLbTf58VYXP6h4pzLQJZfxpqGvNYZ5Gg==,iv:m1eJiUz5FSJ7AvIFAExiOStRhEH0gDOrSzlwnpyH8Es=,tag:YcJwaWSlArOfmtI6LShPtA==,type:str]
            - ENC[AES256_GCM,data:dWGgm2fetkrgGa6rOb4qokXFCs+P+QwKoWoapiEP4J1ltRvcenBOgA==,iv:jNohFcaKGcN8dn+0ir0daFrIYZpOyK2M7jbTmCXqRj8=,tag:nlZ7ilqYgEbqCtja+sxfwQ==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:gilPwjnbn26o6NM0L0RUQVWbXR+N,iv:Id1fM5BK3QDdk3JUgpPYeBDo3CWt0eNtfkfHk3IYtdY=,tag:YlKA+DKZwjrffWaGQWZEGA==,type:str]
                    - ENC[AES256_GCM,data:nZG/aICl8uOPkqwgeasxrLRc,iv:TwYw+UG3c0vslLHsYKZkHjppCXS4JibRevpbZjjvdCk=,tag:YTK1xTYkM7EkAEgWRgdVkQ==,type:str]
                policies:
                    - ENC[AES256_GCM,data:6q6KbbEDYCI0umaTf7V2ZXmN4K/F3NLHG9PXwwiQ,iv:ayIS5AX/g+Rc0jl9UfuJOmm2LhZNvCibSTkC2Yd6co0=,tag:t2vKqlnkc/AyCA/wuZ4sgQ==,type:str]
                    - ENC[AES256_GCM,data:zW6/CuHGFpn2IQQxnEV8,iv:Dj7AJehdSGHd50kCTTf910fA5vN26y92IxgLkQFJGjs=,tag:UnZrNWr2ioRnVh3OylgjLA==,type:str]
                    - ENC[AES256_GCM,data:qZpPsCfDcSqhPQMfLg==,iv:4n4nNeOHwhiBfcJQNlzr9BjMNuS6bxgWiQnWLcGP9BQ=,tag:OkRTBUoOB1SL1bpuPw/zbA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:LpDxIkH7GJ59bgD77bEtXpY=,iv:MqII1KaHefbMNds7hsdgMh/KKrI5upELueLBB739zHU=,tag:W0HkRkP3XjyWd/vXb7tFYg==,type:str]
        - ENC[AES256_GCM,data:BatePIl335rYdLW62LK6X3nD50Y=,iv:56ofxaOo6TMWGZUXe5hZJ6l6/uNWPETaAxik6mb+OZM=,tag:En9uF7gpLRgKah3QACS5MQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:z1ICLeiTTHFokY7KyQ==,iv:enKypF0+Fmlhk7XVSQQ/OesaRQCBqhIKu4XocrVjoc0=,tag:UoWROZoyzHfcBwDYQ3xegw==,type:str]
          description: ENC[AES256_GCM,data:0c/9wF2vbOI/lCrhpw==,iv:Qq4NO5Qv/srpZwXDHSoHbLSqjI5LAhRp7X5fuEXA7bc=,tag:3pgW9jO2uCugiO/WUAMsBg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:XkdSiWu5dY01F7DhIeFu,iv:rmwf6RJSgTc0jQlSbq77Noi7rmvB/XPwPmVgIj9kvu8=,tag:8tgJWBthn4Ut3TTCxd40OQ==,type:str]
        - name: ENC[AES256_GCM,data:Q4EQo9zvKhr4ErkE,iv:mvXLiQyovH5mm6OjK74G8+/A30kswVb+wVWueyBSjuQ=,tag:1V819DPmVCVujCscyCaeuA==,type:str]
          description: ENC[AES256_GCM,data:QPittAbWtYqfuIFnlxN61tpE5n4gyz5L,iv:8ViopMQXH7Z/gn0muRU6jgcb8sjXgFlvtRwyTrfBXcA=,tag:he6a/KuvoKdjztI9mnVOnQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:iw==,iv:i9BSlH909+abT8Bl4uCAlA5XkVcGXnOZfrdpDxrBIm4=,tag:8OTY1k9pLkZJV7MKj+QrJA==,type:int]
          key_usage: ENC[AES256_GCM,data:lnIfpetFgX5m7iKDWU7Z,iv:goEW+cOJmQa+sGXTBbbfVcaPBOQLpV1cIj9chBtt/bQ=,tag:JFTGIEhVeq53jK8oyG3ZKQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:zKnJK8UgHbvVSqg=,iv:YbZwezIxVBTsY5ZQ3XX660z3SSyUAwmvux3UgOlOt8g=,tag:cpU5pLl3Dak5AqCDVd5fOg==,type:str]
          limit: ENC[AES256_GCM,data:E082gsoRbUM=,iv:PDStroHIDMp3uFJkuEl4MhYhZppPiPcfkB3f+dnuPs0=,tag:YnZW7qSnyEY4Od1f1bgdLQ==,type:str]
          notify: ENC[AES256_GCM,data:1TWkjJvUMNc3vM3P4gQQUAblDNtM4iTV,iv:mKigeXBPQM7PlwVz/4KKA0nDjXifDLgVkCfNM/eq5BQ=,tag:ee4lZf/46Agk2/xkzLQWxw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-01-20T11:33:17Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgG2gRlNcEJUVmfAtkJMfZ3OAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+9Vrq10pR9MJROFrAgEQgDvaI79rSCAL1aq/GFy6jtf2QYgwDSLCzESn7cbMgbqRxlHmMqACibu3TDlQaKsUcs7msxQRLM0WnXtkWA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-20T11:33:18Z"
    mac: ENC[AES256_GCM,data:A0GdV3Rs6enAMh6gQHZGgrxJYbeP91pcGYpk1BARfJ+k7f6AjIwQwE8t3P/IifXFPtEFVTlbCoxu+OQOEYMGL4qp6Y4lengHDB6i+v/+Zj9RlGDl6djFrwaUmRtlyYtL3/GgfO0Ft1KbfvUBW/QI7vg6Ls6LUPc7Laum4TA/e8s=,iv:WCwuhwLAV34qV1603h/YzaG1XzwfpvBXg6IR6BwkCh4=,tag:8hsyHsKpZxIETOEjbf8Jxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
