aws:
    name: ENC[AES256_GCM,data:PSF1cqbEJa8b2a3Kk6HCjKc=,iv:W05EDsiPprpcTQxBXyZ9qqe/alnAh0Nhzt0SZj8x+R4=,tag:K0jvt9RYGKiqO/LRfJBRzg==,type:str]
    region: ENC[AES256_GCM,data:TfkAbOiXLJnY,iv:ho04duz+EPdQ/qT4GYSPK3g6nsF6x0yz51wgdPH1s0k=,tag:P84gIo9MksJJkKjA8S1LHw==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:/t6rGi4kTNQoivS9cz39JhA=,iv:cjt8pLtKhRg0kbaZsnB4NSJ29pIgOEp1KA+ehkz2Usw=,tag:Z6eiBRgBLzltMGZRk9Sh+Q==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:qA3Oi/oZdpixivr/+frozec3h6gNkcCradZaPFU5,iv:7HOrqtZRjwOQmzfr0Ad+VEfL+17w1qNoY95yBuieQJE=,tag:ot0NGNfbWfW6RIyZ2tWTAA==,type:str]
                    - ENC[AES256_GCM,data:aR/rpyMtvbbqRu7rUNYu,iv:5rMdBJPGZYeQjIQ/PYEob912pM1KAb6qrB4gsYUP250=,tag:jj/Xk/8Cc1QB2XS1dXi13A==,type:str]
                    - ENC[AES256_GCM,data:sXsMewo5fAe5ZDGEcw==,iv:yCCtQNNWq9rSjVDpEcNWXf2xdtXayxyeWjI3c2mwBYo=,tag:eQYS+bDurhl+q8TozBw5VA==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:+OKLBaW1hM7W59SA/A==,iv:an8x+b+G5oU1F4InW76wnNkDtkyoEAzCQzGXpLQj3QU=,tag:1KRHp0SewYqjf4bUEX6VAA==,type:str]
                    - ENC[AES256_GCM,data:U/9kC5D+ZP6NUEL2GY0=,iv:GMk/venvVrIjB2USuZAG7FUFFyk+qFXza+80hG6LGLw=,tag:aFfAHM+/OdFQqlVSZM6bog==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:Orny2OY1rbKxqA5gg3Sl3/2dK1SIYUAF/yzlQE3ZXFIO8Q==,iv:S1ZPg++f4ijO316LrFzak0tg5kFi0zCTDqfdUDtAMqE=,tag:NedknxHQRuDyH3sUXQgCqw==,type:str]
                sso_role_name: ENC[AES256_GCM,data:qZkK/2CM/te9+MeJnxO5/xjeZGVYpA==,iv:XLFqevbgsNdVYfd43eG+jl7L3kFAdD82Zg3Ze8cREZc=,tag:Iv393+X8JYggCJIr3gH94w==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:kR+K+SaZPaXwScTJ,iv:uVbFuXd+waOEWTRvdZtqZiEgmiMBqRPzjRVOqvkhKpE=,tag:kCepC7yjtzZDUMcOd2oQXg==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:lK39Pu3SrQfgw2pdL7prwSmDRQ==,iv:qDw5kGp14xgnDeGIs2qMyPi0IFgAD6Mtk8I8/M8r6JE=,tag:AVHek52/a4rSuuwY/IvE3Q==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:msuTj5x2qC7BwuRtPsPa,iv:sPran/ElvXUJfM0SPH3/ZuIdMhjXgi9H7egMnfCBfS4=,tag:wWZ17H1gdLoRCwJA5fk/Lg==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:6SL5mBJe,iv:s6cEj1XlRlZvpy1ZA+FJgLixGO98VK4cMac50wutzHA=,tag:AB7b7DexgVtazxwIH2+BEw==,type:str]
                        last: ENC[AES256_GCM,data:So6+woaTNUU=,iv:0ut1EDTTvY65jniyzGIeODpE2zcSiFViIJ+cyZySBhI=,tag:Ogau9VoqAtZE8ErynIkRIg==,type:str]
                    email: ENC[AES256_GCM,data:M9xmxZcJ7uLF5vEzXT4dEwUv69akcT5o,iv:zIcgJDJ1NuKY+pZH9mDhRb1kZtEVyjaRpoaG3FDfXKI=,tag:OQAK6RnkS1uLDQI3g7G+5Q==,type:str]
                    cli-config: ENC[AES256_GCM,data:PF/xmsw=,iv:HBFuuKPyfbdzuIhHgkLxR4phl94rdoucd4hPhey8W9Q=,tag:4fXzNHMrxiwBNiffagCCgA==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:03k7wT+QwYM=,iv:NZCZAYGrPGLQOweJhRGSE9U2taGW9rYGktw05khaN4s=,tag:1RQK01tqcbBpwTej+OrvoA==,type:str]
                pezocoin:
                    name:
                        first: ENC[AES256_GCM,data:jW12Chi68VI=,iv:StzeDjTYfhq4iOHhX4XCUAu0OUfyc7iTTsr1GxxsYTo=,tag:LStFMuZgrSnP/qF46XES0g==,type:str]
                        last: ENC[AES256_GCM,data:FzCi+4zLxSk=,iv:xzwYB4Z+7NVCaVaCBqwf8u8A3LaUW7AfnYr7HtlUYqo=,tag:iTfSirdixKR9QEe3+hd0uA==,type:str]
                    email: ENC[AES256_GCM,data:N4hOSFSGeuPUP4eyvyVHTIvFyBgDv8U=,iv:NviXYAWS1MO5ORnfZIEJnkqrCLwqiq5rKHOBl2lUsSw=,tag:9FmU6LaQOsBmMbo1OeGW5w==,type:str]
                    cli-config: ENC[AES256_GCM,data:QQg4M7U=,iv:ipbcbapEtHV1IwuffHPlai712lKeba4Bzco2zG/vRWk=,tag:TD5cIPmrEo9l9js5ozmPWQ==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:fgnwwupKMvWMipb9,iv:R8AzHyobAehZEDfcMCDzXh4RDayaYb7onYy59xRSvH0=,tag:RBDlUSZL3CZ1JQ1c0qVChg==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:s1K0F1vvzauSWK4O,iv:AL7V2mLU4Nk4a9A2z47xFpWrioS3PgCzFqQ9QIbfcnk=,tag:TFiHs6w+PxlSVOUtIKqOTA==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:DB8Ih1Y6jYP7+zXwz5hwu1PUSrlHglk2VUsG+9rT44sYOJtrMjQKdyob6g==,iv:C3QkqyrflILwBl8UK4UlDXi4OX2M29WF6eSljtckuUE=,tag:k21Cyh/dz7OBujlK7fNt/A==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:3rUehqDfAg7JhSy806B5djs=,iv:WWkrao6tL/X2q1FeWVxHP97iAORbufOEev8j4gM8TUQ=,tag:3VbkItUrhiI030q0HQqfLQ==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:gXZJGFgcQKxd+7vx9Ur57AgDnWzEDCoAlVmUoaOQcUOez2+UAgPR5A==,iv:9tEjOB4v3tqQ/UPNP23QBow0CdrFRpHJxqE0zbP6py0=,tag:pxgoETN6r3ob/90g1y5ksA==,type:str]
                - ENC[AES256_GCM,data:L989tiRZGvYqu8932TCPniVX3q6lu4ExULrTvHy7S+dNx3l/iPGmFQ==,iv:DOe+weLw1YsS+IhjvNWt2U2TLVl04a/KU/Z0RLT+vFU=,tag:IndC8+WiH6STcLpA7ujTfA==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:LBPmuaAnOnMotO192RfpQngg,iv:FaXfdJcVsWsIx74d8rmZKACvL+Y/KdIMRYWIQv3oaXM=,tag:CVF5zgbCUGQfrdV2tyAs2A==,type:str]
                        - ENC[AES256_GCM,data:eL2wsOuw8rLsyLi1WsxYjGCZtg==,iv:rQb4gZxQU4UUCo5ZO966CnSJaHaT77QQakpjsYf/8xw=,tag:eXUZb3pXFisz6UuRvymgXw==,type:str]
                        - ENC[AES256_GCM,data:Q+OM9VkELVfhU4OE7dT1YeMU,iv:+xbBZi4OwiTqSLdrqBZXq2irvV9tSsr1N8uErlIKfJI=,tag:W9nugIVvnqzj9nlUBCdmzw==,type:str]
                        - ENC[AES256_GCM,data:XVI8orMwASraNpgnfIIJuFU60VGqtA==,iv:f31ycYomXz14q8lTHsb95H8xhKAcGkMBCTFZ0/u5708=,tag:wnaQxuxhK8p+8oBcagtW2A==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:jXPSkezr2npuU/SmGu+/WZzIItrl,iv:jixAfNr96cIXzJUyV5loKxcJCX3Mh3+8dgCZN/jMfZg=,tag:pNkFCezOVRfUB5jGOf+U8w==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:LWUwXLr2zxC1no4nU+YY8MPTvJRCrbEzEDWNjmnU,iv:V4O30So16hgkr1QjIgPYwzCzbeB/8g/oFeqGbm1tmg0=,tag:FQOLO8AbNRzn0bNtVBQUrw==,type:str]
                        - ENC[AES256_GCM,data:J/Dqv1YmHbyks3c4sSqX,iv:JQtlWw6wKb2VYGvirlCMeJgfcbxckElIMmhA9W5QVyg=,tag:C0pwXGjZSOnZs40e4Vnafg==,type:str]
                        - ENC[AES256_GCM,data:av9HMXE3GEfXasGXDA==,iv:3zYhdUIgGW60xzfZ3GVtGV3LeOpYfxDxwCTNBh6IrqQ=,tag:Nl8ZLFHdF0SIn/GVbO9Dyw==,type:str]
    buckets:
        - ENC[AES256_GCM,data:s7JVzF+4XzZratgvQoMIVqo=,iv:YZJjvhzRNvnfMHaTCXaRPYKGGVcV80X8/TFM031+T0Y=,tag:tsj1ag6bb7ECqMp5B/K4kw==,type:str]
        - ENC[AES256_GCM,data:GwDCmIqrKmZo1xt6XxcrkINvYC0=,iv:WkuqpfmYhbS97ekJ/GYphciRM9oNicN1n+EtpoImU8o=,tag:XPFYUQ7Q44ycYQxk3r9oJg==,type:str]
        - ENC[AES256_GCM,data:voeeiUU7GZSpWCPbcIBjIt+O,iv:My6fsJkOYG2OpZeQERV5hF4OZ9xqdx3GGFcV0OhkLjA=,tag:+y5c9ZvhiPAvFmtkjCTEMg==,type:str]
        - ENC[AES256_GCM,data:xjNwXJExusPr+/BI5sDgocY=,iv:bAsJ17hIQzrqk3Klmx1RAZ7IWafk+lcYa8LeJf2S9JE=,tag:K2brJUPwT6MiMPqaIvVddQ==,type:str]
        - ENC[AES256_GCM,data:8qYTk1+LFwaGtm6Ci3dzjLXN5hx4,iv:OdWqUmdyHZVVCMYz2EbvgpUAjvKRRFh5Rbe21y2wJCM=,tag:4hLyh4cQ5sTKvc9n2qKR6Q==,type:str]
        - ENC[AES256_GCM,data:1TebLt/QY6NXpROvI21tWyg2HOWC3PkGpA==,iv:Z5/enQSqL7KaVkqSiArhVUGfPG5XWXiQE2nw8P24DAs=,tag:3eJpKA0ElA/HzjiVb+8i+A==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:1FzAf0eBeP6GQuqdXw==,iv:Nd2cZ5tbYiQ2i2VONGcnGyMt96p8/G+Y4+pSVbGP4tE=,tag:7Nn9ARJ7Bvd4mXwUmR4ppA==,type:str]
          description: ENC[AES256_GCM,data:h+lqawqjrbRUCzsLeg==,iv:q0DEHOvofZqV6LnaVU6B/xjRrwqv8HrCaRDPFRMWdh0=,tag:hzBU3h4oGfxHTcrCPzpLGA==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:/5v1CzaxtzkjicIR+3xP,iv:wabbdLgiuOB9emc8/F2LpGDQywKaWtRn8Ru7OK/iarw=,tag:WmcTUY0QPAFpHfN+DWmzug==,type:str]
        - ENC[AES256_GCM,data:6hwI3393vzudzTkuz1fXm4XxEQ//DrdlpNjrr7c=,iv:wDYCaH9K5klnvU6vfHgxDgw7ZdwiC+VHj/p35jUiS74=,tag:1zVpd0eHN46WDzPqjrQLkQ==,type:comment]
        - name: ENC[AES256_GCM,data:O5T93lYCeCeUR8an,iv:/hNzwEhWN+thm7s1L3VOPjjhcQpAuMCQ1/Gor30FXfo=,tag:fk8uuSdDcH6sEvSIxz4kew==,type:str]
          description: ENC[AES256_GCM,data:Y2LCHZlnvlZ/qi4WmMpCVZMyJU4APc/S,iv:hgEZs+rpmQV52VhtByR1zpwpYmuii+xwWtaYImofQVQ=,tag:L+kofpKAdBvzUqop0ui40g==,type:str]
          deletion_window: ENC[AES256_GCM,data:aw==,iv:G17M8lU13P1UdFSYi5d5eK57g4RkZbl0TgyE5fdcvWA=,tag:t626eoPZaXFhnXDeKDIhlg==,type:int]
          key_usage: ENC[AES256_GCM,data:p7SfQmwuwUr8G4LHl2Al,iv:SHCkfmSDdQ56idhY1WPwAjlTHTitJYyyCZptgj9Y1DA=,tag:FRwzLo6XnBaTwdR/nBbItQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:cwv8aRoVLwjD98A=,iv:n0NRQWLYBuoLTDz4AVWNpIs2WYOY9dZA0rfIpSqFZKg=,tag:aOjtrEdbrrc5ioKF5YYOtQ==,type:str]
          limit: ENC[AES256_GCM,data:bJnLUX4Q8/M=,iv:+T+xtfpadO9nkLAxEL7uXmBxt3f7J/Gi8EeI1gnPjCg=,tag:+lssgHa6+RAnfsVZV9A9tQ==,type:str]
          notify: ENC[AES256_GCM,data:+hSuGgUEXPeDuLUahQ2qVCsC1a+CM8rU,iv:bZ3CdlpSRjyK3T8pPR3h3HASQGui4tYUl92sTn/G3JU=,tag:q3gyV+A+KK/NAFJ22A8wlg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-11-30T10:13:11Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgESC/XmfiJ2Fh6p9UFS+9GRAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFj1EIf+C/wOxD+3xAgEQgDu+8rOT//NqxR6Xl4XGPc22aP9pg1D6fHDCIplIyke0uYeiyiVjSLJXYfbo8f5t4R3DdFm/SnlqiemwgA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-30T10:13:11Z"
    mac: ENC[AES256_GCM,data:RboSZau7mNObkF4XwQJDZhjG2h7ZAULSJt8E2u4EzecwOKmOMO9hepb2FZ9RLln+eb0Xy3p2pbPBZJIxgxyYRlEzNOvFWXVPgfCtU7Oqqu8IorxRtLxKkUkS+aar64lr9Ff21nkLPD+aF9H/RWWxW5ebIGSqr4ba8p73M68VEbw=,iv:LYsDqrsa6MvbxXAxs6y4ewC9RIG29jykmaXLYq4PHgg=,tag:V+sCTNScXcmTmWemhwhmfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
