aws:
    name: ENC[AES256_GCM,data:aYTOcVizEZDIg5V8JX6Bkfg=,iv:fz451BKV5CmLEO7S9Q6RsoBY8t6c8R5JEpLCGiPgUbs=,tag:/CCZUW94looG+qY3YeWqeQ==,type:str]
    region: ENC[AES256_GCM,data:ESVwIx7uLkEi,iv:TIn/cSczutapKH6Jf03nt232x+eYJOoX1w6ME4pE8ic=,tag:AM7i0Q5oxe4H1k4l/aiuIw==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:9SDjX/16/7hnXs7BGcltMiZkRuYJEjrelcw68MDdk8uYEyLiSm8eF7weUQ==,iv:s1Nzj98U/mrCApV041Lj6texn6G4Nf1whN3M5tc7vLQ=,tag:4Qdlh97tIVNhjJknhfLXDg==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:Lqp9z3WbcPA70dKzguHuR5I=,iv:CIz2+m7QgEKBAbeOq40g+8qqJmaW9mbv4d2EcvdEVD4=,tag:dzvxH8YuMLxh1R1iTOV03Q==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:naVphlaL93VqCqscKdKHxon7SO/o/2SUk9KbsTW2oqw4A2pvQfyAYg==,iv:iOn7rpWJQEsT9i5P95N0CAWBaAkXz0sda6f6OP9gBUo=,tag:dh71R51UnMVc4UhIqYp3/g==,type:str]
            - ENC[AES256_GCM,data:+bbdDZqIqKGgLXYx+D6lEwILlV771j9xyyPJWS5A7YbkCW+jdoXBbg==,iv:CnzBAzb1Vkn2iJ3NpSXFDA2lqd09VBB9py50B9gqG2M=,tag:+jjEo/HlOU7pEpV+nd9Dgw==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:rVsGbAITu1Qt4Kru3HOpLw1AqA==,iv:He75gXdQE+BELCNUe508PRrc89NrTPrR4x0tW6Giocw=,tag:LWjmV55B/QiTBVdMbD4YMQ==,type:str]
                    - ENC[AES256_GCM,data:s5d2iFg6aBxfZWYnQgK9dpuZ,iv:i4xsHQCpLr1+M+7AcfUocsJrkPPLWT573JgHeMkVjuQ=,tag:I4PFordZ16X1ZCLWrx7mPw==,type:str]
                    - ENC[AES256_GCM,data:4NiZ2Nfla0sV4KG4UQ2Ocpg2zA==,iv:7rXMUCh33bfDS9reONO9HAz72noXFnYDb73GPxtTMsg=,tag:xssoEV8PlaeY77eB+uVzLw==,type:str]
                    - ENC[AES256_GCM,data:e9t+5f2+aTeyylbN31acfSxmd0o=,iv:pViV26oe1v64y1i0DC11/j5xhPAWfpZPSl5MuZudvZ8=,tag:yT2a6okW23HL47eURe4K0g==,type:str]
                    - ENC[AES256_GCM,data:2OFJ2BxfovXtsBeztQ==,iv:uCWjx64cTDgf6WqOcYAK+fB68VG5Pc1UU2CPdT02sXI=,tag:7arYXa7yIqkAEC5aHkVaFw==,type:str]
                    - ENC[AES256_GCM,data:Cc+t5PaydnWsZoiuUcnuD42YO7RMm75QX7a+2ioQvPC3U0LaDlFJQL4Ac/66,iv:y8vslZlmWIXc4r1A8tuWcsjV3vUVYes6XyUZPxXh4gA=,tag:ZLeuFWNFDsDUto8l0kbbRQ==,type:str]
                    - ENC[AES256_GCM,data:najc3Ib/lOwNaxC3PIolzijOJpo7VBIRYeb6Aqs=,iv:zB64+fgoBM5+8J9cCrN1T04fbSHu3xb6joVvF6VJNy0=,tag:Rb8m9cGZQ9HHQQSRjXMxnA==,type:str]
                    - ENC[AES256_GCM,data:/iCkwV1h1DMw2tE7ZmpE/OQwrN0=,iv:8QS7kQXazU/q/p9FCwuZEp8kbwDZjPagcMieaKAn728=,tag:tXwuz5HqfNuLocJjN7SI7Q==,type:str]
                    - ENC[AES256_GCM,data:XFmObEPx3HIHDXQtDdOLqjl1hPnm2kM=,iv:phGlPgpM7NpJ/33EDoMTyefG4HiUV4552NC5EjkWDVs=,tag:KyHeOeXb4GaQq3z3rKmcYA==,type:str]
                    - ENC[AES256_GCM,data:jskSnXoXLoV1IPDLeiMtLQ82V3fcSt7Ar29d0SSn+Q==,iv:4kM69Q+FEWn6PfUdx7bCXlDkGsWYbntqEP/Q3V1U78c=,tag:kavhv94xnefs2ATm7+vi1Q==,type:str]
                    - ENC[AES256_GCM,data:hTMPPu7cquvXoD9pXr+NH2JmtQ==,iv:rtsaNRzi0KZ0Zc5+JOAZ1VYQQs/vze0BZwv/ybalbsE=,tag:MTscstY7XJH4vn1KAdNAjg==,type:str]
                    - ENC[AES256_GCM,data:Wa68BWiN6HPnddTdXCSJULW6d3tkgZokgw/K,iv:wBeny4DjSMZ1SzUFdGnR/8jcMCLT8YY/UzNWA7WYMXE=,tag:8niOzQDeFHJqgvTYoZR4UQ==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:jDe+/tzIgI36LEzDq0CmCEVA4LQi,iv:zTpvqB7CAfmeWXFefxt9+9O6kua9DJ3dBNFLB9FVbts=,tag:VwhVvg0HYwlkXqfVVaGtsg==,type:str]
                    - ENC[AES256_GCM,data:Fx/R7/xBZgYYGmnQcT3iP/X/,iv:UBhUDph5Av+cIEUosnMLVYgFnr5jZ5OW93wc1GQcpSo=,tag:Dogi6t49Qc5xqnrc7uMiKA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:RC0XuVvDUICEvNsmA6e3Zh0=,iv:a5Uj2pkvD9m22gjNUOaofQtExuKVMix9S1J3KoGuozk=,tag:YBN5guSnvshEjHhJsXc+ag==,type:str]
        - ENC[AES256_GCM,data:0RDkCFxZgUe5MRl6ZRiynsfb5Ts=,iv:MxwQk4SFk0E0wt5KcCeMMp6g2TgknWPSiTa9pzqUFHY=,tag:+Ixs9/BDwXFbofe5st54bg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:YJM35Utcv7/YCWBzoQ==,iv:PMocRi0R8Y2MYfbT4bfMkYJKMbS1ttm8Lra5PgVA/AM=,tag:w5WysrlfCGRQSRvtzR6lxw==,type:str]
          description: ENC[AES256_GCM,data:khDAbVnZ4ILh9It+6A==,iv:G8CFJSfAud6J1NsrqmetPC0l/ePRcUbirIhqk54i1XI=,tag:31+ZL+aWaK0MT2YvT+Da/A==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:sHHE/6mDs5PnV5Eft53N,iv:/caHUifrpIH/he8bFgHk8qeUq7uYBDWLSZOxuHsduzA=,tag:v/jWbJWothyE5SKJ4TJoEQ==,type:str]
        - name: ENC[AES256_GCM,data:5SOsu8rYW8Vm4yjO,iv:PsRysl78yO9jYiHiJhFMCDAzS/MCvqG10wDcxOFP/Uw=,tag:MSi/5XJ4u541auToNW6y3g==,type:str]
          description: ENC[AES256_GCM,data:P8RC31dXVnpvt7pnrU8Zau1mDoLgwASd,iv:KfCaCHRB1QhpRfA44EBz3qzV0pDWdgGr42mH8VqKKqM=,tag:Iz1UDe0KrNO+bqmKc9S3HA==,type:str]
          deletion_window: ENC[AES256_GCM,data:og==,iv:X6sOiqtWunmDry+IRQ+AXma4ygiAgw58bIQtR7Yn8Bk=,tag:lTVObn13ovUyD7LxVinMjQ==,type:int]
          key_usage: ENC[AES256_GCM,data:gGQVNcccfrrL65RhnKyo,iv:4WqP6myyOeLP8JKIxM263fKWVno0iohAijPxLAU2VXs=,tag:g0EAX8FyyphCCixzMyJRcQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:qsV0gAio3ErijQM=,iv:3zD4UblMTW4Xz4e/+Hf95IqEAzilyWpyM9ewUFw+53I=,tag:lKZPGbjD8fs4Vxj+NYybyg==,type:str]
          limit: ENC[AES256_GCM,data:43UrMQypLF8=,iv:jvGXCekjJmDKiJz5gsR+lYjmFiufab+Bom3tgV3ZkoU=,tag:9XpP+UAlgfFXfieFJEuokA==,type:str]
          notify: ENC[AES256_GCM,data:pofPn+anayfGOpfe5WeLcY7wtMXGahJE,iv:EyQkEXiGQ6NHFaJUvKHKYsISILkY/hnWX3Iod81c4qA=,tag:IP++LPfpMliu1LQr6MKY1g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-13T19:31:06Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEZOdV4R21j+TLwyvlbn8amAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4JNNCEEARSNRzGFLAgEQgDsmeB5ku5BuW3anJdT4a7zi9VUi/IdBZqVUAOEuDPhznv5lhtj2URF2DrGdorLQYNR36YClVuCOLQCQ+Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-13T19:31:07Z"
    mac: ENC[AES256_GCM,data:wJCEusV6UrzsOauJQjz0fMODxNos/8A4oMEqG9ilm/R1Y+eKmrxrRenNjN0baaWE0IoUnNA3F7GIKmdylNvHstQSRZxPLtp9KIC6/6jubL+7Oset/tj4xksml8KbexxLPAkujtQFkeTats83/3uQKnFmteReyN1mtuphnG0qypg=,iv:hvfEK+yCP71Qt/Xr30BhThV8OjtSZ4bh+mf9Y6BoqqA=,tag:889NLuj2VRGZycmlRNB8oQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
