aws:
    name: ENC[AES256_GCM,data:8URhYbzqzKHeD8KpIzK5CWI=,iv:WR0YsV+I73sGKcin+fEmHcwwWncmwa8+6MPcasFaIGs=,tag:JRvSnk+4V6aZsoDieaGAyw==,type:str]
    region: ENC[AES256_GCM,data:Lgy5WKm+4PE1,iv:U3XG8ggNrR/I5OUVxUC5OL2mdaraaw8jfwd2shhZig0=,tag:h3WBjBdNDYXU709T4sWiaQ==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:YgmakqtldX6wRrklceJbORLTAkoqL/7Coo1Y1pldyg/L/XpOjx268HdfDA==,iv:mGlHgl3g70P6CBRvd4IvSMclPXMCuwep3UherJO0OJ0=,tag:2p3PR2tiQcPjbSIEc5g3aw==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:B8qnk5oi4YocLZJzgenekEQ=,iv:Hjz5zsWOKu3F5jin/c8tjj3TneIDuwp/dUM3WGpWydE=,tag:1vSIJ8TlOUE+PAoWfbozSQ==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:Vyey0+NjRM10VgrBrUXn9JXCpTxobl2DsAMwdaid0oOIcC6iX+Zx2g==,iv:4qKDNq0wZ+RB+vbtl4jDWiQe0NXdzwQCbybi+3Xw4n0=,tag:jQK28ibYt54mtr69h2CeaA==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:yrMyavJKSOWjQ9JEqcFFQQA+ZA==,iv:G+kLFD3t60bArrjjxBTdyAjPMNcRKBXdqB93sfNTosI=,tag:o2eE9j3qTu08P/BvVnyu/g==,type:str]
                    - ENC[AES256_GCM,data:YKOTCKoNmcny4ce8E/fc57yZ,iv:jRbJvs02eJTL7Ftw23EcVnOYDZtfs66QbN8xR0FV6ZE=,tag:KDf0QAFKyagtH9HRmxxBFw==,type:str]
                    - ENC[AES256_GCM,data:yLH20TfCjMgLH3zvQmJrBKZSsQ==,iv:GXjFJskg+0mirJfeWlgDuv/DkOvUXvDFstnMqA/9sdw=,tag:q+ixoJBKZhVWnB8Akh4s/w==,type:str]
                    - ENC[AES256_GCM,data:elnO2dbtPDzELQzZ1gtO4GaUo9M=,iv:Vqs4B2Yr6Py8LjgmWFuLVw65fL33Y3/ZCIsP64snTY4=,tag:cMDZYcNN94OY0kCqS7Al9w==,type:str]
                    - ENC[AES256_GCM,data:tzomZMFDg7/p4ftRzw==,iv:IesWcQ60d/hBEK4i+SzWhn9OdYxSZhO/fgjCH+vnIdE=,tag:KsDn+Olqfok5K5lIu66lsQ==,type:str]
                    - ENC[AES256_GCM,data:VYJvtGbKMazak8GqyWfmaWW/G5e7T7UaSRYlKlgGlCJS+Ol/uLgHcSXD/XY3,iv:QADbMH89eELMo0xR66l0gsbIdv9YL2JQ8NRJRbqxFtM=,tag:3pyCdm+MhVLMwZUvqHPfdw==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:iugzuGdL+Mi1uhk/a1UiGWRJVtpS,iv:hop8mWcT/FpvH+MhwjFpxepV4qcK3PyVDHFwD0wYzbg=,tag:vMbVAPnms492AplcokemPQ==,type:str]
                    - ENC[AES256_GCM,data:N/NnklKyBe7daso82cvLKy/f1r/F4+o=,iv:U5LowByrpc5gjC5kyLjMmEinwkREtYsy/Wz+xtky4DQ=,tag:hrtQ89Oih3RXToVxsmbOpA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:J+ispvzhP/hF8hV9cTW8Ltc=,iv:t4VUz+prVNyykn7NlQ7auXUpguL7SGPWvgLdOt4rp2c=,tag:GhI3E2jE27sgrjjfqXLckQ==,type:str]
        - ENC[AES256_GCM,data:EO9t+9F2sTSDX54CdpWVWsufHw==,iv:zoHP9OHowe98fEibRZSL/xx3VmEKBGFGStwpPINEReg=,tag:VjUKQgXa5uPy9CSJeX0ESw==,type:str]
        - ENC[AES256_GCM,data:keHG+fS8/7v/w0gLRep5J27och8=,iv:NkbIfV3S5WmeoJsugX0HkI83GdBfcvBcgpuCoqO8zpI=,tag:LDjRuf/5przr/kq/CYrChA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:Q0OZxvjMRxmmHwvj+Q==,iv:hCpajzhSAOagJKNoFA5Lg9oxheYqU9HlFoh8d1QcUKM=,tag:Z3CEqMXbNYE2NOOLF9vMrA==,type:str]
          description: ENC[AES256_GCM,data:l+X7GnWy2WT7th3mSQ==,iv:T5wBlE8LECJaYY0Dx1BK2PmHgcvhZqyvJDTKZ1T/EkU=,tag:p/Z4VGDHzVUGxRQ/NTJXuQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:Z6+DxY3TfCvAJNkm3Tb2,iv:Gt4XMnkaz+p+DS4tQ7zTcLOtWzeRJ587fqgZjTRFr2o=,tag:3EyaKXbRwyYHmkcLV7mEMg==,type:str]
        - name: ENC[AES256_GCM,data:MgWlBOdqjl+ALo3W,iv:HUtB60IjxplUJpe7fKc41JoZ0s3VRVzdNbhXfjOFwpw=,tag:FLbaugIGHtfAH0ZS3Mp1Fw==,type:str]
          description: ENC[AES256_GCM,data:JN4fjcdQ99fx58gfZ1w85+cKAgqx4F+G,iv:d+9uchgN2T1O0LnZmF9hyv0CW3u0KJ/ZzBXgHPLPjKg=,tag:H1BEfRBiXG3sm0x8GXhdfg==,type:str]
          deletion_window: ENC[AES256_GCM,data:2w==,iv:yAChmhkUgwutLLl2Zf5PKbB7m2V+o/OYkujMa/y3D9k=,tag:uiGNLGYO3mr5u6uH9Y0Psw==,type:int]
          key_usage: ENC[AES256_GCM,data:hbNX+cKkZBzvktsFrwKL,iv:TM/sVheMLaZkH/MFKQbyoj5eEMM/Y9Rn6g9D7udgOns=,tag:dLxlOLaDVOsfg4b0pLNYWQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:YAgScZfnkwJwxdw=,iv:zfOGm1lRA7w9Mb646aAMp2bJ/zd4PIVUeKkEh8nLuLg=,tag:UuboCDjzr9FWYy2GqF9ztQ==,type:str]
          limit: ENC[AES256_GCM,data:BZv50/oNoPU=,iv:anW/7XgjLjaOb6QioRFmXMom5pE9hCqQaVw9CWjIkC8=,tag:+w+18lVfc12bvqD4iSiAiw==,type:str]
          notify: ENC[AES256_GCM,data:49pTDCgvQjuV2R32aOZAudH/we7eFqx5,iv:7sUryo9OWV8KHgcWoRO/OztRSlv38R/0hRmz8+vxPTY=,tag:whdsYWWHuU1JMsGahmDoJg==,type:str]
    ses:
        - ENC[AES256_GCM,data:geoWhlCxD6J97GwrSI8qg6zQmc7L0ReiwM8pWfVvGQ==,iv:wFJ6nwTJkye+nZYYhHRJOTBh9zmuHLM1Sp8qZDvJb8M=,tag:pcFE9rJtAGXaVxMZI/GBFw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-06-04T13:06:34Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGARFTZNHQMZRY49jjb0j0MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIHc52IDKUkFXpnBLAgEQgDux4QH/MzI1pZAHEobfJaVgoIDjeWYtQB4h/3THFBUXKOYb9dvi/zgZenRSo9sd4d0WEeQj8BIF2JsNaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-04T13:06:34Z"
    mac: ENC[AES256_GCM,data:VSBdrBYFFYAkP9coBf3dcNQWkcBPFfgV7IjvApuIsDGMxvZBQMzjdQtCGb4mbAcGcbgwXzZN/VFCDIIaPSEkdYw4RsT+ihydesWmi0eeN2a7q0KE08X4IZJiMCxgmZ1E8DseAY/Dctec+3fk5ELQ/Dniya/Mj4iZu+0pxoSo7wU=,iv:GcJKLI/cMwQ9rPOWYrXnQo6HSRkC2ZEL15TTc/UtcQg=,tag:KFjpTKdtt/zOGXy8+1xnrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
