aws:
    name: ENC[AES256_GCM,data:myXKLL2+hv/usuPhm1ErXFI=,iv:cV9pKDDOtNPurhAzksLwPZRiStjmbcte4YGr1V4RaHU=,tag:GbMn7qCR+0p1+BrMgQcflQ==,type:str]
    region: ENC[AES256_GCM,data:DuPS2cs56snq,iv:aMOB95izSOmD8lARrDVB5qe14yMpvjtbOCclkG+OOHo=,tag:2BooDCxgSvLS9pqFuOSGlA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:QEzXkis5nHiIwtMQB1bhVa8=,iv:b6Vt8xyIdsU/I6BChiidjImCDNix2h5NU/71au0LF7E=,tag:IaH2qxiMa2+3Me7D/ic64Q==,type:str]
    sso:
        config:
            sso_start_url: ENC[AES256_GCM,data:q7gri1U48T+u3rWxg2dXtQqr93lZNi4Yz0XOR/HWWKUeaA==,iv:ipUsHFEvo07MGXu1JEMGxpMFu3hxEcafWXPxqGmTPXk=,tag:5naXgxJS44Wjg3aimwM4ng==,type:str]
            sso_role_name: ENC[AES256_GCM,data:fnP2FeF5QCj1FlgPRy+VdGApGPpZpw==,iv:9c8ZB7jhEdoCR+roTFX2ytOe1NJpCkL+K9AWCZNU95I=,tag:ABc3elLkJ4yxSMAacTKnAg==,type:str]
        alias_to_id_map:
            certificates: ENC[AES256_GCM,data:cOhXQl27LxQtkqYv,iv:rAzEIzApTaO0dlseX0s2pGMNFjk18Lsby+Exk6kh9yI=,tag:rbK5XL+eOXS3rthi5+37VA==,type:str]
        managed_policies_map:
            Administrator:
                - ENC[AES256_GCM,data:VBcCWRf1C7TUpkil4qIMwVDKaQ==,iv:eJ+GX4FkS9CuuOEm8dzFVaD++tPbLLu74bAO1a/8wOs=,tag:b/am3eZEHhrSVRQaJmZnsg==,type:str]
        users:
            gerard:
                name:
                    first: ENC[AES256_GCM,data:vj6xmnqV,iv:QXobPne58YsP5HRbLzkSGWr8+ZECfaBzZIWIGcycmyU=,tag:sdUriINdO2zGVklBWomOAQ==,type:str]
                    last: ENC[AES256_GCM,data:+qepJ0ZcMA0=,iv:Hv3l40uwKEMJhpyt100uZmZpzSi2IYg8KgwKu1gkWiw=,tag:o/1j3Q2tEUtVglW+lom6wA==,type:str]
                email: ENC[AES256_GCM,data:GoAxwNwH7FzmrdSDvCsVVLtpf6y3wVZC,iv:9GaXQJnJP3AP5tWDRlm5K69bEDF5eimnOZRGqcryp1g=,tag:8xnpTF5Q42Soja7/BS68SQ==,type:str]
                cli-config: ENC[AES256_GCM,data:slFaBV8=,iv:pi9+7ugq4p+BYv8YuEmnHvpGOKGQVWTNwf6qRawRkVo=,tag:lHJ80SLJgehqzfYcQFpzDg==,type:bool]
                groups:
                    - ENC[AES256_GCM,data:N2koYQ7xdeM=,iv:sroSA+Gm9O4knHTzAXlexq3ruXalDxWNUsbWDx/W6qk=,tag:y+W21jc9xOX0qj71pohssw==,type:str]
        groups:
            Founders:
                Administrator:
                    accounts:
                        - ENC[AES256_GCM,data:lQTQGfib9bTYICrE,iv:EnjnoRv6argMpkXTmYNhzlhoNmDfVnnmQkAk+Q/SIv0=,tag:OsjhXJ7inL4AkQUb9RHniA==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:ubfmse4kQqb8lw5WF7de9EirlaSUyLM5c2D0MZgtlanKNErmS+2X5NH3ig==,iv:LyxZGU/cskiYuNcSDHCVlNYkyPHSq/HElHPSKSau6cU=,tag:f2fAq0xj56NNqz+Pw9BehQ==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:N9qINUhgVjNus6OG3DqLV+k=,iv:37E84GUs+l/zTIjfNt3r2IB/n7/tyFwoziUCsZ1FBto=,tag:/EQ/XaBK2jqx2RLujZNdQg==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:UQ6oJ0/xUsN4kMSCpyqXFSYI5X4YXxsTy/AaR/gQ2xxLk0vHhKIMTA==,iv:jKHXrCdCfSFziRTs1j3CS7o8r7qsPc5u6X36Bdn37tM=,tag:rqSMlUyEdxihN3xt/6h+0w==,type:str]
            - ENC[AES256_GCM,data:AXOVXs5qPPhtQI+pCqWYjpVv22aDJ3jrWVNEEU0MNtHALQqqk9wXRQ==,iv:C/PRbQfogjqBVqm1KF/5P76CZKURhupa+tZ2UgyRsbI=,tag:ABVDNm+64B1pXKBDZHHhMQ==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:kQWkgGkIwe2WPLcgFZLVzX0IFevQ,iv:fMv7AHs/PqUncxbnG2wnH13l01NN/PO+qx653qCZ0gU=,tag:8uU1B9hyqvhVzl2b6K4THg==,type:str]
                    - ENC[AES256_GCM,data:19a86bVJ1PMX1aflaRoAG0Sz,iv:abGYOmcN24QkoIdzkhDwlYlD+FMhxnlJk1ZJ1EGnJwM=,tag:f+aYVbFuYQDa62VvoYPtig==,type:str]
                policies:
                    - ENC[AES256_GCM,data:Kb33sue0YMEonJWDvb0ecmEPLvXxigoyBeqQs2j+,iv:nHWRfSpAOjFG9+939eV9JWhgsPJJv4VnH8/NcfmhRSg=,tag:hxm6nEeIQdPdy8AVbQCtxQ==,type:str]
                    - ENC[AES256_GCM,data:HtWLd7JabcCh05jVf8rX,iv:Ev3B9fHYXueM+lSLCBM4BrkQC6qm2EVdpm8TDV26F4s=,tag:LdkZtXwUgw2k6eOIqJUL8Q==,type:str]
                    - ENC[AES256_GCM,data:rZcppuo1KzSh5bM7RQ==,iv:M2id4lIqfi76RNCV9bneUb4B6m/Kt/c0nZTqt5LYpt0=,tag:8mg7JnIeW78kbhLTKKsSDA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:DDcIcBPyEtmCJQc44YY5nKE=,iv:yIRwbUkf1Zu2GblqI3UHPJqwHE5JFF1AJFYYOhvfNJ4=,tag:cTmwrZxdIg1TzshhY5R3Qw==,type:str]
        - ENC[AES256_GCM,data:FCd3eeZ6weqUbXW/wfMsGMjAw+g=,iv:aZTvoe85g5uwWaujzpEz9Q/R+wm0PBB8fIomisK+eZ8=,tag:XQJwtxzIxd9TVZQ5iF8nVQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:uW35RUXrLs01StyqKQ==,iv:Iz31VC1e/XBp1Mv6VyMxPsFYgKQj8DtiDsOJleeGfM4=,tag:W+fX6mU7KRpIadpw3aPECA==,type:str]
          description: ENC[AES256_GCM,data:Ol90X/pDVO1yKMc1Cg==,iv:DFsFjP+VMmZnjR8+gbegfjNBOf47CSINRYOUOJY4qMU=,tag:F+sMPIGcykMr6vEQGsh9Sg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:mV6Swg5t4RHkPX3ObIVn,iv:K0A6tZjBTXk+8w+OL9bMzwkwSfkCqZiusd3vYEgQX3g=,tag:veF+OcnJS1MnRJCyCFqaHw==,type:str]
        - name: ENC[AES256_GCM,data:LPSIwxNwhmtMYXzC,iv:KWqB2jXOP3V+AnBZL2wB/zXkJ+TWUoUMMEyPZzkL1jc=,tag:atUHFVsqcoFS5GjihkDA3w==,type:str]
          description: ENC[AES256_GCM,data:wXPRqFt4qFIsA8lxFNJMya0ZNGl1NZjh,iv:1ZSRZL8IzdCaO//7ZF4IKHUpg4atgi5xbyJm9Ppqjng=,tag:gST/sy9U9Am5fPXav9BscA==,type:str]
          deletion_window: ENC[AES256_GCM,data:pw==,iv:GDzK7WOg5/mapn20oJ6qP3MfjcOaGpqjghmSuPFhw8Y=,tag:DrUx6SgTxDotg68kWgj1Ew==,type:int]
          key_usage: ENC[AES256_GCM,data:iPu/oYqxnPWNcilBXjrJ,iv:xBrBrcHBO3H01xQ+X16/j5JTGN8BEAT5AkQqBwSld00=,tag:TZL3FHGQv9fMzOqxTlOJ+A==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:Os+5+h07S1uPcwE=,iv:ikk+JQ+J8urbQkcjiHjBPA1ULIu3/UskQHVaoCjTw/I=,tag:YVkQ5QDbO9YEhfYaWdQhbg==,type:str]
          limit: ENC[AES256_GCM,data:vGXipdM4bPQ=,iv:U4z61WN2znTtQ4uqpIGadYjRSoePhwX/L5Gjtterf3Y=,tag:hQ9ZWnXMUVeNBGIJiVKV0w==,type:str]
          notify: ENC[AES256_GCM,data:0sLUhLvKGvTmQvJFr+GadGifNQOGBhSn,iv:qO81nXkZLgKvNNBlSYNhhMS/aP90RGdu8P0Y05iBJJs=,tag:dRklouRrF8reXGDkIAsAUQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-01-21T08:24:34Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEUmu5lsc1nC6VZor6nbBPkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfjoC/1Su5sPY+39bAgEQgDtcg3nPKIHw8l5SUghfutLqoKigd40k4CxEWSsGz0MV6yqTZ4kf98cbtS0C3O3RsaXi074k2VdRMEps1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T08:24:35Z"
    mac: ENC[AES256_GCM,data:H/bHpZtU4iRchVWKiI44lzqsxzaoHdEJ1JAJJllWMymdoeQ0w7gZmcdibPkKNP4xvKan4681dZhOJFgrmTlRprAVjGSK4kMf59RPVEQBx+gswpjoa4LzUpQPtCsqYZFk7wS0ORzQcgpWnP8sW4s7YCVoXdBtu8Kl8fT+c5FPGWc=,iv:VgaKHqKxt3vBIQ0ffg8t0N8Bg/E7ZxNlVblhxMfr7nY=,tag:icZkOx1jYrxlDA+GQAx9Vg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
