aws:
    name: centralized-infra
    region: eu-west-3
    oidc:
        url: https://token.actions.githubusercontent.com
        client_id_list:
            - sts.amazonaws.com
        thumbprint_list:
            - 6938fd4d98bab03faadb97b34396831e3780aea1
            - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
        roles:
            github_actions:
                policies:
                    - AmazonEC2FullAccess
                    - AmazonS3FullAccess
                    - AmazonSESFullAccess
                    - AWSLambda_FullAccess
                    - IAMFullAccess
                    - AWSBudgetsActionsWithAWSResourceControlAccess
                    - AmazonAPIGatewayAdministrator
                repositories:
                    - gerardVM/shared-infra
                    - gerardVM/ninja-vpn
    buckets:
        - ninja-vpn-tfstate
        - spot-monitor-tfstate
    kms-keys:
        - name: permanent-key
          description: Permanent key
          deletion_window: null
          key_usage: ENCRYPT_DECRYPT
        - name: spot-monitor
          description: KMS key for spot-monitor
          deletion_window: 7
          key_usage: ENCRYPT_DECRYPT
    budgets:
        - name: cheap-infra
          limit: 10.0 USD
          notify: valverdegerard@gmail.com
