aws:
    name: ENC[AES256_GCM,data:9Yhx23MThNlONWfmmeAPf+A=,iv:NzEk1KDPh27GF9706PdBaU+c61UdyVyHzi/AXvrYmac=,tag:H0CrggAnmG5S0FPfgK01zA==,type:str]
    region: ENC[AES256_GCM,data:veC6bOT6Xcoj,iv:i/CaLt5ZIt8I+rjM9Y7hUXo1Q4EP3SJb+p/Uv+/AxMs=,tag:h7LczlO24SH8UhBvyWanDA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:sWhvCcGA+PjeZ6Qn3WYbMGA=,iv:E3Tdz5ozBl7XjsEIK2PkxIonVnId/2JwRkrE2JxGRx4=,tag:ZfdT7KhqOVezsOscHneoeA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:tH35rHFC08pPNNSU8arGJnQ1ztaDD1XBQ6tzxEgU,iv:Y83e6I/j0d4OLWn2kq+xwJpLIKmRVeSqJB/3h6wLiOU=,tag:+M5YA/Z/PikjfkwvDsCcww==,type:str]
                    - ENC[AES256_GCM,data:arFUH5uDaAatc63gJL3P,iv:B1WfSKEtxSOrJEMXu/hJqjoAzvSfxK585mR7bHuOlKQ=,tag:thgfyEMCPG2dV0hGlvPQ+g==,type:str]
                    - ENC[AES256_GCM,data:d5yJxvvsaNg5WqpaAg==,iv:I1ycp2+9EPSGajrB71yEuzRreQbhDQ9CQzqWqZ62yg8=,tag:Z6GCzAaCi3VBh4Y8pymXrQ==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:+cbbZ10aTEf07i/PTg==,iv:xb08s3LFB0xEI76uozYyqyhmnqdwXgpE1H5zmU+utog=,tag:VCLbPpCuXecSRpzMVEeqRg==,type:str]
                    - ENC[AES256_GCM,data:mb2EAGFKMWvh73c0w4M=,iv:CZrHMXYKwnjK6M/sRY0FKZ2hMo+yIVtRQZJhSc7QlSs=,tag:3v+3xwnPUg+9GYDnvmJmeA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:hDNgV8Ic9R8xR9/a3OIDozKG2CnjdsragymFg1plI90dTA==,iv:CzQhSJH+5gMMnZPTSaGB+cADyuZhumC4vYlfQBwSzOk=,tag:ozSmiU8aIukwkIdiJPr6hg==,type:str]
                sso_role_name: ENC[AES256_GCM,data:isc2oo/ey9r68cQ68CxwsIQkQCvuww==,iv:x4/ThTJ2L81noLVfpjZdKIsdxHRs9n/aHTHDBMk13d0=,tag:7ULFk+g5SKBVmcr8zjJ1Cg==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:Qg7Bzk8Kz+AxpFMo,iv:jfYluESytFkW5swN7rwZyS6lUGGzbejntwqJEhx2O8s=,tag:EjF1LPVYis78S4TjQM04Jw==,type:str]
                simplifier: ENC[AES256_GCM,data:kEPEeYi4YxKFdQRh,iv:7iPHvj6fykQZWbZDCeEh/4AsgBkNU5ODstceG3mfrXo=,tag:+89SDmd+o+KM5QwGQenAFw==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:8Wc5SHr4jiLV4/l5QsP8Gs/ycg==,iv:hUGUhQNthELLcYFcNbHf4rGlHVt0r0Gkf9jmOjL2dwk=,tag:iEudT5aUUmvbfBMf8zr8rA==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:1zm/9BV613M4LNNCgC4o,iv:w45p3u8E/mZ6d1AmwlXYH9OdEzmwVHLH4tSvXLAfXHc=,tag:VzISoJ+U2YQjnsu5b3jxgg==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:JujiQDpO,iv:utaaTwCYcSRcEkGtT0W5BTqG52QlTBUi89SCA1IBem8=,tag:7LnQT/c47mbZXhYtmygdWg==,type:str]
                        last: ENC[AES256_GCM,data:4BE9tnSxqro=,iv:ml3qS5LUXqh+LBP+RS99ipcbuwkdx57hGM8NcaqKQPs=,tag:CRJyEJJ2bxXlY6MQMJO4VQ==,type:str]
                    email: ENC[AES256_GCM,data:v1kaHtRDshMajOLRZXgp2r36hKV0WK2R,iv:0/LU75Ne0BSbE2DwYev2ynj2UGf/UEX5o6WVPiSB62k=,tag:JWhZuxhLuWX1zqcf9SqLdg==,type:str]
                    cli-config: ENC[AES256_GCM,data:w3wljqk=,iv:EMKhstTNG6NQY7sLpeylhCMCh9cNGonGrZDRRlmXAqY=,tag:C40q0zbaiu77JVFI+q0L4Q==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:MZn9ShSOMuI=,iv:DLWW1oIexJGMmTDl4PXN29dafa7LCwYCI4PK7B5S0OI=,tag:F6T9KDSKX7aY68k3XHnxKQ==,type:str]
                pezocoin:
                    name:
                        first: ENC[AES256_GCM,data:RrPRRfDc0YQ=,iv:CqXiCfljEFuWCIzoH66yOd4d7ALwgME5G9HkBBuMkUE=,tag:DO+DtcVy69TGWx5WRAZI4Q==,type:str]
                        last: ENC[AES256_GCM,data:Xok29SBPvfY=,iv:7IaPuyVafR7vZO+yKBO/umApTHzGCap8GZ7Yvd92xbE=,tag:0+skKMy8IWcnNzrz+/UVgA==,type:str]
                    email: ENC[AES256_GCM,data:VQU7nKPaOxw+rJl1Go9UXrliYpTxY5E=,iv:9uClbVlrElTMAki/gZJ/PsZ0Cb/oGnNTHolj3YTJxEg=,tag:pXSLgnMx7/z3nLmM3Ry25g==,type:str]
                    cli-config: ENC[AES256_GCM,data:fI1UBGI=,iv:WrVFpTMvN82447IJp2t8XVKSQ5mjLIptj1fRdXIS69Y=,tag:kUG8wISIsHZtw6jcymEBzA==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:Z06HCfbc/LjM2P+G,iv:wl1Mi7SwsbedHtJgcnNCUngk2KagFG/w8RosJC8PbWw=,tag:JCSXsbx8sBoJoMRXecAe9g==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:A9XiouXxqr6ol+Sy,iv:xwQ08lQy4wS00dzxay0oLgibfqT6JoA4qKz+Ea4EVo8=,tag:/s1Id0LJ3aJo3+aGRr+nsQ==,type:str]
                            - ENC[AES256_GCM,data:rp5usJgCUy8RGA==,iv:ZyuUdt6uS4DaDXidkzecCPDEP35b9k0A/fPTIzTmHeU=,tag:7guoV2FJAY+Z6HfdlG8lMw==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:LeycxRtvTPVg10nozdhVAwN2lokrWzdzTPh5ieOVaRwK3gdRm0iV1ElxnA==,iv:G+bGACScFjz0LyXcREycZt5wbZgJBtz1f6DwU8Hp8k4=,tag:XqIQuQBQ9RIy2WZrVDb2/w==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:AEkvFL1YWwFllB2RVk8ZYJ8=,iv:RZlGVeG5RkH7bB82bcx2InaY8d8YdUOMFEIUUqVPRuU=,tag:tJnuCKv2Sp3D2otnA5iGbw==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:qCXP6H1vYGV251VqAOJ4V1ag5mgjHFUOCnsafuOG3tYYsiy1PYMWXw==,iv:YBfJeu1x0i9EEonHr36MaNWkVe7d3j+z7sx8RcsPAR0=,tag:3sQrne8pjyL8iVJPALCZYA==,type:str]
                - ENC[AES256_GCM,data:OZ7xWHZziqFdntrQ/UFq/xC5PJO+4j0pJyQGo8m51LML3C4cON1Hnw==,iv:jbqS7JBD1RCKtiGaUykKHh33v/wcdZfSX4ejpS4cjY4=,tag:UMrb9pzgQWP9ACG5zaMPHw==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:ViS0yLtPzd6LaQd3gqjIzjUs,iv:7Tl4u/yO6DE2Yy2m9B/YB1w0ziksAdObSNEC9KdHoN0=,tag:tpzmeVaI+sezJc/xLi6pjQ==,type:str]
                        - ENC[AES256_GCM,data:TlZwvSldDDhfzs5FMrhP0Q6svw==,iv:G0VSFTWUBm8q4kF91Se1pSMnkm5TWhYZm3WnffooLGM=,tag:fqA8BGlTTuBgkDlSE3VvnA==,type:str]
                        - ENC[AES256_GCM,data:e+l77qFXo0HCRTJpZwN0wmp3yJ4Dpg==,iv:l5EUNrCE+nFF6j7bqrnCiZWKeBZHQLKTFWoc+pSogbs=,tag:yOXFNCYf9YRHolHpi00dzg==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:KmZGB6kkm7KUxZsTQofz69nEbu9a,iv:LGeAyO0W6CYaseZDL1g6GlEJZLUj0ziyz8x4HbwTuHM=,tag:FpqqvwklUiQk/WPdZcr+6Q==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:wpeRHJXBvgz++RyvkUhn4NOA4w1F88qg5zfwuGG2,iv:l5Md+yKJDDbTsakqcBulYzJZuTETbmU45/x9w3+wYW8=,tag:DvuJv8CdDJI6PQMYl4tcCg==,type:str]
                        - ENC[AES256_GCM,data:UZvNAN6aw8FDXv6U6p17,iv:y77iadNj/rEOHM5Tg8thW8tPBmXWav6RDyR+ly/Hcu0=,tag:qiYEguJ0aBBv++YdQg8zZA==,type:str]
                        - ENC[AES256_GCM,data:E7FzE/9SoYSHuJGI/w==,iv:cD3mj/hNM9haK/TAVmvJ/Ei8z4aoixz38zncyDEvWdM=,tag:OCBOotOWrEj4QUcf1ylNlw==,type:str]
    buckets:
        - ENC[AES256_GCM,data:k3O7lqQ/3qXbw+sNUV227uU=,iv:+p0xx2+fklR8cNcsVUN2uZykoC9a4M5rHGuXrbpKN9M=,tag:Jj90P0fmguOzsLgq86QWzQ==,type:str]
        - ENC[AES256_GCM,data:vXwUIxi97r18PtbcHQJvaqlnX5Q=,iv:7Q2ha9yL32PsDUEPLXFazCwqSXdO3DnNnJbCq7rIkqA=,tag:/Tmi/n7tCxnnf2Xr6Ugfxw==,type:str]
        - ENC[AES256_GCM,data:EMDdsMgVkB6cOzc4c7J02/+x,iv:M+r/RiArtnZ7bbSPo/bZeKJm399wgEw6etDGPuPHePY=,tag:YR7WRYdBxVUBUzCBX1ttCw==,type:str]
        - ENC[AES256_GCM,data:N5gdGJ/jfsBnvlMRJ68hjtE=,iv:mc1+BhG+HvYqD8Gw+zrMczq033sIDANSmoZGDv37FMM=,tag:+Z0oQGzChOLQ5gY7sAizZQ==,type:str]
        - ENC[AES256_GCM,data:jh3VFfdE6V4iWgdd76oXMcVgHerX,iv:JC0sJNpRHfryFGjwfLE6FCuoOux8jcTaV+UCbfFiMfo=,tag:i3uWQTG5/4qLlRNTC8OEpQ==,type:str]
        - ENC[AES256_GCM,data:VXovSME3+UQ5lte7sFj793F/l9fgiLoH6A==,iv:dYb4Zeb2/wYTklvo85CvuCpcTiXsj1ywbUQbuF469RM=,tag:W3WPQOkuHV4WZDTeBsKccw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:x47iOPW9K2OwEwx+Bw==,iv:jCof7WZk6YxC39o5FhvJ0ZvBPCNIqu2e7+/10Fg5+W0=,tag:OH/pYKKqgPENcGRazZHRYQ==,type:str]
          description: ENC[AES256_GCM,data:RpGrTVF3LazifaoPag==,iv:1gUs3o8H4Tp2hZXHTxo5Ob+da13wkGe5Zm4h5l88WcQ=,tag:hszKVuOH2kMGFx9pzk9/kw==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:V8ByNbyxAaQM+cQtijOB,iv:BRHv6S8V/sWL0MXEhyt4iXVjkWabkl94dWT4vZzMgrI=,tag:E8MOW8bmkypVA+UFG2txfA==,type:str]
        - ENC[AES256_GCM,data:TMHkunA3lN75gIBOQltK/wePhaTpJmdojHukib8=,iv:8HU6s9xvaMAeu72o+hZvzYwggHyo5J3BekJAfBAQ8JE=,tag:TvtJBQgEpRM1S0CbqRLlag==,type:comment]
        - name: ENC[AES256_GCM,data:DOeybyoCqZisU256,iv:L1+dAqtnk0Vc6/DM6Hd7q+S3L+bT8BWVzTec1ehfjmw=,tag:FsxgAk6a+FclLB32751DSw==,type:str]
          description: ENC[AES256_GCM,data:nBCzNtifhGgT9LR1MkXRct3yrERsBoX6,iv:eQ/nnFJRIYuJ5M6IIx3nMAeiEnG6eY6Bla8jQtSu7Kc=,tag:RMkGWBsU7fxwXMt7V3fM2Q==,type:str]
          deletion_window: ENC[AES256_GCM,data:GQ==,iv:ZdPq9umD85e/2TPky37bFSZ6a2ew7Ij52yvu1QKez4Q=,tag:HkAsCOwmIvYpfuJ8H9rhWw==,type:int]
          key_usage: ENC[AES256_GCM,data:qswssiJ4TwsJ5Ikj3sr9,iv:oAv6S0ve+/la8D4HNn4qZrRYm1tNRwA7NFRHmRQZoYE=,tag:mbU2GbUAL6sxb2H3/j/sNg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:yIx+fHLxLaRyfSA=,iv:AbHYyr7MsbqxRR0mMIIySMQiVkjR0q4spIH9QAlZxho=,tag:4Sh5SbWogAPkTYfj1PTY2A==,type:str]
          limit: ENC[AES256_GCM,data:c1xrg+QXhv0=,iv:b6JRQ+1FE1mk2xI7sI2sh/L6gDPcyrHCKB+TUp5E58w=,tag:Xx1cbjVHc7pGeAhe7VptIg==,type:str]
          notify: ENC[AES256_GCM,data:ybQa3BIaF8hl+FHotJCYEa4q2+nNgSt9,iv:oKa2vgtVXNW24fYNq4scbzf6CxP9n6x88vWAojNl6QE=,tag:+Z3EzrKdNI8XscADz008KQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2025-01-12T12:48:51Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGi1mTdFmo2yEodeZEpcEi8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaipmmaVz6pgYsgLkAgEQgDsllkQ63OIcGgS2R5KMQQvKuNdIWtuxJ19XtXOPNcb6KG8QMST9Ei6GDqyxBXYfk9TvYGZ7APAMZTHVQw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-12T12:48:52Z"
    mac: ENC[AES256_GCM,data:YG21hY25eB42+IxQ+SKa96IPX+pZsAZApWZLvKQnmMSarN68yOeVNgM4IXjcw8l1fV18qvrdkreiReEKEZ7rRBj5IhNkMj1Td6RFoPAJd6+zlcs/aY0ERmKXO1zppURrWdNn/zmWX2XwAm2WjAB6WjlgW22h7e2hCfDstH4dM+s=,iv:HH9wzWpane8XrwVBAwi4DSUR38bLIYOkbF+G9l9JcoQ=,tag:IARGDJE+2k1t5nPSIkFk0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
