aws:
    name: ENC[AES256_GCM,data:O9GzGH8O5wKICx76rzWoaI0=,iv:d8B/Z5gY4s+XCxI3EyMUl+YtUpEX36KC9LaYNed/KoA=,tag:pBLvcwSgUhhupKkMnZRnsw==,type:str]
    region: ENC[AES256_GCM,data:s3CWK7I9CoWg,iv:Qt+J5DiKd7xJ+30jqVhKyJ/tEFudbDv+QsnCdOJAdz8=,tag:+rlTmDNEa+jDUzNiMGfYwA==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:uegUlmpO0rrKm48lTCz6mMkzM7XeqpF3P5Yw9Zmjiv+CBrIUlvLfMTBZuA==,iv:teNz3EbSouJCMzvBcAyy3614gnGwNrE0z7ilScm0aQU=,tag:Nzu/kzZ5UrTkZh/J0xgKgA==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:RbOXO+iz860q5gAGFr743rY=,iv:cVHbCi2CefVtJKe/Gx5Z/WwIMnFhoAoc2Rlq6fI4s5Q=,tag:MYDJOA01RkBoyZl2Zxh+Zw==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:AvqBvV7QSabMtlowE75NzdVyPENrb0I+GN3iBMp48T5QOLfrp1ZbjA==,iv:zoAwLO4QVj7tZft6jlmuY/UdO7fb/5DrWa1WKe8PHsY=,tag:qA/M8JbY2O+j2A+K2TUZCw==,type:str]
            - ENC[AES256_GCM,data:VgwgQQ95HR1Q25/HdjvlbYDRjgoenoMEyLgZLl8Oh00aQx8bQ5m/Uw==,iv:PhpZmFUDnaJDArmQTNCXEs7fDjwKlaX4egzpoNLbkRM=,tag:aY0TQmJQ86n+YgcU0ccnCw==,type:str]
        roles:
            github_actions:
                repositories:
                    - ENC[AES256_GCM,data:60tItYbL2EHrKP3PD3J9YZTJzMFb,iv:+FwcAOrlw8S3UVR81fQc1z6lUt6ZYDnit1rH9Z8DnWY=,tag:VM4VWMA1EAPMqFCkOaNM7w==,type:str]
                    - ENC[AES256_GCM,data:cNNLAIXMzJXfvQA/cDt8XkP0,iv:+9PWVJvDveWvlYL5RZSc1/cDQWIKjM+JAmS7t9fUjWw=,tag:74vuKgHNqP9eReVFwpRUPA==,type:str]
                policies:
                    - ENC[AES256_GCM,data:/xXPQSS+u5B5fFcqoUeV,iv:OxnloD/CHvoHsXmrLV0JJUN1Yvj2q6yWAKK7FsyuLGI=,tag:SEPJePOfgMEl32KMMGGbog==,type:str]
                    - ENC[AES256_GCM,data:lOXj4LuQSEdaJyFCLw==,iv:RH132wBKeSuY2+APDNNeMQ8m6I7oupp1NEcuapiEJdw=,tag:J0vwSPwDkErU1T2rXNrkRA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:49BVD4raTHj+7Iu141LKFnI=,iv:T3oSbnsiggUKB1/+5yBgHk/lDw0USTQ7kORSRGicVl0=,tag:N1OlGHQsz6LI1u5N+LxHCg==,type:str]
        - ENC[AES256_GCM,data:ub/tZhsNMvsF6Z19GxTjbCWqFAM=,iv:s8Y3wKHGkhSGFI6NyGQFsOJMjNsT7aNBzjhuNhBGR+I=,tag:5l3wpjERsuoutM8rABovCw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:hiZ7B7f/z9+E57s7Yg==,iv:P5hpQRwM4jrB7NQn1PUzyIq+/QZoGDotWvQk23BN2c4=,tag:/RJZx+Mwobw08VuMN1ugpQ==,type:str]
          description: ENC[AES256_GCM,data:juw8oFXCN0ixSUeUPg==,iv:5bccvxr95oMFCIGjc/sh+mhMdX2bQ1yj/MfVfsgpZMg=,tag:yBM0FetPj8J072+Le3eQ3g==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:QEwNltAIMegRD38Ya1nx,iv:A77UzpuotK2tLzOXGkCrvMFgGicLwHVQ6TTZve4GuSg=,tag:iv5xFTJhkvZyVFSbuwFOMQ==,type:str]
        - name: ENC[AES256_GCM,data:6Oa4MMrAwhe4rCP3,iv:wRA8dhS1kOgq3IFOqJCy2sr2LlH3wrCGFvZkIzmXSTY=,tag:MJGIQEwQNQImnMXlyCmT3Q==,type:str]
          description: ENC[AES256_GCM,data:ZSlV4BO5wrmt9YWRqI1OvA2aGE6BUgXX,iv:rNTycTHyJWhiE8N1+wuzc7wCe2v6n8mJwWmbKRt1whI=,tag:TZPHopnpvTWno7lFAeq1+w==,type:str]
          deletion_window: ENC[AES256_GCM,data:Xg==,iv:1CDzlZ5c2WH/JVUbjKbNXRZirgPXti94z2YP2ybZLeE=,tag:esRfhFIdDkmB5YXQ6nptBg==,type:int]
          key_usage: ENC[AES256_GCM,data:KWXWVwIY4oeV3pGYSexS,iv:o00U9SoSFYqnlu+H0wOSQvZou4294yXL14xLeIO5/Mg=,tag:RV7dmeolDdo38edFMGrlBw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:/tbzzCu7u+/feYM=,iv:h3OJoZjtyaGzx0ILou15WmaAAcHvipgSzPBqhv1BND0=,tag:e7rEPFt0INDUAXCyb+y45g==,type:str]
          limit: ENC[AES256_GCM,data:x2zvlaVeUCQ=,iv:UOHuWkhl0WwVP3HAI4gMKIMbfDPCpgSZ5VFe/Rpf0Vk=,tag:J56ZZjw+o5RDw9i+k3IraA==,type:str]
          notify: ENC[AES256_GCM,data:7ohpX+hrtpFuB//5WJacEuMN6CLHYLI6,iv:OgNn0iLjUIZkkc8ayZmHQr5obze2WeqozoQUz2OfR2Q=,tag:ynVPiJPsc6rCEMxbskZFyQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-13T20:05:16Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEx8v9e4oupf/kYTYnbrFUKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIMYtQgz4WBUPVaS1AgEQgDu/kCwIrI346LHsQ3+t3BtJcE2W+zzpnLHNMcRjwmBp450WOgQk2xuXDyHgyLHEyttDffS0PHFG4fZPuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-13T20:05:17Z"
    mac: ENC[AES256_GCM,data:y+iT1d1I/6sie5hHTLtgn9Rp/mTGLulR4Gdyr/KyVWrC2v5fgnO3D64ysotcUQEWRjQAPTvLdgTE00Sr6VVgKeU5B4S5hsKDts1bkbyacNG4g8pUlFFHaXAmHIzgSUIIamMFzEVpQbC1HLelFuNvz4hZ3MNlidVl+Fg2NVkV9mk=,iv:LXDLHTWIz5JnZ8udLu/CFbuAqvE3YxAKJLTbq6p++9U=,tag:apzpMkBDkf31UVlPcbxSog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
