aws:
    name: ENC[AES256_GCM,data:0tvNp9lPm55bnTsT0IGDbFM=,iv:CSNR8Kb462XJ8wE0LAE6lR4lPTEkiuZA9l3Y13R8ksk=,tag:yn8B/H/M2h9ubF6RbtjZHA==,type:str]
    region: ENC[AES256_GCM,data:1a3Mr/QCa81S,iv:wbyGhm8U9fqypxUH26B8wJUdrmJ46+E4DIrDzV2eg14=,tag:bDBzP77hL5XgWu2o3KHZEw==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:WQJOsUzI2zk6ZKs88ke8rY8=,iv:H8F0s7BwbE9XfdEm0HjJtTqj0A0tTvKQyjUkZkzu2yg=,tag:uv58qJIv8QvOZz+MS4kj3g==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:po08HckIuacTsFoqJgc5wEhI8EeiUDAFN5d3iWfd,iv:0GEa7jopqNG7AkzFK60UA3XOKDOdztfdpkP6DrG/sYk=,tag:QIjkD4FOVt64EOyfigd+4g==,type:str]
                    - ENC[AES256_GCM,data:4bYJtKs2n1OYbNUrVjiI,iv:MAo2zgzg2rjl7JvE/EATnLDbSp8dcixZEvNKdBtd+rA=,tag:Lir6aM45WT1T0Qq59KYDLg==,type:str]
                    - ENC[AES256_GCM,data:n9u7RZo0m11iojnYSg==,iv:PbZjItJQ5vtCu7QLZLQdS6N1W6BtDUuxd15cht6vfDw=,tag:7hqPrL9IETPBDm0/e3OFlQ==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:1I8MxNVtZyuwG7II1A==,iv:OwnMzluIySVxwSmT7GeqMBgfEdHOZvt+z2CHcdliYdo=,tag:rYttUPXfDVgMt1yLD30g6A==,type:str]
                    - ENC[AES256_GCM,data:6SO459Kdz/3N7z9HRRY=,iv:vDOnHLxYsyWdzGRSqhhLCFOvZN7ivWbQtG7+e8ogKeQ=,tag:lbIPH67PGOe8iX6bnjaScw==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:Z8sYQWiE5DK8JQYTuqBhH39F5L+qpSfVXLifzuX1rgjjrQ==,iv:JVOnek3fGuAVNb2k5aNj3v+KYLJ44vkCMSYfCeu0tQE=,tag:Ue0JIncXwLnQjWzdFMu0Hg==,type:str]
                sso_role_name: ENC[AES256_GCM,data:YpzE4eUcgv0JIFDRMp50e31Tvt/R2w==,iv:afFC2nMxqmwvZkX0oEq5KlZvpqJQF0KhVANXEVi7tek=,tag:iI7/cZABAE61HszW4QTOmw==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:YxIHVS8fwI1zeX//,iv:1tlo6pwm8yTffdwBoIls+MJ1iNVKquo2YfJFS5BEnLA=,tag:IE74fxqvKurQFVid/2k8GQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:m75cf9p788n9g3dn2qvXuFM1Yw==,iv:4rErJ6F72Kb4hVaxur85qVxrbuUdy+v2wncKP0d7hjU=,tag:9s2ehrAWVxQfY5Hg5Hyqrg==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:z8hu8Ed9,iv:hOgiZkl06cU8JJx3wx4SUVkpwqm2DUg4JjiFSYMj+uI=,tag:YG5pSr58VMnXNHR/1VeJdw==,type:str]
                        last: ENC[AES256_GCM,data:eZBC4S+gMJU=,iv:cLwtCsoh9PtJqt0eOwlzdR2Yl11MqWuoVn3b7jHLVgo=,tag:azW+niotyIs2028lQO3KkA==,type:str]
                    email: ENC[AES256_GCM,data:GTuM/jho0xY7G3Nva9r954QKkN4aT43P,iv:VNwreZqneodgSKnOZHs3bX0c7oMB1Ma+zJBOCuy0A7o=,tag:WB9SXpoYlMkoymRPHmH63w==,type:str]
                    cli-config: ENC[AES256_GCM,data:/Hp8t6A=,iv:yg9n+gB06iac4m1lxFrEcHIIONw0+tW2G0GJaXlAk/E=,tag:1X5qqRQ6247vQC8DcgSxpg==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:Vu5+GTwBvVU=,iv:V4qoZpxDcKcVRpUya9KSGAbgSWeQlhl5/o2w3Z1Gzuc=,tag:rn5TqywDOy/2iqR8GHfKDg==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:ERKd1KYgT6uZ3B/s,iv:Uwahar2GARoph1dat/WPuev36tu9PTYw6ZbnmoXLQsg=,tag:i7uOLyT6Hmt68RKDcF0TRw==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:oz3nB2Lnv02KshgZuY69EBqQLS8UWLW1Hg/st0pao/jH8cs8OVs+Jpc6pw==,iv:9kVAlHR41KfnkPMROz/BVuxbEO+GAJ7WeXVc5VH5RbU=,tag:Qj18pKtQ4PeX5apn876Gbw==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:NsjnVHsKaxFbtnDAWyHg/Yc=,iv:be9eT4FxOeM+OSU4mH11t8QL+X8HcvCBzwAdv0K3kAg=,tag:QPw91BOEGFojwhasfCkd3A==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:JMvQNg9kp3wcpW+tspvvaOYIc0E/JlLSDsUs02LbL9g2sdyZeLfEPA==,iv:VJ5SaqZVNMC7+pQ7g2VAkHQJ0R9lcEvftYf0Lue7Jz0=,tag:+TVJwxuQsMgvlGQ1ebWw7A==,type:str]
                - ENC[AES256_GCM,data:zeALEoOUnjd0kUR7UeKi82mI3hXYabTCQUgYf6XaKJeNYzRMwRxyqw==,iv:ykQJDqVBmxM6j5lbnlY/IHwj2oNjUtAqw3ZEjShUDB8=,tag:eAev7y3XGGMg7hHuujdRiQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:IM34jnOatIHWVybj7HYTl6W2,iv:MZuSH9UJPTjVi7X/mYIS397QAyYjtOt1mne/1nM5XvQ=,tag:i9O99NYc5ilQXLzEpNj2Ww==,type:str]
                        - ENC[AES256_GCM,data:yRRmCP5B3zZLK07YZNgqrbtSYw==,iv:j5kl/liYVwEu7aS4OHinKGRTcNIOLN6O7tVAG0ahfOY=,tag:CAN01l28ComTlKh8ht11tQ==,type:str]
                        - ENC[AES256_GCM,data:RRK5Y9a02B1S5qwC/DHo6txo,iv:ncr2ehOa+ptIjksEtWmoXC53+oIsgQO92sepkIowi/I=,tag:OZTs1G1kRri+ll989YLGSg==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:eKoY3I9oLi94Cpm1Pu7Esi+Y4s1i,iv:B75v3CE/s5AnywCufwWZAW2+dEmZ0TE45K+G3asgteo=,tag:7J7je9EhwDe9tSMcEnpDnQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:H53u7+k5sxIlidHhdgclWGY4mcn1Aexh/4oKDEjt,iv:vnpoCCQMgIJQzc+z6kzohWjcqr0j9ytk7xKycs1fzzo=,tag:895AJ7GwOYoZcj+JR1Lmxg==,type:str]
                        - ENC[AES256_GCM,data:HyZ8K27/Ny5rRh6OwoEt,iv:i2B7v9POd2XDAObmdTUd9wv5B526WCLyOwd3Zj+xahA=,tag:k+N6EfzgblnaMrhIIYzC7w==,type:str]
                        - ENC[AES256_GCM,data:+pn5Fp7tVAJrdJ+sCg==,iv:YN7JmyfcXxgITKvvGg0Yrxst2t+rRvHpy4dDlmzTauo=,tag:eDelo8Jnm61mClYrHZ0bSQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:8cC0a49bSuVBXN6EKT4i2sM=,iv:wsvPcjp0fswu2rBF2t9q69zvu1StDwy0CucAwGSGMXo=,tag:8mxgANxrhuu4jFp8jp+/8A==,type:str]
        - ENC[AES256_GCM,data:aOk4doWa3wyb5cwMdToZF4LmcX4=,iv:GMN3WSdAKH0B6DnwpE1Q58bs+Hme7pmq7ly4ALRM+Bw=,tag:OlQIW4M80410nzIv5AATDA==,type:str]
        - ENC[AES256_GCM,data:KY9amA+1PPIKj526TTGZE9dG,iv:YoA0rBBFdB4kfKbQlkO07RPqv8M5QwSHQ2IdqYoeZ4w=,tag:Az8rke4dXOllDja6ULZGFQ==,type:str]
        - ENC[AES256_GCM,data:MOQ2iP2pQhfpchl6skuPikQ=,iv:ZkZ5ywWFeYMko4I5HCSHqAINxWIjDw8IfhHAZFtQENA=,tag:WqtcRGX9HdMjtp4lD207FQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:onxXDPEiBuV6nKFXKA==,iv:qQtqm6Kt/uU+P3qUdiwJU56CeigsuSF/OA78qi35IAo=,tag:SGo4pmQkdrP83fF6nGVbog==,type:str]
          description: ENC[AES256_GCM,data:Bp4PJg08q9IqMkrX0A==,iv:wXTTYVQHEi93W4GYYRODuttKoBBCM5LvuGDLvl/g/7M=,tag:oF8dTYcIKxXSkes2WKOUog==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:ulepnvsvakT3qAzb/ewL,iv:ho+jXFz+/Jui1eZK5iFZBrCLj0sW7U2bj1r2rzn/b5o=,tag:LM/YeZ6O2vzM+GQw/6nO2A==,type:str]
        - ENC[AES256_GCM,data:9/bQQiePfss/qgZ9qaPmxFRUrGGKRIlYROXRGas=,iv:bul9z3aeXxxxrQoF4MxasSaKHXNSPzHkIbCGzgLYdzc=,tag:uCejQAyS+bJR5tVelylodw==,type:comment]
        - name: ENC[AES256_GCM,data:GPbCAcx8RogMm9/9,iv:/UXL9rW7v7PvXcd539xrp1zQ4TqIzTJwn1p1ev/LtJQ=,tag:2IpmQzehHuh+2UuWo6TfmQ==,type:str]
          description: ENC[AES256_GCM,data:j6WZc4foY4aZJPZFIKwUzdH9InOtEU3O,iv:hhkoKmy0BlJ4yKy2jKys9aBY8giiZtD6B+xVzZT5QFs=,tag:oY13MKee0yHxvvBsqWTpjA==,type:str]
          deletion_window: ENC[AES256_GCM,data:Yw==,iv:/JpOUUhNfBnptOKQz/x3MNX0yWGAlyaMXHf6gnDIwH0=,tag:eQprl/S7TvbsWAaGBw6cAQ==,type:int]
          key_usage: ENC[AES256_GCM,data:hPb5JJThLIahHPKpO5b1,iv:qt7KJjUPiCZ/KVGOCvxDuUcJ3zDUqRh6umXUzcF5FIY=,tag:dhZ6/wIwNPG6zUH7cFC8ZQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:g6y1KhBUnGiulVs=,iv:oSo8Cu0YwuFYo+j8HaJed2BfCsMdP39u+zyh8pnR5XU=,tag:Rv9kJdAzgwAkStSv61p9Kg==,type:str]
          limit: ENC[AES256_GCM,data:W/3qhNFcO3k=,iv:EChwN3+wJSqUg083UU5ZX7djBlw89WzD1ZeFWRYsws8=,tag:hGHjVVyzEjhwCKHis9eIRg==,type:str]
          notify: ENC[AES256_GCM,data:qiValmfgHzMlMFNf+pOxdv8yEHgHY8Zd,iv:MLcxBM3THqzQtftzqmyG/eDKprrz2dFJH4AdSg7PDKU=,tag:MiWBbULo4zpoKyOnEvHZXw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-03-17T15:22:19Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFPK11EVUwA/LvYrmPmgg6MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMn32IVEZEhD4J7Al6AgEQgDsDvDdspINSUaOTbzniH/2nFG/z1ucKqG1rSusGijnTCZo8Vz7BS71sBEP1YMdSq9fpmveQVQ1Pd2GEWQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-17T15:22:53Z"
    mac: ENC[AES256_GCM,data:OORz5+0yXdJ1goqTge2qP8EwM5KCJ57a18fjLB6o1n5O5Omca+81Tsrq/vNMRvTpDC5FiwAMJOq0kBma68T7hNNaKu00TE18IBOMiRlRI+dKZ2OmIRAx1q35PmvT6keEwwClOtdjC+OscklhKsSf2xJnGl2BRjk5zWtfs2IUdjs=,iv:Jvwzei5v7+D3lb8TEQO7BT8HW5FpzSVN9Iav0+dYR6w=,tag:YF8/DS4yRXwU5d/kw436DA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
