aws:
    name: ENC[AES256_GCM,data:MKBBFztICYMfJ3RFrViF1JY=,iv:NJxqIWZ6gNgxEZ2k0SN/x3kWw9PzDk8XT3qY54W6EDc=,tag:dR/1N5t+VUmMmCrrCTNR8g==,type:str]
    region: ENC[AES256_GCM,data:oHh49wyzlQT7,iv:+gXjNzKfwBi5tLnxhtiE+vkNNEarSqHiC92RiQFcmmA=,tag:cbaQ8rtjRuGQ5aJfsOS/zA==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:2X9cpCmHwlt6eDm+8ObPueogUXXL7C7xM3m5aEM5qR+aNWNAfMdx83oEcw==,iv:04sWNgb2cNffXonrGHegZwUm4RrmcFW+etW8HlC3Vo0=,tag:DfTumgvSq7gTmjwEuOwS0A==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:0MquNbz/ZflZMZ8XmSNrvmI=,iv:TLFVPZ2R3F8TKcMwBIF+1uf4+JyfsHNx1APimBQCclk=,tag:eNOCcVLsghVwrR/5HF276Q==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:xEV7TjcZ97G2KVmgZpjFaKaczstgf7KDWnhmO9pbzkeSlL7dHB6cLQ==,iv:EOxHCRAegWk8eHlO7fBJCQ6tcU1mYYGEhZCzrg5hJok=,tag:Li/bTP6ec95KVDfXtF+1mg==,type:str]
            - ENC[AES256_GCM,data:Wxi3gGBMr3IX+9XMkDHu/LbpNFjDND6phpNt3A4OdTbsp6IWdlkP6w==,iv:2a1gjsdUvTxzOFIOuIXW5F4tkKd4yjycRq672NGhig8=,tag:OTbnIoeI2gd8U7nOR9cqpg==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:qkzyEywlj+BNP/y6Q4la2cY32A==,iv:DSM0sxy0rL1MXAYqWXrw+0mKZdI82xErcuR8m9xnNvY=,tag:8pxwLVCMeNCiMDXf8WXWcg==,type:str]
                    - ENC[AES256_GCM,data:0g6/ep05YDExRuJldVtg3pR0,iv:iXtj3jc4ypnvW8BzML70x/OPtYGjFbsN3JDYykJrd1w=,tag:AIopEXoKCaGL9Gjvyt9S5g==,type:str]
                    - ENC[AES256_GCM,data:/jLy4B6p2vFsiKsgVZlyp13Eeg==,iv:dVsCr2QGXbeDJf9PK+kYuc6Z3BL1d3Zhe7GTxzPeZG4=,tag:H7ESbcDvR3rmtPyi1FQ2bw==,type:str]
                    - ENC[AES256_GCM,data:FFTUyg9dQHkD7VI3pNb3r14wEqk=,iv:KOzrQk17GO2oh2MVwmuIDI1K3YDucInvWA0Qm51l0Bs=,tag:H/M6p7WAwPgj6h8tkxn8rw==,type:str]
                    - ENC[AES256_GCM,data:pqbeEI9A9QSqZst71g==,iv:kqKu/AhZ2X6zxL5T6hFIxlgTPwPu6UlLk2xgKWXUi4w=,tag:HtSyVP5J51cr0pye2e1eVg==,type:str]
                    - ENC[AES256_GCM,data:2wpFz4Nsyj7IO2O5HhEUh/2pKWnPBWJo+72aUitcpARTbyovxt2tEAjh8QpW,iv:b9+35WabOUWRTrNOT8//7v8DCzAizh5rYp4rjy4VeTg=,tag:oC8Ui1dWYWZ1clCloilBiA==,type:str]
                    - ENC[AES256_GCM,data:WbrndRYU+fEKKcgE622DZ4HtSqN4OrIVE9t1vdc=,iv:sQt8AJgkRL6jcCJVoj8r9pRDsXE37swROuQeHzatvnY=,tag:c/a4Rb4F2+8WTQ7I9EAVYA==,type:str]
                    - ENC[AES256_GCM,data:7sGmb2dQASvSJuV/R2WMJgABnoc=,iv:iYyUmMfmnz9W3bscOWlUnA0D4COjFBGJbCEIPQXkwNo=,tag:3vBfC9XfNoOwi29jAe8sbA==,type:str]
                    - ENC[AES256_GCM,data:DRO2XEcA7Ytb4ihfSdK6DoUcWMbWMGw=,iv:bJj6k9e1ob2ccLkzJTegDEdWYnd3/iWvtjU7O2BvoXo=,tag:JjoIt4JYAKrQheBC8JX8XQ==,type:str]
                    - ENC[AES256_GCM,data:zvj1eKhzcPTXTi/f7KCso9j2P9FEibhavSMSjvAQpQ==,iv:W2Ylwegy4soxMFnSFj/zhM4JkxQmaBpME2gLqyw6utk=,tag:GRIa+jsxdag1g7iAS/xkTQ==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:ooiImX8Pp+W5D1nbB6mdy6Ndvre+,iv:fT2ozAhMDtZIOYD2LmtBw9oyfKZNdSLMRmrZuU0NWT4=,tag:EygR7oRe3g8rT4oy1JHxWA==,type:str]
                    - ENC[AES256_GCM,data:pmnAIZ0aJK9vfUseoV/LVznG,iv:S6wdUhddRMY0/RIcANAuDsYtZNaSrMiMWvy3k5Ka9KE=,tag:/MwFvekMScYQvHaUXYNByA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:KFi9CInF4hEQ9t98BR/9NPc=,iv:SnM5zAPtwrNY8ogfWQ2qx8QZpBykTsMJwlhfBSSuDOQ=,tag:46Ft+kGlG+E94Crh98tohg==,type:str]
        - ENC[AES256_GCM,data:tLcvDTkD6YZSrdm0CV1gmjHcpZk=,iv:5Mk7XNrtd/pkJXuA6v+r9wqjXz8/KQL4i1iofv2uXtg=,tag:JXzr2guE9DQUE9xfUF57fg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:zO7PyAoCesgKUqXCBw==,iv:tO+p64gK4v3T81BPChTc9vfiD0ZDDGCZI5ExYskN4Mk=,tag:mvAAwb8HpiaWomnh9EPmig==,type:str]
          description: ENC[AES256_GCM,data:3cOUEPv0ziG6+ncTiA==,iv:yMgm1zy5omGkCfgIoMiSQ7wsG9hM2Cc93IOpH4YaWSE=,tag:A6U4UWsbenwkAMlhysPJ6g==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:sbQ9paOzQf66Zw/dAwjX,iv:iWgu9CZtzLRdar1RHHJeKHGGT98HkSEubQs4vhwO1pg=,tag:F2t7DShtYhAxd2mZAILtsg==,type:str]
        - name: ENC[AES256_GCM,data:CMwxIe/SNWwXBfnH,iv:l06RnYYLT+K9ted2L+P2++jD1dRsNuj9TUrnQxq54jQ=,tag:nP9RgRGgFr0pHxYEc2qlqw==,type:str]
          description: ENC[AES256_GCM,data:Bdp7Jyen8uBKbhJxqbwiYEEiNKIwc3h0,iv:POXDyubBjMUnenVAudc9wOGLuMu7VFNf6nxg1YOwYwE=,tag:LD4w40kxdUlophdG4iV0Ug==,type:str]
          deletion_window: ENC[AES256_GCM,data:tA==,iv:owHC9cOVPlQIUQwuR9epmJIrv5Gt4jueqRAlZKRImXA=,tag:dmpEvGMw76j77gUPsAYocQ==,type:int]
          key_usage: ENC[AES256_GCM,data:U/UW5bDYMpUKSRYJDRB1,iv:OQGyX3mdZd04ulPNpyDci4n42/cHwkNyHs7TBqHxc+8=,tag:ujP+jfdsnY3GifyusWD6Ow==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:mqITQkPq9ws1W9Y=,iv:sYMXOX7zSrcffxIYhrUGrFHxniohp8LutnoD224JsRI=,tag:dIw/wlsQBxx9R3yPYPDAtA==,type:str]
          limit: ENC[AES256_GCM,data:QuXNT7SUXKU=,iv:cczPtMkJ8kHmT5rMujXdFWGW9cWRUJqBOOaCzFP0POQ=,tag:oqGnft9OdjbBLSiGBPzq6Q==,type:str]
          notify: ENC[AES256_GCM,data:JjKvOozQTCb5UJXZAb0q13940oLUMUsQ,iv:Y2/HSsAst4ryXQm6vW7FykpjHrlfEM69XsKjMZPoVxU=,tag:qzXjZFXuvLlETDv0kDv4rg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-06T05:40:49Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFSWxBYfKfz2Rxj71J2Tse6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrGNDsJAbCfIK58+nAgEQgDvplzbKRrz8nJlNBTnDH/OqHw8LBgGmwMdJN2IKxhFjjS0FBPlN0jtkPsQMw9Gch5TB+HRV+2/EBZm55Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-06T05:40:49Z"
    mac: ENC[AES256_GCM,data:tDK3VhwGm+Pw3K3Q3RbmmnpPZAN0LvULMrR1JybHh6VDPSAnL3iYEc6Qm1DMHtT+V3aVU8nwIzDFaAGiZLr1dQiqzwvAgS9DMESBxWfoFMEcOmIHyUd+BfY4/4lFsdOdvBikY6V37Db46vMsUUQIJf9jdDG/bHkfxlIPBJcUlN8=,iv:MFLkNHAdE8Ob6Ao2l7o+mjRxBMI2E1heOYlR0/SJwaQ=,tag:dKQpqJ6vwti7b45vANadfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
