aws:
    name: ENC[AES256_GCM,data:rnGl7X/Jmn0undO5NmpW+UA=,iv:wcDyR6EUBbMh77tLtfh/hNihiv30Hi+qehBiVr25C7s=,tag:/JpKyLpS+h7/pGwaQYIJug==,type:str]
    region: ENC[AES256_GCM,data:mQNYR2l+gbB1,iv:B2fFdhS1AOfHZ9dWMef9BODBJdDFHyRL0DilbcuFfSE=,tag:U56kHINNPx/0TO6KTOL3yg==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:77D67NAXB6GyutV52N8axqB7CJI/TFuFNQrK7mvYQh76C/O3gfyW4/I1Tw==,iv:KUC6bUPcKnaOpNkAQLIM1Ewmsnijlzsj4vW+Y+tpSYc=,tag:ajslsJAU4bhtIaK+YrZk8w==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:xu5nq0g0uprPGKzZUB/RmBc=,iv:PS3idOdqJs/mi0nuWPUJB5Wwq2Aa5uZZeATMhrWgAio=,tag:D8+VxwNE0SGAEpYGc9TWEA==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:tiP6NgqAZ6cgA9zuqiShbLtLLSe2VgLMRvWqZEAt3rUf3w6/iJd1nQ==,iv:zJqk6fuISexWVg684IbnAJ2+48sT+vbi69tG0HsUKg4=,tag:k7vTMcayEVKXQlMdfUqgmA==,type:str]
            - ENC[AES256_GCM,data:kUxBXbkH2jnQgIIH3zcLUilTNiXJBiEcydizjaBOy1Mq3Lh9AFNHmg==,iv:3TDHnGILYE8eLiQSPeXM/lvm6i6TGtFjxq1xSKSmpD4=,tag:MVDKclxq1dTEGYjXeSuzhA==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:YQXA/4yOuxSkVLuZyo7N8DrZ/Q==,iv:AGaiRlHncvSSzEaW2I3OH6XiSuFZazHtfEJhZswZLt4=,tag:loCy7AEQDF1tochI1O7RfQ==,type:str]
                    - ENC[AES256_GCM,data:YjfVmmyvRya4wvuLWm6yOy0C,iv:rCzBCY9/bx8OBmoVHlwPGehoAeJ5l3t3vPS1rwpgHiM=,tag:c3epEgY3Cmt+KDmKILgEHg==,type:str]
                    - ENC[AES256_GCM,data:xGrxt0OwVJseGYJnx09wQFmoBA==,iv:CZmV5DovwhOvZFvydFefo04VYZq1kVSkbjub54ifHQ4=,tag:AjytTT6oOenSNnUi22DpEw==,type:str]
                    - ENC[AES256_GCM,data:nErTH7quXflWMcVZ+PCmelWcK9I=,iv:lr/hdlcRJ6NF+LBwbpptOqeXX2d+SaU4Tm4TWrBvFR4=,tag:dXachEXHbMvrb8PtwY4GFw==,type:str]
                    - ENC[AES256_GCM,data:X/CTHmkLuutj+UR2eg==,iv:v+PjJJr4fGFW5h7ska6eCVxGYTqLfOwMX3vlFaxlyvY=,tag:rMbtWebaCNCP2z9vVZAZrQ==,type:str]
                    - ENC[AES256_GCM,data:MSs+f7/UGjd5cwg6JI5rBdm4deuMWBCjF9cCGmtIrvl2+4dtHKT2xVZpVDWC,iv:xYBxuTth6yAKlgeIkROK+kBwBKlX92HYZo1KmX+17h0=,tag:LGU95dP01lkswWnO/y3rzQ==,type:str]
                    - ENC[AES256_GCM,data:yTZvlpgbXFU9fyriWShVFUJR1Qp5bQnVOOQMZkM=,iv:CaJWCYAhJgBjdFOdF58zrCrneRnQBrMAzeZsFTbjYgQ=,tag:Zb87aGEYohhItq2ET0Wg3g==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:Tii4FSMJjrvEOV7eFYVJh7opCdbB,iv:CnaEFPb+BblpjT3Jnou0hpYHw7mMpiLLEPzPOICm52U=,tag:69cUfyUvLyAi/Riewowh4w==,type:str]
                    - ENC[AES256_GCM,data:LmlwdGy+nxMV8EUrW0hwJmKx/dU0pTs=,iv:V8/qSw4ES0ADnFPvKwDQA10qX0hNgXRBUYeNoVWW2fI=,tag:14XQJhtn3WG9Hbk+fQLmgg==,type:str]
                    - ENC[AES256_GCM,data:7xheuMM2D+u3YFvYsq4MJY9q,iv:wGiN3+cxTubBphSKlTPTCcaMCwloZ5mrbBXJMDhcavA=,tag:B0r6292/JZ3gFJSIKFBILQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:jc+2Wr0TSarXl+RjX3FKiSw=,iv:avlhHrBB+rQ+PlpZSvKb3KZOi0NgReVsVj205AZK5To=,tag:zH08wepsMjCiFXcp1F0T8A==,type:str]
        - ENC[AES256_GCM,data:6VWjpQexWaHVT7F5Sjqx7tjsWN4=,iv:jIgNIF0HSESGZXpl3jrZkQ2bEmejdCMFUbA+3pgRzDI=,tag:6xN0L4VElC9ROcl4goUpkg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:crViEMm1t7+U5NdKwQ==,iv:PmRvWcIsLx339wo7YnuBqkvgo/LRVgMecSiAnj8AtfM=,tag:oOlB3CNtSfBWjNji0QWSSQ==,type:str]
          description: ENC[AES256_GCM,data:uSbU6frfdW+3CJBk0A==,iv:2biqTaP6g3VLNDcTreOJZQP2fSW/PwjMISiT0KKQsN4=,tag:IbHannxpwvRU2wc3SuHbog==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:KBylDi5oLtEmIfblsPB0,iv:VgdYjyf2RAAeKaCudKQ1gKYxqB35zg17iHJgE7qW5SY=,tag:wQLvh0M3/hQY/hCCLCF1vA==,type:str]
        - name: ENC[AES256_GCM,data:v4hR/zZPUozjSjOr,iv:DrihqSZ4IwL/oURMGrDgRtpbw9Up6MZ4QVFuUHkTqQk=,tag:HpCzx985qLxnJROD7wvFQw==,type:str]
          description: ENC[AES256_GCM,data:xpU0Gl+9EOGxzDqhMZos+fNnNSpSF+KP,iv:8pKMv0Y2joe3cWNpzmyJYwEjx1PUGkgs1orSYRASpDg=,tag:iFDnRltkWSV2s5ckVgFfoQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:cw==,iv:xK8AGGRzph+DjG8sgB5zuIvkG623WVYakkEhSnRkIbo=,tag:iZnG86uArt5BbOnT8ZGdPg==,type:int]
          key_usage: ENC[AES256_GCM,data:egS6/MrvUbHBa5QnOf38,iv:idGOAFrLs9Qbb9qEIrkvXga/LdYlIL3hH4XR6Vx4iCk=,tag:IVohQ3rOssbAyJpipL4Y3A==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:FGMGkIZN0L3x9v8=,iv:kaujezz/3lTHogt05zL4JugHUZFTt49Jev/wRSRQaCg=,tag:nE7oSkzAVDaB/dE/OoWo7Q==,type:str]
          limit: ENC[AES256_GCM,data:pWqJHu+rqVU=,iv:92+Fz76g2Jm6znLBRDygZgiLRaK8ha0fwSX8ac8q23g=,tag:VSjf3aJRSKQKleUwLnIJuw==,type:str]
          notify: ENC[AES256_GCM,data:nrLCrEL/z4no525a8sv1YAtHN+82cKHJ,iv:i0zFoABYGfhPzWz21LtkAU0i4beS9BKY+2FVlSxSa/0=,tag:1tX5wtRa8/h52WGWMKUbVw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-09-23T23:42:06Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHwE98gL3QYuaxsuKt6ZVq0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMo+Q7oz4Oq3DmjN8AgEQgDs9/AWRay8yddY40/Q5hJl69aJ5TXMUt0uZBRzzUTKuHghBUr8m6mbOOjppd7l42a47H+urF2f+1LE4iw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-23T23:42:07Z"
    mac: ENC[AES256_GCM,data:b9+aZJBaKzUfSoS6IJ2oL3ZjqOSXIDrTA4Cs94ikrSxEPaJRPO/YqSC4aYB2dxuIIcpH8eiHNXeW6wYy94SHLToyOopI7o1Yn7PXid2f9WUgIH8kbfHONqtd1Vs4EYOlv+/7ViYRenRGmhZiMY+w9C8LmGHPIOZZVGTt9sj0TRo=,iv:+ZeGGGOhLxC0ZFXQSPlrbznKWD/ALTn5Ler2ZkwyAgI=,tag:DoPqVD2+PwsVXDOrBCNpyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
