aws:
    name: ENC[AES256_GCM,data:qLAUjOcc2uBQZm9kbWOm0Zw=,iv:f3hsGYxsSGItKD2Hm0mBPgxoZ+rGAQHeKWLxL4Ql/m8=,tag:6xOGxsJThZ4qRV/MzRsrhw==,type:str]
    region: ENC[AES256_GCM,data:SYzj9uyFQzj5,iv:fM/RQVf2PCa/feE5ox1ac20jQJqgTt8Qnnr9f9RRqw4=,tag:3EajuT/pSqqwnQAYO7YodQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:9fMpXXOHHiP4Ageb+1xt9WY=,iv:TP7hq7oXutyO51cfeS0JJ+cIVuPbVAczTLrjMfAG9nA=,tag:eKqYrH1D0TODxNEh4XLWaA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:yzyxWiOLEFhB+F+EhSR4n6P6I15WRnRN3CxT4uRo,iv:DaolkhDcOI7TnisF0lRDi3XvRK7c8nb8s37skFv65So=,tag:2S2NX/mJDvzOMgOmy5cBsQ==,type:str]
                    - ENC[AES256_GCM,data:lphxivuAk9b8Ag3cU58y,iv:Lc88UD9FBAAofCMzqUfnASbYc1YI1dKkwXh9Jlr0PTI=,tag:ie/BMLLXAVXEH1q9zddhYw==,type:str]
                    - ENC[AES256_GCM,data:JOAChnDGp3KyscQ90A==,iv:t7Pt7HM9pgcLsbCBOkbM1U1/rStaKbVBvMFtVRcOWrY=,tag:+b/dvN9XhaYUZyl6tDY/hw==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:4OGlw29SR/T/gxaE4Q==,iv:7k5jqhAhcqmgv8u7+/0mIXlfLB2xVv07istKvBymXRQ=,tag:TIqp1mSt+/nBpyBqcuPw0g==,type:str]
                    - ENC[AES256_GCM,data:l5yWSzVFAVK2yBA+Jvc=,iv:Xpr7w8HAv4MyVIb1aeih+ntUH8yGF08fpaoZzVKb1/M=,tag:lO2QxLyh4Uo/pRp86da4JA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:afRAL7oafnxqT8go4O627xwzFXkDTwbt6osHvtOkQP7ApQ==,iv:BTE389mNZIXDVfTLzSItmRZwS7pXt0LDlljpmkYsiys=,tag:O0J1i1k4Osa6Ukfa+gKk3g==,type:str]
                sso_role_name: ENC[AES256_GCM,data:qytqRlAw43MDk2QD+faa17HbgoWrMA==,iv:HvbiTN1RePaZ0eRREG3bSi2CyZTkhgOwb9KO3KHjIwE=,tag:BDgAitgQxiZa/oRHw8Visg==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:JXti+5HLvEXewa3g,iv:UxHvatIXVws0gB1YoqxJNzBXDvVy/eMSeroKJghZW5w=,tag:qjEQToPC7GmBUCvXjanz/Q==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:3ksJwT3pzCK6fVB7P90XXWDlrw==,iv:W7ajOeDgVA+8Ps9c9oK9ZitD/rcHUlKRFw2H8Lvbmas=,tag:z9hMdnxhwWJgu9wKvUEUgA==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:TmID9mCz,iv:J7uN3nKLbpsP7HIZqddsG7sgZqq76TbTEpc5qdp4mhQ=,tag:PYhLvRXVTgW/EhHlcnQ5Ag==,type:str]
                        last: ENC[AES256_GCM,data:mvD3ya8eoLg=,iv:JSr1vs0ejF4a9I59EppYiO8gYUd88XVEJi7x+bnvlZw=,tag:UFhbaPjF73PQ9aKlIU6e/Q==,type:str]
                    email: ENC[AES256_GCM,data:D04ekJvPycOUGSwQ12FSr1S+GdB3px8i,iv:NJgxRx0OJSWvVX93+Y9CWitJ1GtPP1UKMC61oZAS9aY=,tag:FhXI6ScDX0046Ynj5rKqbQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:yAzW32M=,iv:1349YS2ie+VKVcCbvnWKYUqFMZQIdlMExwG4s3vbg7g=,tag:j+SkkKkwXUMKja3lKnenmg==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:O5gLZ/FkWL4=,iv:n/3OkWIKtxuuUq14X0k4goeH6Ntsh1nxXa0AwJenjkU=,tag:rPOYDsobA90D24pHGb0hgw==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:0HZ50D6JayQAO2Iz,iv:FE3e22vI57i6TefwObz1SNunc4tZyj8ArAKu28rklx0=,tag:oAS5MUcMUxlDZvgLex9RSg==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:T1exuiO1uvkcrZkcG3rUS9HRSMf7AsVa8iS3Ai8OqBEdSPYAtdsy5Z0PkQ==,iv:wXG96TWVQWc23WI8M0EsZQf871b4jHX1BkL13q7+nAQ=,tag:NmGg5sbGm+3SliNVfTO+Hw==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:YciTIrd+El/Lewbrvb2E5eI=,iv:hXblP9ftsmgzDPtwE2hRFGFsNmFUZl9BYvL/sintLV0=,tag:F/V09PlhmoFOZqbX9GwUog==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:DlGGYjmwasOu5Wv+ePCu9c0HdUG8yst2FZhRcXyUmpYOcFvC8KJFNg==,iv:zmRGTUzcoyoRQd5vvDJesU440vttQJnpZrWLnyliBOQ=,tag:r1Lya4H3B/5eaCeJZLV9GA==,type:str]
                - ENC[AES256_GCM,data:tZyXQnDc7NnFVAhDQm8yJvby0GVIFUxdBuVhAM/3pqrmTBoOjEc8XQ==,iv:8MZ802emhMh2DSHsZ8dT5Rc2auFzEMTHRP8TbV589AQ=,tag:oliCcgBz6epBjAnLfpwlGA==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:bZ4oUXg5QeDPrYmwZJohl4lh,iv:SC3q+auuYNIhS1VrEeEywa17E6I3vzjvk0cgpOgEMxw=,tag:wUe257rBN2PYdpO1H00S+g==,type:str]
                        - ENC[AES256_GCM,data:8m+nRrD/3j3MZaylm8ljloHZFw==,iv:YNIMgA3daViYozRF1w4LdHYHIHeQskQZSwnCDDlVC3o=,tag:BtDiHPRZW0dN7WbDks9qgA==,type:str]
                        - ENC[AES256_GCM,data:Gwvy4vopsT/KEpCCYRyj2pB3,iv:+FBdJOFTrILehLYys7lyxlJOJPqqS4PnetBZwXfNOyQ=,tag:gJDy2XjEWpYsli4Y1A158A==,type:str]
                        - ENC[AES256_GCM,data:WBqWCXxPxnnTpx+TMERiXRjtDFAFDQ==,iv:Iom4sRcAdmyzMVGshx4Jh/0cqa85Ca0zQ2RGeC9opck=,tag:XNJmJaDb99G/h2LvagkM3Q==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:7O99VE1jkA62p+xBatCTiR/az7zF,iv:mcLb3YkWNSu/jv/41M2AmHFwoX4X346yVF7WDjBLbu4=,tag:43aaN9toJZXgESIkumi2dw==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:6uWihEwjynF0f4r+NH9Nc80Oh27zecFGT/gdFWxN,iv:HcJBEng69VwVBjGsND4DkxRe+cO6FMp/0InoXv0JRGs=,tag:UmAPR1i7xXQrW4wskxa7SA==,type:str]
                        - ENC[AES256_GCM,data:BINJuYKCChu9PIDihaAX,iv:tlgZI+TRw9psK0TsYB5j7ApROcX0ABFKXjTamDumsRQ=,tag:eE0oTzDlmrPZ2k+lU7nY5A==,type:str]
                        - ENC[AES256_GCM,data:6ihHNkvCra85lzhxrA==,iv:2Rbe5XTljqfozQuRCCdvVIeuqYv/6uofSmYOjSmCtrE=,tag:Np68QdKK7YGBnuavdzD/Lw==,type:str]
    buckets:
        - ENC[AES256_GCM,data:5Z/9nGnX5S2EBcmUcuDXgj8=,iv:M/XA24pznKPxdkk5ghLt3PGVrnhN+F8rZRFFVNeFDVw=,tag:CMP2PMIisEDDWL9xtiznIg==,type:str]
        - ENC[AES256_GCM,data:eVLxJZ+BMgpeAP96uaFHpvmHT/o=,iv:R8KMFzTQn01x0fcMrr6aqF3fVEEQdVQHgYAGJSIaZ1g=,tag:Xwu47HndJWtcAuTO7djOxw==,type:str]
        - ENC[AES256_GCM,data:nsQyToYqOfWtLvQmVVw8eB9i,iv:8sE7TXRlzfdu56C7tMhCiHlZ1eSu1mCk4MwHzeql0pg=,tag:mGTRYJtSo0oW2JtO8b7ohQ==,type:str]
        - ENC[AES256_GCM,data:E3mD7+GPrzZi8BrEPbm8Pto=,iv:2EQ4cpknJx54VJ/Xt7/eIEbbaPNQCHgqxSFAV0PlXis=,tag:8jTgYmxD52akPutaKDLeAg==,type:str]
        - ENC[AES256_GCM,data:nU7Vqz36TmBZNBm1GtFnQo52tlZu,iv:uXFskuwRLkuhFXIuITS/bXl2TOdbRTY6r5hMe8FP5jQ=,tag:GBS2e2PQ3BpbvGEAvyXn9g==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:g146PhZreCxFR7He1Q==,iv:m0AKc5mv104OcmY76nBzsKEDLc8/HG4mgmnppPYir0g=,tag:IaWNYbCrZkFJh2/eivw69Q==,type:str]
          description: ENC[AES256_GCM,data:VhtglNm6GTad4bHkhQ==,iv:eBWaushTZVlHodPD9DhyZKXHLWsKtik9u5gES5nm6oU=,tag:fxCKLH/JyqmxVk64xU8yVQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:8Ajz1fsCp1fpsV7ZUt65,iv:urIk0rWwbMl1SYduanesN6/nvYET42ETPsHAG1Dhpus=,tag:JIhGUbdZ9Qxkruf8BI0DVw==,type:str]
        - ENC[AES256_GCM,data:pNB55hw1+QVudP57kPK5ijY16ZB53TKYsHhKW78=,iv:x16NBqoSXzjfq25mjQKstzQYBXSuWiYl6qwxZAjzkdU=,tag:obpbfHC5gufgqjUslPfMDg==,type:comment]
        - name: ENC[AES256_GCM,data:9Q+d97oNQqwDtoaM,iv:nWQ6j8p1bZvX8kZ2p84M1vvxGXOLh4WOQ9DXWXNX+GA=,tag:lL3tHtXogFn9IkvDNINyGw==,type:str]
          description: ENC[AES256_GCM,data:Q/Vefk3jsMP9nIdMLvykoCpsVrM8D6a7,iv:xuuSocy4edkDUWGuFn4TDeFU60qlVNnhHOm9VUb0Fh8=,tag:/GdXILCvMeRUqNiFF/hXIA==,type:str]
          deletion_window: ENC[AES256_GCM,data:cA==,iv:cbKm05q/4VQPKGSuIsldzT3k7rOQkgqlqvd7+QTldMU=,tag:W6/nEMUFTYgMXpry8iP4JA==,type:int]
          key_usage: ENC[AES256_GCM,data:i4kclAhAeVV4t1K/3lLI,iv:/eIgiSfnGJ2LwvjoFrd49uKPn9/PFVOsFloi60CiQ1g=,tag:tRm1MI9juQc9nCYycrTw/A==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:a2va70W3pyGm7A8=,iv:4nWVDHXe43RmDFLI+U/AhvQdkU6589ltKMMnOiVrclU=,tag:dUQcvSwaU0C+edeHq7G4Rw==,type:str]
          limit: ENC[AES256_GCM,data:4vST7JR9EqA=,iv:4fS0PQor7FniiqpsdZzaHEn8npDq2S628+36/+6WuoM=,tag:GWnTUTEfWTvS2jOZstsrMA==,type:str]
          notify: ENC[AES256_GCM,data:Ms0k4XP0s1dhT2YJ9Cea1+ghsnacwsk9,iv:r+NKtQWeLA4vg6sJ0daYZSQ89KGQKgEQQ7JrV9luuCA=,tag:kPGheOnkckawEIMyyop2Ug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-05-02T20:55:38Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEK6RVPj+ERt9ebDo42CGvBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0GBznzKFvPD+5Xt/AgEQgDuGW4j6zz9R/T+5nND2eYo3kWVh387T8dJHhjZ2PlyTo43Tewt7VeKVDvZ2ZYOLCEtYv2FaIPBlmRlM0w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-02T20:56:01Z"
    mac: ENC[AES256_GCM,data:Ob7IQPe+ODPDmTvG8h9wa+5u0ulXrI7JGYxNWGCNGKcIxC5pY2FwWfV8yBeNHjxHGQxJ0x8KIglEIJnn851BJQSumGHEjz/CmxorxOBHbyJBnqwVWY9bGG/aV1J94o93ghrzCo29qzsFhqnN6YdrEfdYwRX61CUnZ/PZ4X/3+d4=,iv:m/ok3ipC0n8NNp0mwpUqKJGfSugrVLKfY7hiDayD40M=,tag:hqgzwoLfB2nqRsB4Mwv2vw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
