aws:
    name: ENC[AES256_GCM,data:7b7nEPEFtkHEJvqF1Pvq+78=,iv:1okCrAUVtu3PWBtN9iSuJDxagcihIQ0mrOZfZeNl0Gc=,tag:SN9uDX9FYE0ZUQNQYeIHDg==,type:str]
    region: ENC[AES256_GCM,data:zbQVg7aP2lZ2,iv:iCdnuHnfuXitF6HI3iiHgvUFv6gJYIbwFl8qNGXe7So=,tag:OTtGTh3yD+puxuNDzsxg2Q==,type:str]
    oidc:
        url: ENC[AES256_GCM,data:fAZyv/J0UCXvLuH01jrUDJSRjxf0LwCm50U88lBS+t7+bCDFFM2HS5fPzA==,iv:wej8S2qqEUJ2B50r2kIqF9RvXtuxaPD01e2Rep4O70U=,tag:WuCru6CxbZRCBR/fEagIlA==,type:str]
        client_id_list:
            - ENC[AES256_GCM,data:/IQOSee6I9bc/ddLTPxuQBE=,iv:1WNm+aO2XA8AP8vwF+omMFrWI+LSQlWUDUqatqI0Gb8=,tag:hwyq/eUcxh6iTQcs8DfgkQ==,type:str]
        thumbprint_list:
            - ENC[AES256_GCM,data:Xes+QRYcRZqIE0Hj6n2QZH03sBFvtjNO8kxY69P65QqGGH5StIKk2w==,iv:72xBV7+n0lXZwHlktI+tMia0LeHAjfiSzOpep2B2NeM=,tag:21MfVVB1GJ7ynItD1gI9dw==,type:str]
            - ENC[AES256_GCM,data:vwscGOVjePXe8Pi4d7NRJ8xVt5daCqKscfwSQ6br1p3fWAockVGNDw==,iv:9Q7CI0vNMki3X05kfZUDq9JryKo+csNxgUVkC37LZB4=,tag:6YwzaejHFTmvUeTY052fFA==,type:str]
        roles:
            github_actions:
                policies:
                    - ENC[AES256_GCM,data:Omc6PO1v9PoyhGi4tA4B5ImizA==,iv:X+6UN8c23rrpjsHVB9l+rrDfryjH7OATlb6vu92p6qw=,tag:IKg0t9EfMzwNqIvo9p8LkQ==,type:str]
                    - ENC[AES256_GCM,data:TVwHqalqzI9NoXBtmUXEcekT,iv:zIcgOcdA84PEaD9NRFxQ+MNbixBvaX+XrhcfFiCuXa0=,tag:63E2b6TVpB6xBFPE54ENSw==,type:str]
                    - ENC[AES256_GCM,data:zNP8ZVaxGt6uAhhnpWcFRiMdCw==,iv:P6TnYrDMFsj4hKKOdcNjve0Sgdx2/QI5JchlyTEI5wg=,tag:agrdsRxQxsu3zFCPIigutA==,type:str]
                    - ENC[AES256_GCM,data:9wRpzWcjVRW15QJKnZKE4NtsnVI=,iv:T/PG6ycOkF0MDk90IA4h9gUYHdhTj+CvYgCneBthk7o=,tag:Z/vKHZ+ugfIsrFBy/WuevA==,type:str]
                    - ENC[AES256_GCM,data:VUY45J8IQSuR13+UDA==,iv:HQoqpKn4Va0vdzkXEX+N+Oz6Tc3bnEq1uY5N+0nc0xg=,tag:DKY/TUR+XlHb/cjryO8+bg==,type:str]
                    - ENC[AES256_GCM,data:RsvLVGAej4L5I489UjvnbX1ps69shHyteSTX6EUiiXW1tvQRBnvwSjrR+h+9,iv:T0fqeu6jmEzRgx/sT6srsAFgJy4Lkxmi5H5Vq0V92jA=,tag:iOsU9D6jPs2BrZI2drVS1A==,type:str]
                repositories:
                    - ENC[AES256_GCM,data:hqJg8KQewGikRvI4V1wh29sYBdFs,iv:FDadjJ0uBK8VJJvUH+t0wUkTsGH/E9IlMCVeX+dnLIk=,tag:xGccPgmU5IpK6coNZvcu8g==,type:str]
                    - ENC[AES256_GCM,data:oHXHT1suiNP4ZGS9/ivuOXt1gn/Pdew=,iv:RNZSztIxJx9MsFJbscUCx2ffCEn9trYlXBnW2YhhMqg=,tag:v/9CPidoDqfwOdXhmYLKtA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:iLi++vlwSld2lOldQCobWLk=,iv:YIaRa8YGfe2FxstZ0qBsCa1ZfPGKW5m/o7AYxl3UUxo=,tag:bkpynVMBpjM2FKQI35Wkcw==,type:str]
        - ENC[AES256_GCM,data:C48K+C9ONbZYDOjprNztAKCCCw==,iv:rBZO0D/rtGQO/fudFG6OF5Yju3WmQn+quZ/HsnvOxm0=,tag:WapPoPw+iECGCW72JM8Epg==,type:str]
        - ENC[AES256_GCM,data:hVRjc/BbRyr+APKn8yta2fkTZwM=,iv:6rDZnqKFnt1Swr5GMR0zaGVefC5DkGI5vD7fE6hAY6g=,tag:KgIv1kdt/rN0ZFiQ8Izl6A==,type:str]
        - ENC[AES256_GCM,data:FFAljJvNRIGK61k81KvR1EXxU9vCR10nRA==,iv:XsTzKZKerQ7hAN18Mg0KTk/t+vERw5qOOmS6RBFvOIk=,tag:XSZ+qwobMkT41NIzdo61og==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:0ORuuMAOgAJmlQ+vZQ==,iv:+H22kJ8xeUrI5PMPGjXjgLQs8CtYkf/dqsR44JsGur4=,tag:yMLFrd0dSLnXEWjq8Y1U9A==,type:str]
          description: ENC[AES256_GCM,data:Xtt3ZkCCe8Hr1PrQLw==,iv:m+3aCtTeXY3hOh35KHIynYY5Fh5UklpVsXp0+Wt7K04=,tag:frTCTH2q8XStkYQMPkqkgQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:WvUg8z23W6i+aTqM5O8L,iv:BHtLrShhKGEs0NB5D9ABvxqNIPcLkGuTwSRbJ55jq6c=,tag:Vx7S7PsNYHhtc5gctvUQIg==,type:str]
        - name: ENC[AES256_GCM,data:nsl57deXXFX1eYrh,iv:qTHJd+o/u3lv8jYvIqk/3xTVOuleEwelNcqkN0mhPq4=,tag:xk9BF6+MOZ48lMv/6RjcIA==,type:str]
          description: ENC[AES256_GCM,data:4wMpRWVPMLkQZYT5PLe53uy8L+LhfDG1,iv:whe+A9PTUf3/YgZi55kElyF0nP5lc8CiImX5BwR8y3M=,tag:uMXGXwx0F+hoHpdpC3g1Cg==,type:str]
          deletion_window: ENC[AES256_GCM,data:cw==,iv:RnCfWhC+wNTT24NThu4CV1ld3ImU0q9MWShXa2fVrdA=,tag:u9xGd/Hrd0cYk4RQgWx96A==,type:int]
          key_usage: ENC[AES256_GCM,data:s3v6in9rsaaivQLeHmAx,iv:lwbuSXouZc3BNJt4Opc2kBVOL9SEmdA9NjV4ZKdFX0c=,tag:p1ehwQEAXvN7yUUqOmuuIQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:eyqHIO+13c8FIf0=,iv:+PZJSC87XKNOKv9KDAdkmdpK3k4Ldsdfy+Uegsl2kWg=,tag:NHV/z9F6s44Pr0FZER79mA==,type:str]
          limit: ENC[AES256_GCM,data:hLXXD5B+awU=,iv:kVIqAy3mRF1DlCMvXwg+wRR/1V9rHUWggVYSSZ4yPzY=,tag:UnzclntctqMddiyGpKEhgw==,type:str]
          notify: ENC[AES256_GCM,data:0QYp5aqQAd/Ra+3qtqmvshgUPgfEVpqB,iv:jAEDPBzLshAe724u0n8H/uqJi23gVkOtUAp0zLMxXfg=,tag:/3DPejSxdw6QgTkdtp8aNg==,type:str]
    ses:
        - ENC[AES256_GCM,data:cGOx4afyLLKL0+pP6tDX+qeowQCud27Ag/diGhizog==,iv:LJ9LVpRxQAroMYVIme4JGfcaCU6yyeA1j+IysQt0/Bw=,tag:7cF27meDEK+K+ZiX8vNA6w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-07-01T15:24:47Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEml+k93Pjw8QcEGLNbqrQqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMduP7z9B5LYG5XyHxAgEQgDvlX7fSrCMWZxBMu3M26fJc4UAFyf/8Xmfp6mumiKM6fyhXujAFNXUKo+sje8q5Y9lzlY6H9IQ8vAxVEA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-01T15:24:47Z"
    mac: ENC[AES256_GCM,data:Lmjz01wCIQYyRtyscBCF5THYRITqc5v/gIQcDwAmFGti6MiQsuCobvzyzIgoK44QWY9VcOpxuiZjMN3gDYU8Mtkh0a/6Tr9RPGP3P24Ry2OoSv1HO8HuT+VXDsf0zMijJzcFRpDmWnaz9s5w4bA+yXX4cp2N3vavm3hi7/Twmgo=,iv:exkYojuBdbCmvkUsjE6zUHAhUS4tRk9Sf+HmxzT2Se8=,tag:vTZ9BQB9dP1ti+nKqxKoCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
