aws:
    name: ENC[AES256_GCM,data:DbZGsiEbfax7Ma0nehetEBQ=,iv:bEkXJFnEHf3NME6zw9YdJBRx/YHlriDf1R1imXRUd74=,tag:aKwUxB62l93180vK14S2dw==,type:str]
    region: ENC[AES256_GCM,data:M3hpauclJfp4,iv:lUi4TorGB+ie0wgx5sbra+NyTVnZkYmyfK59dQ6IsIg=,tag:Ln443SD5LGQKyXePiOAeZA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:BDNJ1HXljMxcK7NkXc4E9xY=,iv:uvrTqhQ33yXeTI+MTV/PFu7zhV9e9O742yJeVAi7Dz0=,tag:wkh4xYn7BEX19fpMvOQGIw==,type:str]
        - ENC[AES256_GCM,data:nXHRr5xvTM5B5zpdgq4qTWPF+Kw=,iv:jYFkhI/IDoTemgnYEL36Aqnk+8VGeOmWzDoJKtlqYTs=,tag:OQqaUxMzpSA+iuIjyH0V5g==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:6XsPZt+/kD9nUojo3A==,iv:KCk/2Z6uc6X/QRUKcaBJRod/Iz9kXWb03ugsyg4YeDM=,tag:torzdScwWdd49q6kUeDG5A==,type:str]
          description: ENC[AES256_GCM,data:kkyCwBtqLIJAZ9GQRQ==,iv:o8KKGQPYzkoWK8xrznK2958clDr3jadD2xRjMRFGUlM=,tag:ZAwqJD2IowJEQqcmmYGvBw==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:beYYATaTH95jseJvwU1B,iv:b/AvGTpDe99aByJJ46anN1/UNQQW5O4PT0dgJGH60js=,tag:BXgl+B/fWuAuR0tNe12saA==,type:str]
        - name: ENC[AES256_GCM,data:f+1kKM0fvKF+gGbR,iv:jcxbqs0iNAO4+UKaxOZi7Ut03XmgSf+bzS7g0+x6iMQ=,tag:hMHZw9Z52Lv+g/HMoLOq6A==,type:str]
          description: ENC[AES256_GCM,data:dhJ9nuZeHZl8SJR9aVtPU1gx7M8Lbs8E,iv:/pQj+RQF/CP+RZhZfRqGV/0p+YuVNfLCMxRgjpjFpcg=,tag:gT5BQB7V4YvVP0c5juRzAg==,type:str]
          deletion_window: ENC[AES256_GCM,data:Xw==,iv:6eva9c7kjpIqnNH+p1+Fp5fIIbnElYtUyyKIaMeY7yc=,tag:Qjr9BljXaNgsiuIyKJOZog==,type:int]
          key_usage: ENC[AES256_GCM,data:tZF9FZKP76RQ9yWFwJM9,iv:+SJgb6iqpD45NRKdQ/FwEVKlH0tSLr9BhG6tbisEovo=,tag:EXHQolrkmatjoVyW8xMALg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:ByTYXNklblXjjgs=,iv:/ASyU5CBNEvWU9tTmUSt9BjNJ7OZUQqe/hXekeYlI0Y=,tag:UpKFnbONgI9jcA3H691zXg==,type:str]
          limit: ENC[AES256_GCM,data:0tYhlkGtwME=,iv:2tRu9YDArPbagxl2Vkjc/sNzja1HcXBZbqjAkZDpxK0=,tag:Nm+Ai2nIcUQv5N+1JZA+Fw==,type:str]
          notify: ENC[AES256_GCM,data:1CSUrDCWhRM1nmr9xYOnZ2mmJG3rK+q5,iv:JRDqopB0ArxYMF1DD1WTrrFWts/zCrOWojWLa2Ba0PY=,tag:Vq+dIc6b1tYXkqWxa0XWAg==,type:str]
    ses:
        - ENC[AES256_GCM,data:xKjzs+3fdTLK/QClbAs0dRSHx88Brip+,iv:iFqpxGw9TKERUEbVCvRtg0yttiNkUaW2QfqWYGxXufc=,tag:1qDiic3D9sLiVVzrJS51sg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-05-28T11:09:05Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgErpl9neVjKwDBw/6behD0YAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRNCZXgCXRhbl6MJ1AgEQgDsxg5CYjY7+j2CXP679ZFjnwiWNsSHiDv7+I1ngAXnHJUxAQkql7xV454vbbfW+5d2RVABo/n+GEsz6HA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-28T11:09:06Z"
    mac: ENC[AES256_GCM,data:3JV01/rcLLypRRog98HWdGmAMlvEMrZIteCEpHQ/3bN7SNK0HcbyJ27K01OPjqBPFUxG10uS2oEpi747b+sl0WfUC9s39JuVD27aydkVn8yDMDGSm1iol3RTI1THJTxDy6p9knNlDd2Eu0/zWOhtII1V+OKvbhoW8X303pfKYBc=,iv:O8DVJtRwoYfzVcLjerL1CJIXRddPZI2t6PJQdqvRexI=,tag:u8SfYrg8mHV6jsOKa7w8tw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
