aws:
    name: ENC[AES256_GCM,data:Ig9woy8+5edEE/jVhVvrkag=,iv:WzYXWN0S26b/0tw39mpQxTHOpbybiK9OfXjq88cNOLI=,tag:ArZpzxWw8XlxxdG52Tvzjw==,type:str]
    region: ENC[AES256_GCM,data:+JAx7W3cpBk2,iv:ePD77/qQAotAjH/QCLaOTFjPKPf0V0YrJKM0vZb6wuE=,tag:RGhoWMReGMZgkaw2qDFLdQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:VIn+/1SakAN4cjDXpeQM+4s=,iv:TXuI0NyTDiaFJvB4sF+eClN2uBpegGfHTdUOwR1ZPI0=,tag:z6i43SGK7WFkFEVB/gS6Xw==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:nY7izIUSLSrEzR7JUVFVJfuhX+x7uetYqdX1amM6,iv:XWRdBfnBMAOzKRC9sdCC0Am/+xsjnqCVbGGUNIqL1WQ=,tag:wNMyT8kzf9Gr9lQ6jRFP9Q==,type:str]
                    - ENC[AES256_GCM,data:QIprRxkAXRz/GcyfP65d,iv:UznEagBJ9FneRHeFGynNGITuBlORyE9hjQkzS+TMYAA=,tag:PEjQcQQUkciWVojg2G3eJA==,type:str]
                    - ENC[AES256_GCM,data:4xe8VAwZFIogevXdbA==,iv:Z1OsqYtHDIbOzzUYkUtfy+E9S+slxOXLwg5AcixLIws=,tag:YGEHHtUjUmrEKHlRIU3sjw==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:s81r2zaLx3HRsKoWxA==,iv:S3bTWXJRwBRA4T3OQq6oGbJZhBOwshePQ1BqfYIEnLM=,tag:P0Eb02J4INCDVJSfDSbmpQ==,type:str]
                    - ENC[AES256_GCM,data:qxeeKF+5wYY3ZioPcPw=,iv:5ZrH0iMF1DA7HXv4t9tWE1j0AP1Da5wN8P21x7aw9ps=,tag:FTOViNRZrxWte1Pwj9/dKw==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:HO94yZ+HX1cbLlTOXJUxP+g80bQMjGNwmiv/eQPlbIdYLg==,iv:BsKcMxLhNhx4XipOkERai6a6j8Wbg1voxAoSYmV6dWA=,tag:JRxlMKVFhBsQJ8Im7F6E9A==,type:str]
                sso_role_name: ENC[AES256_GCM,data:tPtmyAL/HQig+1phNVBxKNuuI0IBZw==,iv:lBiRi0ATwbx04yQzRhfvIndv6ECPr124FvC8O1TDYqQ=,tag:mPcGYB84clevZT+AU3xX9w==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:cGVyKeW1oIutunQ0,iv:JJl1exen+xIIf0oOqXmdCPH1uFzEZvQ2SlNXvClCtGo=,tag:ZNArUQK1hV/BkA+RtAwH0A==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:7zLOreoo9ubRoiv3+cnJ0+X6aQ==,iv:G1A+kA9KkNJz6g2JuR1Nc+eWbU8YkYxZwnHE5cNJRUw=,tag:4Rsci5vf45mcCuM3NoaDrw==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:nhVBn6bermvklugU8G5U,iv:DPKSBDn33Rf57FxZyAjl08noo3y4ROLr9owEF5eV6zE=,tag:lrTL1RDrIkxGRql2tWCVOw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:2j2nVh+9,iv:/EwFXS7N6yr14rAVKZPbxbgS+mar367AbLrLKcuOajc=,tag:+JI8UIJ0Vdhr8IL1izrwOg==,type:str]
                        last: ENC[AES256_GCM,data:sqAIhnjASnc=,iv:NEAfuOWtNC++FtklEABgyvHE2+sBnn042ap26X7emSQ=,tag:k4QWoxCCP0uSlLXCxZ7nNg==,type:str]
                    email: ENC[AES256_GCM,data:NmeJQukE8C3eeb/fbgbEty4yQKbhLk4C,iv:E1jXnlYOivheKheF67RlXyv9TG0Yrr2MPkmO1+rq+80=,tag:U0jUN4RO7Xu/6v79aIc+tg==,type:str]
                    cli-config: ENC[AES256_GCM,data:RexxiIs=,iv:lSIqC1pQvExcdhChgPxMR+cDFPd04V0VHQ958R4v+Cw=,tag:U3/+DuRIef5Dr7bvPqesOA==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:/5X7NDPsauY=,iv:OmEHbsmO+BMwu8UNfmz8DnEGohLVz7ZMG560TgwQa50=,tag:pIrAuyhh1+xCyQ+vp9/Opg==,type:str]
                pezocion:
                    name:
                        first: ENC[AES256_GCM,data:X+IvHA1ig+A=,iv:C1Lv9X6xDqpySLeVtRkTSNZdLY4WWv3J7BjTag/EGPA=,tag:b/ZN6Xa/+vorTmTxKiqi0w==,type:str]
                        last: ENC[AES256_GCM,data:KEMdAFBftUc=,iv:qRL6vJwU8TDBL0SlP4DtO2pn+PGO5E7aiTC/HI1dyfg=,tag:J16TRUP92nFjEIJ3zKA0fA==,type:str]
                    email: ENC[AES256_GCM,data:RIIKgpZNGrvvMWyorb9iweIGLfRmtaQ=,iv:Iwf2dsvZQgbPd/1BSSTmIeR4y8BSqSSekw5eZ7jru0g=,tag:QZjUv3FwSR2rLWrZDh1jKQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:i6mCQs8=,iv:MdFUb1EJyYwauBu/ILhxTFv0pVWe+u9mQxsrHOzqZMo=,tag:trniLeXIAlbaVxqNLR8Y8w==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:7V+WedZlsTQXTU5F,iv:mCfYJjkOf3930cYkL/L4HOIDCB5Kdc0ehe+duqFQp2E=,tag:qIi/iPJg8cbNb0sTAPfU6g==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:qMaIhGKsqT2GAV9x,iv:2JVtWBe6aX70kJ8l2WKGeM+k5msk5Wml8tn+BWoJAy8=,tag:mSnFOfogTgK6RVTMFyaoAw==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:djJvD/RAVXLEUqtSloIN3Oo4jLXg9hIxryCcviTWyPNTooNOlhJsEwQUrA==,iv:yzZ5Wwh7lSeAPHx1fwPlTT8F5/mQegIuN88rTKbxlYA=,tag:mD2fxrpZA1K9nE4FM9bhAw==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:LJZn4/RrcS5tSNO9i+WT7SE=,iv:SHH5fS2jgmxSNhZfXLvHBQmtJoDmB3JeE0QP/BFwHlM=,tag:80oJlVqONCjT/4vvwzGO6Q==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:mOmGT8gll9iT8tn4aB8XcuU0wID63kKScK4kAgdlGqyofDsb3byWDQ==,iv:e0nGV9gy9+OyhWN8vX0RAeUz/c/w/0xXBtkj9hSJg1E=,tag:I4PmDe0spSDdlAwVYXTx6Q==,type:str]
                - ENC[AES256_GCM,data:LgTE8fgEnylMBBSduSnq+e07NyTZYm5L6kV+508m4YspaFpoIFpG8Q==,iv:TzMivulKUjN4VPhfYd18CReyXuV14b8qlparG33pTOw=,tag:JxeGupgArfUd7kSPTSaHQQ==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:NCbf4PJGG8r2yIAvlPSR9WmK,iv:974aCp9s5jtb+RM6nNG3omVvz5tkfgTxkLMFeo5Rruo=,tag:6kJnpaKRveHZxvPMQ2XHiw==,type:str]
                        - ENC[AES256_GCM,data:8Qzvf1iX6ph7Nui0ZR9X5IYr5g==,iv:b2vuVWiHnsH9US+v7DTzHKH0jwLhfsA4dIJQ96qbNI4=,tag:zjFg80YqKDGZ1Qa0RSg6xg==,type:str]
                        - ENC[AES256_GCM,data:a0z8eEle64/bqk0XWE3yhatw,iv:QobX6Af8lCp8NVCprqqFz7ROfFmkBUzbF+zORs2OSAQ=,tag:bP8Lj94vJUNvsG9VkYOojw==,type:str]
                        - ENC[AES256_GCM,data:BQY5Ahn2KgDYebTLosI89rtKqlta6A==,iv:3lX0Y3vrbnGQGb/JXqaVq6uC3NdmVLbincFWNaxQuts=,tag:TXjgpnL0YoH9RZ8CgGby4A==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:Hxp6qzKdj7JgixSCxeL2yha/2xe3,iv:HVurvR5BFqll3jdq6CJ51HiZGoO78sq98hQ6l0PiNEw=,tag:HCalMdLCc5s7LsWsBJg7vQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:khZQ9AvUFJGbhyjv7ydETTomVLqHi+wEWrJsLapy,iv:1hH4CVvSpUu/06QQkXQ7wzF7afgRhoTT9PbGK76+TuM=,tag:sLAS55X07POVXjozCPe7vQ==,type:str]
                        - ENC[AES256_GCM,data:fpjCiqYa/f9yLodA6J7E,iv:dub2nZ9QzuZcRMsmjiatC4NOspGgFiRTDDYtu67Ny5g=,tag:PUvlgrOSFQaEsvyrEwhgtQ==,type:str]
                        - ENC[AES256_GCM,data:zdLKMGZhCbXDg6yPBw==,iv:R1YARVtaKpwm750v1g9E58PBsW6pZ/v1szM+Lk/1bzs=,tag:rtwnCNDTTT+oZwOUy5a4bg==,type:str]
    buckets:
        - ENC[AES256_GCM,data:xSad77ddUHJNiVEU9fq6K64=,iv:W1wa7SGXk3zNCoP186qAYuU2PITUV+3GORaZosf5/oA=,tag:nqBsSiosT33f7TTStqElNQ==,type:str]
        - ENC[AES256_GCM,data:Y258IgT4bNKvuWdBxglrHqm0zVY=,iv:wi7vgZPDe97iy3cUgJ7fmyB1RAI8j/gcCfMr3qdrOEQ=,tag:CJJ5ozbeRiG4Ip+fIdZwvA==,type:str]
        - ENC[AES256_GCM,data:oqv1TjC/DyoSmPT0lwFEa1/B,iv:FCfuUiNq3JHzjlni3K1qGye6lyssCKBMchcXCl3VRWY=,tag:wtgQ7inAb1FYrF6TZ4lCyw==,type:str]
        - ENC[AES256_GCM,data:bNP/yFoqWVcJZTxSBM6KEHk=,iv:qu+bcCy19jUYoH0OWKY5R+NfGs3kpzdlK5HIGuuRv70=,tag:NpAPQc5GF18Hfch72qGFEQ==,type:str]
        - ENC[AES256_GCM,data:BT3KgD8n8jLcoBAu8n0FImhM2jTS,iv:cPIBR7fQcEKRgnz3Rg9g2fJudQbpl29XkR+hx7wIhPc=,tag:u0iR2P9VrotyhCzlpygDqA==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:IhB/wcnUvu+BTmonxg==,iv:si4AxhufxMjIs6H2wILOaUs/uC/mHPcBn0Ied92Jf/s=,tag:nKZXQppLEyNL3m7ARz9lyw==,type:str]
          description: ENC[AES256_GCM,data:sdxse8C8MlzqCa5+RA==,iv:fa7hTBTU1pRLlWKvIl/KYIk2e96zL6CiIsehJL5UlI4=,tag:QjOp409Th5x/bGu/XmGLIg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:prJiffI16mnaOw6/ksv/,iv:Z/FpLpbwIPQ3k8JZXIFL8ggp5bv77hZpr4CtEDH7FbI=,tag:zOYTMsIDJNxy0LlQ9rW2pA==,type:str]
        - ENC[AES256_GCM,data:EW3G9yqbcXGPJ1o+57+JvdSfxmjbx3rWc9hDMAc=,iv:z+w9RV2I1boDfMP+tCmPP5His2xC/XVqqCCrWJkU4Ic=,tag:GpavkTS2Ufd7h/c0z6rXTg==,type:comment]
        - name: ENC[AES256_GCM,data:w6UDGKaQmIvTFYbW,iv:R0qeXbs5Xc4CAxObD6uH2dgapxpwdyVxQvV5zNiKP48=,tag:Wj4sYdTJNIObPNMQSvKQgA==,type:str]
          description: ENC[AES256_GCM,data:07cQ4Y+ajzqCIuClQLw+DWI+QYSDDNd8,iv:W9YuHT1P69elLdG4bMcOLAixYK1lV/KTVGFZhjlLmGI=,tag:zF1KDgw5H9o+X/CoerzFTg==,type:str]
          deletion_window: ENC[AES256_GCM,data:rw==,iv:7K2Al7WJdNl8/NsdDGK64qdR3VPn2Kj+1sWy+rKrMHg=,tag:0kdZCNBrDt+I4i5IxAEKaQ==,type:int]
          key_usage: ENC[AES256_GCM,data:PIf0hmGrwtdURPjf82xL,iv:h5BjdFvBu8/baxPQAlUHgVDceOUcJ0jdqBhx3e3wE2c=,tag:N7viW4c66KkYwIkm/WaSjw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:fnJadb39USYUecM=,iv:ndhUKQsvGhPJgG+Xo2F2FPWDLxkc9lu7JBKSopY6JAU=,tag:OhQsm2eivcY/bP2QBrxHeA==,type:str]
          limit: ENC[AES256_GCM,data:4HBcBP8OE+o=,iv:FR/K3l+imYtXT+3v66jE4Lp6pVnGQtZ4VU/JhKB/58M=,tag:+agotwkSMsFbzwm0uZ8i2Q==,type:str]
          notify: ENC[AES256_GCM,data:nzyEfigoWal0njXuYX4SWEjhrOhdcmSw,iv:6L8b8/acqJlKwpegXMH/Vvxnyso2gQVxZQGNd9dZONc=,tag:uCduenzxVwGMv8hZ7klFZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-09-21T18:31:42Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgE/Z2qHUGYSZwyt8wYOEZ9JAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbl/Igkp3OHI76MMzAgEQgDvX7wAls2NZ3XyDbCyGvq9Rhq0s4+n9ydu9yOCNxEv+7lE/qxaIIa6Kai5ix9IWD3dDjrtcgfDShA0epw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-21T18:31:43Z"
    mac: ENC[AES256_GCM,data:1pUU0XD3as+prZO+DWKnPJSzp0rI+ysWQ6sFfw0p51OtLL5gEYP20yIiQHTG7vppZ/Z6kvowjJRz6ATkSKPBbm3xEgu10BndDUfWk2SeoFw9nM4+Tsxm4hDDbwQ9TStt775O6p8/sGT2JfToGs8WZv/nz3tKsWOBGg4PZUPQzek=,iv:QLdPISQoaAhaFPF1Ko1Zabjk5R97TLxu/d0yAO07kjI=,tag:Apetf/6xQHglIckF/yplZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
