aws:
    name: ENC[AES256_GCM,data:FN4JMPYIFhq5nKD7YOzzkxM=,iv:0Oo6LE92RhHGCkh9iEGDfi2yDdGBgn7j+Sv/fksGFe4=,tag:RefQ+lP+1olKarAGx48ydw==,type:str]
    region: ENC[AES256_GCM,data:Lf2gYwYycJL0,iv:ekFHK6gSj3I50Xi8dgm9PzqmfnBZ4vz5DircgaUP3TQ=,tag:2y0qNWbMOHhPelejPjH7gQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:vt3XZ+Oe4KGBSVDCvshQys8=,iv:3HtO1URKRM6qpCFdlDVWX5gBFEN+n3bTxB1kPmo5kwE=,tag:8u8QzjgGRGM7oCfzEwVNYg==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:7NRw4DwaHi2rt1B01SSjDPlsMc/r27bKKg4OLZn/,iv:SHbL2hF88rPE8XUzfXXFqQfUjXoXkN+rrzF8HQp1nwQ=,tag:AhOp10wgRSMMb//JfAgShQ==,type:str]
                    - ENC[AES256_GCM,data:dOXSzR2DtVpgJItSuF5C,iv:LW52q2DpVeaqKgfkgLNbs84Q1QF1CEkHSQQCWnCj4v8=,tag:iJhRmCdFLIn9pkfhFBAjhg==,type:str]
                    - ENC[AES256_GCM,data:lb1lllKiE70PNdJ2fQ==,iv:NgDNi/lIGfWyLe9HdCP/GNEiAThgyWd/NFKkAx91aM4=,tag:wC3eDy96hcDDkbbgLgXY2w==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:W1tOZXcoin2ImPI2Kw==,iv:9MkxJ61+VdBNu7mmVlfrKS1Cw4t3A30EZ4xffnT4tZE=,tag:wDoxZClSwgXTpUeqFVBxwg==,type:str]
                    - ENC[AES256_GCM,data:uM0Adqqgpe6JGjS6Suk=,iv:x4DQBNa5b5gCJ/IkqtQnJXZWwqd/uWy19gHylxOQNoU=,tag:CeBbye2CxxD0hi57/sk+NA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:CLUPZsFnNjuaRWtDmDnIr7qztfCAGkQunzbZfgJ/sWOvMA==,iv:ERBiQOqoLNb8hdZMG8yRCUw8cj85CrOe1KcoBb8qxD4=,tag:Zq+gamPdVzCFQADofiiaWg==,type:str]
                sso_role_name: ENC[AES256_GCM,data:KhDQaPp6SWpM9c3byyO0BJvzndYqmA==,iv:KvqwQGWqL9jbuCgwLsL9HnRYLoNsgHe/Pt0ywvr2C5g=,tag:R27I6kiMeXeJgMsTnkuOxA==,type:str]
            alias_to_id_map:
                certificates: ENC[AES256_GCM,data:PGgHouwra1RV53OH,iv:xMjd5BbkWbcK6g4ZaqlTIn4Ze0VHTCZ6/aUV1qQ0ywQ=,tag:ntQJ6UDA5o7kwsq3tkE4ZQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:GmD4WH2Gu4CXAVlPewPXl7OymQ==,iv:lJGM+z20KWDKGES/cnjGHlKgHripYqiV3NiF1EPmZns=,tag:lAy75t3y5Qt1q42sVU5ZTw==,type:str]
            users:
                gerard:
                    name:
                        first: ENC[AES256_GCM,data:+61/u1bo,iv:gVxcuTMYT1dSWSag6gpWw39iPZBRuNEXAXZMpemf2ys=,tag:F+AbbtFy51/jv50CeLUWxA==,type:str]
                        last: ENC[AES256_GCM,data:Tf9KikaCPpo=,iv:+Q5mNTuCn8hlao1yQ1+YtCy1sFCeDlH6iVVP3QPMVbo=,tag:iDrOtp/H3441ZzhXxJSoGA==,type:str]
                    email: ENC[AES256_GCM,data:n4/E4c8IzPUY27PCmgjKcYOfB2tW71y9,iv:TaHbq56+12b9Egms7tVAY7tJns7e3YJ5vX/Js5Zj6m8=,tag:PaP55QEBekRmVH+5/k1aHg==,type:str]
                    cli-config: ENC[AES256_GCM,data:v832xGQ=,iv:7Qowhcz5JpptV2O1d3RBSgURntjaI7q8NOE8iCTkHcQ=,tag:biVZNJi1wEP6WHFCxhNU5A==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:0WTlbYEfZPg=,iv:Mzdd+fj8VK0oRgMWWmkJ5erpBs8aGeDhzAOQS1Z5GPw=,tag:tHoNtL9dhQOP13AZBiIeLA==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:ei9sQGkTZ83THtjo,iv:8syioTrG7n5sG7KZDz4yL1mujUajsGZSMROHu5bSNW0=,tag:srD9AJo7F8sQ0AXQHYB4+w==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:ejNI6W3/GVM0nbhBy4N37A8ZKK9dMYe/+IUBY8driHqqrqporv2/aiYGTA==,iv:IN9ziYsbv2jlIrRp9APimChioUN01QzO0EeurxOvW7Q=,tag:8yhNn8wtTQLyVXvcSSTypg==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:LgmRKkKZM1im5h5s62i/ok8=,iv:dZ9dnB+KELC2aeDlLzr+SU1TzsJ16nzgXwqwE1m98lM=,tag:XCqsWkCBJmvtaDZDDIe+Fg==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:ra0c9EGTFa0YLxBv4qYCt+/5bPVQkZugbuXfJ0JdCrF9cAV1Rn5hQA==,iv:Uc8juQcOgJvIsEm+Ai6EG25poz/brnUtXblY8eTDUjQ=,tag:tO+ERRq4SCVo+qd2uOBz0w==,type:str]
                - ENC[AES256_GCM,data:J+lFJYuakuPxPst8n9pucb+j66akqxd1LiaTr8BdRYs5ZvaiPsj7rg==,iv:n7pB6WynluRT6hbklyPrvqWnm1zR2OuaOUt/a00c4RU=,tag:nojawG40BOV/+mrVl8V9pg==,type:str]
            roles:
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:euz3NJvsuqohO0Hn2X0BI+QM,iv:WYZcn9l3ExfC0MY/HDLKRlhAoYgfgn0sLoUvpiHhwgA=,tag:z5nGboXMHCWjL1kuq51FMg==,type:str]
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:ijjUojVPtUr9MtVJBTeDy+DZ9Yw+,iv:BH7lVDBrgzLnAZEximQXwZmZnFvW+mz3DqaTJY8st/0=,tag:3z005moGqHOFmTXjppWlJA==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:zx+WttMxl9/C3D0RLuhsuiIH7ywyqCX1N9KUyoPr,iv:irJQrgcg6sG5Yxz2XoUFhH04a7rMPgNMdWLSJon0yRQ=,tag:9d/0xR5a5yMh+eyck82L2Q==,type:str]
                        - ENC[AES256_GCM,data:j5qWz8e/WM9z+EP6m3Am,iv:GiI0NPC4jiDp8w+sl31oHd/QrU6N/peE27oU9pdSnE4=,tag:6sLW6mvRtS4aDT2Si4STtg==,type:str]
                        - ENC[AES256_GCM,data:V2e0ZLPwaYvVzuDLCQ==,iv:0HuxGvOV9SlDeVC7aoWWMSfIuSiH3DKE8mPY7ARVi2c=,tag:9VT+hf88RrHky8OQzYuL9w==,type:str]
    buckets:
        - ENC[AES256_GCM,data:RUUCwSapGGABAT/ecoUzuPY=,iv:BbZ7FXmuGlURviAPHL9Ku1WMMT/DwBlbK14ILd5fr/o=,tag:5t0CbUPkZBf2SrH/9rM8bQ==,type:str]
        - ENC[AES256_GCM,data:WKVCqgf+7T5IpvLL1WCEjs1FXpk=,iv:S/iIhEAzsE51xcGRqPo/5dgQ0ArSkk3JbLDtvEqU3Ks=,tag:SOrpWyrFlIS3As4Ya7UrTQ==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:qe7cK7DTFEEJ2MKJ7A==,iv:jwoqwkylhnBNANCtY9KisMpl1nBv7WSqpSFqhbZML2I=,tag:/KNMspu6LMOndre/lwG0tA==,type:str]
          description: ENC[AES256_GCM,data:nOjCWyNsJVEgLHdceg==,iv:2Lz1qpt1QYT/FyRxngSD5ve7DrtG3emrYoUp3lWLl6c=,tag:TZSejz2eCEXWc6jZUoRLHA==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:qTe0awZMURNfybzyYzAy,iv:RF5JVQZjVXxnEzGzfwlZWrJRzoAAfekIAmnuRZmOOOw=,tag:42deUowGP9Ozm75sX4C9zQ==,type:str]
        - name: ENC[AES256_GCM,data:JmpGkRBRhz2O8veQ,iv:tZg+rWL0Mvio2KH0P+5wi3Cu/jjoMsQeGs9CHpOF7iE=,tag:uSCFuIxnjFjSQFVZCEhQcw==,type:str]
          description: ENC[AES256_GCM,data:yWSMwd9N2Zhq0GwmySIB+tKPHnbrURAK,iv:HWegz9eJTZl5vaydVEZ7m2cjlAVTIrayKCg6kb0t1yk=,tag:pBik4LB2SjebI8vgZDXDCQ==,type:str]
          deletion_window: ENC[AES256_GCM,data:tA==,iv:7DKxOWFZKSdUDmsH5VQBgl9UODECPs82CwWqMcj6XdU=,tag:AF+AQwTalB9VcdUef1rAOQ==,type:int]
          key_usage: ENC[AES256_GCM,data:6m0YwQmR7MzoaTNxw17H,iv:Yq6Yfs4vn9juoUQwixNLi5J355GL8VSryxnuEBCkeK0=,tag:/5StzoBE2k8BTM/KMPSNMA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:V8giJTOORq9dnqI=,iv:apQpPKnNOZteVVYgDTNeZNteZndPW93i9U3BM5lh77s=,tag:v7mjJIbWSdH4Ushs4BocjQ==,type:str]
          limit: ENC[AES256_GCM,data:O9dUflYO2h0=,iv:gLVSPDJ3HKfBJe1lQ7ZvpDkZweIVv45WZbkDGTvLBkA=,tag:wcEAmsuaSviYj1j02/d6rQ==,type:str]
          notify: ENC[AES256_GCM,data:cYxmJexEVhRs0IiU57CDsbZtIN5lELN7,iv:b4lkEIVUKuaWi/SRGRH6bsYk5We+gfPGt5N0VjO2M4U=,tag:wHP+Ce6W6C1KYbRJnnIFYA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-02-11T09:14:00Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHHXDCzQn64l4jP/CfGuJpZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCL7jPC1r02CYECfNAgEQgDvCsxiWPHp5ufhbRPDeu6m8TB/uo02zU8FUIuL2oy8vUSTehHWo19nFm1BKZAvBVvLL2MC7fbcTEjdAzA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-11T09:14:23Z"
    mac: ENC[AES256_GCM,data:3W7U653r00cplAQw6vpzXFbeZNYs9G6cF/Fop0XcidyTmi6hlufHETc4+vLnCyOEP9f9Poufg3G/wEIH3zkKOKyVx7jGHtyfdr8lHno8cco7dFjk6Ja07cFjO4OL3BGY0mW17fPVH2NdjsV54fNKxus4eSsHQKZWud2/h3tJlZQ=,iv:eG3BgthYEHH3wSDobPh8F6xVGfqD9GVja4A2dFxrY18=,tag:tYfxb3+m4dSr/RKuR1r7Ww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
