aws:
    region: ENC[AES256_GCM,data:YYqNb3lr5/O1,iv:lZcIkE3Bn0wRKO69hfoOwNBRGe/W7Jgsxwdq6nQXhCU=,tag:7JVfYCvET4mSiqrZUZiZKw==,type:str]
    accounts:
        account_0:
            name: ENC[AES256_GCM,data:/aLVTgRdCgeCn/PXLQd6WOB1hPHX,iv:anAarS8co6n6gwWFpYBLOzOMw2r7cEkfqppZhElRxGc=,tag:OntyJ/lsYEd6eI5Etw6IBA==,type:str]
            id: ENC[AES256_GCM,data:aU6jHUSR9pzRbyoP,iv:N4QBHavS+/v2MdFGGQ9CcVrg5MvznVbGcSu8LDb4Ksg=,tag:pcMusN1Td4eOTz8W8Gnelg==,type:str]
        account_1:
            name: ENC[AES256_GCM,data:lxXkp9uIYjV8gQ==,iv:J3C6ABdwKffqH6ZrDAvt54HmR03ERCQtjynly7aSJ9I=,tag:FJmmaXkOh6HHt0sQGlXHHQ==,type:str]
            id: ENC[AES256_GCM,data:BRpH6Dhu8BqAVMhz,iv:q/yh+3gABZUMKUiKXMgpKhlG1mLD95kJV1W2J0jPR2s=,tag:6QAQKYkChPyedlicxuGYBw==,type:str]
        account_2:
            name: ENC[AES256_GCM,data:mnA2xeZxnvo=,iv:MvWvVZ2lZrparWALuXg2Lq6a+UtXfHHRjS7t7uWAc6w=,tag:NmJ3vIliXggnhqc6wf2R8Q==,type:str]
            id: ENC[AES256_GCM,data:vDaHGrbTEx1BOoRx,iv:LQPN0wuxSJdO/MpDk883aWyB5VcyQvK6+G7sK4oFWQM=,tag:l53EMC5kmjvPtdxlUVLo4g==,type:str]
        account_3:
            name: ENC[AES256_GCM,data:uGgd1CAR8XYVZQ==,iv:vPs5QqIkSteVFnHKsnAFsWoguUgyxO8xHVOLcjZa4yQ=,tag:Yu8XhTSFEg+Jc0uf4YzkFg==,type:str]
            id: ENC[AES256_GCM,data:jz6VZkKW12O4gAiC,iv:LD4gJzDP4/UbMFZnNNV8XyI3Qliu7dMncDE0PZozupM=,tag:YYG+qFAWfl2NqupHkBdClg==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:vXNtjW/KDud5cXunzLkcp3k=,iv:PTZbBWhzLByNmYs8/9rLYkWFbZyWRJgNHbCK1yP9VZc=,tag:Z/SsdQMQkvTzIXGASdSG5Q==,type:str]
    iam:
        machines:
            fluxcd:
                - actions:
                    - ENC[AES256_GCM,data:xMy3puKXgJlTol4=,iv:CzXMI5IOzDBZ/uRH9spkt2KxUdyBx54iw999m+I+UlM=,tag:2A2sUiCTSiVg5toXopNbow==,type:str]
                  resources:
                    - ENC[AES256_GCM,data:Kx0e8ytEhWgVGshi7J0DIijZzFAGjeHXri8JOklnymaVwDbMHoKDBZZp8bKgEtqElKXVyoQil7ETnZbLBrP2Esb03r6ZATp+4edn,iv:HyqxoIit9evO/bxk6MmfrbVeB4IluQ37Wjs/uyOyLRU=,tag:pC48o/OeeJLW0vpnw2Xv2A==,type:str]
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:n8D6C5+Jzx3cHyVFgYu/ssBWvLLe2nAhUSX5z5HV,iv:II1Dlxz+NiN+J3pBMNEljqOHC5aSb66LMaziptI9Z1E=,tag:+ursocFkurRlnHNNrT3OJw==,type:str]
                    - ENC[AES256_GCM,data:hquSAkI6GKVAeDgz67Qv,iv:P093TbZfkvJs0d0KArQyml03XU9oeqxOVDk/xq+9Rwo=,tag:X4WE5yq2B4LSSFkwbIDgyw==,type:str]
                    - ENC[AES256_GCM,data:j6Ot/9zxrKI/GhJo5A==,iv:odpq9EQWSjNKjcmyUb2glFykJoPik7ct9DnAjbJfJrg=,tag:hEegBLcq2FsMvu/kk5yuyw==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:kgv8ZMKcYLxbkvJy+A==,iv:+fv1eDj6UOWjNZGsWzJIFLwht89YSKmok9mwKXCPg+w=,tag:L/bE+97zlXmlH+h0/NZvjw==,type:str]
                    - ENC[AES256_GCM,data:QeixxqJgE99Swyzx+MQ=,iv:OMRODedRSLXaozC7yCsRm2tv1jsZYO3/1HDsL8kqkK8=,tag:/lJJcUtmc+SezPOWabZEDQ==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:USe5gV1vliHn7l7fVvoe2EkEs+JY60SnUIyaI341Z6mxlw==,iv:Nb2SyEGC8ZDfJgTyBFojMv/rC7zRRk/xdQFA0RIbOEc=,tag:gvqyQWjgzHHp9akarClXvg==,type:str]
                sso_role_name: ENC[AES256_GCM,data:635W64Rxy4mzkTG31Yq2BreU+pFRqA==,iv:xc4RwWmRtzTi4fhMMhN+reVZ31Z6TSgGvcpNgr+lJTM=,tag:C88KrrHRmK2JKxJjQmQVMA==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:o61ROHe1/pArsuxwIYFA1PTf6Q==,iv:jVnZBQOztrDEy6S08POtItscYEM6uu9KcLNXaTBUrh8=,tag:KvuFhJ2hCRosXcbIfXVhXQ==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:7YsrbEyZF3EmgCaFUgmG,iv:zwOqbwB/j9oB3D2vEoPQE3dfvN4xEngTPteAaQ79Too=,tag:ZsjFqKwBffCORByzLRH9bw==,type:str]
            users:
                user_1:
                    name:
                        first: ENC[AES256_GCM,data:D7/+dHuJ,iv:LWQEwvhRkQfuvBhgwrO0AUKeSo2IIwBCZnjvfvUBdk4=,tag:1g4ut+ONn+0Ui4v6yjhvvg==,type:str]
                        last: ENC[AES256_GCM,data:UjWEhnqasHU=,iv:w7FN+GJ3v9UEcIgY/2R8LNjesrsTSsF9UuTjK1nb/dA=,tag:tvNoKkBnVx3rCHFaMaaR+w==,type:str]
                    email: ENC[AES256_GCM,data:M0Z9Tm0xvac2O7YJ6IGv0F5DEsKaSYs/,iv:P7k4Qc+59Ahg4bNGR2ILcC/u5kDrG+md3eb1ZwAXvMg=,tag:L1MkxOuZwOOcdedN6fC8MA==,type:str]
                    cli-config: ENC[AES256_GCM,data:xVH++Q8=,iv:iHtIs4YHyj6Qtg8gI4qqu6JXLEzDEI6O9LJesp3m+fg=,tag:9+1oD78vworlra+fgsGuZw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:H/hJS03tWII=,iv:mzqrLi7IpGdPsGCmpXPikmJTBqcO27GGf7JcRhFAsN8=,tag:00rXvAOI8uwqa7euHgxPgQ==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:ItqwLdKVPZPRci3xOSQvULQiG38A,iv:LZsrN2odfkZ0qJK0K8xOIgPEiacHY6/MxwapUL+flvk=,tag:LAQMfYmmOtX/hYcY+F/mTw==,type:str]
                            - ENC[AES256_GCM,data:iqo5Mpw50Deh+A==,iv:Pdosw2OTd8HfGDMwjBVmpoAzpeOqJfWIpN4vaNILKJM=,tag:gUIdKCw7tFSYnadFXlgWxA==,type:str]
                            - ENC[AES256_GCM,data:Zntw1uSr7HU=,iv:G4j4/vyQeWd+/R6yJPhA8oq19OxehnmxWeK7omrhcmo=,tag:FCMj/J1xTgn9LEA8VPnB7w==,type:str]
                            - ENC[AES256_GCM,data:EFSqPbOWdHPQlg==,iv:l6fFLg9CMb3T84Omlxjv2sPw9xRNgkFGVUCevXbYMpk=,tag:5fp+Mxm6D5pYt+qa0yM/fQ==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:X7zP1y/wsVHnTLFVQd2pJtyEDkN6a7uuirWQxbU71xOBUcYodN8QlWHB9g==,iv:iDq+Cbgs/Dn0TJZ6EPd0LnVxwvdHrVIqqQ/gGTHPLfE=,tag:gjSpCFSmGp+uOZt+XCdZZg==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:PBKLvOsD+PjM+BQG9ELyFtc=,iv:wgQR/4oFF/v87cRu+c2GH3zpZ3+3tRhU2KWT8yl5xfg=,tag:nSeViNFbheNT3JO4zcspeg==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:djjWB8xQxg/eCZ+kpztUmonDR9+LiKNl/gD+F2BJcl91rkhp5KWbsQ==,iv:l6K8OvzFbRb4OW502hOdSZUICo30FdXmBiMVgNapwzw=,tag:ZnwseAmSMDOOeCqh33XiaA==,type:str]
                - ENC[AES256_GCM,data:6g6O3fdgFir7jkLxfEMSZUn2xM+IklEQWncYu6C0XBEJnRT/WiA1nQ==,iv:hxSueR6KETwfD81mBMn6DJEaKuM+VEO984yUdsNBMB0=,tag:oE44A3U8c9x+ZAg1vRyRhg==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:OO6Q1EmYg4FkBus2ANCkV2OwEk99,iv:dlwnGXPNZVQLUyNzrSSe2cXfyhZ67lVr//Opblaw8GM=,tag:pYEQc6+JQjGxpbIa5/AzcQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:rP3u72uT+ODithqkIZV9x9bL2m/be3wmpMnNPd2e,iv:v3LgOFDL4XPxKJryoSqs2H2cI5lk4WWKhQtKi70RJWo=,tag:RqIPkfeu1Y/6Alzzr+/xFQ==,type:str]
                        - ENC[AES256_GCM,data:t9cFhmnmaicDX+36loRh,iv:zuVThXCh0AggW+Da/sD1sNTBAKspPdqXvp3B01DM2pk=,tag:FB/ioDX7EUWxuw/xzMU+fg==,type:str]
                        - ENC[AES256_GCM,data:40BE52AAOYyR5aC/Ww==,iv:LwyP/CFW9Z9MOh7YOpCKVoM75YFqVeydb6FgByc34Fg=,tag:HzSxcS0JWkc0JKJVMH1Xmg==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:lgZZGe9J4cjkcpUosmljIakN,iv:itOL0zoDIKX5VSvrPcZ/4rs3nlJfsyPQTpoTYx3Hi80=,tag:/NN9xfteM/UVaXKVSaMA/g==,type:str]
                        - ENC[AES256_GCM,data:YvkBx/NyXKbBMtRUg+VPEXqq1w==,iv:Ll8opN5jZvcsnLkSq2YlseBudTzXHzsXETVYTuUPIVM=,tag:+bHNykXByte+Ai/JO0TfgQ==,type:str]
                        - ENC[AES256_GCM,data:rGgmf+2OpJTXr6aQ5bHirB+O4XiFIw==,iv:FQr8qQrKJ6IFWn/0TANZCLOdX7dukXmrVM5m10pvBR8=,tag:435l5jSv19qIB6VVUjxj5w==,type:str]
                        - ENC[AES256_GCM,data:25RavC/fu92lqsU4cSSkFo5QiH5LlSM=,iv:99HkrgzkvIjNSje5z+KP/sjhhmpYYLGKdwcRniYM+0c=,tag:IPJCAh2J7EJHPLNnVfC7Qw==,type:str]
                        - ENC[AES256_GCM,data:8l+9TV46unLFjgfiHQnY6uy/wb4Y,iv:PmR/Jcu+QvGwV+9aRgQODxu+6hFuLBzhZ+rN5nVcjdc=,tag:Rxo7SneNccKdX2gBEkUEJw==,type:str]
    buckets:
        - ENC[AES256_GCM,data:QG07RuhOfhPxGP/98+tVAJ3o,iv:4gkjqCrjpfg9BOOiTW/G6Vu1nksDPJcwVYuEK+cYfbo=,tag:KRWQeP1mTpnMaWYdJOcsEw==,type:str]
        - ENC[AES256_GCM,data:U5wPt42QKI8C5HwtOxP1bnA=,iv:T2ddYkaDjGoiQsI/eVnjxvs7Niu9qC8P0MvrXP0yZeE=,tag:PP/lQ5RwknEN0LvcWC9dKg==,type:str]
        - ENC[AES256_GCM,data:mbMrjbSD7FvqiGKJkWFHEtp7CzAQ9bZYjA==,iv:ec1gdYxJiv0joXIGhCjcd0aKt/ebHRHh/Y54ayOVIh0=,tag:D2NRvpQaBUb5DHMEIs20Jg==,type:str]
        - ENC[AES256_GCM,data:LnG96F9fnZdQkP4wN+qNrz99E4kcLd+/bPcMcqk=,iv:vnc67z8TB88DkhRHny6dykAzJIxLYtv8UaatujjOgrE=,tag:Lhu9ZOk8/0tcA7Pxo5fG+g==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:Fzoa6A0MWB5shOTRcg==,iv:teIriCc9nVpC2adW4V+WFoXRRNWaBlkzkoao5vnOCVE=,tag:lHwPYhIjqc7fVKTqNl/Kkg==,type:str]
          description: ENC[AES256_GCM,data:mAhijZN7rvAkIHI5+A==,iv:mBNyhczQGLDfajUvSFwJ8KKZcV43InAE8vo79aL/hyc=,tag:Z58EO33dnAvdYTsXxsBVqQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:3XRyRsgOZKdMvQlE28DO,iv:N9AnlO/MWsdm7qdg4vRqWI+U/kZy0fv7HV65YO9MYQk=,tag:Si077I4tsFA5IFlWxMfdEg==,type:str]
          extra_policy:
            - id: ENC[AES256_GCM,data:2H59g27wV7bqLSwhf7+QRPlxEPGMQsjWLN673GNkIY8A3oM=,iv:8cvC0zUQavfbWTmqnLogXwbIDGJN8OupHpEAaecPMVw=,tag:atm7ctj6kH9/CpW/Vo727w==,type:str]
              principals:
                type: ENC[AES256_GCM,data:uacD,iv:3uC/2d+ki53ZpqeEGb9jN2D+rCfArcIW1L9UJ1q/WME=,tag:Rnkacg7Av82jIpZ0O9edlA==,type:str]
                identifiers:
                    - ENC[AES256_GCM,data:1xbtjyvKh0WwaCELfYDsQHANdOscIzX+3JJtQfs0g/A3oS6UVUxpaNhtUJMf,iv:5QEspqYpBNavY8BlMlTyp4zdd3zBNUAYIIkXgChd4pc=,tag:YuH9aEvR5bOLpbbWd4FnLg==,type:str]
                    - ENC[AES256_GCM,data:I3NgiMjp7ugeYU+6fXHa+0g76MMSivkafHEOuvVmfLergfhfDeO6YNoPUyB+ys1tPzsE,iv:mrxfrMPHw7eQsKfCItEWE78Ms7XV3Fade2Am3WPa1Po=,tag:nfsTo7/pJ0yeKBzBn5tmzA==,type:str]
                    - ENC[AES256_GCM,data:7wpdk8Px2VPHWZOtkUXDnbmXUVc/EK9PLenWX1Txmx5rekdEL694uLZiuAdk,iv:TDe9JCfae2bZpX2RWt5S8wpVA2Z02Bw8riKVk8sGTkA=,tag:PNOacmNInygZUrrAMMp4iA==,type:str]
                    - ENC[AES256_GCM,data:AsEzu6lRx3pJHQLHspcivSAsVp9hPxF7/kVhmo6NBorgcTHFK/cKA+Zu9iFdfpmPK47Q,iv:Kep4CAsCN+O7edFeYyAW9uk7RwTaw1WM5xj5FUlr6Yk=,tag:sTgXG6MiMPEus6Mn4BNplw==,type:str]
        - name: ENC[AES256_GCM,data:aoWI66vvHbw=,iv:IAOtv3cnSJKLvUHwNLvGZS0anyAaelUN7Ugoon2n0SM=,tag:OkTkdczyRmr72seki/stbA==,type:str]
          description: ENC[AES256_GCM,data:ogetV9lUSMsVwFkl2j4xQveP6r5netVofhZs16FbQKuU,iv:2c8PsxPHKPdBh0UzDZePSzartyM7x9yLWOdNub76lyI=,tag:6CTrfzxgKg/T9QZY+ZdeTw==,type:str]
          deletion_window: ENC[AES256_GCM,data:mA==,iv:RZm4qlgenjQqCOQEJn4hRz/paNQXe/AO6I9x9KcrHl8=,tag:EVIsdX0OGBAPyosso3bg6A==,type:int]
          key_usage: ENC[AES256_GCM,data:TMuUoWY7uEIWgTqU8urK,iv:bkGJwxk8QugKitcRWfomjbVzO6FkyKDQvQ+IRzhIklY=,tag:9MEk4B1qbjCpLA+wxKc/RA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:n2frRYFRVu383Jk=,iv:AzisNjO1lFVjX7Y4Muwk2SfmJrQrgZD2QXn17VRRApM=,tag:cqvGNyQIQMe3dKVLw01dzA==,type:str]
          limit: ENC[AES256_GCM,data:GOsLAe9BSYA=,iv:+KlZ4jJhNaZOA6YP7CqFCB23KAX7Dl5dnlTmcOmRVzU=,tag:6NcFZkmbMLjzq1ufjYepeA==,type:str]
          notify: ENC[AES256_GCM,data:CCLVIrfHhubbrxCTCo53aCm8o89OomEL,iv:+YBboBzCuS0YhshG0mQiQtZjMbXIMqmxlvUw0NnzIw8=,tag:BHsNK19+HQh+yfbU2+yy/w==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-06-14T16:48:16Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgG8ps/nLZIadPPEluBFpIP6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0p7H/bzU5HSiqnQxAgEQgDuRjEcgadB59Y6YE75rervF6cT0SZTp2+YzRPHak1/h/I1ekL6V5bdtRLXsZ9i9Y4DUl4N3WYBVpfWuJg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-14T16:48:17Z"
    mac: ENC[AES256_GCM,data:MtWrQvKm/HkATkWVdINedQYRz01JG/N5qtxt/wXhOH41aHDw2SxbuLxcW4EjxqS2L/0ckgiaFogmI1rgZ0X+0HMCMPJfcVIsnQHuOrlpWSIsFW4vxra+CKrnmF/5OJJswMVJqpMOa30QbkBzSvUBKwN9QiEF/TXLdoy5dG2Nc2o=,iv:HWHfPy4bZTQPKzv3E73/DMtTOWnEzBUmOEtZBdrqqDE=,tag:q5+iWQtb8Y4Tjq9X9nciTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
