aws:
    region: ENC[AES256_GCM,data:3mrkEg7Lwso6,iv:ETed18kZrKqwbNSnEcICZsxHJLaxBA0DBPewTCfGfc8=,tag:4s7dqaR00Ty6rD/a8hv5KA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:aCJop0c+irY2BG8FekSMp7+PwifNLWqwIBQc01v1,iv:0+dvZTuyaM96gfhpgtBp6bBlO0OB4IiBD3Jv2+jjnHc=,tag:KVjGz4KyjkJbJzxwh8ye6g==,type:str]
                    - ENC[AES256_GCM,data:3+ksmI0KaTjv7HzM/qbZ,iv:381UdzS26lH7iAYrl/eCAEpGtG/nNTsck3RqWFvHsGw=,tag:yMxbsteFQKGMKZZ03CYEcA==,type:str]
                    - ENC[AES256_GCM,data:aVmDDMN7qqxaDfN51w==,iv:7lkUb+O/u/bcHH2zjIHuF4KJE0NvR7rlD9d9fqNdYSU=,tag:r3L8zcTet5x3IyZnclsnWQ==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:7nvFxsUGgxx0qGxc+A==,iv:DL26+ZrjGGrNZhU3D9q935CsN9oNRUriESPIHeQ9o1c=,tag:9J2uL82J5Ec4wmKFOau+BQ==,type:str]
                    - ENC[AES256_GCM,data:+mZfLvcUaL3/LOQo4qw=,iv:59dIz0qlIQOtVNCKKiQZKA+zRW9Aam+Emv/4/8akEKA=,tag:i/EgRya0le5giN33TBZKvA==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:J9viYZE+wblPXSLWXooRZ1kpX4HM9LFTCiVXDaCTfBf0FD7EvM9BeVp0og==,iv:VkgSwPnQZ1FLFDxR9862yAV7fjkb2yUB1LilLU0kfOM=,tag:Judpndja6z0791DT6AdxaA==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:cWFCluhjvhaicDpGskzhhLY=,iv:RgdVr3IH1wAnu9cCSZDkxwsRzgV2lTBN4RLjvCycuuo=,tag:KSg528bQXeVt9MtS4JHk5w==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:Bql9yESUL6tijX2xurcY5NcGTyo6anowTBrpniPbR8Ygp3uigFlh1g==,iv:CBStkAq+Qsqj91oRGoYZJNBYvao2xWG50omooSGczB8=,tag:4QuwNE19+yfYiqiSkofFmQ==,type:str]
                - ENC[AES256_GCM,data:gYxm3utNe9pHE+LvQRWV8cQENGl3e+iL4yhriOYU3oDDVO1ndtRrPw==,iv:BRdNvZGEWe5QO/pL0jg4+M3WLDSJqFgjkQM2SC7WUqo=,tag:svgSeNRIY0GU5gln/6OZBw==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:n9UvNWMBUPplSMDN1oFBPev5aKAM,iv:WG83i7yOHYQclD0MDzp+/Y+c/OdozN4WCnHkFkY1BI0=,tag:1DtnIdPSzHw5XbbYU7A/QQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:jwplmk6a4gg4ud+mq9e2dO+DuajncydnWi6MPD/i,iv:Hcv/TyOqb4D0ravCMO3HUv25PCcOy8FYmczkx27W5sk=,tag:gIwzfGm3G1Njq/zwHCm99Q==,type:str]
                        - ENC[AES256_GCM,data:+nRNnFfVssAOsvKxw55d,iv:fKHJBUhvJY9xDC0eNmooulrmBq9hLpv+t0ghjAzf64A=,tag:Wu7y6i/5pLxvUZ7DqHgAGA==,type:str]
                        - ENC[AES256_GCM,data:kQLMWmqqRJH4bv7lUA==,iv:L0XlebuWpXDB3wXtmnGY1Fvrtxo/JXckcOAilmj+Uvs=,tag:QjgoGyU1S+thuEYttucCAQ==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:gxQhEi+bGdqWa5r4v3iZioS9cw==,iv:uSsrmRBlBnEbeWMjjaPTwsIPf7B5NYKvufiemIdXGAQ=,tag:XsW7DteC9zcFWSejSb7XcA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:948n6t4QtyTYNKV7tMXVnGWGxiXR,iv:+jHyMFq12GvGNqMJ+EitnyMEqUbGY8Im+YrCSFpYBWE=,tag:eYmTIeYKv149cxqTsDNURA==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-06-13T15:05:36Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHYhsdVV20xuiITI2rbTY37AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMS/9Z58w/2y52xnIDAgEQgDtvrft8zJS7yC+XDP3asDco/cpL7Yb/bfJyWX7QraHzFdcba040jgSoB2GOqdURbePg2MXZSrHX0+vRtw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-13T15:05:37Z"
    mac: ENC[AES256_GCM,data:+qfxgvKRIxyuUCTibOBuj71szjX0AU8PoCE0bPfZRl1HBpMSjst3p6p6GbKy4ksOrdzUeEX3SNRp5ZwdLQyb3gO7J3+zPJkBMFYqfpXB0JfBvW4i9MXZqT28kajSGcLC7COO4Dngl2aSqGw1T0ZJu5KMMp9vJEu+edwc+VipW0I=,iv:zbkNP5KTWPIMCqQPjzdaxdeDmzPGn9faVrHw8+yPcYw=,tag:m34RObQOZsPHihAoaxHcFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
