aws:
    region: ENC[AES256_GCM,data:QcU8Paw7fjx3,iv:bEAi6Sx7v6JGSnnIK3LNzaHBWCUXlLeXv6T9aKt4b4Y=,tag:5rm/QltoKVltdtUDhsbrdg==,type:str]
    accounts:
        account_0:
            name: ENC[AES256_GCM,data:cEysDpNriMj4KeyZSzfET072tbIe,iv:f1N+hgXPFwJeOsakrIhYzZNc6ghhenP21cQVKaJ9gOo=,tag:EyBoR7Hrwyqy08ZDXo19Wg==,type:str]
            id: ENC[AES256_GCM,data:mh8ALhOLV3MEvqs2,iv:Q/X/xZP0KQ1U8y1ghGFM/AW268VSU4d9NFTskX5QIv4=,tag:iKaESn4qD5FQv3VrM8wBTA==,type:str]
        account_1:
            name: ENC[AES256_GCM,data:pqAkSuNPDlxmbw==,iv:Bj5BjMwJuJvT4a3IyOM+5pv1owY1KYhxV3NzKG53Md4=,tag:XHy/KJINVSfr0CNV85JxBA==,type:str]
            id: ENC[AES256_GCM,data:9C3La3bTWcuyxtuA,iv:VwS88qnTUMAhmyUjkPZ8DBtcwm3FLJVDHeBGEuIOibk=,tag:HPEWKzRtTsgJXOpVYSy5aQ==,type:str]
        account_2:
            name: ENC[AES256_GCM,data:T8ysVpozCOM=,iv:bv4urUHm3s8rE4ZnRN5aFL5M9vHlUCmaC0TPYoRj3vQ=,tag:jDuAMhJaWTvuw9N2eqbwFQ==,type:str]
            id: ENC[AES256_GCM,data:uIyIWKV2naqSfryA,iv:HZdD/my4/5Aeb9ll+7sKvEFJfYzCKxKoDYgZo8aB6DU=,tag:qoNmijUdMrk+yyFnKpwXeA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:t+DURkrtuiMhYPjYbEsNk4Y=,iv:In4kHy65+ul/pyxxv6ZXANAdCOFd9HwxRCt1VdQ+2yo=,tag:MUimjYyauH17xxW61oE8Tw==,type:str]
    iam:
        machines:
            fluxcd:
                - actions:
                    - ENC[AES256_GCM,data:sOwBpYoMElMikQk=,iv:sKcdOfgh6lkoOuBFAXTmumSMa7vN4LgFfF5aN8Dwq2Q=,tag:K0pAFBSVxZ4D7RhdKQlBxg==,type:str]
                  resources:
                    - ENC[AES256_GCM,data:JQ==,iv:bqnFAA6/tGcpJXgVKLAvrEQmhVRDM6Y687f97D2QE5g=,tag:fZt9RwNHrCXL6u8Rjozg5w==,type:str]
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:ycbZR3akQAB7IUGGt6ApFNZo7IatpoKsePagkz0m,iv:TJHnnjvyZnP3AF0qthiqSccxc9W6IoHmuI0S81PLPzE=,tag:KamfxpOVmX2bFtqOu8Nfsg==,type:str]
                    - ENC[AES256_GCM,data:SYJh9kv52GoHmvxNi9d3,iv:IR4ZLEg7ySu0IUbWj+R2eAwB+dzIYGrBQc1/mwkVGxg=,tag:ej0Oc82KsU7NhiEdcRJN8w==,type:str]
                    - ENC[AES256_GCM,data:iFPYf/FWM3LMMFEBLQ==,iv:ZljKtPWQTkuMaBK9i0ddJqFnW4g05PD2MCVzWwmCWuI=,tag:EiYDAk8G3VDNjM2A0ozBUA==,type:str]
                allowed:
                    roles:
                        - ENC[AES256_GCM,data:b2b4B9mDgXoFP2rCpw==,iv:XlkW1LMhFVPiUOpr38ij9/CcHMjln+GT7HuydcLOV68=,tag:DiA1dbsFiz1weqeHZxaCWw==,type:str]
                        - ENC[AES256_GCM,data:0XFH06fy2dFczF4m2CQ=,iv:e0baCCTqX6i7G8SvrE6UPP4fdpC7ylIZ5A3bB35V4JY=,tag:vVZDwXMrJq33ybgTa8P6bQ==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:q+/L03zQ9MITVtw1XwEgkxm40qAbCweFCAs8eLoe0AibnQ==,iv:2glrsv/hc70JfNfpMpQcniY/KPJf6SPgfYXQzcYiXTA=,tag:/4SUFQNWomztuoIwSuQoWg==,type:str]
                sso_role_name: ENC[AES256_GCM,data:tHoSuNqfUNoUtHJplmBLfZdBRlyPaA==,iv:IH9Iy1fl0ecQF6vBZaZx19cxc9PC8/E4opumVD876S8=,tag:9ZBcCK8zkm36w4FvDYHuow==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:9gVKE15pZpPOWV7TjqgTHtZh4Q==,iv:b2gbTa/XA4xv6hGQhyM4gSztEIhUM00XUU2GoOLife0=,tag:ZxWa4d3CSDK3zrAiqZFQdA==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:LHcPtL1PheyHcZz1a+rT,iv:nyba/ppku+vpgVbAZPJMR17Duj1D3rf13L3FwYn9BKQ=,tag:UjnUg85Te689rmx1xb6vUQ==,type:str]
            users:
                user_1:
                    name:
                        first: ENC[AES256_GCM,data:K+0ys5ry,iv:ADb1F5zhL6mwLfje3pZdEx1qPHfLv8OWOJWi9YPONSY=,tag:BmBHGa35CkwxjhdOHRzhfg==,type:str]
                        last: ENC[AES256_GCM,data:gUNvAm1+9FE=,iv:yI4nMuRzRxGFhO41pFHRGWjXksTGBb0d0hX0+rxQ7rs=,tag:CyriKyfb3v9/kqZHbieUxA==,type:str]
                    email: ENC[AES256_GCM,data:zfwDAgFYNgKulMEWfFHJHx6BinLoFwb/,iv:u23w0xovmnjTP176jr7IB+/+pwzLczvoRmRcPMzac+A=,tag:tt5RXi7HJEWaMvgR5lB8YA==,type:str]
                    cli-config: ENC[AES256_GCM,data:k0pyuaY=,iv:tXWkw/icQtdkvHbkeWjFRryeEE2rZK49KvRuBxdThOQ=,tag:T/ahLuvmumiisBLNTn4+Rw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:LgsWKcbHz9g=,iv:ByDcLdSwiKMzSle3u3KACBzCgZr0GY6S1wkGZ5ioGcM=,tag:JQ73Rvw1IU+pW6+4cPhh4w==,type:str]
                user_2:
                    name:
                        first: ENC[AES256_GCM,data:8OP9,iv:YR05Exhnt1k1HpOKqMBRlNhSkh9SDgS/wpanSMF4ZgM=,tag:qVRJugddsCNE5G/LkxVk0Q==,type:str]
                        last: ENC[AES256_GCM,data:9Vxd4Pw04w==,iv:YWJnO63KrVfBv/hUhxyfFob4zpblH1Y1Wysf2PletX8=,tag:53Dg9FA1bTqoQVFb80H9dg==,type:str]
                    email: ENC[AES256_GCM,data:eHBNA8J7z18R7MEvVnYCcNNiQhklFgI=,iv:IPkp1WnWeq7ZXUwyuYzSXWQYBRCuou78qJb3+wkg8AE=,tag:2KWk5tFUtvSnBoVkU6AvCg==,type:str]
                    cli-config: ENC[AES256_GCM,data:QXdmQFc=,iv:cLQZ9kj+BG8s8Okr+clf84QUdLyNrtINkq5CW9PhFs4=,tag:4iW2NIxjAAo9NxRZQ0UQSA==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:fp6rMn/nIe9PSw==,iv:sFYCxi3rWP5gdNd0L1j8ye3RMqGykaLWesKwmpHrRMk=,tag:vX9eDxmokXWmNZVl+UhXPw==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:jdcdcs/TToOlM4JqvMoHz23Ff9x9,iv:2o0GkP6HnOnmnr3bpJYJGPR/k6PtxKH6Orq3zZncVgQ=,tag:aStHM5cA1tFmTseZd94u1g==,type:str]
                            - ENC[AES256_GCM,data:YU/bmP9OqlaAFg==,iv:aEXUaFqMJGcn4/9ecdd/E0tU+kWszzgQ/8eiyQzz0MQ=,tag:31QSDfnN3azLM2Md5dX8Tg==,type:str]
                            - ENC[AES256_GCM,data:R9m7WT4F+OM=,iv:c1R+mt8k9o1YPZwnT0eQF82v8rgESNwAwSXsx4BsXMQ=,tag:VyLim0q6J6PejlSpjKHj6Q==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:zITps+AtecfaS8RZ1WeVr7xu6CIsRJq+ttPRS9QH9oJFKiAeyeYvfsC7YA==,iv:ItpUEzuBkw0Kh4zxJa+bnZCyR2O+ZEA9xhfEpYABbuc=,tag:JpXWv60jOGDvAbFsiQmlSg==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:UJYUt5SdLN4k2A34yjnoxbo=,iv:ncaPkyGTF6LreRQiPShWjaWy0ZTwxMoQECm8g6jX8h0=,tag:DDWmuimq5EKh6f+GT0UWgQ==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:HVcoQfF5QHhN8Nztx8x7lLtpV2U8PnlgJL4EuUPT+wux2Cjkpqb9Gw==,iv:C5lMLWK6/O+u1Pr4KaGSW3UXcNh02lg8ltxvw4fUCXk=,tag:Uc/e3A3Y19lHw3DmwgK6tQ==,type:str]
                - ENC[AES256_GCM,data:d8JBSdOpn/F4VrWgqF9qcXCU+9kgNDZmoZHeHmMIPeOxaxDRXYhEQw==,iv:OOWW6/u1tDc4MR2hjb+YcdWU98o4r47MWPupMj7qmEs=,tag:OrA8Svqh26z9vTi0+eAdWw==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:sev+56WfzM3kfVcLB2s3EOA+voCz,iv:V36Yv07jJxE0a3Q2jWRAelG8c0PdHei7DfhzSb/D+14=,tag:CLSFcOPnncdDF9Br3qR8TQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:3Clm8l3mCTxEknDUHWa3NtbofGQfpezijOxsU3vy,iv:lTlrymx2JuJWK2mwyIDbcQlTCM+6XvSP8dMNQNDfVkA=,tag:ij3ps94QL26JnFBrnpgHTg==,type:str]
                        - ENC[AES256_GCM,data:NF7dgqTKx1o6BpbOu8hk,iv:/LJAW/v8eNdUFs9cyPWL+IYpjpYhdWrZHYrFupaAIVU=,tag:htzIoPnPv2cl55SjbO6dhA==,type:str]
                        - ENC[AES256_GCM,data:kc2ccoVKPCO25/NbNQ==,iv:eq8nfWdoYCo+q3tUuvFggrsF5Eh99HiGCESGKUGVIo8=,tag:Gn70tElxFxSUIkVtBpmIuA==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:L6ys0Ww1uaNF48V7VBho33hJ,iv:FZI0jlx1e1JfxkVflFkf/GWElcigqpBwX9iBbo1fUZ4=,tag:dckHhilivhNdep96CUasMw==,type:str]
                        - ENC[AES256_GCM,data:kh2skF38Ru/NHwzZUqP9UUuT7w==,iv:ufc2bR7vLF5CkE+8QYCa1YOYNgIkSvvsT5H2klRlyJc=,tag:Ly7FgXmRXCY34EWUODXjSg==,type:str]
                        - ENC[AES256_GCM,data:r/5rC695xPKtLQbXsflKtjjCpKR68w==,iv:+4xS83Qxivbmd07oUJ1L9Ezpc5tD/PHtyKGD87zNfeE=,tag:oNLQDdWRHJ9XcS6uB2zh3w==,type:str]
                        - ENC[AES256_GCM,data:1W2UOvFwPvyj68zuo0mgKn7AsjiSgr8=,iv:PN4atVaixwRN7VwmqqQ1HgRX3zmd7rl360TFuq6T0MQ=,tag:bZ3kTiQsslcc7gdGQzEvrA==,type:str]
                        - ENC[AES256_GCM,data:aUdEZ94WjkBU7QPLd4TXu87WmuHQ,iv:SulMGDUm3Ir7GC/vZw3ABwvxXh98k8ar7ASyoaStHZM=,tag:vL73xPiOR0HrpfwBGsbUug==,type:str]
    buckets:
        - ENC[AES256_GCM,data:zLu4gCnZDFcmSJVaY/aW0Tqr,iv:p9fhaEY2oJis73+fdvu9XjEEJrIf+vojFREw3ettx2o=,tag:/Qq+WUVPsNr/qY3H3IIRFQ==,type:str]
        - ENC[AES256_GCM,data:U26Vy4e/mk/PeYEKMLDR/NA=,iv:KD/rc1ggxO6rs5XekeuM0li1YZYEuYIvse00COHA84g=,tag:C/uTm2JQZ7dSMlfOuCkDiw==,type:str]
        - ENC[AES256_GCM,data:K036KzYS9OKp9ZXeksa72ALIBCKzc0KhFw==,iv:jw1FewF8G8nAMLeO13zTFWx03RGUxbYNiGRqHKcTF8o=,tag:eW1OxE9StAcMCLIK5xLW3Q==,type:str]
        - ENC[AES256_GCM,data:PuAa6EKL8Db6D4feFuQRDYto4bvxo3DypGocRUI=,iv:Zlwap9ahvIaW3Z/l4QC7dzY4pKL+oi+LiTU6ibOKHb8=,tag:WSVM3k+lz07PK7TIGPEh5w==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:DXbc/Lm/sVO3Un2XCg==,iv:Tiqfj2zc5ZFTAfsUNWRHpxI4MieAHt4eD5S4t/nWFKY=,tag:zUzGaCmUUmK36xQ49OSHYA==,type:str]
          description: ENC[AES256_GCM,data:2Sl/mq7tYyIt1OhW5A==,iv:I+oSd7B5kfXoPXcEVEKFXxEMi7F25B1QliA9yRJszwo=,tag:AzXdVcBaU8Y3sluEUSRgyQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:WAvFOM7N9aYLezu70Mc7,iv:e12B/zFKoNWSaEb2Mp9ysr6oqvb6YB8S7Reh4WX5t78=,tag:thRhNqGS8loNDkZ0Du9/oA==,type:str]
          extra_policy:
            - id: ENC[AES256_GCM,data:dgw0+EGZTHYxVSLp9Erk1iy4DRX3GgPCM5ovaX48ELZxbv8=,iv:sluDHDmnbxOLJUoMjSp4YF/FJJXf/OgHoArUNwHZ+Ak=,tag:pgdRH8E52Pa3Hvyk5stnIw==,type:str]
              principals:
                type: ENC[AES256_GCM,data:5NSo,iv:iDBAwRhg6o6KDmVa5N17Pl05NFB6m/WC9P57eyORcoA=,tag:ks6qdmosxxxWeCY0Tb30Ag==,type:str]
                identifiers:
                    - ENC[AES256_GCM,data:RcmMgUwXbALuxP5cEReBv00tehPcNfwc2XQCAzkxTIKPyUWrfOK22hZi9QOW,iv:ogkvvNrSVxcrtIG2Qziz1EO8cGmERL0MCLxQcEnF9/g=,tag:f0nqLdmg3i52Nqq5iJDBcw==,type:str]
                    - ENC[AES256_GCM,data:xaB7NukGnQCqxlC5VupRKQkVyAeDqdGMU51aP9MHGzUiPORdY7/blJ+cTaWhXAO8xVri,iv:v3pm04N83ZUcSxr88DKTnn7r4pa+fLJG7jrrYZp7v2A=,tag:XleqgQHEzmC17jyivjJ5oA==,type:str]
        - name: ENC[AES256_GCM,data:I3BfqvAo28A=,iv:cmx9EfpP6bkcnXDUdOHumICWlwtdAitQjE+LDlLHkws=,tag:/CROqkva6xArtK3BmzCz8A==,type:str]
          description: ENC[AES256_GCM,data:XFttEICMAHSPoVEXlbluPzSxucJY8vr8/05nG0kRcTmX,iv:B7SIVjxfhejZQiVb6dv2Qa9z4paoTWrbD1JBeF70VrA=,tag:UBzqpyGIFEVnSSeceqiXag==,type:str]
          deletion_window: ENC[AES256_GCM,data:MQ==,iv:eKoBT+9ayW+k0bKZvRceTfc5CR+9PSb3YJLM2kAqJng=,tag:gehDt05rq3buycXgmomaug==,type:int]
          key_usage: ENC[AES256_GCM,data:Qn/0abqYQUS/7r8FDDp5,iv:5HkAHTwNLfqyxlVNnt0pL5tJzCwOr3uyuOWUUa2l1T8=,tag:yvnWlV/K23B9/mO/LYbMBQ==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:fMo0/PZsLXidUdg=,iv:2ApHmz8q5gA1JhPBFwCWKVtp6MQZn1+BSYqvRNRbef0=,tag:mpdeheXGyDuW9U+op0MkOw==,type:str]
          limit: ENC[AES256_GCM,data:KX/Py/Mx+Kk=,iv:6wmunCF6OuwV4lq3gRoLcl9O0IH/3lBOHgW1rJ51eak=,tag:3wDJjM1h/Kaosip2NPoNXA==,type:str]
          notify: ENC[AES256_GCM,data:s6ZQEBEoJgzs5yKYNPaSBDh+GdFgC4m6,iv:xa6k2xpd1AewYSFqdtlOzLj56DAh6yr0tx+9fSixJwI=,tag:EfROGgx0e8zW9xJKM3XWVQ==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-05-09T18:59:57Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGISRq/3/425zF0YIUlXG7BAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdqZudYO1TM93XOCRAgEQgDu1jPsmoHNDOsAr8QMlzV25pwhtGGXa/HbXhTJW8YCSONxFJVbJQGAAbakJkqLS0pY3n1tOGDZEELkN8Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-09T19:00:03Z"
    mac: ENC[AES256_GCM,data:KGknLDLaUhRzxzAjmgAy4yyuhjRCEje/eVGzJhKfeOFOxXdXzzzXQfhBAu+8hckt1HxOGzs4E1ezsFv92D1OoFOuTTBzQGLb0rdgm7Cqe3CXWKlFblVa5HDpSul/0Vh4m6jRVTVYQD/IdF5kzbNFvrJGqag0Mcau0Z0qeCTtc5o=,iv:XVxC7c/kPiaGu3fq0HLP1nKEqE/H/ilA4wbu5oQmOrg=,tag:p/mFbBpDYlLCA7FDDcy4Sw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
