aws:
    region: ENC[AES256_GCM,data:AnEtEOsBv8tl,iv:aN0wBSsXuDz/tUGwdaSejZt1MXN4yr8MKCWqqSVWf2M=,tag:HqkYpWEZIhx5UIRkVSUUjA==,type:str]
    buckets:
        - ENC[AES256_GCM,data:ih9vePnLSOrevFl7vjBitMRm3yB+,iv:t9t/MNKZtQUZWuWN6tRIBO+89FdHOyvb7+CepVWNpMc=,tag:IlnSUQ0MaktyW1jQfxnDAg==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-06-13T15:05:37Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHVEAr1vx9CF1r/AEILNxBQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsIXJk9VtalhgpPTWAgEQgDtEPopwN9QMlXKAyhmQhk2QWBNI6GJ3pHYknTe1dYh5HOadyZ+D66QmoQQjVAEZ1QeUVpePpS23akHSgA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-13T15:05:38Z"
    mac: ENC[AES256_GCM,data:fVPwA+J+G3voDJbSxBrqY3KQKe63b+iPwas/jwEAqT4VJKDsjUD5E9M4yg2uigicILRTwU8Jgtbl3b+ohBZCS3Sre2HTcnngnaFAsDhet8k8wCp3neOIx2dbPQe5T/w5IrbYXLpg+HNBdpRGHRu3IvtAAF2HvaqVqTSYXORm7OU=,iv:zttAhPjwwJMCPfs/bpex/vIGEQEmz0aX9V4p3g/xWZs=,tag:EJwwJVvJix6/YWb9o2jvVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
