aws:
    region: ENC[AES256_GCM,data:rjbwSjpmrGb8,iv:RJNTNUFXH9ujzyEh/H4phfz0LvkFpd6+JY7EtS8Yr48=,tag:1GG3JRqFIRbpQVZjNRYOZw==,type:str]
    accounts:
        account_0:
            name: ENC[AES256_GCM,data:YVxqB3eha/F2v42qI+H34gv+V3qG,iv:lf37KTgnsEow94HlpqHWJ+5uT/NQo/QwpXtgJOUp6Ec=,tag:IKmoc8ml50UJYDajHBuRUA==,type:str]
            id: ENC[AES256_GCM,data:7Xm4WM6uL7owyNM8,iv:SK+wGqL+mlJU8TIm0HU2I4+VzkPMeMZdt6xdnqyDDIY=,tag:Tzx866fFrdecmjSe6B1bjw==,type:str]
        account_1:
            name: ENC[AES256_GCM,data:Fl8AnAnTU+vdzg==,iv:zaC55JsUmnzvKW3HKJQpeg0p2B95d1U9Qh/x7voiN5A=,tag:FSzUL5pC8ta4OK/ABzN6dw==,type:str]
            id: ENC[AES256_GCM,data:JYwyrWggerLOMNi1,iv:K2plN+CPbibYggOUPVM1zFiqAxNiZ5aluv1EjHZG+pQ=,tag:JQdZYmpxhQ7lWi4oM0glzw==,type:str]
        account_2:
            name: ENC[AES256_GCM,data:QLwDvkg51aY=,iv:ecDPCCB0IxxsAR+PmDR4PbWBvI2EkFKejFd4o+tnT4Y=,tag:tCqZcUa3lA2DOO5Iysk/qA==,type:str]
            id: ENC[AES256_GCM,data:0+z0uHKzTEpDzMKt,iv:vKp5sAZhA0nptbBbldZ1z6rGNSR+0tYlQv3rguBsais=,tag:2l+jGzoCn0In5vMpWi8LqQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:6AN9FpFcTf3Rg8OMlR3NPEc=,iv:QZlWPtuhPrCBbndZE32tTTITmcrIamQ635hzAArPRQ0=,tag:Z+0KeOVru4ku2KonzbPOvg==,type:str]
    iam:
        machines:
            fluxcd:
                - actions:
                    - ENC[AES256_GCM,data:+GPWhjfMPzyycns=,iv:afherAYDUxJz/JHm/h95cL25pLTr7VtPHXC2rcFmHOw=,tag:hsQ3ctdtUrgRlMhUSCMp5A==,type:str]
                  resources:
                    - ENC[AES256_GCM,data:LYPghce7QmbTz8NhZxsyDjx9WMdJ/26u/wdoO/IPC1Fi0TIMSwQUNE0IJks5tGA7D0J7mbV6ots/7WTitVjOul2FFhhJyGqzkV0d,iv:YLvQ2P/Io7kyrs4gFAfP5IFujPDMEKyVu3o+ouDjFE0=,tag:R95RVpRItTdEXBq5jxJC/Q==,type:str]
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:7oCvWhrJo5KAWBn8SQW8nCEF9qcaVRw0rf+2NJh2,iv:9WMF0fQ0ahk5F5ZrAnV09ek/G6W3FzvAP2o7pLrzJs8=,tag:SBXxcg518qQPL1c5a4h2jg==,type:str]
                    - ENC[AES256_GCM,data:M8pRpdZhNbuRMD/+YUNr,iv:FfDYlfoBXjh1E36VkGfmBq7oDl6ae2ZIYv4+1w8BNKA=,tag:+mLi9KK4fqwD+a+VG7mn0g==,type:str]
                    - ENC[AES256_GCM,data:35JB6w2Nin4k5BUuSw==,iv:47IHQd1gCfsA9rwK9r57WWne8Fz5Y2HEuPXFuptQTjs=,tag:p+iy7gYgnqOXRyE0X0iJYw==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:N37aDzEE6Vs/bMb0tg==,iv:hrf5iYlPZfM+jqTRTO3DgXg457vah4l8U1jqM/8es+w=,tag:ChIRwlYh0MnPEqS5E/V5Ew==,type:str]
                    - ENC[AES256_GCM,data:BPwGQqtdSBJGbEvfN4o=,iv:zqOBs/R+u8R9Sh6OY84kpVtuTa2+E/MS9U9qmpeLujU=,tag:YHxHpatlsW/iKWEvJtV9zA==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:KyQv0DqjqUeFBoMMDw3hKZsM91LS96gUXd3YTDRS7v0Jow==,iv:4nV2IXEiC1RDNX+TrHyXisB5rR9Ks64hzLHGXW58oM0=,tag:ABR5htx3xmuMfmt5h9ITvQ==,type:str]
                sso_role_name: ENC[AES256_GCM,data:gCvUO9n2lRiruW+Vzriodpe8Eh3UkQ==,iv:OEEzFQv2nGlXg5wKMScmO8pgrCwBspnLgrlhEut6w8g=,tag:GYrtNQJF3mFTw68HZi+UNA==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:22mH+FkeQTA3Ehc1WkJ7Q9ZyfA==,iv:IcyS5DFOOqOLl/THokLwUdM5sS+TM+nrN8W/P0yK6tU=,tag:dkwDEi+NM0vZV1vuXVQ3eA==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:n8IrnP9QInJonfIJhWz9,iv:Tc+NmuHLfpJCbmLHJ12/AsEcAdz/rcqBkN/SaIPgXR0=,tag:XAQmYpYp/Gb04BVBslV7ag==,type:str]
            users:
                user_1:
                    name:
                        first: ENC[AES256_GCM,data:Mhl4WpSO,iv:wB0yrat56Z4/3OlcYCuulVL1BZoVnUfMEK7P8FvME00=,tag:sGQwsTvBLfzHEbYICda/cQ==,type:str]
                        last: ENC[AES256_GCM,data:qbAJ8HSxIzI=,iv:lWnVdKZww+FSf8gQ1gOGK0Oei3mwWts/mZ0sXc+FAXc=,tag:pBpW18e1K5d5mRORpnFwfg==,type:str]
                    email: ENC[AES256_GCM,data:KC8xd/KHV8BIm9IHCLUTPgo6wHE3cFOG,iv:dsHr9CBzQ9/+/HZHQz4Yc+yGhqHyTQuhYn7qBnI7fSE=,tag:2TQTa6BNpCDfaALIR8EZbA==,type:str]
                    cli-config: ENC[AES256_GCM,data:ORnIPuA=,iv:il1R/RiRHfR8YngK/kDGF5MVmh3Gsj9T16btdXi/Isg=,tag:QwgplpQK5JB37aH973tmsw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:dKyTAwJ/RO8=,iv:VmxupbxbrvrGEoENq+l5+oFI4ks5jr357j6IFnY7DuE=,tag:svkQCemaGwKKujgm3ePaPQ==,type:str]
                user_2:
                    name:
                        first: ENC[AES256_GCM,data:s0c8,iv:O+PjqKg8jG9v7//f2iqtD5giMfRAMdjBQ0dMVHpAHLo=,tag:bFYBIMSytljuPdp//ohWHg==,type:str]
                        last: ENC[AES256_GCM,data:416SiIiSNw==,iv:eLaeQu+vz3DQe02vkyKbNFgxw9rs54L/eQ8721qy5Fg=,tag:XUlkIb20ilGMNSPFrUtvYA==,type:str]
                    email: ENC[AES256_GCM,data:FDAQvYDGOSwfwBYrpgUl8cDgE24sdOE=,iv:60pE81e8x9sTnTIRB2IIr5jHQb3LMifCGnTOHiHm2K0=,tag:UcTPQlzx+IX6q1Ky5+CP3w==,type:str]
                    cli-config: ENC[AES256_GCM,data:E6WaND4=,iv:7kEZA7Y5IZ00Kj6OckbstUvxLUVTKWl9a30nNVJ27lU=,tag:epP3jyge4OA62ubq5CFURw==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:COAMV3mJuHx2cQ==,iv:dGUBpPcqYs5KNsq3KJjTKM59HIiEoG7adyJHGiZliK8=,tag:4BcavV3wD2gK+5MZviJCaw==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:ZsXEAXoKpSEUT+AfJoE9c7MKgtaS,iv:xLxhM10zI/nh1vF2QfmTlL5lCIjDbAa1IYYyvYRz/lo=,tag:fFDkAVU/ukMUU81cYCyOIA==,type:str]
                            - ENC[AES256_GCM,data:+3jU5fjwc+BLWw==,iv:/vuqlKYhQURe/gne0xA6JVXAUZR67h2q+JxWNsJ/1qU=,tag:amE2w/JVOPR2gR35GGmtSA==,type:str]
                            - ENC[AES256_GCM,data:NQcc/8tX1j8=,iv:0ZaiNMtOazgb50xGA7+MhVAqjmrUiXYoxCRIf11HBBk=,tag:7YzUPr5ZrVJGZLZg2rMKTw==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:ivXz/UNVZHXNIW//f4CfxFSXT76ZwqOqz2RkHSwK/F9I/9GBJswyeYIDlA==,iv:csaN6/vZS23m5klHfYd+VlKjYSQ1v1dbbCkZBDoqgxI=,tag:VB+itl4itf20iMV1BdB7TA==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:Oy8D3HgC7JxwWKpv84UbEmg=,iv:1mkNcwT/ZDRstn4RbesBB1NjhP79Fib5BHTNzEDgXIw=,tag:WDgFJo5lPwFpAVgF1eyerg==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:X/SnF/6prcgwz7Gb6DDuX1h3nfy2rvV/1HRvulEIf+xh3P5CFei94w==,iv:tq5+1Q3C6CWzK0jpYsRyq16gHM5byP5tvePUY57S/6c=,tag:+pGmVnDXMUzmvCd3Qsza6Q==,type:str]
                - ENC[AES256_GCM,data:AAW7fehPrAc/Cao52i1q8OhSPsiW8G/nwgeU3/AmyRaYBWQSnD9h+Q==,iv:NYesOM4pjTHedlTxBZ9UgPyT4nJ+EZVnQU6gLfL/wzU=,tag:b3vpvvomuHpoMrRWVZfx/g==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:EpiWiZl3evU7nZeinItcBCH/8GZl,iv:HtmUaVvAbJawarvo/6HN+ZrcQROj616hALm8Dam/5y8=,tag:PWDwwb6hE05PDYKMHIKuCQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:jzpJdZFEDxabkeFESy5g8TEYnJbL299mQ3Hy7pcD,iv:GFP5zMI8kWO5yi1zxkvXs13vQ9qdFCogg3zuyyxR24Q=,tag:yG7oEKS4/gkk9kb7HSWodg==,type:str]
                        - ENC[AES256_GCM,data:cz4wwKlDtDNAdCqSVEwL,iv:4AGWMxUpl+VVs/HKu+p1uDkgvIABU2+VILAzMButMGQ=,tag:uvIdBriwSnvNnpenD4YJYA==,type:str]
                        - ENC[AES256_GCM,data:aelFEx2+VwDUmSn2MQ==,iv:yHNYDPohn6CmobLZYoqE2IJJvhKy40VyrXT1QoT3UAw=,tag:QHYwDnfEnlBO3VO2Adpigg==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:UdZBmCDpdcuzrM2bGCJyiZ6w,iv:amhUCieIDH5OeYTnDeJjFIzpOir3VSB8FtyUdYID38w=,tag:I6Rz4uVqrIpxVoxcIFcs9A==,type:str]
                        - ENC[AES256_GCM,data:TUWFjZdu6IvAScg4JMMGO3k1fQ==,iv:OFj6cy8Q7DFJTHkB96KcNpXVwrCTp50vWqNQKwPrjJQ=,tag:1MCC+L72JlZuXHy3IWx+NQ==,type:str]
                        - ENC[AES256_GCM,data:5Ob5GxIlTSHBsjIeXEDcgxWZgfZWqA==,iv:8xtY5Vx1P0wAXOvBjYRC5lVlwJCo+zwMwrz8y0KNFT4=,tag:/+c2sA2GeONoEcbiubemdQ==,type:str]
                        - ENC[AES256_GCM,data:H3mULJF4aNkYogjhzO1rSgSgxZocAOI=,iv:sKqIkNbF38HKS571mLGuCCud6a6xbxod372j4LQ6iMs=,tag:ylEkp6qwD4YZ1TgFJEhn/w==,type:str]
                        - ENC[AES256_GCM,data:yUzmcV5KolhAVsf7AAYrbNicXL4P,iv:Sqi2LwCyt4v3PZ5tzlRKyRrW+5PBhh57gTqRb/nrVWE=,tag:Dw/0/SizW1AttoIpycJC0Q==,type:str]
    buckets:
        - ENC[AES256_GCM,data:WBYsBI/Dd+LCmWyUVUwzhjxz,iv:jfC9QFkvnXgJb6QLVm38uw7ZAdtDTYUcIr356qA8wBI=,tag:biz2lKPyEL04S/w8Z58pnQ==,type:str]
        - ENC[AES256_GCM,data:l3xwDSmmMtJqXk6CK1sCeT0=,iv:jf3A9ECPYdU3K0mPcB7cjnCyCJAtdlRnZ42ThfMtUZ0=,tag:TGW1LAtdvb3uzUn9HoGAsQ==,type:str]
        - ENC[AES256_GCM,data:E2wMHWQk+Tk3r3f1z5auJCRyb7FY9wgjNg==,iv:aLOcjTavC/3PWdad8Cy/FI5aVcuG+PTzgzJ95TTLFNY=,tag:B/lK8SW59ceWVlHf7AqKaw==,type:str]
        - ENC[AES256_GCM,data:mWllU9FOP9Li75ipYe6L/EFVsEaOlUR5Tv0Fsdk=,iv:KpX1H8fV3d0aLffChCmbGqqhmtMQJULIGjLnJrSFpzY=,tag:Zne2WezAV6Kxo5K6Fce2Bw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:2WXORWJFQaarobCBBg==,iv:vnbVAlfjZFyIDQG07Wv+D69nw2u2ec0nLsZ9OIrJGnM=,tag:Fhby+XTUeCDvTplG7Q6z9w==,type:str]
          description: ENC[AES256_GCM,data:kwZqVRwjcKMpecYLOw==,iv:JXm8uahR8nCvtAy1IMJ5/fxfIHelVhy7duwDPQyYSfA=,tag:zbWTk2/4msMYkJ7fprXcHQ==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:EBKmWwogyni0vtdETfQX,iv:ezbp+40s1cKdB+IEGIHwhBhpTkTraDvM9OCSd9I6x7w=,tag:DzlNM4plQy9n9AnzAZMMdA==,type:str]
          extra_policy:
            - id: ENC[AES256_GCM,data:qS7C0GmLimC8tZmm2xsxbouDkArpxmzYSpvRT6Rj4D2jRXw=,iv:L32zojgC/xTRqjCszE13gVV9w3xPjbpXq89DFsLnZHU=,tag:+JZZP2TgQ2WP2zEHeROXwg==,type:str]
              principals:
                type: ENC[AES256_GCM,data:HY2W,iv:4TJ6aAVDRVY2ARgNDZgY3jNk6iABv0kcRhPECNtwcc4=,tag:s/R6Pg8ilQOXAZ+cxxArpQ==,type:str]
                identifiers:
                    - ENC[AES256_GCM,data:N6QldirtQtk+vRLqtyhseTpZMjjrvi7npzLJpPPyAiec2Jcdri4FLYMYlfbp,iv:0iKo2WQFZ2znz1zjnWovkCV+BcpMD915GlgbBiF4eeY=,tag:BJUj7YcNp5BkfigrPFAFFw==,type:str]
                    - ENC[AES256_GCM,data:RanwGwAdeROtUGr4NXkMcbJ2yIAUNRgsvSfqaVfZfBKBmyu7uA4mJkWG0fsGlu8dsYh8,iv:dZzT/lU7WdNA/acgBonbwNqk0azflVLmNwWBEGOrlwM=,tag:vvRb9qp3kiF76e4LcZd0fg==,type:str]
        - name: ENC[AES256_GCM,data:1LTXWmOzu04=,iv:ClP8oHGjeBuq5AzJFZkvdnhFz7EPKvefV7uvTICj3Lc=,tag:6B+IGY1xltCa3pNcO7SmIA==,type:str]
          description: ENC[AES256_GCM,data:7Z2ZcS3WIoEGkkpCBG+HD969BkpNH5B4NDWce7fFessJ,iv:BHRVccYob5JX5Vc6X+AxZ0bN525Yl18RWsFP63ci15Q=,tag:yx3WetwFLxmE6iygoutpUA==,type:str]
          deletion_window: ENC[AES256_GCM,data:dQ==,iv:KEq/nUhDKyc74NTnoulFvREZFg2ITkfSQImvut1nnGo=,tag:h/cevsaFxLkUtXiUXgIC8g==,type:int]
          key_usage: ENC[AES256_GCM,data:tTq2KUOqhOLa2Q/rlqyg,iv:5h+DAuBCcaNmWCIx/L8sgakxC6plijR8xWhfr2eI9Ls=,tag:ZhR0/R5OK2tZb+KWbQYEYw==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:KJ7J83mb9HOxYLA=,iv:KdOQ5ouELxZUD8LjjLjr4D0njRQv0K+Q9nBVDNKZ2LU=,tag:9YpebC0eP0l+6mkZE7BJDA==,type:str]
          limit: ENC[AES256_GCM,data:6CJNLCpmDdo=,iv:6ncEj3f1Y6+TBwau4hyy7yHSvIARvrdGEr834GqqLvA=,tag:AzQGDjexQcf03RN69jxP5Q==,type:str]
          notify: ENC[AES256_GCM,data:m5RseU9vQJI69nes/Lak9xygeUW1qSZu,iv:l6+5dihvCJet6lBEZcGIeiaxka/9D5Yix62tmhDJP+8=,tag:Oce2/iwMJEeEObJljamFWQ==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-05-09T19:06:13Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEhvFbwpfnbKH68myy2V8loAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtewpUMnf5vy+YpxRAgEQgDtccB1vQLXH1kL1Me71ckqgV93vfEWSM8O6AtbdRKvXemspOm99w925blq2LP47FAj5IG07SKKgWE7qog==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-09T19:06:15Z"
    mac: ENC[AES256_GCM,data:AkPzFLcSq59Eeedqy5Fsp395DXitN64BKHH8Sxz4aE5cz+aUZibrmUEhm333yRfNvYbQ5iK+T7U6+Bn+D7WtVmATXFctW1WsOalVhoHfKGFWzC2yFWv02ZLLUXWYZItHZVhe34ivvAud8I1I0E8Wu/ksElpxuhibspca05Sqr8Q=,iv:b6FTNZtU4XYWf+cwEpkmPD4IkMu/VNtCP0GNisRjmgo=,tag:dPugkgEv4C9oBc4eexsSqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
