aws: {}
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-06-13T15:05:40Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGJZ0D91Ow5J0VSKzof+gGFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiWeMrBM7tkOhaCy1AgEQgDuBCVdnuHxTY6GoMMhjoom2AEfKDm07zsEktegFAMRloNEQHmPkqCaiBbWf3KfFDYC/UrolHmV4s/0y5g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-13T15:05:41Z"
    mac: ENC[AES256_GCM,data:UXNaJNnoD2ODtc/Dl69MkNA4uxhXI/IbiJ2t1cY+M+b1lO54TLf9lNMjtt3Ovc87Diydnd8/VF97Rk48/0owEqZcsCpXUf5ftVoxW4AqSkzw+0wjXrBXztXV7u3ywsKIQRapV7XfDV2HvGDdsbEdA6SCGVYY9qLJa8PREMMePP8=,iv:foE3nJeGrassQkJ8KNd/aWB6q/NEU2foYvh9UxWpQrs=,tag:QsfhdE8K88i556bmLpc4OQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
